### ISSUE TITLE
SSE "Deployment failed" errors

### ISSUE THREAD

**Issue by rdparker** [Nexus-Mods/Vortex#100]
With a fresh install of Skyrim SE in E:\Steam\... and Vortex BASE set to E:\Vortex\{GAME}, enabling mods routinely fails with a

> **Deployment failed**
> X files were not correctly deployed (see log for details)
> The most likely reason is that files were locked by external applications so please ensure no other application has a mod open, then repeat deployment.

message. I've tested this on a fresh install, after a reboot, with my antivirus disabled, and while running Vortex as Administrator. The results are always the same.

I'm attaching the [full vortex.log file](https://github.com/Nexus-Mods/Vortex/files/1812568/vortex.log) of the session. The only changes I've made are replacing my Windows user ID with &lt;user&gt;.

Since I have several versions of Visual Studio installed, I've not yet been able to successfully build Vortex from git and try to debug it myself.

**Comment by TanninOne** [comment]
The error message is "ENOTSUP: operation not supported on socket" when Vortex tries to create links.
Is E: a network drive?

**Comment by rdparker** [comment]
No. E: is my larger gaming SSD. That's why the socket message was confusing.

Sorry for the late response. This got buried in my notifications.

**Comment by jpinsonault** [comment]
I'm also getting this error

> Sat, 05 May 2018 06:50:52 GMT - warn: failed to link error=ENOTSUP: operation not supported on socket, link 'm:\Users\<user>\AppData\Roaming\Vortex\skyrimvr\mods\Cloaks of Skyrim SSE - v1.2.1-6369-1-2-1\Textures\Clothes\cloaksofskyrim\sagecloakmythic.dds' -> 'M:\Steam\steamapps\common\SkyrimVR\data\Textures\Clothes\cloaksofskyrim\sagecloakmythic.dds', link=Textures\Clothes\cloaksofskyrim\sagecloakmythic.dds, source=Cloaks of Skyrim SSE - v1.2.1-6369-1-2-1

It's an SSD as well. I've also been running NMM and I'm trying to migrate. Thinking that might be related

**Comment by TanninOne** [comment]
What filesystem are you using on that drive? (If you don't know, press the windows key and type "diskmgmt.msc", that should open a tool that shows the file system for each drive)

**Comment by TanninOne** [comment]
Closing for lack of feedback.  Most likely the drive was exfat or refs which both don't support hard links.
Vortex now offers move deployment for those cases.
