### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by PhatSion12** [Nexus-Mods/Vortex#10012]
**Describe the bug**
It worked fine before I purchased premium then once I did it stopped working and now says certificate has expired when I try to download mods
**To Reproduce**
1. Download mod

**Expected behavior**
The mod downloads with no issue in vortex

**Screenshots**
![image](https://user-images.githubusercontent.com/91754993/135668509-5afcb919-622b-4460-9fc1-1330a34fd746.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version latest version

**Additional context**

**Comment by IDCs** [comment]
duplicate of #10005
