### ISSUE TITLE
Can't deploy mods due to symbolic links not supported between mod staging folder and game folder

### ISSUE THREAD

**Issue by Titian510** [Nexus-Mods/Vortex#10026]
I downloaded a few mods and tried to deploy them but all I get are "Some mods are redundant", "Deployment failed: 17 files were not correctly deployed. The most likely reason is that files were locked by external applications so please ensure no other application has a mod file open, then repeat deployment.", "Symlinks are not supported: It appears symbolic links aren't supported between your staging folder and game folder. On Windows, symbolic links only work on NTFS drives" I don't understand what the problem could be since nothing else is open and both the game XCOM2 and the file where the mods are at are in the same drive(an external drive with a storage of 2 TB). 

 -OS: Windows 10
 - Vortex Version 1.4.16

**Comment by IDCs** [comment]
Hi @Titian510 - as the error message mentions, symbolic links only work on NTFS file systems. By default external hard drives are either distributed in an unformatted state (no file system) or at times pre-formatted to use the exFAT file system.

Right click  on the device and select properties - that should show you the file system.
![image](https://user-images.githubusercontent.com/8960252/135968248-e71cf503-b7ea-455d-b1f7-75c626ee0688.png)

You will probably have to format the drive or use a different one that uses the NTFS file system.
