### ISSUE TITLE
API Docs error IContextMenuProps supports array or string

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#10049]
This line of the API documentation is incorrect:

https://github.com/Nexus-Mods/vortex-api/blob/e891c2f3dc69e85accc4ec41b20ee1261985c96b/lib/controls/ContextMenu.d.ts#L19

Can be updated to : `instanceId: string | string[];`

Relevant function using this property: https://github.com/Nexus-Mods/Vortex/blob/76b77494db78e39568cb12fe31e83c04ce1a2903/src/controls/ContextMenu.tsx#L34

**Comment by TanninOne** [comment]
The code clearly expects a string and isn't intended to support an array of ids
