### ISSUE TITLE
Unhandled Exception on new installation - email related

### ISSUE THREAD

**Issue by Sharkateer** [Nexus-Mods/Vortex#1006]
I installed a clean copy of Vortex today, and authenticated its use of my Nexus profile. I also pointed it to my SkyrimVR installation. I doubt its related, but my skyrim.ini was read only. 

After closing and relaunching Vortex I am given an Unhandled Exception. It seems that this should be recreatable on other machines. I hope this helps, please contact me on reddit if you need further details. 

Using Vortex 0.16.2

![vortex error](https://user-images.githubusercontent.com/26576758/45397740-0897ea00-b607-11e8-964e-f7e14815d7a0.png)

**Comment by TanninOne** [comment]
fixed in 0.16.3
