### ISSUE TITLE
Vortex roms folder disappeared

### ISSUE THREAD

**Issue by lululu00101** [Nexus-Mods/Vortex#101]
Last thing I did yeasterday was playing skyrim SE after downloading Bruma from vortex. Everything went well...but today as I was going to launch the game again via Vortex, I 've been warned by two strange messages claiming that bruma masters were not activated and all the mods were missing.......effectively there were no more mods... neither in mods page nor in the respective folder

How is it even possibile something so stupid could have happened ? I didn't touch any folder myself...I just wanted to play from Vortex.....please help because even if technically I can still run the game, now I cannot see anymore mod version and dipendencies...I only have my roms in the plugins list

**Comment by TanninOne** [comment]
Have you changed your mod path in settings? What did you set?

**Comment by lululu00101** [comment]
I followed a youtube tutorial which suggested configuring paths this way (worked flawlessy for an entire month)

Skyrim special edition installed in E:/SKyrimSE

Base Path            E:\Vortex mod manager\SkyrimSE
Download path   E:\Vortex mod manager\SkyrimSE\downloads
Install path          E:\Vortex mod manager\SkyrimSE\mods

The last thing I installed (succesfully) was Bruma SE. I don't know if such a large file could have cause problems. The strangest thing of all is...the dayafter, both mods and downloads folder were empty !!
Now I cannot even run the game from vortex...
I had some mods conflicting with others whose priority was solved by Vortex. Obviously now without Vortex managing the conflict is alive and ready to strike. Tested the game without vortex, all is fine but .....man I would just avoid to reinstall everything again with a different manager

**Comment by TanninOne** [comment]
And where is vortex itself installed?

**Comment by lululu00101** [comment]
sorry, I forgot to tell you

It's installed in the same folder E:

E:\Vortex Mod Manager

Should I have choosen the first download option ?

I am starting to think that maybe choosing the custom install and not disabling the option to auto update maybe caused this issue (I misjudged the weight of that alert)

**Comment by TanninOne** [comment]
Yeah, that's the cause then, please read https://forums.nexusmods.com/index.php?/topic/6454716-do-not-put-modsdownloads-into-your-vortex-install-directory/
The solution is not to disable auto update but to not put data into an application directory. Ever. Unless the application is specifically build for that.

Could you please give me a link to that youtube video?
