### ISSUE TITLE
Symbol to indicate when a mod is completely overridden by another

### ISSUE THREAD

**Issue by Pyro2677** [Nexus-Mods/Vortex#1025]
In MO2 when you overwrite another mod it will tell you with the lightning bolt when it is being overwritten and when it is doing the overwriting with the little + & - signs. When all the files are being overwritten it has a grey lightning bolt which shows that you don't need that mod because everything about it has been over written. I think this is helpful with people using different texture mods so they can see quickly whether it is pointless or has some textures not overwritten. 

Is this something that might be added in future releases?

**Comment by leegion552** [comment]
This is exactly what I was thinking, is there a way to manage which textures overwrite others?

I have so mods that I want bits of but use another mod in place of a bit I don't want. For example and overhaul mod for all weapon textures in Fallout 4 but I want to use another mod that changes pipe weapons. I just want pick and choose the textures the pipe weapon mod replaces
