### ISSUE TITLE
Extension Update "Dest already exists" error

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#10267]
**Describe the bug**
A lot of users are reporting a "Dest already exists" error when updating extensions. It's unclear why this happens, but if the 7z file already exists, Vortex should continue with the install rather than throwing an error. 

**To Reproduce**
I cannot reproduce it directly, but there are several threads on the forum about this error:

Recent reports
https://forums.nexusmods.com/index.php?/topic/9758778-dest-already-exists/
https://forums.nexusmods.com/index.php?/topic/10647173-vortex-failed-to-install-extension/
https://forums.nexusmods.com/index.php?/topic/10661978-vortex-error/

Old reports
https://forums.nexusmods.com/index.php?/topic/9457528-error-dest-already-exists/

**Expected behavior**
Vortex ignores this error and proceeds

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by Pickysaurus** [comment]
Additional report: https://forums.nexusmods.com/index.php?/topic/10891528-vortex-installation-failed/

**Comment by TanninOne** [comment]
This error has only been reported recently on specific extensions (Dying Light specifically), is this still generally a problem? @Pickysaurus

**Comment by Pickysaurus** [comment]
Haven't had any more reports for a while. I'd guess it doesn't happen as often if at all anymore.

**Comment by TanninOne** [comment]
I'll close this then but feel free to create a new ticket if it gets reported again
