### ISSUE TITLE
"Start Game" from task bar starts multiple games

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#103]
Clicking the "Start Game" option from the task bar icon seems to start multiple instances of the game, at least after switching between managing different games inside vortex.
Most likely every time the game is switched a new listener is attached to the "quick-launch" event.

**Comment by M4lik** [comment]
Was this fixed in 555d490b4fc4710a47578dcb68d6f2ed9ac3850c?

**Comment by TanninOne** [comment]
I think it is.
