### ISSUE TITLE
HttpError: 503

### ISSUE THREAD

**Issue by Biskit1943** [Nexus-Mods/Vortex#10365]
**Describe the bug**
When starting the application i got the following error message:
[vortex_bug.txt](https://github.com/Nexus-Mods/Vortex/files/7574278/vortex_bug.txt)

**To Reproduce**
Start vortex

**Expected behavior**
No error message at all

**Platform (please complete the following information):**
 - OS: Windows 10 Home; Build 19042.1348
 - Vortex Version 1.5.0-r43+internal Unknown

**Comment by TanninOne** [comment]
http code 5xx implies a server error, 503 specifically is "Service unavailable". Nothing Vortex can do about that
