### ISSUE TITLE
Upcoming LOOT changes that may affect Vortex

### ISSUE THREAD

**Issue by MacSplody** [Nexus-Mods/Vortex#10397]
Just in case you guys haven't seen it yet, there are going to be a few changes for the next release of LOOT.
Skyrim VR & Fallout VR are going to be spun off into separate masterlists.

https://github.com/loot/fallout4vr
https://github.com/loot/skyrimvr

Not sure if the next one will affect Vortex, but localization is going to be put into a separate file called prelude.
https://github.com/loot/loot/issues/1492
https://github.com/loot/prelude

**Comment by TanninOne** [comment]
Thank you for the heads-up!

**Comment by pStyl3** [comment]
LOOT v0.17.0 is now [released](https://github.com/loot/loot/releases/tag/0.17.0).

**Comment by TanninOne** [comment]
I don't think this had any effect on Vortex.
