### ISSUE TITLE
Mod files get deployed to wrong directory (Fallout 4 - Load Accelerator Mod)

### ISSUE THREAD

**Issue by MrSlimbrowser** [Nexus-Mods/Vortex#10409]
**Describe the bug**
I tried to add the ["Load Accelerator"](https://www.nexusmods.com/fallout4/mods/10283) mod for Fallout 4 to Vortex. It doesn't have the "install with vortex" button on nexusmods so I hit manual download and added it trough Mods->Install from File. It has been added and can be enabled/disabled just fine but doesn't work. Reason for that is, that the mod consists of 2 files which belong in the games main directory (.\\) but Vortex deploys them to .\Data\ instead.

**Expected behavior**
On my system, Vortex installs mods to s:\VortexModManager\mods\\_ModName_ and deploys the files via hardlink method. When I changed some files from F4SE mod, it seemed like Vortex simply keeps the folder structure in the mod directory when deploying, like this for example:
S:\VortexModManager\mods\SomeMod\launcher.exe --> S:\Fallout4\launcher.exe
S:\VortexModManager\mods\SomeMod\Data\xx\some.dll --> S:\Fallout4\Data\xx\some.dll
If that is not the case, how does Vortex determine where mod files belong?

**Screenshots**
![Fallout_Mod_Problem](https://user-images.githubusercontent.com/23149710/143309174-32f823d9-4d26-4b6d-bb45-79a69d437102.png)

**Platform (please complete the following information):**
 - OS: Windows 10 21H1 (19043.1348)
 - Vortex Version 1.4.16

**Comment by TanninOne** [comment]
Vortex has no way of automatically determining where mods need to go, you have to tell it by assigning a "mod type" (double click on the mod, scroll sidebar until you see "Mod Type").
The default mod type installs to the data directory (for bethesda games), the mod type "Engine Injector" (or is it called ENB in 1.4? can't remember) is what you want, to install into the base game directory.

**Comment by MrSlimbrowser** [comment]
Thank you! I felt like I clicked trough every menu and option but I never double clicked on the mod. Unfortunate that this pane is hidden like that, but I see that has been noticed before in #2466
Is there any documentation on how vortex deploys the different mod types for each game or do users have to stick to trial-and-error at the moment?

**Comment by TanninOne** [comment]
@MrSlimbrowser no, it wouldn't be easy to document because it's different for every game. For the bethesda games you really only have to know that everything that's supposed to go into the game base directory has to be set to "Engine Injector" but many games have their own mod types and the rules are always different.
