### ISSUE TITLE
Use IPFS as distribution protocol

### ISSUE THREAD

**Issue by RubenKelevra** [Nexus-Mods/Vortex#10423]
**Is your feature request related to a problem? Please describe.**
Currently, all mods are stored locally as archives and additionally extracted. If IPFS would be used the files could be fetched from its cache or the network, if the cache doesn't have the archive anymore, due to storage limitations.

Also, traffic for the nexus mod servers is pretty massive. IPFS would be able to shave off a large amount, as everyone who has vortex running / ipfs client running and some of the archives still in the cache would help to distribute it.

**Describe the solution you'd like**
IPFS is similar to BitTorrent, but the whole network is like one large torrent swarm. You only need the Content-ID of a file (basically the checksum) to locate nodes which has them and then locate the nodes in the network which have the lowest latency to fetch it.

Since the content is addressed by its checksum the content cannot be forged or faked by anyone and the integrity is guaranteed.

The protocol is for example used by Netflix to distribute their content to all the cache locations around the world.

IPFS also allows creating clusters to hold a large amount of data reliably available in the network with guaranteed redundancy. So if someone likes to support Nexus mod he/she could just join the cluster and share some bandwidth and disk space.

Modders could also just add their files to Vortex or IPFS Desktop instead of uploading it via the browser and just fill in the CID for the file in the browser. The cluster would then fetch the file automatically from the modder's computer and add redundant copies.

**Describe alternatives you've considered**
BitTorrent would be an alternative, but this would be much more complex, as every single mod and each file for a mod would need a new swarm.

**Comment by TanninOne** [comment]
It's an interesting technology but primarily it's a business decision. I can't do more than forward the suggestion.
