### ISSUE TITLE
Bell icon for missing masters persists

### ISSUE THREAD

**Issue by BigBizkit** [Nexus-Mods/Vortex#1043]
0.16.4

The new bell icon indicating a missing master does not disappear even when the missing master issue has been addressed (unlike the notification, which correctly disappears when "checking again").

Bell icon only vanishes once Vortex is restarted.

![image 11](https://user-images.githubusercontent.com/41682455/45736117-ecd1ac80-bbe1-11e8-91bf-a69b3297e5f6.png)

**Comment by IDCs** [comment]
Fixed: https://github.com/Nexus-Mods/extension-plugin-management/commit/d50ede6b55a5915a7acf2f14b68e0b371e794b0a
