### ISSUE TITLE
Support for manually specifying alternate settings folder other than appdata / programdata

### ISSUE THREAD

**Issue by mikeloeven** [Nexus-Mods/Vortex#10487]
**Is your feature request related to a problem? Please describe.**
This is a request to workaround issue #7579 which was closed due to a technical limitation that caused extension modules to fail if junctions or symlinks were used to relocate appdata folder 

**Describe the solution you'd like**
I just want the option to manually specify which folder vortex will use for its settings and database to a location other than appdata

**Describe alternatives you've considered**
using symlinks / junctions which will not work due to #7579

**Additional context**
Current issue I am having is a steam library folder stored on a NAS. The issue involves multiple computers sharing a single steam library folder. Loading vortex on one computer is not aware of changes made by vortex on another computer this causes the game state to desync and generates deployment errors. The reason I want to be able to change the appdata folder location is so all computers will be fully running vortex off the NAS and not storing any conflicting settings locally

**Comment by mikeloeven** [comment]
I suppose an alternate option would be for vortex to be "Aware" that multiple computers are accessing the game director by leaving a change log file so that if another vortex sees a unexpected change it can look for the file left by the other vortex install and use that to automatically resolve the conflict.

**Comment by TanninOne** [comment]
Vortex needs to know on startup where its settings are. There are only two ways to achieve this, either we need to use a default location (AppData or the registry) or you have to specify the directory on the command line.

For our internal testing we have added an option to Vortex to do just that, call "Vortex --user-data y:\your\custom\directory", of course you can create a shortcut to do that.
But please understand that at this time we do not consider this an official feature, it has received limited testing, there is no UI around it and while we'd be happy to hear about bugs we're not going to provide support.
That may change someday but no promises.

**Comment by mikeloeven** [comment]
@TanninOne I wonder if this could be accomplished in the future using a plaintext .cfg file placed in the executable install directory. it should be trivial to have the client on launch check if a file exists in it's own directory defining location of the user settings. any way I ll try the command line option see if it works thanks for the advice.

**Comment by Fromlostdays** [comment]
Not looking for support, just want to pass along my testing of this feature.
1: I'm not sure if this is a limit with command lines, but if any folder in your path to the custom destination folder has a space in the title of it, Vortex will stop at the space and store its appdata files there:

e.g. 
   O:/Modding Utilities/Vortex Cache creates the folder
   O:/Modding 
&      
   O/:ModdingUtilities/VortexCache stores the data in the "VortexCache" folder as intended.

2: Even when successful Vortex still creates a folder called "Vortex" in the appdata directory and stores a bunch of files in it. It seems like more than half the files still go to the original appdata directory regardless. What does work is that setting a custom directory automatically has your mod downloads and staging into that custom directly, which I assume is one of the main reasons people would want this feature. Even as is it will still save you space on your C: drive without having to change the downloads and staging folder for each game manually.

Thanks!

**Comment by mikeloeven** [comment]
What might be needed is a portable version that stores everything in the current directory along with the executable this seems like it would be easier to manage for NAS setups with no data being stored in appdata

**Comment by TanninOne** [comment]
@Fromlostdays This is the windows shell doing that, the command line is split up before Vortex ever sees it. You have to put paths with spaces in quotes.

@mikeloeven This is a much deeper rabbit hole than it may seem. For one thing, the installer software we use deletes the application directory and reinstalls the new version on top to ensure there are no left-over files from older versions. Any files, be they configuration files, mods, ... would be deleted on update.
Further, the best compatibility for the deployment process is achieved with hard-linking files from the staging folder to the game directory. This requires the staging folder to be on the same drive as the game, not the one with Vortex.
A portable version like you describe would either support fewer games (as we'd have to rely on symbolic links) or fewer system setups (all games would have to be on the same drive)
These limitations would then lead to more confusion and frustration among users.
