### ISSUE TITLE
build requirements missing from bootstrap.ps1

### ISSUE THREAD

**Issue by nicman23** [Nexus-Mods/Vortex#10542]
**Describe the bug**
Build requirements on a clean vm are missing on bootstrap.ps1
**To Reproduce**
run bootstrap.ps1

**Expected behavior**
yarn build completes.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version master

**Additional context**
i also needed dotnet 3.5, cmake, visual studio 14.0 for yarn install and yarn build to complete.

**Comment by TanninOne** [comment]
dotnet comes preinstalled with windows, you'd have to go out of your way to not have it already.
visual studio build tools do get installed (that's all we need from vs), cmake is not a requirement to my knowledge at least I'm not aware of any component that needs it and doesn't pull it itself and finally this is just a script to bootstrap your local environment so you can start developing, it's not supposed to produce a finished build.

**Comment by nicman23** [comment]
> dotnet comes preinstalled with windows, you'd have to go out of your way to not have it already.

no it is not specifically version 3.5.

> visual studio build tools do get installed

how? on the text that is printed from the bootstrap.ps1 it is not specified that it needs 14.0 and its specific assemblies.

> cmake is not a requirement 

it is.

> bootstrap your local environment so you can start developing, it's not supposed to produce a finished build

that is the issue, it does not. you have to waste time just to produce a build.


this was all performed on a clean win10 install from a clean iso named Win10_20H2_v2_EnglishInternational_x64.iso with a md5sum of `2ff3aa5bb18ddc990e13a3994c125b5a`

i have a zfs snapshot of before and after. it can reproduce the above and can provide access to the vm. please do not dismiss and insta close issues, especially on basic stuff like does the project build on machines.

**Comment by TanninOne** [comment]
> no it is not specifically version 3.5.

we don't require 3.5, the only .net module we include is built against .net 4.5, dotnet is backwards compatible and is updated by windows update so any windows that has been updated within the last 8 years should be fine.

> how? on the text that is printed from the bootstrap.ps1 it is not specified that it needs 14.0 and its specific assemblies.

it downloads a specific version

> it is.

it isn't

> that is the issue, it does not. you have to waste time just to produce a build.

If you consider building vortex a waste of time, don't do it. We publish binaries.

> i have a zfs snapshot of before and after. i can reproduce the above and can provide access to the vm. please do not dismiss and insta close issues, especially on basic stuff like does the project build on other peoples' machines.

We provide binaries for our users, that is the only form of distribution that we officially support.
If you want to submit pull requests to improve the build system and we can verify it doesn't break what's been working, I'll be happy to merge them but if you can't set up a build environment for Vortex, you can't build Vortex, we're under no obligation and have to capacity to provide a one-click build-from-scratch for every imaginable system.
