### ISSUE TITLE
FOMOD ModConfig.xml gameDependency version check not working in Vortex

### ISSUE THREAD

**Issue by dunc001** [Nexus-Mods/Vortex#10648]
**Describe the bug**
As the title says, the gameDependency version check does not currently work when installing through Vortex.  It works perfectly well when installing through MO2.

**To Reproduce**
Download the latest version of iEquip (1.6.4) and install through Vortex.

**Expected behavior**
You will see that neither option of the dll is selectable.  The installation will allow you to continue, but the files which should be installed based on game version will not be installed.

**Screenshots**
[url](https://imgur.com/Ivpeq2F.png)

This is the section of the xml which isn't working in Vortex

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version - latest

**Additional context**

**Comment by dunc001** [comment]
I have just updated the ModConfig for now changing NotUsable to Optional so when the game version check fails in Vortex at least users can manually select which version they want.  So downloading the current nexusmods file will no longer fail if you try it.  To induce the issue simply edit ModConfig back as per the screenshot in the issue report and you'll see it fail.

**Comment by TanninOne** [comment]
This is fixed in Vortex 1.5.x (I think starting at 1.5.1)
