### ISSUE TITLE
Feature Request: 7 Days to Die ;  Mod Installation Pattern

### ISSUE THREAD

**Issue by agreen72** [Nexus-Mods/Vortex#10653]
Hello,

So I was trying to use Vortex to install an overhaul mod for 7DTD that was manually downloaded from the games forums.  It has the correct file structure but requires the zip contents to be unpacked into the Root folder.  The current extension only has one type of "mod type" or "mod installation pattern" as referred to in the documentation [here](http://wiki.tesnexus.com/index.php/Creating_a_game_extension_for_Vortex)  

Currently, the only mod type vortex handles are what are called "modlets" on the 7DTD forums.  It currently only installs to the  7 Days to Die/Mods folder.   However there are some Overhaul mods which require files to be installed into the root game folder.  There is currently no option to do this, as this is with games such as fallout 4 or skyrim when you select the Mod Type to be 'ENB', that switches where the mod files are linked to from the Data folder to the games Root.  

I am requesting the addition of an 'Overhaul' or 'Root folder' mod type or 'Mod Installation Pattern', for 7DTD that directs the .zip contents to be placed into the Root folder. 

From my brief research, it used to be the case that mods installed with Vortex were installed to the Root folder, but a bug was submitted on this github and Nelson3219 and someone else changed it to direct to the Mods folder instead, which made sense with the changing file structure of the game.  You can find that thread [here](https://github.com/Nexus-Mods/Vortex/issues/3045). 

Hopefully it is rather easy to add an additional Mod Type to allow the user to select where to place the mod contents and handle the popular overhaul mods the game has.

Thank you for all you've done for the modding community!

**Comment by IDCs** [comment]
@agreen72 can you please send me the link to said overhaul mod so I can find a pattern we can use when identifying these overhaul mods ?

**Comment by IDCs** [comment]
Also - please note that due to how the load ordering system works, if an overhaul mod is basically a collection of "modlets" - I'm afraid it is impossible with the current system to assign prefixes to the modlets that are part of 1 larger "overhaul" mod. Our entire system would have to be re-designed which is not something we wish to do since we're close to release our very own collections system to the public.

**Comment by agreen72** [comment]
Here is the link to the download.  The mod is Undead Legacy, the experimental A20 build.  
https://ul.subquake.com/download

**Comment by IDCs** [comment]
Hi there - I've added the ability to install root mods. Unfortunately there is no solid way for us to identify if a mod is intended to be installed as an overhaul mod - we're currently assuming that any mod that includes the bepinex mod loader to be an overhaul mod - this is extensible through an array, and I expect we will have to modify this in the future as we identify new mod packing patterns.

The mod you included does indeed come with its own modlets - as I mentioned previously these will not be arrangeable via the load ordering system as we currently do not have the ability to actively modify a single mod's contents on deployment.

**Comment by agreen72** [comment]
Thanks, I have tried to install it, is there a trick or an option to install to root? because it's still installing everything to the mods folder.  Perhaps I need to update the 7dtd extension? How do I do that?

**Comment by IDCs** [comment]
The update hasn't been released to the public yet - what you can do is download the vortex-games repo load_order branch and copy the game-7dtd folder and place it inside `%appdata%/vortex/plugins` folder - that should force Vortex to load the latest version of the extension.

**Comment by agreen72** [comment]
I see.
Thank you!

**Comment by agreen72** [comment]
Looks like it works perfectly, thank you!
