### ISSUE TITLE
[0.16.5] Vortex doesn't detect all mod updates

### ISSUE THREAD

**Issue by Anvirol** [Nexus-Mods/Vortex#1065]
I've seen with several mods that newer versions are available, but Vortex can't detect them.

According to Vortex I'm on latest version:
![image](https://user-images.githubusercontent.com/3955313/45887061-6e346500-bdc3-11e8-94af-d8325d6212b8.png)

Nexus tells me otherwise:
![image](https://user-images.githubusercontent.com/3955313/45887079-80ae9e80-bdc3-11e8-89f2-9a4917cd10db.png)

**Comment by TanninOne** [comment]
fixed in 9a3fb40955df457253098247342266dea4ea704f
