### ISSUE TITLE
UI Enhancement: Cycle Rules Popup

### ISSUE THREAD

**Issue by ArtaiosGreybark** [Nexus-Mods/Vortex#1071]
![image](https://user-images.githubusercontent.com/24878945/45924809-772f4e80-bf09-11e8-85dd-6ff18d3da932.png)

As can be seen in the above screenshot, it is really difficult to tell the mods apart since many of them have complex names and the comma serves as a poor separator. Additionally, Vortex will always display the original mod name and not the one you have renamed the mod to in an effort make it readable.

![image](https://user-images.githubusercontent.com/24878945/45924845-2b30d980-bf0a-11e8-83ec-b107a8d97560.png)

Here it would be nice if Vortex told us how the other mod is set to load. If it set to load before or after. This makes it easier to resolve cycles without having to go back and forth.

**Comment by TanninOne** [comment]
current Vortex releases show the full name of the mod to the left of the rule type and also have a more obvious way of displaying the "inverse" rule on the referenced mod.

With commit fed81ab11b5e21d99485d1d21077b22664d2a4c6 we now also show the customised mod names in the dialog and " -->  " as the separator which is hopefully a bit better to read.
