### ISSUE TITLE
Bannerlord on GOG detection

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#10751]
Detect MnB2: Bannerlord installs on GOG.

https://www.gogdb.org/product/1802539526
https://www.gogdb.org/product/1564781494

I think it's the first one, but here are the two IDs from GOG DB

**Comment by IDCs** [comment]
done in https://github.com/Nexus-Mods/vortex-games/commit/1d3289c3f2530c90832cbea50b152baeab020ec6
