### ISSUE TITLE
Any Game can not start

### ISSUE THREAD

**Issue by ReneMuetti** [Nexus-Mods/Vortex#10790]
**Describe the bug**
When I try to start a game via the Vortex Manager, only different error messages are displayed. But if I then start the game via the corresponding Steam link, there are no problems

**To Reproduce**
1. Go to 'any Game'
2. Click on 'Run'
3. See error

**Expected behavior**
The game should be started. Instead, only an error message is displayed

**Screenshots**
https://info-panel.net/vortex/error1.png
https://info-panel.net/vortex/error2.png
https://info-panel.net/vortex/error3.png

**Platform (please complete the following information):**
 - Windows 10.0.19044
 - Vortex Version 1.4.16

**Comment by TanninOne** [comment]
please provide the log file with your report (c:\users\<username>\appdata\roaming\vortex\vortex.log and vortex1.log)

**Comment by ReneMuetti** [comment]
I would like to provide the LOG files - but the directory is empty.

**Comment by ReneMuetti** [comment]
i could uninstall everything again and then reinstall completely. I would also empty the directory in question so that the installer has to recreate everything in it.

**Comment by ReneMuetti** [comment]
I have found some LOG files in the program directory. Maybe these help with the troubleshooting.
https://info-panel.net/vortex/Vortex.rar

**Comment by TanninOne** [comment]
Your system is misconfigured to the point where the  backend we use (electron) can't operate correctly any more.
You have a reparse point for the appdata directories so appdata\roaming resides on e:\roaming while the windows configuration still points at C:\Users\Internet\AppData\Roaming

electron can't deal with application code being in reparse points so any vortex extension that has been manually installed or updated doesn't load correctly.
That isn't something we can fix on our end
