### ISSUE TITLE
Enabling 2 mods with conflicting files may lead to unexpected winning/losing roles.

### ISSUE THREAD

**Issue by lolzcalvin** [Nexus-Mods/Vortex#108]
Enabling one mod, then enabling second mod with conflicting files may overwrite the former one even after adding rules to load latter mod BEFORE former mod.

**Example and walkthrough:**
Game: Fallout 4
1. Download and install [AWKCR](https://www.nexusmods.com/fallout4/mods/6091), then download and install [concealed armor](https://www.nexusmods.com/fallout4/mods/6434/).
2. Enable AWKCR first. AWKCR has the most recent ArmorKeywords.esm (10/10/2017).
3. Enable concealed armor, which then will lead to conflicts showing up. Concealed armor has an older ArmorKeywords.esm (19/12/2015). 
4. Don't enable all concealed armor plugins (it has multiple plugins).
5. set rule to load concealed armor before AWKCR.
6. Enable ConcealedArmor.esm and ConcealedArmor.esp from plugins tab.
7. sort load order.
8. check Fallout 4/Data folder for the hardlink of ArmorKeywords.esm.

Result: ArmorKeywords.esm is still pointing to the one in concealed armor (19/12/2015).

**Comment by TanninOne** [comment]
I don't think this is still the case in current releases, please re-report if it does still occur after all.
