### ISSUE TITLE
Oblivion: The Vortex load order doesn't work

### ISSUE THREAD

**Issue by Irv1n3** [Nexus-Mods/Vortex#109]
I don't know if it's a hardware issue on my side but the reproduce steps are straightforward:

1. Install Oblivion Deluxe (Steam version)
2. Install the 3 UOP with Vortex
3. Check the plugins order, everything seems fine
4. Close Vortex
5. Launch Oblivion Mod Manager
6. The plugins order is totally different that the one noted in Vortex

**Comment by TanninOne** [comment]
fixed by https://github.com/Nexus-Mods/extension-plugin-management/commit/1bcfd49c888496ba86a51ef6e78f15ecab73f92e
