### ISSUE TITLE
Explore requirements for support on Steam Deck

### ISSUE THREAD

**Issue by demortes** [Nexus-Mods/Vortex#10957]
I'm wondering if there was consideration of getting the application listed on Steam or somehow supported on the Steam Deck so that games on the device can be modified using Vortex.

Since it's open source, I wonder what the maintainers of Vortex might think about it, what they would want from it, and once I get my Steam Deck (After Q2 estimated arrival), perhaps I might be able to spend some time helping out, or someone more expierenced might be able to.

**Comment by IDCs** [comment]
This is indeed something we could look at once the device is released.

**Comment by demortes** [comment]
I think theoretically is to get the software listed on steam. Would broaden
your target audience as well.

**Comment by ashtonx** [comment]
To be honest you can try it now with running some linux install. 
Aside from making more eyecandy ui it's not much  different.

What is different is making vortex run on linux and handling wine prefixes.

Steam afair creates separated prefix for each game. And mounts the needed directory, question is what would be best way to handle it. Personally I'm not really that knowledgable about wine to answer it, but if anyone wants to handle it I'd start here.

https://wiki.winehq.org/FAQ#Wineprefixes

Also check out proton source, it's python that handles joining all various parts together.

Yes I just want this stuff without putting work in ^_^;

**Comment by szszoke** [comment]
Wine prefixes are just folders after all that contain a similar file tree to your Windows C partition.

If there is a mechanism today that scans the file system for games, it should be able to work on Linux as well.

For games that use Proton, the location of the wine prefixes is in <STEAMAPPS>/compdata/<GAME_ID>.

I think the trickier part would be to launch the games. They should be somehow launched via the same Proton version as they would be when they are launched directly via Steam.

**Comment by Yu-457** [comment]
Hi all, 
is there any update/Roadmap on this one? 
Ive been trying to get it to work trough lutris but without success. Would be great to see it running natively on the steam deck !

**Comment by IDCs** [comment]
Unfortunately no update on this yet; small team, lots of work, etc.

But in the meantime - you can mod your game through the magic of copy-paste
https://www.youtube.com/watch?v=Hv8VOkIgwvU

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here as the Nexus Mods App team are already working on support for the Steam deck. You can track their progress by following this epic and related issues: https://github.com/Nexus-Mods/NexusMods.App/issues/148

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
