### ISSUE TITLE
Switching games heavily slow, if mod download folder on NAS

### ISSUE THREAD

**Issue by AzedraX** [Nexus-Mods/Vortex#11005]
**Describe the bug**
To safe space on the SSDs in my computer, I have set up my download folder of Vortex on my NAS. If I active another game, it seems that Vortex start reading the complete download folder with all its archives of the to be actived game, also if there are no changes. For games with many and/or big mods (e.g. FO4 with 115 GB of mod archives in my case), it takes endless time for Vortex to read all archives through the network.

This is not a bug in principle, but makes Vortex for me more or less unusable.

**To Reproduce**
-

**Expected behavior**
The possibility to shift quickly between the games, if the download folder is on a NAS :)

**Screenshots**
-

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.5.1 BETA

**Additional context**
-

**Comment by IDCs** [comment]
Unfortunately this is a use case we just can't reliably debug or assist with. There are too many environmental factors in place that could cause the delay such as - are you connecting through WiFi ? are you sure there is no packet loss ? does the NAS drive go into sleep mode when inactive and is forced to boot up every time Vortex attempts to query a file ? does the NAS drive have a security system of any sort that may delaying file operations ? What are the NAS drive specifications ?

Vortex itself is using system level file operations - if Vortex can't reliably read your drive, then I think you'll find that all other applications that query your NAS drive will have the same problem.
