### ISSUE TITLE
Vortex finding old profiles in One Drive instead of new Baldur's Gate 3 Patch 7 location

### ISSUE THREAD

**Issue by beodawn1** [Nexus-Mods/Vortex#11072]
**Describe the bug**
I have just done a clean install of Baldur's Gate 3 on C drive at C:\Steam\steamapps\common\Baldurs Gate 3. I have checked that the patch 7 profiles *are* in the correct location for patch 7 and they are and I have 3 profiles made. Two just for testing to see if mods will work and they are not. Mods downloaded from Nexus are installed in Vortex just fine but when you get to the point where you have to choose the profile, it finds 5 profiles that were from early 2021 that I haven't played in a very long time and just happened to, by bad luck, deleted from One Drive and the in game Profiles earlier today. I have never used mods with Baldur's Gate and never realized I needed a profile to match plus I expected a new profile to work. 

Vortex is not locating the new patch 7 profiles.

I just downloaded and reinstalled the newest version of Vortex as well. 

It still sees those same 5 profiles. Now oddly enough I had like 20 profiles so I don't know why it is stuck on those 5 from a year ago in One Drive, especially when I deleted One Drive's Larian folder. 

**Expected behavior**
I expect to be able to match my vortex mods to patch 7 profiles

**Screenshots**

**Platform (please complete the following information):**
 - OS: windows 10
 - Vortex Version 1.4.17

**Additional context**

**Comment by beodawn1** [comment]
I just got a flash error from Vortex saying that it couldn't locate my profile (one of the 5) in it's documents folder... so yes it is still looking for it in the old location

**Comment by beodawn1** [comment]
The baldur's gate 3 extension version is 1.0.5

I can't get it to remove and I can't find a way to update it

**Comment by TanninOne** [comment]
Vortex 1.5.3 will support the new location used since patch 7

**Comment by AlonelyWalrus** [comment]
I'm having a similar issue, I deleted an in-game profile due a mod issue and created a new one, now Vortex is not picking up the new profile, the file path it is using is for the old profile  'C:\Users\(Myname)\OneDrive\Documents\Larian Studios\Baldur's Gate 3\PlayerProfiles\(Deleted Profile)\modsettings.lsx'

I then went into the documents and deleted the "Player Profiles" file as it still had all my old profiles saved games, I then clean reinstalled the game thinking it would auto create the "Player Profiles" file with my new Profile in there, it didn't. Now I have no idea where my new saved games are, I have saved them as wacky names to make them easily searchable in my PC but nada, and I can't link the new profile to Vortex as Vortex will only look for this deleted file path...
