### ISSUE TITLE
Issue report when there is no issue

### ISSUE THREAD

**Issue by Katarsi** [Nexus-Mods/Vortex#1109]
![screenshot 38](https://user-images.githubusercontent.com/43729860/46261440-cd952200-c4f3-11e8-9b3a-6c5c2dc56538.png)

**But actually...**

![screenshot 40](https://user-images.githubusercontent.com/43729860/46261522-fcf85e80-c4f4-11e8-91e7-d0f8eb7e1fc2.png)

I don't know why it says that SkyUI isn't installed, when it apparently is.

**Comment by IDCs** [comment]
Fixed in https://github.com/Nexus-Mods/extension-plugin-management/commit/f7061bff3eb0cf547330e3715bf78c559df38cb8
