### ISSUE TITLE
Backup/Restore Directory

### ISSUE THREAD

**Issue by trymeouteh** [Nexus-Mods/Vortex#11192]
Please have a setting in Vortex to also store the mods you download into another directory which you use to easily backup the mods for yourself. Essentially you can set a directory such as _Downloads/Vortex Mods Backups/(Game Title)/_ and in there you can now and then copy the files in that directory and back them up however you like such as the cloud or a harddrive.

When there is a update for a mod you downloaded, it will be downloaded into your backup folder also.

The files in the backup folder will be the archived files of the mod such as mod001.7z or mod002.rar.

Maybe also adding a setting/feature for when a mod is placed in the backup folder, it will uncompress it and recompress it to the file type and compression level you prefer so you can have all of your backups be 7z files with ultra compression?

And this directory can be used to easily restore and install mods on new computers buy placing the archived mod files into the backup directory and instead of Vortex downloading the mod and installing it, it will just install the mod using the archive in the backup directory, no need to download it again from nexusmods meaning less bandwidth for nexusmods to dish out.

I like keeping backup of all of my mods and having a built in feature in Vortex will make this process more automated and easier to do when one uses lots of mods for many different games.

**Comment by TanninOne** [comment]
I don't think this is within the scope of Vortex. There are plenty of applications you can use to create backups
