### ISSUE TITLE
App/Installer fails with Uncaught Exception

### ISSUE THREAD

**Issue by bkitej** [Nexus-Mods/Vortex#11204]
**Describe the bug**
App/Installer experiences an Uncaught Exception.

**To Reproduce**
1. Download from "Manual Download" button.
2. Open application installer.
3. Two "Vortex Setup" boxes pop up, one with a progress bar, one saying "Vortex is running. Click OK to close it." The progress bar hangs, unless/until "OK" is clicked on the other box. 

**Expected behavior**
The program to install.

**Platform (please complete the following information):**
 - OS:Windows 10
 - Vortex Version 1.5.5 (though 1.4.17 experiences the same/a similar error)

![image](https://user-images.githubusercontent.com/31401313/155718484-520427e0-1a7e-46bd-ab88-cc50e9614688.png)

![image](https://user-images.githubusercontent.com/31401313/155718572-2975dc9d-33da-46b3-8cc7-8a766f5a50aa.png)

**Comment by TanninOne** [comment]
This is caused by something on your system, most likely the AV, interfering with Vortex loading one of its modules.
