### ISSUE TITLE
Improve INI coverage for Bethesda games

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#11251]
**Is your feature request related to a problem? Please describe.**
Vortex does not include all relevant INI files for some of the games it supports.
https://github.com/Nexus-Mods/extension-gamebryo-testsettings/blob/4f928ce3e73aac9e10455620b0f632d70c61ba16/src/util/gameSupport.ts#L14
https://github.com/Nexus-Mods/extension-local-gamesettings/blob/29c66de5c8de6a6f324079848d7e9f6535680641/src/util/gameSupport.ts#L45
https://github.com/Nexus-Mods/extension-collections/blob/d53922f98a14aecc8db1b189f861bbbacbed7b4c/src/initweaks.ts#L11
https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/ini_prep/gameSupport.ts#L26

**Describe the solution you'd like**
Add the following INIs

### Skyrim SE
- SkyrimCustom.ini
### Fallout 3
- FalloutPrefs.ini
- FalloutCustom.ini (Requested by @ceana7 below)
### Fallout 4
- Fallout4Custom.ini

**Additional context**
These INIs should be managed by profiles and tweakable in Collections.

**Comment by Ceana7** [comment]
I would also like to add that for fallout 3 if [Command Extender](https://www.nexusmods.com/fallout3/mods/23682) is installed there is also FalloutCustom.ini which if present will overwrite both FalloutPrefs.ini and Fallout.ini which is identical to the feature JIP LN NVSE adds to Fallout New Vegas.

**Comment by IDCs** [comment]
@Ceana7 - that would force us to add Command Extender as a hard requirement which I can't justify doing. In most cases the default INI's should be sufficient.

**Comment by Ceana7** [comment]
@IDCs That's what I was going to suggest as I remember there being a commit a while back that did the same thing with Fallout New Vegas regarding the custom ini added by JIP LN NVSE.

**Comment by IDCs** [comment]
done
