### ISSUE TITLE
[0.16.8] "Application state is invalid" after update from 0.16.7

### ISSUE THREAD

**Issue by Anvirol** [Nexus-Mods/Vortex#1137]
Looks like every update is an adventure.

My .ini files weren't read-only, so it's something new. 
0.16.7 was working fine after read-only was removed.

![image](https://user-images.githubusercontent.com/3955313/46434175-8b6e1980-c75b-11e8-9fdf-775a0b5707fa.png)

Initially it looks like it's working after executing repair, but it's probably too early to tell if something is gone.

**Comment by TanninOne** [comment]
This was expected with this update and it's mentioned in the changelog.
As we fix bugs in Vortex we will occasionally find out that earlier versions left stuff in the application state that's somewhere between useless or harmful and then we use this verification step to clean it up.

**Comment by Anvirol** [comment]
> 
> 
> This was expected with this update and it's mentioned in the changelog.
> As we fix bugs in Vortex we will occasionally find out that earlier versions left stuff in the application state that's somewhere between useless or harmful and then we use this verification step to clean it up.

Thanks for clarifying that 👍 
I read the release notes, but couldn't connect the dots between this pop up and the note "fixed: download state verification (may trigger repair dialog on startup)"
