### ISSUE TITLE
Save Button donot work in Conflict Menu

### ISSUE THREAD

**Issue by sorrytome** [Nexus-Mods/Vortex#114]
After the update to Vortex 0.13.6
I am unable to Click Save Button in Conflict Menu.
The Image of that is down (Save button donot work)
![untitled](https://user-images.githubusercontent.com/33935257/38175237-0be9c7de-35f9-11e8-84ba-255d9542a76c.png)

This seems to happen only when the manually downloaded mod is install without putting it in Download Directory of Vortex..

**Comment by AnotherFoxGuy** [comment]
The save button seems to be fixed in 0.14

**Comment by TanninOne** [comment]
correct
