### ISSUE TITLE
Allow externally installed mods to check for and/or install updates via Github releases.atom

### ISSUE THREAD

**Issue by cure1245** [Nexus-Mods/Vortex#11415]
While Nexus has a great many mods available for games, there are many that have either stopped being uploaded to the Nexus website (e.g., new maintainer chooses to update to Github), or mods that were never in Nexus in the first place. If a user of Vortex has many of these external mods, updating becomes a very unwieldy and time-consuming process.

Seeing as Github is probably the single largest place that hosts external mods, the ability to download and install an update based on a new entry in a given project's RSS feed (https://github.com/:owner/:repo/releases.atom) would be an excellent addition to Vortex. If that can't be done, then at the very least a notification that there is a new version of an external mod would probably be an acceptable alternative for many.

**Comment by TanninOne** [comment]
This functionality could be added through the extension system and no one would stop you.
However: The development of Vortex is currently funded to 100% through ads and premium subscriptions from nexusmods, you can't really expect us to use that money to make it easier for people to avoid the site.
