### ISSUE TITLE
Enhancement: Set base mod install path

### ISSUE THREAD

**Issue by chill0r** [Nexus-Mods/Vortex#1148]
**Version:**  
0.16.8 (custom install location)  

**Description:**  
Currently the mod install path is set per game to the default directory *{USERDATA}\\{GAME}\mods*.  
Adding a global option to set this base path would remove the need to change it everytime you add a new managed game.

**Comment by TanninOne** [comment]
Not worth it tbh, sorry. Setting the mod install directory is a matter of seconds, even if you have a lot of games we're talking about a one-time setup that takes mere minutes here.

If we add another setting that makes the settings screen more complex, it could confuse users what they have to change and (maybe most importantly) if you change the base directory we'd have to move the mod files of _all_ games which could take ages, go wrong and with a very high chance that users do it accidentally this has so much potential to create hate I'm not going to do it in the hope of maybe saving some users a minute or two.
