### ISSUE TITLE
error: The Sims 4 mod directory on different language

### ISSUE THREAD

**Issue by chill0r** [Nexus-Mods/Vortex#1149]
**Version:**  
0.16.8 (custom install location)

**Description:**  
Activating "The Sims 4" leads to error  
*Missing: C:\Users\\$USERNAME$\Documents\Electronic Arts\The Sims 4\Mods*.  
Depending on the language (on my side it's german) the directory is named differently.  
*C:\Users\\$USERNAME$\Documents\Electronic Arts\Die Sims 4\Mods* would be the directory for the german installation for example.

**How to reproduce:**  
1. Install "The Sims 4" in another language than english.  
2. Add "The Sims 4" in Vortex as managed game  
3. Activate "The Sims 4" inside Vortex as selected game

**Comment by chill0r** [comment]
@Pickysaurus that's only for locating the main game directory, not the mods directory in the case of sims.  
The main game directory is found without problems

**Comment by IDCs** [comment]
Fixed in https://github.com/Nexus-Mods/vortex-games/commit/4e69cd165fbb0b495f1266d9c9d83eae034fcd90
