### ISSUE TITLE
Better mod sorting

### ISSUE THREAD

**Issue by Alatarius** [Nexus-Mods/Vortex#11629]
I have been frustrated that I am unable to categorize mods. Most mod creators don't add a tag to what type of mod it is (Construction, Visuals, Audio, etc.) However Vortex doesn't allow this and I have many mods that have no category and it's a pain to sort through them all when I have a huge list and maybe 1-2% are properly categorized by the creator.

It would be nice to have a system where someone can categorize their mods themselves to better fir their own organizational system.

![Vortex](https://user-images.githubusercontent.com/101660302/162247083-e40ee223-57ff-4e19-b3f7-2e573f2b1e38.png)

[edit]
These are the only options available:

![options](https://user-images.githubusercontent.com/101660302/162247859-4b20d0b2-2a99-45e6-8c82-85e68d97c08e.png)

**Comment by TanninOne** [comment]
Of course you can assign categories, just double click the mod and then find the categories dropdown in the sidebar.
