### ISSUE TITLE
Vortex does not release its handle on `Skyrim - Interface.bsa`

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#11672]
**Describe the bug**
If a user wants to replace their `Skyrim - Interface.bsa` file in a mod, they are unable to deploy it because it will show as "in use" by another application. 

After checking Resource Monitor in Windows 11, it appears that Vortex creates a filehandle for this file during startup and never releases it. Meaning then when it attempts to deploy this file, it's still "open". 

This could be a problem with the BSA-reading library used as part of the fonts check? 

**To Reproduce**
1. Install Skyrim - Interface.bsa as a Skyrim SE mod. 
2. Attempt to deploy.
3. See error.
4. THEN - Close Vortex entirely
5. Open Resource Monitor in Windows
6. Under "Associated Handles" search for `Skyrim - Interface.bsa`. Note there are no results.
7. Start Vortex.
8. Refresh the handle search in the resource manager.
9. Note that Vortex maintains a persistent handle for this file. 
10. Attempt to deploy. 

**Expected behavior**
The `Skyrim - Interface.bsa` is correctly released when not in use. 

**Screenshots**

Showing a deployment attempt in resource manager
![image](https://user-images.githubusercontent.com/31670524/162750587-950c7a75-9a6f-48f3-b0ac-7f1e31fa5ad8.png)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by Pickysaurus** [comment]
Related thread on the forums: https://forums.nexusmods.com/index.php?/topic/11280753-engine-injector-setting-and-downgrading-skyrim-aese/

**Comment by IDCs** [comment]
Done
