### ISSUE TITLE
[UX] clicking to queue a mod shifts list at unpredictable times

### ISSUE THREAD

**Issue by Helios747** [Nexus-Mods/Vortex#117]
Right now, if I click to install a mod, it queues it up. Great.

What's not great, is that I basically can't queue a ton at once with my mouse because the list restructures when it goes from installing to finished.

A reasonable solution that doesn't involve redesigning the UI is to just keep the list as it is, and don't restructure the list. Just change the status.

If you don't mind getting your hands dirty, the list could be redesigned to be dual pane with installed mods and available mods.

**Comment by TanninOne** [comment]
I'm not sure what you mean, the list is always sorted by one attribute. Unless you sort by an attribute that changes during install (like the installation time), what get's restructured there?

**Comment by TanninOne** [comment]
closed due to lack of feedback
