### ISSUE TITLE
Vortex not enabling mods for Skyrim VR

### ISSUE THREAD

**Issue by skeezerbean** [Nexus-Mods/Vortex#118]
I had downloaded quite a few mods for Skyrim VR, and it did a great job of asking for each if I wanted to use them for Skyrim VR, and enabled in the plugins.txt file. Later after I had closed and reopened Vortex, any new mods I downloaded, then installed, then enabled, never update the plugins.txt file.
This is using 0.14.0 on Windows 10, not sure what other info you may need

**Comment by TanninOne** [comment]
Please create a new issue if this still happens with 0.17.x
