### ISSUE TITLE
Update Blade & Sorcery support for 0.11

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#11891]
In Blade and Sorcery 0.11, there are two changes we'll need to review in order to continue supporting the game properly. 

The game.json version detection should be retired (although we may want to keep it for a few months for players who are still on 0.10). 

Both the game version and minimum mod versions will now be in the EXE details.

![image](https://user-images.githubusercontent.com/31670524/167870338-0e770dcc-f9da-49e4-9830-3075f911ba97.png)

File Version = Game Version
Product Version = Minimum Mod Version

If the mod manifest `GameVersion` does not exactly match the Product Version, the mod is considered incompatible. 

Edit: for the purpose of Collections we might want to ship the Product Version as this is more relevant?

**Comment by IDCs** [comment]
done in https://github.com/Nexus-Mods/vortex-games/commit/8264368d912f66b7f99fd9956683db781a29fa38

**Comment by IDCs** [comment]
Yes - it's backwards compatible
