### ISSUE TITLE
Sync sources in a collection workshop with the sources in the modlist

### ISSUE THREAD

**Issue by lgbtqPP** [Nexus-Mods/Vortex#11901]
**Is your feature request related to a problem? Please describe.**
Currently when creating a collection in the workshop, I have to manually add the sources again, even though the sources are added in the mods section. This is quite cumbersome and tedious.

**Describe the solution you'd like**
Whenever a mods source is changed in either the modlist or the workshop, it should automatically update the source in the other section.

**Describe alternatives you've considered**
Not really any alternative here, except to do it manually.

**Comment by TanninOne** [comment]
The sources information on collections is more detailed than it has to be for mods, you wouldn't be able to set all information on collections and thus would still have to toggle between the two screens.
Besides: We would be taking options away from curators who may _want_ to have different sources between their local setup and what they give out.
