### ISSUE TITLE
Reinstalling a mod will sometimes duplicate it

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#11945]
**Describe the bug**
When reinstalling a mod, it sometimes appears twice in the "Version" drop-down even though only one version it actually installed. 

**To Reproduce**
1. Download and install: https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=282492&nmm=1&game_id=1704
2. Check for updates
3. Install the update 1.8.0 (or above?)
4. Once installed, reinstall 1.8.0, updating all profiles.
5. See that it shows twice in the version drop-down

**Expected behavior**
Reinstalling does not duplicate the version in the drop-down. 

**Screenshots**
![image](https://user-images.githubusercontent.com/31670524/169836108-5b0f3861-aff2-43d0-916f-a44a528aa22f.png)
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/8755154/vortex.log)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by IDCs** [comment]
fixed
