### ISSUE TITLE
About Vortex Issue Code: EPERM

### ISSUE THREAD

**Issue by CheeseBoi12** [Nexus-Mods/Vortex#11970]
How do I have full read/write permissions to your "Program Files" folder for Vortex. I'm trying to purge Fallout 4, but every time I try I get that error that Vortex needs to have access to 'C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\src\common\common.vcproj'
but its written protected. I just need help on how to actually do this. If you can please tell me step by step of how to do this because I would really like to have this issue fixed.

**Comment by TanninOne** [comment]
You control file permissions through windows explorer. Right click the file or folder -> properties -> security.
There you can assign permissions (you want to allow write, you should already have read) for your own account or for the users group as a whole.
If you give permission for a folder that will affect all subdirectories and files within as well unless you explicitly override it further down, so giving yourself write access to "C:\Program Files (x86)\Steam\steamapps\common\Fallout 4" you should then also have that permission for C:\Program Files (x86)\Steam\steamapps\common\Fallout 4\src\common\common.vcproj" and everything else alongside it.
