### ISSUE TITLE
Plugins.txt and Loadorder.txt for Xbox Game Pass aren't correctly detected. 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#11985]
**Describe the bug**
Bethesda seems to have moved the location of the `plugins.txt` file for Skyrim SE, meaning that Vortex no longer writes the load order correctly.

Old location: `%localappdata%\Packages\BethesdaSoftworks.SkyrimSE-PC_3275kfvn8vcwc\LocalCache\Local\Skyrim Special Edition MS\Plugins.txt`

New location: `%localappdata%\Skyrim Special Edition MS\plugins.txt`

This may also apply to other Bethesda games. (Testing required) 
- Fallout 4 - `%localappdata%\Fallout4 MS`
- Fallout 3 - `%localappdata%\Fallout3`
- Fallout NV - `%localappdata%\falloutnv`
- Oblivion - `%localappdata%\Oblivion`

Further to this, the Xbox app now lets you install the game to a custom location (e.g. `C:\Games\Xbox\The Elder Scrolls V- Skyrim Special Edition (PC)\Content`) so the logic for determining if an install is from Game Pass no longer works as it relies on the game install path containing a specific string. Can we consider storing the game store as part of the game detection so that it can be used by logic that depends on it? This may include a drop-down under "manually set location" that would let users change it. 

**Expected behavior**
I am able to manage plugins for Xbox versions of Skyrim SE.

**Comment by Pickysaurus** [comment]
All games checked, ticket updated.

**Comment by IDCs** [comment]
The xbox path detection appears to function just fine which means we simply had to ensure we point towards the `%localappdata%/{game}` paths.
