### ISSUE TITLE
Fallout 3 "Failed to deploy mods"

### ISSUE THREAD

**Issue by Goofysoccer** [Nexus-Mods/Vortex#120]
Hello,
My Vortex fails to deploy mods. For reference, Steam is installed on my C drive, Fallout 3 was installed on my C drive through Steam and moved to my D drive (with a symlink on the C drive so the directory is on the D drive), and Vortex is installed on my D drive. My base path is on the D drive. [Here is a link to the log.](https://pastebin.com/Ek1HeP4v)

**Comment by Goofysoccer** [comment]
I fixed the issue by disabling the Vortex archive invalidation

**Comment by TanninOne** [comment]
This error should be fixed in 0.14.0
