### ISSUE TITLE
Vortex lost all metadata after port to new host... how to recover?

### ISSUE THREAD

**Issue by RootlessAgrarian** [Nexus-Mods/Vortex#12015]
I'm using Vortex to manage Nexus mods for SkyrimVR.

I upgraded to a more beefy gaming PC, which meant porting my entire Steam library including SkyrimVR.

This meant that pathnames changed for Vortex default locations like mod staging folder and mod download folder.

All of this seemed to go OK, my mods are all working, but Vortex no longer has any metadata such as source, version, etc.  So I can't use Vortex  to update any mods.

Where does Vortex store that metadata and is there a way to restore what was lost across the port to new host?

**Comment by IDCs** [comment]
http://wiki.tesnexus.com/index.php/Moving_your_Vortex_Mod_Setup_to_a_new_Computer
