### ISSUE TITLE
extension

### ISSUE THREAD

**Issue by ggtiao** [Nexus-Mods/Vortex#12037]
![image](https://user-images.githubusercontent.com/23329070/172730589-b9e0b062-3901-41b7-b67f-222339adb8fa.png)

**Comment by IDCs** [comment]
We (Vortex support) cannot debug networking/protocol issues - if the problem persists, contact our web team instead https://github.com/Nexus-Mods/web-issues

If you're using VPN/Proxy or have any security software (some anti-viruses can at times redirect or corrupt packets) disable them and try again
