### ISSUE TITLE
A way to surpress redundant mod message.

### ISSUE THREAD

**Issue by Creshosk** [Nexus-Mods/Vortex#12059]
**Is your feature request related to a problem? Please describe.**

I constantly have the "This mod is redundant" message.
The problem is there are other mods that are dependent on the redundant mod because of the way they look for certain file names.
I disable the redundant mod and I get a message about missing masters and unfulfilled dependencies. Sometimes at the same time. So having the "redundant" Mod satisfies some of the requirements of other mods.

Disable redundant mod and I get told that it's required by other mods.
Enable it and I get told it's redundant.

Why can I suppress errors that do effect the game, but not ones that only effect deployment and not the game itself?

It doesn't even tell me what other mods are making it redundant, just to disable the mod that's a master to other mods.

**Describe the solution you'd like**
Just a way to suppress that message. Yes, deployment of the mods might takea little longer. I'm fine with that since it still happens really quick. But I'd like to be able to hide the message rather than being yelled at by the program in a loop of "This redundant mod is required by other plugins."

**Additional context**
![image](https://user-images.githubusercontent.com/107381888/173276488-b1a5ff78-02db-4406-aec1-0aabde87a91b.png)
![image](https://user-images.githubusercontent.com/107381888/173276570-adf4e569-4d11-4717-8d6d-c5eb10e30278.png)
![image](https://user-images.githubusercontent.com/107381888/173276592-4712be81-8f5d-48d4-aa46-1f7b4f0dde8e.png)

**Comment by TanninOne** [comment]
Redundant mods **DO NOT** affect the game, that is the whole point of the message. Nothing can depend on it because it does nothing.
The mod is either fully replaced by another one (potentially a second copy of the same mod) or it is empty (e.g. because it wasn't installed correctly or deleted after). 
The second screenshot you posted even confirms that you are actually missing files that would be required. That is a second check independently saying the same thing.

Don't ignore this message, don't suppress the message, fix the cause.

**Comment by Creshosk** [comment]
It'd be nice if the people would actually read what's being said. I don't know how to fix the cause because my only option given is to disable the mod that Vortex claims is redundant.
Which then breaks the dependency others have on the redundant mod.

**Comment by TanninOne** [comment]
It's funny how you claim I hadn't read your message when you haven't read the initial notification you want to suppress
You say
> It doesn't even tell me what other mods are making it redundant

But there is a bloody "Review" link that would tell you exactly that and a suggestion to look at file conflicts that would also tell you which mods are conflicting.

**Comment by Shrimperator** [comment]
I would actually really like a way to just disable this message, too, even though it serves its purpose perfectly well :)

The reason: I'm fully aware I have redundant mods installed, and intentionally don't want to disable them. The reason being: if I remove one or some of the mods causing the redundancy (by fully overriding another mod), suddenly the initial mods (which were previously fully overridden) aren't redundant anymore. Now I'd have to go back and remember which mods I had enabled originally, before they were overridden by the now-removed mod.

As it stands now, I just keep having to click the message away, even though I definitely don't need it. A way to acknowledge that some mods are redundant and not to show the message again for them would be neat.

Just throwing my 2 cents in here: there are definitely instances where redundant mods are intended to be kept by the user. And even having one such instance means having to click away the same message over and over again.
