### ISSUE TITLE
Plugin tab disappeared

### ISSUE THREAD

**Issue by Natouuu** [Nexus-Mods/Vortex#12071]
Vortex version : 1.5.13
Windows 10

After enabling a mod in game in the load order (skyrim se), the game crashed on loading a save and now the plugin tab is missing 

The plugin tab under mods is no longer here, the extensions "gamebryo bsa support " and "gamebryo plugin management" are both on failed and i can't enable them back.

Error message on the extension : failed to load: The specified module could not be found.
\\?\C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\node-loot.node

After enabling a mod in game in the load order (skyrim se), the game crashed on loading a save and now the plugin tab is missing 

[vortex.log](https://github.com/Nexus-Mods/Vortex/files/8901558/vortex.log)

**Comment by Pickysaurus** [comment]
Possible duplicate: https://github.com/Nexus-Mods/Vortex/issues/12041

**Comment by IDCs** [comment]
Pretty sure the savegame crash occurred for the same reason Vortex can't load those libraries anymore.

Try downloading and installing the latest C++ redistributable and let us know if that helps https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Pickysaurus** [comment]
According to this thread (https://forums.nexusmods.com/index.php?/topic/11602493-vortex-win-10-defender-and-hair-loss/#entry110866713) the proposed solution worked.

**Comment by IDCs** [comment]
Thanks for confirming @Pickysaurus
