### ISSUE TITLE
supportedTool is reported available even if Target does not exist

### ISSUE THREAD

**Issue by Bladehawke** [Nexus-Mods/Vortex#12086]
**Describe the bug**
Possibly related to #12073, If a tool is removed from the filesystem, the tool button remains active (not greyed out) even after refresh and Vortex restart.

**To Reproduce**
1. Set up a tool in the dashboard
2. Remove the tool from the filesystem
3. restart vortex
4. tool remains active
5. clicking the tool launch button shows error dialog 

**Expected behavior**
If the tool path is invalid at set game mode start or 'discover-tools' event, the button should grey out indicating that it won't work

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.5.13

**Additional context**

**Comment by IDCs** [comment]
Thanks for your report - a bare minimum file validation is now done whenever a new tool is added or when the tools order changes. This will of course ensure that the tool becomes invalid when restarting Vortex.
