### ISSUE TITLE
Xbox Game Pass Games in a custom location aren't detected properly. 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#12109]
Follow up to this ticket: https://github.com/Nexus-Mods/Vortex/issues/11985

> Further to this, the Xbox app now lets you install the game to a custom location (e.g. C:\Games\Xbox\The Elder Scrolls V- Skyrim Special Edition (PC)\Content) so the logic for determining if an install is from Game Pass no longer works as it relies on the game install path containing a specific string. Can we consider storing the game store as part of the game detection so that it can be used by logic that depends on it? This may include a drop-down under "manually set location" that would let users change it.

Much of the logic around "is this an Xbox game?" relies on reading the discovery path, which may not be correct or expected anymore, especially when the location is set manually by the user.

**Comment by IDCs** [comment]
Vortex still resolves this information correctly as the program data path is still generated. Stop assuming functionality - if you encountered an issue and can reliably reproduce it, post a step by step guide for us to test. Closing as this ticket has no information for us to go on.
