### ISSUE TITLE
Allow grouping of multiple versions of a manually installed mod

### ISSUE THREAD

**Issue by lgbtqPP** [Nexus-Mods/Vortex#12103]
**Is your feature request related to a problem? Please describe.**
When installing a mod from a file and then installing a new version of that mod from another file, they don't get grouped together even when they are named the same thing and their version numbers are set different.

**Describe the solution you'd like**
Group mods together when they have the exact same name.

**Describe alternatives you've considered**
N/A

**Additional context**
![temp](https://user-images.githubusercontent.com/88749068/174457897-dff65395-3309-4916-a02b-8c253ebb1dc8.png)

**Comment by Pickysaurus** [comment]
Grouping depends on Nexus Mods metadata. If they aren't files from the website, it's difficult to group them at present. 

If they _are_ from the website, it's better download them directly with Vortex as then they won't be missing the metadata that allows them to group.

**Comment by lgbtqPP** [comment]
No they are not from nexus, I wanted to have this functionality for other manually installed mods.
