### ISSUE TITLE
Button to open source nexusmods.com page.

### ISSUE THREAD

**Issue by Spasticon** [Nexus-Mods/Vortex#123]
Each mod needs a button/option to open the source nexusmods.com page.

At a minimum. NMM showed additional details as well as had a link to page.

**Comment by TanninOne** [comment]
This exists already, just double click a mod or press space while it's selected and a sidebar opens which, among other things, contains a link to the nexus page.

**Comment by Spasticon** [comment]
Fastest issue turnaround ever!

(That is seriously not very intuitive though, or maybe I've just been using too many SaaS web products to think to double click a list row...)
