### ISSUE TITLE
xSE rules highlighted as an error incorrectly (1.6.1 beta)

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#12339]
**Describe the bug**
The rules for SKSE64 that are automatically set (to warn users if two copies of SKSE are enabled) show a red status on the deployment icon and the rule itself even though there is no issue. 

![image](https://user-images.githubusercontent.com/31670524/178262539-bc7a4197-dffe-495a-b86d-5c45907d5d71.png)

This seems to be more of a visual glitch than anything else as it doesn't block deployment. 

**To Reproduce**
1. Manage Skyrim SE
2. Show the dependencies column
3. Install SKSE64
4. See red UI elements.

**Expected behavior**
If there is no issue, this should not be highlighted (it wasn't in 1.5.x).

**Comment by Pickysaurus** [comment]
Related: https://forums.nexusmods.com/index.php?/topic/11670428-unnecessary-warning-skse-64-215-for-skyrim-ae/

**Comment by Dark-Dominion** [comment]
**Fixed in Vortex 1.6.2 Beta**

----------------------
Released on 7/12/2022
Electron 19.0.7
Node 16.14.2
Chrome 102.0.5005.134

**Comment by IDCs** [comment]
Thanks for confirming @Dark-Dominion
