### ISSUE TITLE
SSE CBBE AIO Install failure

### ISSUE THREAD

**Issue by Bored2022** [Nexus-Mods/Vortex#12382]
**Describe the bug**
I'm not sure if this is a bug per se or a mod error but when I try to use Vortex to install the CBBE AIO- Installer mod for Skyrim Special Edition, Vortex churns out an error. I'm unable to make heads nor tails of it.

**To Reproduce**
1. Select "CBBE- AIO Installer.rar from mods list
2. Vortex will attempt to install the file
3. Once it has gotten around 90%, the error message will pop-up on the screen 
4. Error reads, "Invalid XML: The element 'plugin' has invalid child element 'image'. List of possible elements expected: 'description'. (Line 9, Pos 9)
The element 'plugin' has invalid child element 'image'. List of possible elements expected: 'description'. (Line 21, Pos 9)
The element 'plugin' has invalid child element 'image'. List of possible elements expected: 'description'. (Line 33, Pos 9)

**Expected behavior**
![1-22](https://user-images.githubusercontent.com/105631917/178931350-e5465695-4765-4213-9f4b-865e24fdbc5b.jpg)
![1-2](https://user-images.githubusercontent.com/105631917/178931369-64233119-ea33-4af2-8f6a-cb5b6cf6ea09.jpg)

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10 21H2
 - Vortex Version 1.5.13 (stable)

**Additional context**

**Comment by IDCs** [comment]
The second error screen is clearly telling you that the mod itself has failed validation and that you should inform the mod author about this issue..........

**Comment by Bored2022** [comment]
I have already contacted the mod author, and there has been no reply, hence why I am asking on GitHub. As Vortex refuses to install, it will not function at all.

As it turns out, I have found the same mod on  a different modding website that seems to work as intended. So, this issue is now considered moot.
