### ISSUE TITLE
Downloading mods for Skyrim SE is filling up C drive but my game is installed on my D drive. 

### ISSUE THREAD

**Issue by WHBG-Pukes** [Nexus-Mods/Vortex#12413]
Problem as described by the title, my mod staging folder is in my D drive so I'm not sure why it is filling up my C drive, is there anyway to prevent this? My C drive is now full but there is plenty of space left on my D drive?
![image](https://user-images.githubusercontent.com/109431243/179364904-30e0daf6-b22a-4adc-99a3-533ec81c666d.png)

**Comment by IDCs** [comment]
Make sure your downloads are also sent to D:\ - use the "Download" tab next to the "Mods" tab that is displayed in the screenshot.

Can't help you beyond that - if there's something else that's filling `C:\`, you'll just have to figure out what it is and deal with it.
