### ISSUE TITLE
[Dragon Age Origins] addins is invalid ( ...\_merged.dazip\Settings\AddIns.xml)

### ISSUE THREAD

**Issue by othara2017** [Nexus-Mods/Vortex#12487]
**Describe the bug**
Deployment interrupted

**Expected behavior**
It's supposed to run without any problem as I just download the files from nexus and open with Vortex

**Screenshots**
![2022-07-24](https://user-images.githubusercontent.com/47287814/180615718-4551c213-889d-4a92-82a9-1809a3c4de0f.png)

**Platform (please complete the following information):**
 - OS: Window 11
 - Vortex Version 1.5.13

**Additional context**
I found two issues regarding this problem, addins is invalid ( ...\_merged.dazip\Settings\AddIns.xml), they are not helpful. Note that The mod folder is in the same drive as the game installed, but the Document>Bioware folder is in the different one.

**Comment by XanderRoy** [comment]
I am having this issue as well.
OS: Windows 10
Vortex 1.5.13

I found others solved this problem by[ correcting the steamID ](https://www.reddit.com/r/nexusmods/comments/trqz88/comment/i8ryai4/?utm_source=share&utm_medium=web2x&context=3), but I have not been able to get it fixed yet.

**Comment by TanninOne** [comment]
I doubt very much that changing the steamID would be a fix for this, I suspect that user changed something else at the same time.

The addins.xml file mentioned in the error message is created by merging the individual addins.xml files from different mods - that merge process probably went wrong.

a) It would be helpful if you could send that file in so we can see how it's invalid.
b) You can help narrow down the problem. Duplicate the profile, then disable as many mods as you can while still producing the error. When you have a small set of mods causing this, let us know which mods that are.

**Comment by IDCs** [comment]
@XaraRoy, @othara2017, as my colleague said - please send us your addins.xml file also give us a full list of the mods you have installed

**Comment by IDCs** [comment]
Assumed fixed

**Comment by Gikkak** [comment]
to late the error was due to the language of my mod, i used teh localised version of it and it works
