### ISSUE TITLE
Vortex can't make up it's mind on what the download folder should be

### ISSUE THREAD

**Issue by sougeki** [Nexus-Mods/Vortex#12513]
Pretty much every time I open Vortex, a few of my downloaded mods for Skyrim SE change folder. Ever since I started modding SE, the directory used to be named "skyrimse", but for whatever reason Vortex recently decided to start moving downloads to a folder named "skyrimspecialedition". It wouldn't be an issue if it made everything work fine afterwards, but if the mod I'm trying to reinstall was, unfortunately, selected to be moved I can't reinstall it anymore. I have to first go to the directory, backup the mod in question, uninstall it through Vortex and then manually insert the mod back onto the downloads folder and install it again. It seems to be random what mod gets selected to be moved, and new downloads NEVER go to the "new" directory, so the only thing that does is to generate trouble for the user and errors of downloads needing to be repaired on the app.

**Comment by IDCs** [comment]
This has already been fixed in Vortex 1.6 #12077
