### ISSUE TITLE
Outdated error message

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#12511]
**Describe the bug**
Users are still shown an error referring to a button in the UI that no longer exists. A different solution should be offered or Vortex should solve this itself.

![image](https://user-images.githubusercontent.com/31670524/180814399-ab9a35ef-6e77-4fb8-8985-80c998198fd1.png)
https://github.com/Nexus-Mods/extension-plugin-management/blob/b494840e96920fdf76afa4d36f7159068184e187/src/util/UserlistPersistor.ts#L157

**Comment by TanninOne** [comment]
This was addressed in https://github.com/Nexus-Mods/extension-plugin-management/commit/cf162595c5c25c06f7cd34cdb2489bb5261d4f98
