### ISSUE TITLE
Lacking Unmanaged Games (Subnautica and more)

### ISSUE THREAD

**Issue by DNA-Company** [Nexus-Mods/Vortex#12527]
Inside the "Unmanaged Game Tab", there are only 87 Unmanaged games. However, the official wiki/tutorial of adding new game to vortex (https://wiki.nexusmods.com/index.php/Adding_a_new_game_to_Vortex), the Unmanaged section have 140 games. Additionally, from the modding tutorials online, there are definitely more than 87 Unmanaged games.
Also, just like the title suggests, I cannot locate Subnautica in the list.

Not enough game screenshot:
![Not enough game](https://user-images.githubusercontent.com/51323660/181158670-cc0b98f8-0ff9-49bc-bc6c-63e3301a6f52.jpeg)

No Subnautica in the place it should have been (Alphabetical Order):
![No Subnautica](https://user-images.githubusercontent.com/51323660/181158724-2069ad0e-6fc3-40bc-8108-197bc5228bee.jpeg)

Operating System: Windows 10
Vortex Version: 1.5.13 (Latest Version downloaded from the official website - Automatic Install Location)

**Comment by IDCs** [comment]
Have a look inside your extensions page and see if you have any disabled extensions - try re-enabling them. If their status is "Failed" - double click the extension and send us the error it gives you.

Please always include your Vortex logs when reporting an issue so we can solve it quicker - it's located inside `%appdata%/vortex` (any `vortex.log` files)

If Subnautica is missing from the extension list - use the "Find More" button and download it through there.
![image](https://user-images.githubusercontent.com/8960252/181174008-9f01a2da-b313-4374-ba6a-93b1120178b5.png)

**Comment by Antineutrino-4444** [comment]
Thanks for replying, but, the same issues still occurs after I checked the extensions (They are all previously enabled) I tried to disable subnautica and enabling it again, it doesn't work. Even if I disable all other games except subnautica, the game section still does not contain subnautica.
Having Extension Enabled
![Having Extension Enabled](https://user-images.githubusercontent.com/51323660/181258171-4c171100-91ee-4f3b-8136-1cc0f58d2c16.PNG)
Still not having subnautica
![Still not having Subnautica](https://user-images.githubusercontent.com/51323660/181258184-b660897c-9878-43da-9236-8404e9243e67.PNG)
Log:

**Comment by TanninOne** [comment]
You don't have the Subnautica extensions installed. What's showing on your screenshots are stubs, those exist because in the past, Subnautica extensions shipped with Vortex and now they are managed by third-party devs.

Your problem is that your network/firewall prevents Vortex from downloading the list of extensions so Vortex is only showing the games included with Vortex itself, none of the ones supported through extensions.
Your log file is full of error messages
> Failed to fetch api config message=getaddrinfo ENOENT raw.githubusercontent.com
> failed to retrieve list of surveys errno=-4058, code=ENOENT, syscall=getaddrinfo, hostname=raw.githubusercontent.com
> failed to retrieve list of announcements errno=-4058, code=ENOENT, syscall=getaddrinfo, hostname=raw.githubusercontent.com
> failed to fetch list of extensions errno=-4058, code=ENOENT, syscall=getaddrinfo, hostname=raw.githubusercontent.com

Meaning Vortex can't resolve any of the data files we're fetching from github.
> raw.githubusercontent.com

You can try if you can access, for example https://raw.githubusercontent.com/Nexus-Mods/Vortex/announcements/announcements.json in your webbrowser.
If yes then your local firewall is blocking Vortex specifically, otherwise your network is blocking your system from that page entirely.

**Comment by Antineutrino-4444** [comment]
Thanks for replying
I think it is the firewall problem and I live in China, so, I tried to use vortex again after I enabled a VPN (which allows me to access google and the link provided above through a web browser). However, it still doesn't work.
So, I am trying to find potential solutions and the log is below.

**Comment by TanninOne** [comment]
That log still shows the same issue downloading the list of extensions I'm afraid:
> failed to fetch list of extensions errno=-4058, code=ENOENT, syscall=getaddrinfo, hostname=raw.githubusercontent.com

(ENOENT stands for "Error NO ENTity" so basically "not found")
