### ISSUE TITLE
Blade and Sorcery game extension is completely non-functional

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#12539]
Since the updates for B&S U11 many features of the extension are no longer functional. 

- Before each deployment, the warning below appears incorrectly. 
![image](https://user-images.githubusercontent.com/31670524/181285608-59f1ebf3-d671-4d2c-babc-693241726bda.png)
- The mods are now deploying to `Blade & Sorcery\BladeAndSorcery_Data\StreamingAssets` and not the `Blade & Sorcery\BladeAndSorcery_Data\StreamingAssets\mods` folder.
- The load order tab shows any installed mods as "Not managed by Vortex". 

This seems to be mostly related to the change in the "Official" mod type and the version of the game going from 10.0 to 0.11.0. I would suggest we remove any legacy code from a long time ago in order to simplify the checks.

**Comment by IDCs** [comment]
- What Vortex version are you testing with? (No matter how irrelevant you think this bit is - ALWAYS include the Vortex version - it absolutely ALWAYS matters; massive changes to mod installation have been done as part of 1.6 - the issue might lie outside of the game extension)
- Is this on a fresh U11 build or did you upgrade?
- If you upgraded, what did you upgrade from? Did you have any mods installed when you upgraded?
- Were the mods you were using targeted at U11 or some other version?
- Did you install the mods as part of a collection or one by one ?

**Comment by Pickysaurus** [comment]
Reported by a user on 1.5, replicated on the latest internal beta. 

In my case, it was a fresh install to test with no mods installed.

Mod was installed individually. 

Any mod marked as U11
