### ISSUE TITLE
Vortex hangs after splash 

### ISSUE THREAD

**Issue by Dragonmist2022** [Nexus-Mods/Vortex#12575]
Vortex version is 1.5.13

Vortex mods Skyrim, Skyrim Special Edition, Fallout 4, Fallout New Vegas, The Sims 4, Oblivion, others
Nexus premium subscriber to better access new collections feature of nexus mods
Skyrim Special Edition collection has 330+ mods

Vortex is running in Windows 10 Home version 21H1 with 16 GB RAM, 64-bit operating system, x64-based processor

What's been tried to resolve the issue

a) Restart PC
b) Shut down PC and back on
c) Re-install .Net Framework 3.5
d) Check disk for errors
e) d/l Vortex latest version from Nexus and run Vortex-1-1-5-13-1653386664.exe
f) Search Google and The Nexus Forums
g) Read Vortex FAQ and Troubleshooting
h) end task Vortex in task manager and run again
i) Reset Documents folder to defaults
j) changed Vortex to run as administrator
k) changed Vortex to run in Windows 8 compatibility mode
l) other
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/9227793/vortex.log)
s

**Comment by Dragonmist2022** [comment]
@TanninOne thanks for your reply.  I had not considered a locked file.  Using the lockhunter tool I confirmed that no files were locked in the state.v2 directory.  I also rebooted to clear locked files.  I also checked the permissions, removed run as admin and run in compatibility mode.  No progress was gained.  Any suggested next steps?  I can provide the state.v2 directory for analysis.  Or delete the Vortex folder and re-install but I don't want to lose configurations and saved games.  All help is appreciated!  Thanks

!

**Comment by HawthorneK456** [comment]
Hi,

Thank you for your initial report of this issue. The issue may have also been resolved in a later release of Vortex. Please ensure that you update Vortex to the latest version and if the issue still persists, please open a new bug report referencing this issue.
