### ISSUE TITLE
Can't find my games 

### ISSUE THREAD

**Issue by Torroche** [Nexus-Mods/Vortex#12585]
Hi 

So I was using vortex to mod my ff12 game yesterday and today I can't find it anywhere, I've run a scan which says I have 5 games that I can manage but it is still not showing ff12.  I have searched for it and the only ff game it shows is ff7r, which is not the game I want to mod at the moment.  

I cannot think why it would allow me to mod and have the game showing yesterday but today nothing.

Any help would be greatly appreciated.

**Comment by TanninOne** [comment]
@Torroche We have no way of investigating this, please send in a feedback from inside Vortex and attach your log files through that screen.
