### ISSUE TITLE
IModRule type lacks the `type` field

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#12599]
**Describe the bug**
When using Vortex's built in types, it appears IModRule lacks the `type` key, which appears to be required for a valid rule. This could be the case of using the wrong type.  `IModReference` also appears to use a different definition. 

**To Reproduce**
1. View the type: https://github.com/Nexus-Mods/Vortex/blob/2ac2799a11b6dc7c68ce0141779e1eb2331179ac/src/extensions/mod_management/types/IMod.ts#L96
2. Compare with a rule as set by Vortex:
```json
{
              "type": "recommends",
              "reference": {
                "description": "Animated East Scarp Fish",
                "fileMD5": "a8f80b77116df9f841d296e9f167c1ab",
                "gameId": "stardewvalley",
                "fileSize": 9173,
                "versionMatch": "*",
                "logicalFileName": "Animated East Scarp Fish",
                "tag": "JpfBkwpWP",
                "md5Hint": "a8f80b77116df9f841d296e9f167c1ab",
                "repo": {
                  "repository": "nexus",
                  "gameId": "stardewvalley",
                  "modId": "10913",
                  "fileId": "50201",
                  "campaign": "collection"
                }
              },
              "extra": {
                "author": "Gervig91",
                "category": "Fishing",
                "version": "1.0.0",
                "name": "Animated East Scarp Fish",
                "phase": 0,
                "fileName": "Animated East Scarp Fish-10913-1-0-0-1643785755.zip"
              }
            },
```

This implies to properly define a rule you need to declare your own version:
```
type IModRulePlusType = types.IModRule & { type?: 'requires' | 'recommends' };
```

**Expected behavior**
The rule type can be used for rules in Vortex. If this is exported from `IRule` that isn't available through the API.

**Comment by TanninOne** [comment]
https://www.typescriptlang.org/docs/handbook/interfaces.html#extending-interfaces
