### ISSUE TITLE
How to delete/reset all configuration?

### ISSUE THREAD

**Issue by Nordomus** [Nexus-Mods/Vortex#126]
I'm stuck at endless error loop, even after reinstalling to new version and deleting old folder in program files. All broke on it's own today and removed all installed mods, was working fine for a few days on 0.14 version.
I've also deleted folder in appdata local and still nothing is fixed. WTF.
![vortex errors](https://user-images.githubusercontent.com/25961180/38576701-303e2eb0-3cff-11e8-9d59-876e6fd521b2.JPG)
![vortex errors 2](https://user-images.githubusercontent.com/25961180/38576991-fc8e15c0-3cff-11e8-8b5f-7dd8b962938f.JPG)

**Comment by TanninOne** [comment]
Nothing broke on its own.
Have you read the error message? It actually explains what the problem is. Apart from removing that report button there is nothing I can do if you ask vortex to put data into directories it doesn't have permissions to write to.
