### ISSUE TITLE
Skyrim SE - ESL flagged plugins are reported as normal ESP in Plugins

### ISSUE THREAD

**Issue by c1nderS0ul** [Nexus-Mods/Vortex#12662]
The exact version of Vortex you're using: 
1.6.5 (Pre-release)

Your operating system:
Windows 10 x64

What you were doing when the bug happened:
I just sorted plugins with the integrated LOOT in Vortex.

What exactly the bug is (crash? error messages? unexpected behaviour?):
Today Vortex got an update and now ESL flagged plugins are reported as normal ESP in Plugins but when I check that plugin with SSEEdit it does have ESL flag. It only counts .esl plugins as light and not the .esp flagged with esl, Vortex says I have 1526 plugins and 16 light plugins when yesterday it was saying I have 185 plugins and 1357 light plugins. 1526 plugins is way over the 255 limit and the game shouldn't work, yet it does work.

https://streamable.com/brx7i1
in this video you can see how Vortex has the 'can be flagged as ESL' icon on all those plugins but when I open them with SSEEdit they are already ESL.

If you get any error message, include the full and exact error message. Do not paraphrase, do not leave out information that looks cryptic or unimportant to you:
There's no error messages.

**Comment by Owlchemist** [comment]
Yep. Just updated to 1.6.5 and having the same problem.

**Comment by TanninOne** [comment]
Will be fixed in the next update.

Please note that this is purely a display error in Vortex. Your plugins are still light plugins, they have not been modified, Vortex just doesn't recognize them as such. Don't panic, don't convert plugins through Vortex with this build.

**Comment by c1nderS0ul** [comment]
I know, just reporting it.

**Comment by Vlad0254** [comment]
Yes, purely a display error. Like I mentioned in my report LOOT was showing my plugin/light plugin numbers had not changed so after submitting my report I launched the game fully expecting it to launch and it did.

**Comment by Owlchemist** [comment]
There's another similar problem - It doesn't seem to recognize form 43 vs form 44 anymore, so it's not giving the incompatible warnings with loading Skyrim LE mods into SE.

**Comment by c1nderS0ul** [comment]
It has been fixed in 1.6.6

**Comment by Vlad0254** [comment]
Thanks for the quick fix
