### ISSUE TITLE
Factorio doesnt see mods installed as a symlink

### ISSUE THREAD

**Issue by deadair3210** [Nexus-Mods/Vortex#1269]
Vortex ver - 0.16.8
OS - Windows 10 Pro x64
Bug - Factorio offers no other option for mod installation other than Symlink (Admin), but the game does not see any mods installed in such a way. Manually installing a mod works fine, but deploying a mod with Vortex causes the mod to be ignored by the game.
Log - https://gist.github.com/deadair3210/3c50493d8071787d66a6059339dda68c
Log shows installation and removal of mods, as no error occurs in Vortex itself, at least in the way of error boxes

**Comment by TanninOne** [comment]
If this is the case you need to move the install path to the same drive as the game directory and then use hardlinks for the deployment method (settings->mods).

**Comment by deadair3210** [comment]
The game, the mods, and the downloads folder are all on my E: drive, it still only lets me select SymLink. Other games let me select hard link and move so i dont think its a folder location issue

**Comment by IDCs** [comment]
Hi @deadair3210, apologies for getting back to you so late on this issue!

I've added Factorio to the unsupported game list for symlink deployment methods https://github.com/Nexus-Mods/Vortex/commit/475b6b32de5e3f299e1fa2c5657f88facf802ab2. Unfortunately you will have to use other deployment methods (preferably hardlink).

Can you confirm whether you are still unable to select the hardlink or move deployment methods in the latest Vortex version ? (0.17.3)

**Comment by IDCs** [comment]
Assumed fixed.
