### ISSUE TITLE
Window Drag disable during popup causes softlock in certain situations

### ISSUE THREAD

**Issue by Tony-Goat** [Nexus-Mods/Vortex#12847]
The "File already exists" popup disables window dragging in Vortex. This may be intended behavior in certain situation, however, the following actions caused a soft-lock:

1. I dragged Vortex partially below the bottom of my desktop so I could run LOOT
2. I noticed a compatibility patch, that I went to the Nexus website to download, having forgotten that I downloaded it in another profile
3. The "File already exists" popup occurred because of this
4. However, the dialogue's buttons rendered below the desktop, so I couldn't click on them, and I couldn't drag the window to bring them up (screenshot attached).

![image](https://user-images.githubusercontent.com/70238376/185764702-2979e3a4-71b8-4242-801b-001843ea880b.png)

It's quick to work around this just by Alt-F4ing out of Vortex and reopening it, however, it's still a usability issue that occurred and I figured I'd bring it to the team's attention. This occurred on Windows 11, so I don't know if this would happen on Windows 10.

**Comment by TanninOne** [comment]
The top area of Vortex is supposed to still allow dragging the window around, I'll see if I can reproduce this issue.

**Comment by TanninOne** [comment]
I've just confirmed: the window can still be dragged around, the area to hit is the top 15px of the window while there is a dialog open.

**Comment by Tony-Goat** [comment]
Then can I suggest increasing the draggable area near the top to be the same for both when the popup is up and when it's not?

Without the popup in place, the entire gray title bar (105 pixels) can be used to drag the window around, reducing that to 15 pixels introduces inconsistent behavior that confused me, and making dragging consistent would make for better UX.

**Comment by TanninOne** [comment]
Nope. The window-drag overrides other behaviors of controls in that area of the window.

If we made the drag area bigger while a dialog is shown, depending on theme and window size, the dialog controls may stop working.
