### ISSUE TITLE
Cannot manage detected games from "List View" in 1.6.7

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#12875]
**Describe the bug**
The button to manage games is not present in list view.

![image](https://user-images.githubusercontent.com/31670524/185870507-0b861fe4-d3b7-4157-8555-91410edbdb7f.png)

**To Reproduce**
1. Have a game installed but not managed that Vortex can detect
2. Switch to list view. 
3. Find the game. 
4. Note that you cannot manage it at all. 

**Expected behavior**
Being able to manage games from both views.

**Comment by IDCs** [comment]
@TanninOne do we even want to keep the list view?

If so, I'd suggest this gets assigned to @mxswat?
