### ISSUE TITLE
XCOM2 can be added with an improper location set; then unable to correct/remove

### ISSUE THREAD

**Issue by christopherdolan** [Nexus-Mods/Vortex#129]
The XCOM2 expansion "War of the Chosen" is installed by Steam as a sub-directory within the root XCOM2 installation directory (`path\to\steam\XCOM2\XCom2-WarOfTheChosen`). This sub-directory itself resembles the root game enough to fool Vortex into thinking this is the correct path.

Long story short: I fat-fingered and selected the expansion's directory within the XCOM2 root directory. Now Vortex is unable to activate XCOM2, nor am I able to correct the directory selection.

I'm new to this software; I'd appreciate a workaround!

**Comment by TanninOne** [comment]
Next version will allow manually changing the directory.

I'd prefer to fix the auto detection though. Could you please do the following: 

- open a command prompt (cmd.exe)
- cd into a different directory if you want, you need write access: `cd c:\users\<username>\documents`
- run `dir /s path\to\steam\XCOM2 > xcom_filelist.txt`
- send me the generated file called xcom_filelist.txt or attach it here.

This will give me a complete listing of the game files including the expansion, so I can make the auto detection more precise.

**Comment by climbupthewalls** [comment]
[xcom_filelist.txt](https://github.com/Nexus-Mods/Vortex/files/1899716/xcom_filelist.txt)

Here you go! Thanks for taking a look, @TanninOne !
