### ISSUE TITLE
cannot access old mods

### ISSUE THREAD

**Issue by Volksenchimer** [Nexus-Mods/Vortex#12947]
**Describe the bug**
I've recently moved to a new computer following my old one breaking, I've reinstalled Vortex but my masterlist and load order for my mods (only tried SSE so far) is missing, I moved my ESPs and such into the right folders in the vortex application but it will not accept my old data

**To Reproduce**
1. copy vortex game data
2. install vortex in new computer
3. put old game data on new computer (same account)
4. boom, messed up mods

**Expected behavior**
I expected Vortex to load my mods as if I only put them on a flash drive

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Comment by IDCs** [comment]
When moving your Vortex setup to a new environment, moving the mod files themselves is not sufficient.

Please read:
http://wiki.tesnexus.com/index.php/Moving_your_Vortex_Mod_Setup_to_a_new_Computer
