### ISSUE TITLE
Notification Popups Obscuring Mod Management GUI.

### ISSUE THREAD

**Issue by Ah-Ftagn** [Nexus-Mods/Vortex#1295]
Notification popups are interfering with the queing of downloaded mods to install or deploy by overlapping a minimum of 10% (Possibly an amount only limited by the total window size) of the mod installation/deployment GUI. Tested on an ASUS ROG GL551JW with a screen resolution of 1920x1080.

**Comment by TanninOne** [comment]
What would the alternative be? The only way the notifications can't overlay with anything is if we reserved space for them whether it's needed or not, I don't think that's better.
