### ISSUE TITLE
SkyrimVR mods download to SkyrimSE

### ISSUE THREAD

**Issue by Tyrindor** [Nexus-Mods/Vortex#130]
When in the SkyrimVR profile, all mods downloaded via a Nexus link go to:
C:\Users\username\AppData\Roaming\Vortex\skyrimse\downloads

Then after I install them they get copied to:
C:\Users\username\AppData\Roaming\Vortex\skyrimvr\downloads

Basically, you must keep two copies of each mod. Only way around this that i've found is to add SSE as a game, and change the directory paths to be the same as SkyrimVR.

**Comment by TanninOne** [comment]
What do you mean by "Then after I install them they get copied"? Automatically? That's not supposed to happen...
When Vortex downloads an archive it picks the directory based on the game the download is intended for, not based on the game currently active. The idea being that if you are managing skyrim and download a dragon age mod you probably did so to install the mod for DA later, not so you can install it to skyrim.
I didn't consider the case where that game isn't even configured.

**Comment by nwcas** [comment]
In case anyone also has this sort of issue, a good way to manage SkyrimVR mods that are actually SkyrimSE is actually to disable the Nexus Link Handling, then just download mods manuallly and drag n drop all you mods in to the mod list while working on SkyrimVR in Vortex, assuming you've already set up your base paths etc it will assign them all to SkyrimVR automatically and handle properly afterwards. 

If your managing SkyrimSE as well this might be different, I only run the VR version now.

You can re-install, remove mod/archive without any issues. Works really well.

**Comment by TanninOne** [comment]
This should be addressed in 0.16.x since we now have a central download directory.
