### ISSUE TITLE
Stuck while switching profiles

### ISSUE THREAD

**Issue by TuTAH1** [Nexus-Mods/Vortex#13001]
**Discription:**
Just enabled profile function, go to the game, create new profile:
Deleted other profile (there's somewhy was other profile with just 1 mode), copying pervious, (renamed both), switched to the new profile, stuck with the message "Stuck? Please check your vortex.log file". ~~And I don't know where's "vortex.log" file, and can't even google it~~. **Please, write full name (path) of to vortex.log or/and make "vortex.log" text a link to that file.**
Post Scriptum. I found it only thanks [to this topic](#422). It's in `C:\Users\%username%\AppData\Roaming\Vortex`. There's my log file: 
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/9480387/vortex.log)

**Screenshots:**
![screenshot](https://thumb.cloud.mail.ru/weblink/thumb/xw1/3fhm/PqsAWqNNo)
Not great style of progressbar. I have no idea is it 100% or 75%

**Platform:**
 - OS: Windows 10 21H2
 - Vortex Version: Just updated, 1.1.6.8

**Comment by TuTAH1** [comment]
But with second time It's switched momentally. Not sure is it really worth fixing it since it's not repeating behaviour. Close the issue if you wish. But can you say why some games automatically creates another profile with 0/1 enabled mods? (some don't)

**Comment by Mopotter** [comment]
I'll be watching this.  Mine did this also, Had just opened the games and wanted to do a different type of character.  Neither the original or the clone would open.  Never did figure out why, also had problems finding the log and started a blank profile to see if it happens.

**Comment by TanninOne** [comment]
@TuTAH1 Sorry for the late reply. Your problem is/was caused by a bug in the Valheim extension (https://www.nexusmods.com/site/mods/210) which apparently doesn't work correctly if Valheim isn't actually discovered. You should uninstall the extension until an update is released.

@Mopotter Your issue isn't necessarily the same as that of the OP, we'd need to look at your own log file to know.

**Comment by Mopotter** [comment]
I'm not really concerned, so won't do a report,  but appreciate your reply
and I do think you all are great..
