### ISSUE TITLE
Window ungluing and repositioning when messagebox appears

### ISSUE THREAD

**Issue by TuTAH1** [Nexus-Mods/Vortex#13002]
**Describe the bug**
If I glue Vortex's windows in the one side of screen, It'll unglue and repositions if some messagebox appears

**To Reproduce**

1. Glue some application to one side of screen, Vortex in other (grab the app's window; move cursor to the side, untill Windows shows a transparent box of future window position, drop it. Windows now will show the list of app for other screen side – choose Vortex)
2.  Do something that makes a messagebox (like deleting the mod)
3. Vortex's windows will change it's position, making messagebox unreadable. You also can't move Vortex until closing the messagebox window (that (probably) may be unreachable)

**Expected behavior**
Vortex's window stay where it was, just like when it's unglued.

**Screenshots**
This is folder with screenshots. First is initial position, second is after messagebox appears. Third is gluing Vortex back and calling messagebox again: https://cloud.mail.ru/public/Wu12/L3KCm1KPG

**Platform (please complete the following information):**
 - OS: Windows 10 21H2
 - Vortex Version 1.6.8

**Additional context**
That's happens only if it's glued. I can't predict where it'll move

**Comment by TanninOne** [comment]
That is unfortunately not under our control. Vortex only sets its own position when it first starts, after that its position and size are controlled by Windows.
When a message box in Vortex is shown that requires your attention, Vortex requests windows bring it to the foreground so you can see the message but we don't request the position to be changed. Afaik we also can't control the "stick to side of screen" behavior so even though Vortex could memorize its position on screen before the messagebox and then force it to move there (which would be an ugly hack) that would still break the side-by-side window setup.

Personally I use Microsofts Powertoys (Fancy Zones) for window tiling (https://docs.microsoft.com/en-us/windows/powertoys/fancyzones) and that doesn't seem to have this problem plus it's way more powerful, maybe that's a solution for you?

**Comment by TuTAH1** [comment]
Thanks for your solution, I'll look at it. But if the Windows causing this problem, the best option would be to add "never bring Vortex to foreground" option in Vortex settings
