### ISSUE TITLE
Vortex folder management causes issues with certain Elder Scrolls Construction Sets

### ISSUE THREAD

**Issue by UnusedCactus** [Nexus-Mods/Vortex#13017]
**Is your feature request related to a problem? Please describe.**
I've been trying to make a Morrowind mod using the Construction Set for the game. The folder management removes most of the files from their respective folders, such as Data Files\meshes\d not having any meshes at all in there, only the __folder_managed_by_vortex file, an ini file, and a txt file called "Warnings.txt". This is a problem because TESCS requires files to make new items and activators, and cannot access files that aren't in their folders. This seems to also affect Skyrim's Construction Set as well, and would probably affect Oblivion's too.

**Describe the solution you'd like**
A setting to make it so the game files stay in their folder.

**Describe alternatives you've considered**
There really isn't an alternative, the files need to be there to access them.

**Additional context**
Both of these screenshots were taken after I made Vortex stop managing Morrowind, and depict the issue I described above.
![image](https://user-images.githubusercontent.com/87100678/188313870-263f1dc0-76d0-4b38-997a-21f6bdc7cbf7.png)
![image](https://user-images.githubusercontent.com/87100678/188314157-b9f0c2c9-8fb8-4036-9c44-8a2546ef20c2.png)

**Comment by IDCs** [comment]
@UnusedCactus, Vortex will not remove files that it manages unless you chose to purge your mods (or forgot to deploy) before you started working on your mod.

Additionally, it will obviously not touch any files that it does not manage, and will not remove the folder if it detects any remnant files.

Can you perhaps describe the steps you were taking inside Vortex before trying to work on your mod? Am I correct that you did not deploy/did purge your files?

**Comment by TanninOne** [comment]
I don't really understand the problem you're trying to report here.
When you have Vortex stop managing your game it gives you a confirmation dialog that says: "This will uninstall all mods managed by vortex and delete all profiles".

So you tell us
> Both of these screenshots were taken after I made Vortex stop managing Morrowind

that you had Vortex stop managing the game, which deleted all mods, and now you complain that the mods aren't there any more???

**Comment by UnusedCactus** [comment]
The Data Files\meshes\d directory is a folder used by the base game, mostly for doors. If I boot up TESCS with only Morrowind.esm, Bloodmoon.esm, and Tribunal.esm, looking at the "Door" tab will show that most doors take their files from there. I have had less of an issue with getting mods with their own folders and having their assets disappear. 

![image](https://user-images.githubusercontent.com/87100678/188443727-21c0d7bd-d194-4c07-bfaf-82d048a13c5f.png)
I mentioned that I had made Vortex stop managing Morrowind because, within my thoughts, that may have made the "__folder_managed_by_vortex" file get replaced with actual game files. The game still works without those files being in those folders, and TESCS will still use files that say they are in those folders if the object that uses them already exists.

**Comment by UnusedCactus** [comment]
They are in the BSAs it seems. Also the Warnings.txt file just said something about there being duplicate meshes. Strange that they made the game's files be in a BSA, but have the official modding tool ask for files in specific folders.
![image](https://user-images.githubusercontent.com/87100678/188469767-7ead7a91-bce1-44e0-aa84-e56f8f6875c8.png)

**Comment by TanninOne** [comment]
No, that's totally normally. BSAs take less space and quicker to load (at least on modern systems) but directories are easier to deal with, that's why most games have their assets in archives but for easier modding, mod files are loose files in a directory structure that matches the base files so it's clear what gets replaced.
