### ISSUE TITLE
Vortex issue with fomod installer

### ISSUE THREAD

**Issue by JDHeck** [Nexus-Mods/Vortex#13033]
Heya, having an issue with fomod installer workijng with Vortex.  I use MO2 and it works perfectly, but users are saying it's not installing the files.  From what I can tell it seems like vortex isn't liking the combo between "already selected on a different tab" and "doesn't have the fine", but checking the fomod designer site and it seems like it should work.  I've worked with a few guys that know a lot about fomods and they're also saying it should be working?

[https://fomod-designer.readthedocs.io/en/stable/advanced.html](url)

Here's the Fomod installer:
[ModuleConfig.zip](https://github.com/Nexus-Mods/Vortex/files/9498137/ModuleConfig.zip)

It can also be found on my mod here (and u can see the Bugs also):
[https://www.nexusmods.com/skyrimspecialedition/mods/40816](url)

Also, this came off the Icecreamassassin Mods discord if it helps...
![](https://cdn.discordapp.com/attachments/916850881851457566/1016469913558331402/unknown.png)

Let me know if you need more info.  Thx!!!

**Comment by TanninOne** [comment]
@JDHeck Please describe the issue itself.
Which mods/plugins do I have to have installed? Which install step is the problem is occurring on? What do you expect to see and what are you actually seeing?

**Comment by TanninOne** [comment]
closed due to lack of feedback
