### ISSUE TITLE
ModInstallerIPC.exe error

### ISSUE THREAD

**Issue by HyWell** [Nexus-Mods/Vortex#13046]
**Describe the bug**
Unable to install mod
![image](https://user-images.githubusercontent.com/21263451/189405126-cca8ac85-bb15-46e4-b426-0e2ff36145e6.png)

**To Reproduce**
1.dotenet.exe --info
![image](https://user-images.githubusercontent.com/21263451/189405970-7fe547a0-8e5f-4017-ba7a-224f8d9ef169.png)

2. Click on 'install mod'
 ![image](https://user-images.githubusercontent.com/21263451/189406126-8d3d010a-eb09-4c08-9afa-1e4aee099675.png)
![image](https://user-images.githubusercontent.com/21263451/189406185-fade96d3-7224-4469-a635-8141149cbf55.png)
![image](https://user-images.githubusercontent.com/21263451/189406256-8c184bd3-af54-44e6-aa9d-9c1c5308504c.png)

**Expected behavior**
Install the mod normally

**Platform (please complete the following information):**
 - OS: [10.0.19044 Build 19044]
 - Vortex Version [1.6.8]
![image](https://user-images.githubusercontent.com/21263451/189406508-cb65d627-e11f-4df2-bd1a-299cd9b8a7a1.png)

**Comment by TanninOne** [comment]
@HyWell Please see the pinned post on https://forums.nexusmods.com/index.php?/topic/11865088-microsoft-net-check-failed-vortex-167/
Likely the second part there is what's relevant to you.
