### ISSUE TITLE
Mods tab dissapierd from side menu

### ISSUE THREAD

**Issue by roman5129** [Nexus-Mods/Vortex#13066]
**Describe the bug**
Mods tab dissapierd from side menu, i didnt do anything it just suddently dissapeard. any suggestions how to fix this?

**Screenshots**
![missing mods tab](https://user-images.githubusercontent.com/113455641/189942147-443c83df-4f15-45a8-9f22-b707a23521be.PNG)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.6.8

there is log file from vortex:
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/9558548/vortex.log)

**Comment by TanninOne** [comment]
You have no active game (see top left). Manage a game from your "Recently Managed" dashlet or games tab, then there will be mods to manage
