### ISSUE TITLE
"Mod has dependencies" Logic Rework

### ISSUE THREAD

**Issue by naqaden** [Nexus-Mods/Vortex#13071]
**Is your feature request related to a problem? Please describe.**
Yes, a few.

It's strange that Vortex recommends disabling dependencies. If mod B requires mod A and I disable B, why would I want to disable A too?

Dependencies are either libraries/resources used by other mods, or any mod with addons or patches. Removing dependents in no way indicates I'm done with the dependency. It's *possible*, but shouldn't be recommended. It's not necessary or helpful. Usually I am trying out addons, removing what I don't prefer, and being pestered by this prompt for no reason.

Granted, the prompt states the dependency won't be disabled if it has other dependents. That is how I know this is, for some reason, intended behavior and not a bug.

Also confusing: this prompt will appear regardless of the current state of the dependency. If I disable B and leave A enabled, then later enable B, Vortex offers to enable A, even though it was never disabled. This may qualify as a bug.

Technically separate but related: if I disable A first, there is no prompt to disable B too, even though B won't work without A. This is strangest of all.

**Describe the solution you'd like**
1) The removal of, or at least option to suppress, the "Mod has dependencies" prompt when disabling a dependent.

2) Smarter prompts:
2a) If disabling a dependent, don't prompt when the dependency has other dependents. Currently, Vortex will already skip disabling the dependency in this situation, so the prompt is unnecessary.
2b) If disabling/enabling any mod, don't prompt if the recommendation is already disabled/enabled.

3) The addition of a similar "Mod has dependents" prompt when disabling a dependency.

**Comment by TanninOne** [comment]
Vortex doesn't "recommend" you disable dependencies, it offers you the option to do so.
Vortex is funded by and developed against primarily the nexusmods.com which has no dependency system outside collections so the assumption in the UI is that if you disable a "dependent" mod, that's actually a collection and the "dependencies" are mods installed by that collection.
In that specific scenario you will almost always want to disable the mods belonging to a collection when you disable it, I had to fight to even get that dialog in, the alternative would have been to always disable them automatically.

For that same reason, if you disable a "dependency" you do get a notification telling you that a dependency is now unfulfilled or that a collection is incomplete.

Even though Vortex is built to work like a package manager where any mod can have dependencies, the site offering is not and the UI has to be designed around what users will actually experience not what it could theoretically be used like. If nexusmods.com ever gets any usable mod dependency api then the UI will certainly be reconsidered.

**Comment by naqaden** [comment]
> Vortex doesn't "recommend" you disable dependencies, it offers you the option to do so.

The checkbox to accept that offer says "Apply to Recommended Mods."

> the nexusmods.com site which has no dependency system outside collections

I haven't run into a Nexus game yet that didn't have a requirements section listing both dependencies and dependents, though mod authors misuse it sometimes. I am probably not understanding.

Anyway, it sounds like solution 1 is rejected, and maybe 3. What about 2a and 2b? There are situations where Vortex can skip the prompt without going against its purpose. Basically: when accepting the prompt would change nothing.

I forgot to add, this prompt interrupts the reinstallation process. Every enabled dependent I reinstall prompts me to disable its dependencies, then leaves the dependent disabled. Manually enabling it of course prompts me again, this time to enable its dependencies (even though they're enabled... the 2b problem).

Well thank you for fighting for the prompt at all, in that case. Having no experience with collections, I can't say I followed that, but it does make me wonder why Vortex can't tell I'm not using them, to skip prompting altogether. Consider collection detection another feature request :)

**Comment by TanninOne** [comment]
> I haven't run into a Nexus game yet that didn't have a requirements section listing both dependencies and dependents, though mod authors misuse it sometimes. I am probably not understanding.

Yes, there is a field in the mod description area, that lets authors put in a link to whatever.
This is from humans to humans, it doesn't identify a file that Vortex could actually download or check whether it's installed.
Plus the api doesn't even export that information to mod managers.

Again, if regular mods having dependencies was something that actually existed in practice and users were exposed to then I could make a case with the UI department to make the UI work for that in a more sane way but right now, as far as UI is concerned, dependencies means collections.

Just to clarify: I'm not rejecting your proposal here, what you're suggesting has already been debated internally before this UI was designed and a decision has been made. Until circumstances change there is no point opening that conversation again.
