### ISSUE TITLE
Install mode "Replicate" and binary patching are mutually exclusive.

### ISSUE THREAD

**Issue by Rattledagger** [Nexus-Mods/Vortex#13082]
From #13069 (number 5)

If tries using binary patching and in addition install mode "Replicate", everything seems to work correctly with no indication something didn't work.

But, anyone trying to install Collection will get many error messages, since can't find the file to install.

Possible fix, trying to select "Replicate" + "Binary patching" should give an error-message, since otherwise anyone trying to install will get multiple installation errors.

**Comment by TanninOne** [comment]
1.6.9 does warn about this now.
