### ISSUE TITLE
update zlib once 1.2.13 is out

### ISSUE THREAD

**Issue by NicBOMB** [Nexus-Mods/Vortex#13165]
**Describe the bug**
Building node-gamebryo-savegames on Linux fails due to invalid `cmake.exe` command usage and zlib's CMakeLists.txt file being outdated for the latest versions of CMake.

**To Reproduce**
1. Launch a linux distro (maybe WSL)
2. Setup the Vortex repo.
3. Open `GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management` or `GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management/node_modules/gamebryo-savegame`
4. Run `yarn install`
5. See error log below

**Expected behavior**
Vortex should use `cmake` instead of `cmake.exe` when building on non-windows platforms.

**Log**
```
GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management
❯ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > babel-loader@7.1.5" has incorrect peer dependency "webpack@2 || 3 || 4".
warning " > ts-loader@6.2.2" has unmet peer dependency "typescript@*".
[4/4] Building fresh packages...
error GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management/node_modules/gamebryo-savegame: Command failed.
Exit code: 1
Command: prebuild-install -r napi -t 4 -a x64 || npm run build
Arguments: 
Directory: GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management/node_modules/gamebryo-savegame
Output:
prebuild-install WARN install No prebuilt binaries found (target=4 runtime=napi arch=x64 libc= platform=linux)

> gamebryo-savegame@2.0.6 build
> npm run build_deps && autogypi && node-gyp configure build && npm run copy_deps


> gamebryo-savegame@2.0.6 build_deps
> node download_lz4.js && node download_zlib.js

200 OK
Extracted 16 entries
200 OK
unpack GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management/node_modules/gamebryo-savegame/zlib-1.2.12 GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management/node_modules/gamebryo-savegame/zlib-1.2.12/build GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management/node_modules/gamebryo-savegame/zlib
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmake.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:476:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn cmake.exe',
  path: 'cmake.exe',
  spawnargs: [
    '..',
    '-DCMAKE_INSTALL_PREFIX=GitHub/Nexus-Mods/Vortex/extensions/gamebryo-savegame-management/node_modules/gamebryo-savegame/zlib',
    '-A',
    'x64'
  ]
}

Node.js v18.8.0
```

**Platform (please complete the following information):**
 - Vortex Version: vortex_devel (app/1.6.10)
 - OS: Manjaro Linux x86_64
 - Kernel: 5.19.7-1-MANJARO
 - node: 18.8.0
 - npm: 8.19.1
 - Yarn: 1.22.19

**Additional context**
zlib was added to [fix savegame screenshot views](https://github.com/Nexus-Mods/Vortex/issues/8097#issuecomment-741797245).
zlib recently published a security advisory https://github.com/advisories/GHSA-cfmr-vrgj-vqwv.
It's unclear whether Vortex is affected, though there is also a [native Node.js zlib library](https://nodejs.org/api/zlib.html#zlib) which was confirmed to be unaffected. I'd imagine most operations Vortex uses zlib for are deflate tasks, whereas this vulnerability relates to `inflateGetHeader`, found in
`Vortex/extensions/gamebryo-savegame-management/node_modules/gamebryo-savegame/zlib-1.2.12/inflate.c`.

As of writing, zlib has over 200 active pull requests and issues, many containing fixes to the vulnerability and specific issues while building via CMake, but none have been merged and no new release has been made.
The situation should be monitored so as to incorporate any new zlib release ASAP.

**Comment by TanninOne** [comment]
a) I'm fairly certain Vortex isn't affected, this security advisory is about functionality for reading gzip headers, it specifically says "NOTE: only applications that call inflateGetHeader are affected". We don't.
b) The files we're talking about aren't untrustworthy files from the internet, they're generated by a game from a reputable (well...) games company running on your own computer.
c) The version of zlib we're using is still the latest existing release. I'm not going to switch to a development build of the library to avoid a bug that doesn't affect us.

I'll happily update to the next zlib release once one is out but this has no urgency.

**Comment by TanninOne** [comment]
ok, zlib 1.2.13 is out and I've updated it
