### ISSUE TITLE
Collection mods downloading at 68kb/s to 500kb/s

### ISSUE THREAD

**Issue by alderwyn** [Nexus-Mods/Vortex#13201]
**Describe the bug**
This was my first time downloading through Vortex and it was for a collection. The download speeds had a low of 68kb/s, a high of 500kb/s and a median of 149kb/s. I left my computer on for around 48 hours downloading that collection. My average speed is over 300MB/s. My region is Oceania.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a collection
2. Click on "add to Vortex"
3. Watch the slow speeds as your life passes by...

**Expected behaviour**
At least 10MB/s...

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version: Latest stable version from the date of this post.

**Additional context**
Sending issues though Vortex is broken.

**Comment by TanninOne** [comment]
https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
