### ISSUE TITLE
Fixing the i18n problems

### ISSUE THREAD

**Issue by M4lik** [Nexus-Mods/Vortex#134]
I think I've found the way to correctly implement HTML Tags in the translations.
I've dug a litlebit in varios i18n docs and it seems that, as long as you don't specifically tell the lib to escape HTML, it won't do it. (I've checked this with `log('debug', t('feedback-instructions'));`)

So I've quickly tested it and replaced the numbers in `feedback-instructions` with proper html tags. That didn't work as expected. The page did not render at all. Next I've tried to replaced the whole `<T>` Tag in ReedbackView.tsx with
```HTML
<div>
  { t('feedback-instructions') }
</div>
```
The output was more what we want, but sadly the Tags got escaped.
After a little testing and searching I've found that this is not a wrong usage of i18n but a xss prevention from react itself. So now I've again replaced the tag, this time with
```HTML
<div dangerouslySetInnerHTML={{__html: t('feedback-instructions')}} />
```
and: Hooray, It worked!
<hr>

**So:** To solve this whole issue I would suggest to replace the current `<T>...</T>` Element in (extension-feedback)[https://github.com/Nexus-Mods/extension-feedback], revert the last two commits in #132 (@dertrutinator I guess you know how to do this...) and put the English string in `locales/en/common.json`.

On an additional note:
I also would suggest to extract all Texts and Strings and put them into `locales/en/common.json`. This would have two major advantages:

1. All Texts would be in one single place which is good if you just want to fix a typo or somthing, because you don't have to search for that String in the app sources.
2. It's WAY easier to translate somthing because you could just copy `locales/en/common.json` to another directory, and start translating.

There are also some smaller advantages, like we could structure the locale files to be like this:
```json
{
  "premium": {
    "go_premium": "Go Premium",
    "capped_dl_text": "Uncapped downloads, no adverts",
    "support_nexus": "Support Nexus Mods"
  },
...
}
```
A categorizised structure, which can be accessed by e.g. t('premium.go_premium')
This would also be useful because you can then get the context of a String at one glance.

I don't want to make this Text too long, so I will stop now, but I think you get my point :)

Greets
Malik

PS: @TanninOne @dertrutinator

**Comment by TanninOne** [comment]
Using dangerouslySetInnerHTML would mean that translations could inject arbitrary javascript code.

Regarding the second point: I absolutely hate localisation systems where the code only contains ids and you have to go to a translation file to see the text that's actually going to be displayed. Sorry, but that's not going to happen either. Its too much work in development and I'm already struggling to justify localisation per se, considering this is a NexusMods tool, nexusmods is not localised and thus our users can be assumed to know english anyway.

**Comment by M4lik** [comment]
> I'm already struggling to justify localisation per se, considering this is a NexusMods tool, nexusmods is not localised and thus our users can be assumed to know english anyway.

This is fine. I've never said that Vortex needs a localization system anyway. Then I would vote for disabling this feature completely because it would be kinda irritating to have it implemented but not really supporting it. But I imagine that some time in the future when Vortex gains more traction, that people will want localization.

Regarding the first point. Yeah, I forgot about the fact that locales don't have to be implemented beforehand, but can be loaded on-the-fly. Sorry for that.
