### ISSUE TITLE
Mod updates are installed as separate version instead of replacing older version

### ISSUE THREAD

**Issue by darkrain261** [Nexus-Mods/Vortex#13426]
**Describe the bug**
For the latest version of Vortex, everytime I update a mod, it will be installed as a separate version. There is no pop-up that asks me which option I want to do:
1) Overwriting old mods.
2) Install as a variant.

This also means that all the rules applied for the old version won't be applied for the updated one and I have to manually set rules for the new version. Besides, I can't switch back and forth between two versions as both of them are installed (The version drop-down is still available once I uninstall a version).

**To Reproduce**
1. Download a mod update
2. Install it.
3. Mods will be installed as a separate version.

**Expected behavior**
A pop-up will appear to ask me which option I want update to be installed. Older version will be replaced (uninstalled) by newer one. All the rules of older version will be applied for newer one once it's installed.

**Platform (please complete the following information):**
OS: Windows 10
Vortex Version 1.16.14

**Comment by darkrain261** [comment]
One more note, all the selected FOMOD options won't be saved either (which is shown as "preset" when updating or re-installing mods) so some options could be missed if FOMOD has numerous options or I have a long modlist and couldn't remember all the mod when selecting a patch in FOMOD.

**Comment by TanninOne** [comment]
I'm not able to reproduce this but I suspect that - for whatever reason - meta information for this mod got lost so Vortex couldn't correctly identify the old version. To reproduce this we'd have to know how the meta info got lost in the first place.
