### ISSUE TITLE
Gamebryo - plugin - management will not install

### ISSUE THREAD

**Issue by GreenDragon5221** [Nexus-Mods/Vortex#13424]
As the title says I cannot get this to install in vortex. I have tried reinstalling vortex with and without my antivirus and it wont work. I just get a notification in vortex saying there is an issue with it and when I click fix I just get another notification with an button that says more. Then I just get an error message. Does anyone know how to fix this? I am using the most recent version of Vortex on the website, and a windows 10 computer. 

![Screenshot 2022-10-26 232535](https://user-images.githubusercontent.com/117045913/198904352-c5a77fc9-14d5-4a76-9978-b98a378e24ac.png)

**Comment by TanninOne** [comment]
@GreenDragon5221 That extension is shipped with Vortex, it doesn't have to be installed.
Please check the "Extensions" screen and check the error message being reported on why the extension failed to load.

**Comment by hvuong182** [comment]
here

Failed to load: The specified module could not be found.
\\?\C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\node-loot.node

**Comment by TanninOne** [comment]
@hvuong182 This indicates that either your Vortex installation got corrupted (It should warn you about that on startup) or a setup error.
If you get a warning when starting Vortex about it having been modified: reinstall Vortex, don't let your Antivirus corrupt it, if it still happens, rethink your choice of AV.
If you do not get a warning, install this: https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 (the x64 variant!)

**Comment by TanninOne** [comment]
closed due to lack of feedback
