### ISSUE TITLE
Federation

### ISSUE THREAD

**Issue by trymeouteh** [Nexus-Mods/Vortex#13481]
**Is your feature request related to a problem? Please describe.**
NexusMods is a centralise platform. Would like to suggest open sourcing NexusMods to allow others to self host their own NexusMods website and have these sites connect with one another using federated protocols like activitypub.

**Describe the solution you'd like**
Open sourcing the server side code and website code of NexusMods and adding federation abilities. Allowing anyone to self host their own NexusMods server and self host their own mods if they wish or allow others to host their mods on their instance.

Also allowing Vortex to connect to accounts on other instances and download mods from other instances.

**Describe alternatives you've considered**
None

**Additional context**
Mastodon is a Twitter alternative that is federated. Lemmy is a Reddit alternative that is federated. There is no game modding platforms that support federation.

**Comment by TanninOne** [comment]
Nexus Mods is a business. You're effectively asking a company to destroy its own business model.
