### ISSUE TITLE
Bittorrent

### ISSUE THREAD

**Issue by trymeouteh** [Nexus-Mods/Vortex#13480]
**Is your feature request related to a problem? Please describe.**
Lots of bandwidth is required from NexusMods servers to distribute mods to modders.

**Describe the solution you'd like**
Allowing NexusMods to upload .torrent files and to allow vortex to download torrents, seed torrents and manage torrents from NexusMods.

**Describe alternatives you've considered**
[IPFS](https://github.com/Nexus-Mods/Vortex/issues/10423)

**Additional context**
Will reduce bandwidth load on NexusMods servers and allow mod authors to have the option to distribute their mods on NexusMods using a P2P file sharing protocol.

**Comment by TanninOne** [comment]
This is the Vortex issue tracker, what you're suggesting is a suggestion for the site.
