### ISSUE TITLE
[Bug] Linking mods with non-numeric version numbers is not possible

### ISSUE THREAD

**Issue by dbknightx** [Nexus-Mods/Vortex#135]
I have two Skyrim SE mods, Simply Bigger Trees v1.0SE and Realistic Aspen Trees v3.6SE, that both have non-numeric version numbers (1.0SE and 3.6SE).  When I attempt to link them the 'VersionMatch' field will not let me enter these version numbers.  I either get a 'range invalid' error or a 'doesn't match the mod' error if I remove the SE.

At a minimum, it would be great to be able to empty out the Version Match field to accept any version number.  As it stands now, there is no way to order these two mods.

Vortex 0.14.1 on Windows 10 (fully patched).

**Comment by TanninOne** [comment]
We only support matching semantic versions, otherwise you have to use `*` to match everything
