### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by PakRatt** [Nexus-Mods/Vortex#13549]
bain.py  193 calc_crcs: Failed to calculate crc for D:\Steam Library\steamapps\common\Skyrim Special Edition\Data\Scripts\FNIS_aa2.pex.vortex_backup - please report this, and the following traceback:
Traceback (most recent call last):
  File "bash\bosh\bain.py", line 187, in calc_crcs
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Steam Library\\steamapps\\common\\Skyrim Special Edition\\Data\\Scripts\\FNIS_aa2.pex.vortex_backup'

bain.py  193 calc_crcs: Failed to calculate crc for D:\Steam Library\steamapps\common\Skyrim Special Edition\Data\Scripts\FNIS_PCEA2.pex.vortex_backup - please report this, and the following traceback:
Traceback (most recent call last):
  File "bash\bosh\bain.py", line 187, in calc_crcs
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Steam Library\\steamapps\\common\\Skyrim Special Edition\\Data\\Scripts\\FNIS_PCEA2.pex.vortex_backup'

bain.py  193 calc_crcs: Failed to calculate crc for D:\Steam Library\steamapps\common\Skyrim Special Edition\Data\Scripts\FNISVersionGenerated.pex.vortex_backup - please report this, and the following traceback:
Traceback (most recent call last):
  File "bash\bosh\bain.py", line 187, in calc_crcs
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Steam Library\\steamapps\\common\\Skyrim Special Edition\\Data\\Scripts\\FNISVersionGenerated.pex.vortex_backup'

**Comment by TanninOne** [comment]
These errors are from wrye bash.

**Comment by PakRatt** [comment]
I'. so burnt out trying to get my game setup I didn't pay attention.

Thanks for checking it out.
