### ISSUE TITLE
Vortex Net Framework error denies installation of mod

### ISSUE THREAD

**Issue by Arqeydas** [Nexus-Mods/Vortex#13556]
**Describe the bug**
I just installed vortex, downloaded first mod, and upon install attempt i recieve error info that i need Net Framework version 6.0.9 installed for vortex to work.

- In error prompt window it says about net framework 6.0.9 so i installed it, fixed it and restarted computer, didn't work.

- There is option in vortex to automatically fix issue, it causes vortex to download framework 6.0.6, but it's **unable** to install it because it doesn't recognise this extention , so why is this fix option even here? I installed 6.0.6 manually, restarted PC, still doesn't work.

**To Reproduce**
1. Go to Vortex main screen, download any mod.
2. Click on install mod.
3. Wait for the end of install.
4. At the end of install see error.

**Expected behavior**
I expected the vortex to finish installing the mod.

**Screenshots**
If applicable, [add](url) screenshots to help explain your problem.

**Platform (please complete the following information):**
Windows 10
Vortex Version 1.6.14

[
![sgssgsggssg](https://user-images.githubusercontent.com/119087812/204067843-61f7f091-2155-4ab7-b48f-4f1156fdf4b5.JPG)
](url)

**Comment by Gutsman2099** [comment]
Hey, I just had this problem installing fallout 4 mods. I managed to get it working by uninstalling my desktop runtime stuff, then installing exactly version 6.0.9 like what it says under app host version in the error message you posted.
after I did the install of 6.0.9 I just hit install again and it started actually installing them.

**Comment by TanninOne** [comment]
see https://forums.nexusmods.com/index.php?/topic/11865088-microsoft-net-check-failed-vortex-167/
