### ISSUE TITLE
Vortex installing mods for the GOG release of Skyrim AE splits location of config files

### ISSUE THREAD

**Issue by Serpentstar** [Nexus-Mods/Vortex#13584]
When installing mods for Skyrim AE, GOG edition, Vortex is placing data in two different locations within %user%\Documents\My Games.
The GOG edition should have files placed in Skyrim Special Edition GOG, but they are being split and being placed in Skyrim Special Edition

![image](https://user-images.githubusercontent.com/751507/204957100-f6c0167a-af03-4f1b-882f-4ae3e47085c9.png)

Install the game. setup_the_elder_scrolls_v_skyrim_special_edition_1.6.659.0.8_(64bit)_(59094) and setup_the_elder_scrolls_v_skyrim_anniversary_upgrade_1.6.659.0.8_(64bit)_(59094)
Launch the initial SkyrimSELauncher.exe
Skyrim Special Edition GOG gets created.
Launch Vortex, set up GOG location and start loading mods.
In this case, SKSE, and SkyUI.
Everything should be being installed to a single folder under My Games, Skyrim Special Edition GOG

![image](https://user-images.githubusercontent.com/751507/204957426-699b0a26-722c-48a2-8d72-ca3170aa92c3.png)
![image](https://user-images.githubusercontent.com/751507/204957462-57ffbef0-42f8-4541-a34f-fd3e236f07b1.png)

**Platform (please complete the following information):**
Windows 10
![image](https://user-images.githubusercontent.com/751507/204955936-af9a9f21-d329-4443-a633-b9896a413d3d.png)

**Additional context**
This was identified because I cannot get the Mod Manager menu option to appear, which is necessary for many mods that have configuration capability.
[Skyrim SE GOG edition.zip](https://github.com/Nexus-Mods/Vortex/files/10128968/Skyrim.SE.GOG.edition.zip)

Added screenshot of missing Mod Configuration menu option.
![image](https://user-images.githubusercontent.com/751507/204960109-91cf1f20-1c32-4242-912c-2944799c75b8.png)

**Comment by Serpentstar** [comment]
The only way I am able to get the Mod Configuration menu to load is to sync the directories of 
C:\Users\Username\AppData\Local\Skyrim Special Edition
with
C:\Users\Username\AppData\Local\Skyrim Special Edition GOG

and 
C:\Users\Username\Documents\My Games\Skyrim Special Edition
with 
C:\Users\Username\Documents\My Games\Skyrim Special Edition GOG

I had to merge the information from each Skyrim.ini into the other.

**Comment by MrGrymReaper** [comment]
I can confirm I'm also noticing something similar with the configuration files and their storage directory for the GOG release. This prevents the saved games from working correctly with Vortex as well as the game, as well as preventing the saving of log files and/or mcm features involving external configuration files for modifications.

I worked around this by before even starting the game's launcher or Vortex creating symbolic or hard links to the destination folder of the GOG release and the source path being the Steam release folder name. That way when I ran the launcher and Vortex there was no need to have to synchronise the directories as the path requests for one would redirect to another.

**Comment by TanninOne** [comment]
Could you please check if 1.7.0 fixes this?

**Comment by bukiru** [comment]
**mklink** would help
this problem also actual for me

**Comment by TanninOne** [comment]
please track this issue on this ticket: #13413
