### ISSUE TITLE
Missing Metadata after Importing from NMM - Can't fetch them automatically (SSE)

### ISSUE THREAD

**Issue by Kongolan** [Nexus-Mods/Vortex#136]
Hey there,

first of it's a shame that you are the only developer on this mod manager... I already grabbed the current master build and will soon maybe fix the features myself, which i need.

I tired to import all my NMM data into Vortex (which indeed is a long process without a proper loading bar, it seems like being stuck and took me around 3 hours for 150 mods). Also can't cancel it without running into problems and it on huge files it just takes too long and looks like it freezed. Actually i would like to skip this BIG files, when i just want to grab the metadata from NMM with all the categories and version numbers. 

The import feature needs some cleanup, that it doesn't lock vortex fully or maybe make it procedural, so we can see which mod is already fetched and we can skip mid-loading. Beside of that the result was that all mods were imported and it also cleaned the data folder well, BUT no meta data was fetched, so i can't update them and so i'm stuck with the horrible mod names. I really like the feature of NMM to change the names when trying to check for updates, because the naming of the mods needs to be fixed when they are not readable like "German Version - 80224".

So my basic request is to have a way to automatically change the names and fetch the version numbers and metadata, because they are literally missing. I really need the categories to have a better look over my mods, and i don't want to set them all manually. If not i at least want the option to grab the metadata from NMM in a sort of pre-import state, so i don't need to copy the big files all the time, when i already have them.

I hope this can be fixed sometime soon, because it shouldn't be a hard fix, as long the core features are already there, and i saw i can already grab the modid automatically and even the nexus page associated with it.

**Comment by Kongolan** [comment]
Just posted it to Nexus in a kind of advanced version: https://forums.nexusmods.com/index.php?/forum/4306-vortex-feedback/

**Comment by IDCs** [comment]
Hi @Kongolan, apologies for not getting back to you sooner; NMM import process should now import categories(https://github.com/Nexus-Mods/extension-nmm-import/commit/d76ea5df1cd5d306dfd54c826b58774cc0ebefce) and mod metadata(https://github.com/Nexus-Mods/extension-nmm-import/commit/3a441a72c33338b5090d1bbb2348ea55e1c1acd0).
