### ISSUE TITLE
Baldurs Gate: Patch9 

### ISSUE THREAD

**Issue by Deshke** [Nexus-Mods/Vortex#13681]
**Describe the bug**

the `modsettings.lsx` moved in patch9 to the `PlayerProfiles/Public` and is no longer in the `global` directory 

![image](https://user-images.githubusercontent.com/1473225/207732050-ff6b8eb9-6c77-4ceb-8e9e-1673d9629dc1.png)

https://github.com/Nexus-Mods/vortex-games/blob/70c2f8d64e129fa942da21eb30fbd510b8b04542/game-baldursgate3/index.js#L81 needs to be updated to reflect the new location 

**Additional context**
patch9 changes do patch9 things...

**Comment by TanninOne** [comment]
I have not received the patch 9 update yet, I didn't think it was available yet. I'm not comfortable changing this when I can't test myself, hopefully this can happen before christmas.

**Comment by TanninOne** [comment]
Well, Vortex users have profile management anyway, was confusing to have the game do the same so I'd be happy if they leave it out. ;)
