### ISSUE TITLE
Category search by words and not by presets

### ISSUE THREAD

**Issue by Kongolan** [Nexus-Mods/Vortex#137]
Categories currently can only be searched by full presets and not by just a word like "magic" or "texture", it would be by far more helpful if we have a substring search like the mod names have. There is no reason why i have to search for a specific category when more than 1 contains "body" or "gameplay" as words

**Comment by PhoenixTheSage** [comment]
It should be both, what make it worse currently is that the categories only show up if you have a mod installed from whatever category you're looking for...making the category lookup useless for finding archived mods that you'd like to install.
