### ISSUE TITLE
Vortex launches subnautica in epic games instead of steam

### ISSUE THREAD

**Issue by frankmanboy** [Nexus-Mods/Vortex#13712]
- OS: [Windows 10]
 - Vortex Version [0.16.12]

when i press the little arrow to launch subnautica through vortex, it launches epic games launcher. i deleted epic games launcher and now it is telling me to look for an app in the microsoft store. i have the correct manually set location so idk wth to do.

**Comment by frankmanboy** [comment]
nvm i got a solution

**Comment by frankmanboy** [comment]
new problem: mods dont even work. i tried many times but the mod tab in the options just doesnt show up

**Comment by TanninOne** [comment]
Support for this game is provided through a third-party extension: https://www.nexusmods.com/site/mods/202
Pleas report issues with it to the author.

**Comment by Skullplayer** [comment]
When I use Vortex and I am pretty sure than I did everything correctly and I dont know why but when i launch the game trought vortex no mods are installed, I use epic games, any idea why it doesnt work
