### ISSUE TITLE
Redundant Mod Detection Appears Faulty

### ISSUE THREAD

**Issue by flaccidbagel** [Nexus-Mods/Vortex#13736]
This is a follow-up to some older bug reports, along with additional information to try to clarify the issue users are facing. Please see closed issue #12059 (A way to suppress redundant mod message.) for additional details on one of the reported scenarios.

The issue being reported is that the Redundant Mod detection feature incorrectly flags mods are redundant. This has been reported several times, but none of the reports I can see actually show conflicts detected within Vortex, which leads to most discussions ending the same way.

I think this is what's been missed. In many cases, checking review shows that the "redundant" mod IS the mod doing the overwriting. Below is an example. I've just installed a mod that backports a mod called Constructible Object Custom Keyword System to Skyrim SE (1.5.97).

[Constructible Object Custom Keyword System](https://www.nexusmods.com/skyrimspecialedition/mods/81409)
and
[Constructible Object Custom Keyword System SE](https://www.nexusmods.com/skyrimspecialedition/mods/81723)

It is expressly required that Constructible Object Custom Keyword System SE (C.O.C.K.S SE, yeah, unfortunate acronym, but its what the author calls it) requires the original file as a prerequisite, and ONLY modifies two files present from the original mod. Installing it, and marking C.O.C.K.S SE as the winner of the conflict results in this redundant mod message. 

![image](https://user-images.githubusercontent.com/34853221/210183352-7913d42d-ba4c-4f6f-9203-fde694d33053.png)

To confirm however, I then checked the conflicts for said mod:
![image](https://user-images.githubusercontent.com/34853221/210183376-1d826db4-4ee9-4717-8c55-c76fe216ead8.png)

Note that both files show that C.O.C.K.S SE is the conflict winner, and that there are ONLY two options, C.O.C.K.S and C.O.C.K.S SE.

This has happened with other mods as well, but I don't have those installed any longer to demonstrate as I've tried other setups in the meantime. So if this mod is STILL somehow redundant, then there should be a better check for what other mod could possibly be modifying the same files, but at present it simply appears the detection has a fault.

**Comment by TanninOne** [comment]
@flaccidbagel Have you changed the mod order rule _after_ that notification was generated? I can not reproduce this with these two mods either. I can make it generate the redundant mod if I load the base version after the SE version and then deploy, if the order is correct (SE after base) then the message isn't generated.

Also, could you send in the output of the "Review" link in the dialog?

**Comment by TanninOne** [comment]
closed due to lack of feedback
