### ISSUE TITLE
Halo MCC: New Mod format

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#13745]
There is a new mod format available for Halo: MMC since Steam Workshop support was added. This is much simpler than existing patterns and doesn't actually need deployment. 

A new file is available at `C:\Users\USER\AppData\LocalLow\MCC\Config\ModManifest.txt` this contains a plain text list of directories that contain mods. The game will also search a few folder levels down looking for content (exactly how many levels is unclear).
Example:  [ModManifest.txt](https://github.com/Nexus-Mods/Vortex/files/10337199/ModManifest.txt)

Mods that are compatible with this method are contained within a single folder and must have a ModInfo.json file inside the first level. e.g. `My Mod/ModInfo.json`. 

This JSON contains lots of useful information about what the mod includes and which of the MCC games it's intended for. 
[Example ModInfo.json](https://github.com/Nexus-Mods/Vortex/files/10337236/ModInfo.txt)

Example mod: https://www.nexusmods.com/halothemasterchiefcollection/mods/967?tab=files

# References
https://www.halowaypoint.com/news/halo-mcc-december-2022-update
https://learn.microsoft.com/en-us/halo-master-chief-collection/excession/creatingmodpackage/creatinghome

**Comment by Pickysaurus** [comment]
@insomnious I've just been poked about this. Is it something we'll have time to do or is it better to come from the community?

**Comment by insomnious** [comment]
Will investigate this week

**Comment by ConnorDawn** [comment]
On behalf of the Halo Modding community, not only will it make the lives of modders easier, but also the lives of people who play and use the mods through Vortex/Nexus. It's a no brainer <3
