### ISSUE TITLE
Fails to do every task it should do.

### ISSUE THREAD

**Issue by Greeley** [Nexus-Mods/Vortex#13769]
**Describe the bug**
Installing any extension fails, cyberpunk specifically fails because of 'bluebird' npm package is missing.
Searching for an extension that you know is there eg. cyberpunk doesn't return it, instead you must scroll through the list.
Tries (and fails) to install Baldur's Gate extension without any prompt from me, the user, whom should be decided if something else other than vortex get's installed on my system.
Uninstalling doesn't remove all content from your device. 

**To Reproduce**
1. Make an account on Nexus Mod site
2. Click on 'Download Vortex'
3. Wait
4. Install Vortex
5. Wait
6. Launch and try anything

**Expected behavior**
Mod manager to manage it's own dependencies, if it can't do that, how can I trust it with mods to games the developers have no clue about?
**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version [Vortex-1-1-6-14-1665055915]

**Additional context**
Literally wanted it for one game. Installed through GOG, and I have multiple drives in my machine.

**Comment by TanninOne** [comment]
The report contains nothing tangible we could investigate. Tens of thousands of users have installed the Cyberpunk extension just fine...
