### ISSUE TITLE
Vortex enables disabled plugins

### ISSUE THREAD

**Issue by bukiru** [Nexus-Mods/Vortex#13772]
After restarting Vortex it enables plugins that I have disabled. Why?

 - OS: [e.g. Windows 10]
 - Vortex Version 1.6.14

**Comment by bukiru** [comment]
No problem until I have 1200+ mods installed. Vortex can't work with lots of mods?

**Comment by TanninOne** [comment]
Sorry, this is way too imprecise to investigate anything. No, it doesn't really make any difference for Vortex how many mods you have.

**Comment by bukiru** [comment]
WTF?  Your said nothing in common and close issue?
