### ISSUE TITLE
re-engine-wrapper

### ISSUE THREAD

**Issue by n0brainer** [Nexus-Mods/Vortex#13777]
**Describe the bug**
Tue, 10 Jan 2023 17:09:45 GMT - error: Failed to set game mode text=re-engine-wrapper dependency is not loaded!, message=Error: re-engine-wrapper dependency is not loaded!

**To Reproduce**

Try to add RE: Village to Vortex
Vortex says it needs to enable support
Download
Restart
RE:Village does not show up on supported list

Extensions show: 
RE Village game support "failed" (screen shot)
Re-Engine and BTM support are both enabled (screenshot)

RE Village no longer shows up under Games within vortex (RE 2 & 3 are listed - screenshot))

**Expected behavior**
RE Village shows up in managed games

**Screenshots**
![Screenshot_20230110_112224](https://user-images.githubusercontent.com/2116991/211619828-658b59c7-afa4-4003-860b-1f9cddebf314.png)
![Screenshot_20230110_111924](https://user-images.githubusercontent.com/2116991/211619832-2a0b5f52-5789-477b-85e2-7666706e9bbe.png)
![Screenshot_20230110_111948](https://user-images.githubusercontent.com/2116991/211619835-7d3a1cfc-fee3-402f-9474-27254976b682.png)
![Screenshot_20230110_112006](https://user-images.githubusercontent.com/2116991/211619836-05d4a24c-bf79-4a91-9b49-75c9faf63706.png)
![Screenshot_20230110_112026](https://user-images.githubusercontent.com/2116991/211619841-34cfe6f7-6712-4755-a0af-3324676b8ba1.png)

**Platform (please complete the following information):**
 - OS: Win11
 - Vortex Version: 1.6.14

**Additional context**
Tried rebooting, uninstalling RE Village (and ensuring the steam folder removed), Reinstalling RE Village, deleted the plugin, restarted Vortex, etc.

**Comment by TanninOne** [comment]
Is this still an issue? I can't reproduce this, with these two extensions installed they load fine for me.

Also: If you double-click an extension the sidebar gives an error message explaining why it failed, what does that say?

**Comment by TanninOne** [comment]
closed due to lack of feedback
