### ISSUE TITLE
BepInEx Root installer not activating when expected

### ISSUE THREAD

**Issue by toebeann** [Nexus-Mods/Vortex#13864]
I'm developing a Vortex game extension for Chained Echoes to add support for BepInEx plugins/patchers etc., so naturally I would like to use this extension to ease development.

However, in testing of my extension, I noticed that the BepInEx Root installer does not seem to take hold as I would have expected.

For example, one of the currently available mods for Chained Echoes is [Ultrawide Support](https://www.nexusmods.com/chainedechoes/mods/4). The main file for this is an archive with the contents:
```
plugins/Tobey.ChainedEchoes.UltrawideSupport.dll
patchers/Tobey.ChainedEchoes.UltrawideSupport.Unlocker.dll
```

i.e. it contains both a `plugins` and a `patchers` directory at its root as it requires a patcher to function.

Looking at the codebase for the extension it would appear that this configuration should meet the criteria to be considered a BepInEx Root mod, and indeed the modtype does seem to take hold, however the root _installer_ does not seem to activate for this mod, instead it seems to fall back to the `fomod` installer:

```
Sun, 15 Jan 2023 13:49:16 GMT - debug: extracting mod archive archivePath=C:\Users\Toadbomb\AppData\Roaming\Vortex\downloads\chainedechoes\Ultrawide Support-4-0-1-3-1673633479.zip, tempPath=C:\Users\Toadbomb\AppData\Roaming\Vortex\chainedechoes\mods\Ultrawide Support-4-0-1-3-1673633479.installing
Sun, 15 Jan 2023 13:49:16 GMT - debug: extraction completed
Sun, 15 Jan 2023 13:49:16 GMT - debug: [installer] test supported
Sun, 15 Jan 2023 13:49:16 GMT - debug: [installer] test supported result {"supported":false,"requiredFiles":[]}
Sun, 15 Jan 2023 13:49:16 GMT - debug: invoking installer installer=fomod, enforced=false
Sun, 15 Jan 2023 13:49:16 GMT - info: granting app container access to scriptPath=C:\Users\<removed>\AppData\Roaming\Vortex\chainedechoes\mods\Ultrawide Support-4-0-1-3-1673633479.installing, grant=true
Sun, 15 Jan 2023 13:49:16 GMT - info: determine mod type gameId=chainedechoes
Sun, 15 Jan 2023 13:49:16 GMT - info: determined mod type id=Ultrawide Support-4-0-1-3-1673633479, modType=bepinex-plugin
Sun, 15 Jan 2023 13:49:16 GMT - debug: installer instructions [{"type":"copy","source":"BepInEx\\patchers\\Tobey.ChainedEchoes.UltrawideSupport.Unlocker.dll","destination":"BepInEx\\patchers\\Tobey.ChainedEchoes.UltrawideSupport.Unlocker.dll","section":null,"key":null,"value":null,"priority":0},{"type":"copy","source":"BepInEx\\plugins\\Tobey.ChainedEchoes.UltrawideSupport.dll","destination":"BepInEx\\plugins\\Tobey.ChainedEchoes.UltrawideSupport.dll","section":null,"key":null,"value":null,"priority":0},{"type":"attribute","key":"installerChoices","value":{"type":"fomod"}}]
Sun, 15 Jan 2023 13:49:16 GMT - debug: removing temporary path C:\Users\<removed>\AppData\Roaming\Vortex\chainedechoes\mods\Ultrawide Support-4-0-1-3-1673633479.installing
Sun, 15 Jan 2023 13:49:16 GMT - info: finish mod install id=Ultrawide Support-4-0-1-3-1673633479
```

This results in Vortex presenting an error notification `Invalid Installer`, which warns the user that the mod attempted to install files which were not part of the archive:
![image](https://user-images.githubusercontent.com/45315526/212545725-266ffd32-0dfa-474d-aec4-13e7547001b3.png)

The mod does seem to install correctly, which is good, however I am hesitant to release the extension while this issue is present as it will falsely alarm users.

I have tried manually reconfiguring the archive to begin with a root `BepInEx` folder which then contains `plugins` and `patchers` as subfolders, but I get the same result.

Is this a configuration issue on my part, a bug with the modtype-bepinex extension, or something else?

Here is the main function of my extension, if it is relevant at all:

```ts
export default function main(context: IExtensionContext) {
    context.requireExtension('modtype-bepinex');    
    
    context.registerGame({
        id: NEXUS_GAME_ID,
        name: GAME_NAME,
        logo: 'gameart.jpg',
        mergeMods: true,
        queryModPath: () => join('BepInEx', 'plugins'),
        executable: () => GAME_EXE,
        requiredFiles: [GAME_EXE],
        environment: { SteamAPPId: STEAM_GAME_ID },
        details: {
            steamAppId: +STEAM_GAME_ID,
        },
        requiresLauncher,
        queryArgs: {
            steam: [{ id: STEAM_GAME_ID }],
            xbox: [{ id: XBOX_GAME_ID }]
        },
        setup: (discovery) => setup(context.api, discovery),
        getGameVersion: (gamePath) => getGameVersion(context.api, gamePath),
    });

    context.once(() => {
        context.api.ext.bepinexAddGame?.({
            gameId: NEXUS_GAME_ID,
            autoDownloadBepInEx: true,
            customPackDownloader: () => {
                return {
                    gameId: NEXUS_GAME_ID,
                    domainId: NEXUS_GAME_ID,
                    modId: '2',
                    fileId: '2',
                    archiveName: 'BepInEx_x64_5.4.21.0.zip',
                    allowAutoInstall: true
                }
            }
        });
    });
}
```

**Comment by TanninOne** [comment]
I'm a bit confused because the log you posted doesn't really align with the message in the UI. The log displays a successful install through the fomod installer script, it wouldn't have produced that error message.

The bepinex-root installer on the other hand is indeed buggy and would produce that exact error.

The problem occurs effectively because the installer tries to unpack the files twice, the first time works, the second time the file is already gone from the temporary directory and that produces an error.
But the end result should still be all files extracted correctly which matches your observation.

I'll fix that for the next release but until then you might have to tell your users that they can should ignore the error message and maybe manually verify whether the mod was installed correctly.

**Comment by toebeann** [comment]
> @toebeann I'm a bit confused because the log you posted doesn't really align with the message in the UI. The log displays a successful install through the fomod installer script, it wouldn't have produced that error message.
> 
> The bepinex-root installer on the other hand is indeed buggy and would produce that exact error.

That is confusing! I can promise you however that these are the logs which are produced when using this basic game extension and then installing that Ultrawide mod with it, which is what lead me to believe that the bepinex-root installer was not in fact activating, only the bepinex-root modtype.

But now that I think about it, the bepinex-root modtype is never automatically assigned to a file, it must be assigned by an installer as per this codebase. So that is perplexing indeed! Perhaps I wound up against a strange edge case here?

Let me know if I can be of any help re. producing logs/stepping through the debugger/providing replication steps.

**Comment by TanninOne** [comment]
You could be more aggressive about notifying the user, e.g. use the context.once(() => ...) callback to send a notification or even pop up a modal telling users about the compatibility issue, then update and remove the notification once Vortex 1.7.5 is out.

But if you're ok waiting for the fix that's fine too.
