### ISSUE TITLE
Getting misconfigured documents folder when trying to install vortex when document folder is in correct location

### ISSUE THREAD

**Issue by Ethomas2000** [Nexus-Mods/Vortex#13871]
**Getting misconfigured documents folder when trying to install vortex**
This is appearing even though my documents fold is in the correct location and vortex is even

I followed the install instucion video found on nexus, ive also followed the instuctions on the error page.
I also tryed doing a custom install and having it go directly to C/Users/{user name}/Documents it added the files to documens 
as if it installed but still showed the error rather then launching the app.

**Expected behavior**
Its shound install and run vortex without issue

**Screenshots**
![Screenshot 2023-01-20 115452](https://user-images.githubusercontent.com/56280612/213757451-1c126fec-07af-4edd-8e90-e1a7104cf50a.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex-1-1-7-4-1673430283.exe

**Additional context**
I had uninstalled my original version of vortex that did work because it stoped working after an update, although I used to proper
uninstall exe found in the file.

**EDIT**
After trial and error i was able to brute force it to install with custom location although the normal install wouldnt work.
Thank you

**Comment by TanninOne** [comment]
The point the wiki article is making is that the documents folder in windows can be configured and it may not actually be set to c:\users\<account>\documents
If you scroll down in the article it tells you how to fix that.

**Comment by danimperatrice** [comment]
I'm having this problem, where Vortex can't locate the Documents folder cuz its misconfigured.

How did you do it ?   Can someone redirect me to some solution?  Thanks.

**Comment by Ethomas2000** [comment]
https://wiki.nexusmods.com/index.php/Misconfigured_Documents_Folder  This will show you how to fix your documents if they are in the wrong place (try restarting your pc after doing it, if it still isnt working). 

https://www.youtube.com/watch?v=R25FEL45O80&ab_channel=Apoqsi this is a video guide on installing vortex with the auto install.
The files location should look like this C:\Program Files\Black Tree Gaming Ltd\Vortex

**Comment by danimperatrice** [comment]
I tried following their instructions, as in this link.

https://wiki.nexusmods.com/index.php/Misconfigured_Documents_Folder

 
But it so happens that my Documents folder doesn't have a LOCAL tab anymore.

![nolocaltb](https://user-images.githubusercontent.com/127637955/224544144-1ee53354-fd20-49cd-9b02-03bcb0b3d723.png)


I'm gonna watch the whole video when I get back from work.  Thanks in advance.

**Comment by Cyanide68** [comment]
Can you explain how you brute forced it to work? I am having the same issue, and my documents folder is in the correct (only?!) location. I only have one drive. The docs folder has never moved. The wiki shows a whole different properties pop up, with a location tab, and I don't have that. 
I've opened my own thread here, but the trend seems to just be "link the wiki and close" without actually helping, so I figured I'd ask you too. 
Screenshot attached of my documents folder and the properties popup showing location. Second screenshot showing install path.
![image](https://github.com/Nexus-Mods/Vortex/assets/142811439/97e82648-f38d-41b1-af9c-0dc70d928ede)
![image](https://github.com/Nexus-Mods/Vortex/assets/142811439/11b8b886-b47e-44b5-b481-f3202261d254)

**Comment by Ethomas2000** [comment]
@Cyanide68
   I used custom location Version 1.7.8 its the most bottom "Old files" this let me pick the install location which should look like this
(C:\Program Files\Black Tree Gaming Ltd\Vortex) 
I also included a like to a youtube video that helped explain a little about how the files should be installed. 
https://www.youtube.com/watch?v=R25FEL45O80&ab_channel=Apoqsi
After everything looks right try restarting your PC then launch Vortex, I honestly dont fully remember how I did as it was a little while ago but I just kept trying to intall though the diffent ways I seen on Nexus.
you can also make blank folders and give them the name that the install is looking for. After the hassle of updating last time and how usless the support is here I wouldnt recommend updating from nexus again

**Comment by Cyanide68** [comment]
@Ethomas2000 
Thanks. The Version I have allows choosing the install location, and all that. I've done all the recommended things, restarted uninstalled, restarted, reinstalled, etc. This machine has been turned off and on again more times today than it has in the last 3 months. Videos, random internet threads, every thread about it on here... And the useless "support" have just made me beyond frustrated.
I've given up. I'm using BG3MM instead.
