### ISSUE TITLE
[Feature Request] - .NET 7.0 Support

### ISSUE THREAD

**Issue by HylianSteel** [Nexus-Mods/Vortex#13916]
**Is your feature request related to a problem? Please describe.**
Currently, Vortex only supports .NET 6.0 as a requirement to launch. I have 7.0 installed instead of 6.0 and Vortex isn't usable without 7 due to the prompt that blocks you upon launching Vortex without 6.0 installed.

**Describe the solution you'd like**
I'd like .NET 7.0 support for Vortex in the future.

**Comment by TanninOne** [comment]
.NET versions aren't compatible across major releases either way (and not "forward" compatible even on minor releases) but you can have multiple installed alongside each other.
If we change the target version it might work for you without 6 installed but then everyone _else_ who doesn't have 7 installed yet needs to install it.

The way MS have designed it you'll just have to live with the fact that just about every .NET application will either ship their own runtime anyway or needs a different version installed globally. 
I have 5 .NET runtimes for 3 .NET applications I have installed that don't ship their own runtime...
