### ISSUE TITLE
[Feature Request] Better handling of rescinded mod updates

### ISSUE THREAD

**Issue by HylianSteel** [Nexus-Mods/Vortex#13919]
**Is your feature request related to a problem? Please describe.**
When a Mod Author has to pull a new update they recently released for a given mod, Vortex can't seem to properly handle that and keeps flagging a mod as needing to be updated. (If it hasn't been updated at all between the time the new update was released and when it was pulled)

**Describe the solution you'd like**
It'd be nice if Vortex would be able to re-identify what the newest version of a mod is and then unflag the mod as needing an update when necessary.

**Describe alternatives you've considered**
Alternatively, and additionally giving the user the ability to mark a mod as already updated would be helpful as well.

**Comment by TanninOne** [comment]
@HylianSteel It should already work like this. When Vortex checks for updates it simply determines what it thinks is the latest version on the site, if that's newer than what you currently have it suggests an update.
So if the author pulled the latest version and the installed version is the newest one (again) Vortex shouldn't recommend an update after checking for updates, it shouldn't matter what the previous check found.

Please provide an example where it doesn't work as intended so I can investigate.

**Comment by TanninOne** [comment]
You're right, that doesn't work as intended so this is a bug.
