### ISSUE TITLE
Beat saber mods constantly showing multiple popups

### ISSUE THREAD

**Issue by Josh-65** [Nexus-Mods/Vortex#13983]
**Describe the bug**
When I go and update/install mods I get multiple popup for 
1. Possible game update (This is pointless since I'm actively and knowing installing mods. An option to turn this of should be made)  Yes i install BSIPA and have ran beat saber before installing mods
![image](https://user-images.githubusercontent.com/26977075/217468700-62e2bf3b-1338-4f4e-ad1a-85df822e9082.png)

2. Asking to replace or crate a new version even when I haven't got any others versions. There should be an option to always replace.
![image](https://user-images.githubusercontent.com/26977075/217468766-ae4b0e51-75c8-4674-8283-c324593d2525.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to beat saber mods
2. Install a mod that has been installed before
3. Wait a few seconds
4. See the multiple popup

**Expected behaviour**
It shouldn't show either of the popups

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11 build 22621.1105
 - Vortex Version: 1.7.6

**Additional context**

**Comment by TanninOne** [comment]
a) Beat Saber support is added through a third-party extension, the first dialog is not part of Vortex itself
b) The second dialog means you definitively have an older version of the mod installed which means you absolutely have to make a call if you want to replace it or not.

**Comment by Josh-65** [comment]
For the second screenshot it can't be since I just install beat saber with no mods then used vortex to fresh install a new mod.

**Comment by TanninOne** [comment]
Then the dependencies being resolved there trigger two versions of the mod to be installed, this dialog gets triggered on the second
