### ISSUE TITLE
Improve the "Failed to start up" error message.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#13991]
An increased number of users have been reporting the "Vortex failed to start up" message and are not clear on how to proceed/fix the problem. https://github.com/Nexus-Mods/Vortex/blob/cffe502501d3d9a1c1afdc3b7c75dceb61fbec53/src/main.ts#L11

![image](https://user-images.githubusercontent.com/31670524/217828361-0e92e0e9-82d4-426f-8d5c-b1e6db942254.png)

Can we update the text to the template below?

> # Vortex failed to start-up
> An unexpected error occurred while Vortex was initialising: ${ERROR MESSAGE (no trace?)}
> 
> This is often caused by a bad installation of the app, a security app interfering with Vortex or a problem with the Microsoft Visual C++ Redistributable installed on your PC. To solve this issue please try the following: 
> 
> \- Reinstall Vortex from the Nexus Mods website
> \- Install the latest Microsoft Visual C++ Redistributable (you can find this using a search engine)
> \- Disable any anti-virus software or other security apps that interfere with Vortex and install it again
> 
> If the issue persists, please create a thread in our support forum for further assistance. 

## Recent Examples

- https://forums.nexusmods.com/index.php?/topic/12614493-vortex-unhandled-error/
- https://forums.nexusmods.com/index.php?/topic/12614433-vortex-failed-to-start-up/
- https://forums.nexusmods.com/index.php?/topic/12609582-your-vortex-is-corrupted-message/

- https://forums.nexusmods.com/index.php?/topic/12610671-unhandled-error/

**Comment by TanninOne** [comment]
This is implemented and should be released with 1.8.
