### ISSUE TITLE
ECONNRESET Whenever I try to upload a SkyrimSE Mod Collection into Nexus

### ISSUE THREAD

**Issue by diotodd** [Nexus-Mods/Vortex#14017]
Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at __node_internal_errnoException (node:internal/errors:595:12)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)

1. Go to Collections>Workshop
2. Click on "Create a Collection/From Profile"
3. Choose "Upload New" on the new collection.

I expected to collection to be uploaded into Nexus succesfully

![cc3](https://user-images.githubusercontent.com/69166498/218708311-73044034-4941-49a0-a868-c620019ebcb4.PNG)

 - OS: Windows 10
 - Vortex Version 1.7.8

**Comment by TanninOne** [comment]
ECONNRESET means the server (or a network node between you and the server, so it could also be the firewall, ISP, DDOS protection on the server end) is closing the connection, that's not a client error we could address
