### ISSUE TITLE
Invalid Mergex XML data, also can't make a report

### ISSUE THREAD

**Issue by Lippiece** [Nexus-Mods/Vortex#14028]
Thank you for your work.

**Describe the bug**
Vortex has issues merging Friendly HUD and Autoloot mods. When both deployed, the Autoloot menu is always displayed in "Mods" options menu in game. "Report" button doesn't do anything.

**To Reproduce**
1. Install both mods
2. Deploy
3. See error

**Expected behavior**
For those mods to coexist peacefully and for the report to be submitted.

<details>
<summary>Illustrating GIF</summary>

https://user-images.githubusercontent.com/47634624/219773062-bdbd1745-b0ec-45e0-9f7d-339380e3fc1e.mp4

</details>

<details>

<summary>Screenshots</summary>

![Vortex_4djTkH2co6](https://user-images.githubusercontent.com/47634624/219772219-a23e075a-0a66-479d-b306-05eae175be23.png)

![Vortex_kZevbIYjbA](https://user-images.githubusercontent.com/47634624/219772224-d4531ae2-5199-47f1-9100-ea52c47e1498.png)

</details>

**Platform:**
 - OS: Windows 10
 - Vortex Version 1.7.8

**Additional context**
"mods" folder contents:
[mods.zip](https://github.com/Nexus-Mods/Vortex/files/10771137/mods.zip)

**Comment by TanninOne** [comment]
@Lippiece 

Sorry, your attached file does not include the relevant file (<staging folder>\__merged\bin\config\r4game\user_config_matrix\pc\input.xml or - if that file doesn't exist - <game folder>\bin\config\r4game\user_config_matrix\pc\input.xml) - without it there is nothing I could investigate.

My suspicion though is that the first path (to staging) does indeed not exist and the file in the game directory has been written by an incompatible application.

**Comment by Lippiece** [comment]
OK, thank you, [here](https://gist.github.com/Lippiece/0079e4797d676fbcba7f73855aba4056#file-input-xml-from-__merged) it is (from "__merged...").

And [this](https://gist.github.com/Lippiece/0079e4797d676fbcba7f73855aba4056#file-input-xml-from-game-folder) one is from the game folder.

Also, may I ask why sending reports from Vortex with the "report" button doesn't work?

**Comment by TanninOne** [comment]
I can assure you it works, we get a ton of reports sent in that way. I'm not sure why yours doesn't work, do you get an error message or maybe something in the log file?

The only reasons I can think of is either your attachment is being rejected by the server (due to size or some kind of virus protection, I can't be sure what the server is doing with the files) or your account might be banned from feedback due to profanity in the past (the feedback system has its own ban list)
