### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by xGrimReaperxx** [Nexus-Mods/Vortex#14037]
![What is this](https://user-images.githubusercontent.com/125866385/220055937-f46c372d-2976-4d18-8593-cdee30acdd47.jpg)

I have no idea how this popped out. I have no anti-virus and it was still working fine prior to this thing appearing. It updated and it churned this error out.

**Comment by TanninOne** [comment]
There are three possible reasons for this error:
- you're trying to run Vortex while it's still being updated and it just so happens that the installer is in the process of installing that exact file. In this case the error should disappear if you just retry a moment later.
- an AV or some malicious software is locking or has deleted the mentioned file (xmljs)
- you have a broken installation of the VC runtime on your system. You can repair it by getting the installer from here: https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 and installing it again.
