### ISSUE TITLE
On opening, nexus attempts to access files inside a drive that doesn't exist.

### ISSUE THREAD

**Issue by Vogladyte** [Nexus-Mods/Vortex#14081]
When I open up nexus I receive the following error, however nexus doesn't interact with anything other than my C: drive, which it and all the games I use it for are on, and F: is a USB drive. this doesn't affect anything while launching my games, but it does pop up multiple times with different messages I open the app. It's annoying and I was wondering if there was a fix for this? Thanks in advance

Message 1: 

**Accessing "F:\Steamlibrary\steamapps" failed with an error that indicates a hardware problem. This may indicate the disk is defective if it's a network or cloud drive it may simply indicate temporary network or server problems.

Possible error causes:
1. "F:\Steamlibrary\steamapps" is a removable, possibly network drive which has been disconnected.
2. An External application has interferred with file operations (Anti-virus, Disk Management Utility, Virus)**

Message 2:

**Accessing "F:\Program Files (x86)\Origin Games\ STAR WARS BATTLEFRONT II \__Installer\installerdata.xml" failed with an error that indicates a hardware problem. This may indicate the disk is defective if it's a network or cloud drive it may simply indicate temporary network or server problems.

Possible error causes:
1. "F:\Steamlibrary\steamapps" is a removable, possibly network drive which has been disconnected.
2. An External application has interferred with file operations (Anti-virus, Disk Management Utility, Virus)**

**Comment by FernandoAFOliveira** [comment]
I am having the same issue. **Accessing "E;\modvortex\Witcher Script Merger... This is the DVD-Rom,

**Comment by TanninOne** [comment]
Vortex doesn't have its own list of Steam library paths, it gets that list from Steam itself.
So for this to go wrong here, your steam configuration would have to have that drive set up as a steam library. You should be able to fix that in steam -> settings -> downloads -> steam library folders

**Comment by LoneStrider18** [comment]
I am having this issue with The Witcher 3 also, and what you claim isn't true. Steam hasn't, and never had my E drive being my disk drive as a steam library, or any interaction with steam. This issue only exists with The Witcher 3.
