### ISSUE TITLE
Please update built-in 7-Zip 16.04 to latest version

### ISSUE THREAD

**Issue by Anvirol** [Nexus-Mods/Vortex#141]
Based on files located at Vortex\resources\app.asar.unpacked\node_modules\7z-bin\win 
Vortex seems to be using 7-Zip version 16.04 which was released back in 2016. 

Since then there has been performance enhancements and security updates.
If Vortex is indeed using these files, perhaps there's some merit to updating them?

**Comment by TanninOne** [comment]
Damn, this is a regression. Good catch.
Version 0.14.3 (current stable) has 7-zip version 18.05 bundled but I forgot to merge that change to the branch of 0.15

**Comment by TanninOne** [comment]
fixed, 0.15.2 now comes with 7zip 18.05.
