### ISSUE TITLE
plugin delete button for Vortex mod manager

### ISSUE THREAD

**Issue by XystianStrader** [Nexus-Mods/Vortex#14100]
Is my feature request related to a problem? Yes, it is. let us review. It takes a complete removal of Skyrim folders in their respective places and then an uninstall and complete reinstall to get a "clean Skyrim install" that is ready for mods right? In Vortex Mod Manager, you can go in and remove and uninstall all previous mods, but not the plugins, and why is disable/ghost feature not enough? Because when I take the steps to get my "Clean Skyrim Install" ready for modding and I open Vortex, I can have no mods in the list but there will still be a complete list of plugins and one or more of them may be the issue why you had to initate a "Clean Skyrim install" procedure. Now, I'm still learning the modding thing, so I cannot pinpoint which one of those plugins might be the issue skillfully. The point being, you should have this "delete plugin button"feature, so that your Vortex Mod List AND you Vortex plugin list are as clean as your new "cleaned Skyrim install." Because without it, one or more problematic plugins are still on there and could somehow activate, thus tainting the entire install, which is why you reinstalled, when you could have simply had the button to delete all plugins as well.

I would like to see a simple "delete and delete all plugins" button feature added so that this awesome mod manager can be compatible with starting the modding sequence all over scenario.

I cannot think of an alternative that would simplify everything when it comes to the plugin list. Vortex Mod Manager is superb. It does a LOT of the work for you. I am a new user and find it easy to do just about everything else but the plugins.

Thank you for your time. I know this topic has been brought up before and I see why those threads were closed, so I did my best to explain it all very thoroughly, as per your request. This feature would simplify modding for the less skillful that want to let Vortex do what it does for them. Voretx does everything else for me, but the above stated and it appears there are other users who need this feature as well but were not able to relay the information necessary to make the feature a reality. This feature will give you the ability to do the only thing you cannot do and for that reason it complicates common clean reinstall protocol. It is a confliction with the common protocol of clean installs and the feature would make Voretx capable of EVERYTHING. Thank you.

**Comment by TanninOne** [comment]
ngl, this report is extremely hard to read, punctuation and some better grammar would go a long way.
Also, a ticket should ideally be short and concise, not tell a story.

anyway, afaict, I don't think a  "delete plugins" option would be useful for the use case you describe. plugins and mods are connected, removing the plugin while keeping the rest of the mod rarely makes sense and in those cases, disabling or ghosting the plugin is perfectly sufficient.

**Comment by XystianStrader** [comment]
Ya wanna refer to my grammar when what I said made perfect sense. If yer
competition does it, you might wanna consider it. In yer case, at this
point with Vortex, yer correct on that aspect, it isnt needed, but should
be offered. And bless yer heart, talkin noise cause I type in my Texan
accent.

**Comment by Solverbolt** [comment]
I am reopening this myself, as this is still a very big problem. 

I have more than 18 different plugins for Fallout 4 that are disabled, but I cannot remove. I have even tried a complete clean wipe of Vortex and Fallout 4, and as soon as Install Vortex, the plugin list is back. 

Ghosting and Disabling is not sufficient when Vortex is randomly activating disabled or ghosted plugins that have no output, as the Mod they were associated with is gone, so it crashes the game.  

@TanninOne To be blunt, give us the ****ing Plugin Delete button and quit being a grammar Nazi extraordinaire

**Comment by Grammerless** [comment]
F U n UR Grammar.   Maybe u need some Punchuation.    Just give us t button.
