### ISSUE TITLE
Vortex Mod Manager will drop frames after new download

### ISSUE THREAD

**Issue by Scarundy** [Nexus-Mods/Vortex#14113]
Your username/username(s) affected
Scarundy

Bug/error being reported:
Every time I download a new mod, Skyrim(SE) Becomes unplayable. Frames dropping to 15FPS or even less.

Optimally an ordered list with the steps needed to reproduce the bug

Example:

    Download any mod
    Download with Vortex and be sure to deploy
    Open SkyrimSE and see results
    -->

Expected result:
Enjoy SkyrimSE with my new mod(s) Installed

Actual result:
Open up a save and get blasted with framedrops, Almost impossible for me to even close the game!

FIX:
Updating my (Nvidia) graphics drivers after installing a mod. Very tedious.

ARGUMENTS:
Yes, my vortex is up to date, Yes. I tried the game without ENB/BethINI or any other tools installed. Yes. I sent an email to nvidia before finding out Vortex was the culprit and they were as confused as I am. Yes. I tried other driver versions.

Conclusion:
Vortex is at fault. Please find a fix, and update.**Describe the bug**

Platform:
 - Microsoft Windows [Version 10.0.19045.2604] (WINDOWS 10)
 - Vortex Version 1.7.8

**Comment by TanninOne** [comment]
Vortex just installs the mods to the game directory, it has nothing to do with your performance in game.

**Comment by Scarundy** [comment]
Well, it got fixed for some reason. I have no idea what's going on with my
game.. apologies

Op ma 13 mrt 2023 om 11:18 schreef TanninOne ***@***.***>:

**Comment by TanninOne** [comment]
Thank you for the update!
