### ISSUE TITLE
Can't upload collection if initial upload draft is deleted. Vortex can't find the webpage, locking you out.

### ISSUE THREAD

**Issue by Technic235** [Nexus-Mods/Vortex#14115]
I had a bug that locked me out from uploading my collection. I uploaded my collection then decided I didn't like the first revision and I didn't want my mod page to show two revisions before I even uploaded it (for no reason, really), so I deleted the revision. I assumed I would be able to upload my collection again as a 1st revision, but I wasn't able to upload because Vortex thought it was a 2nd revision, instead of a new upload, and couldn't find the collection's web page.

As a result, it gave me the error message "The server rejected this collection" and "not allowed to edit_collection? this collection". The collection was 50+ mods and contained lots of install instructions/dependency connections so I didn't to redo all that work. I did end up creating a new local collection and spent 20 minutes copy-pasting all the instructions, using a word editor as a go-between facilitator.

For polish reasons, especially since Vortex and Nexus are meant to last for years, I believe this should be addressed somehow.

**Comment by TanninOne** [comment]
I agree, but this is not something that can be fixed on the Vortex side, please report here: https://github.com/Nexus-Mods/web-issues/issues
