### ISSUE TITLE
Vortex slow to start up, and buttons rarely work

### ISSUE THREAD

**Issue by NerdyB1443** [Nexus-Mods/Vortex#14123]
**Describe the bug**
Vortex is extremely slow on my PC to the point takes almost an hour for it to even open, and buttons on certain things rarely if ever work, and when they do it once again takes forever for it to do anything.

**To Reproduce**
Issue 1 reproduction: 
1.  Open Vortex
2. wait for at least an hour for anything to open and then wait another hour for everything to settle, sometimes it won't settle at all and you have to close and reopen the program

Issue 2 reproduction:
1. repeat the last steps
2. click plugins, infinite loading screen
3. go to collections, and click resume, nothing happens whatsoever

**Expected behaviour**
Vortex opening and settling in a reasonable time, and the buttons working, no infinite loading screens

**Platform (please complete the following information):**
 - OS: windows 10
 - Vortex Version: 1.7.8

**Comment by TanninOne** [comment]
Can't reproduce. Without further information this can't be investigated.
