### ISSUE TITLE
bright theme hover color

### ISSUE THREAD

**Issue by soraphis** [Nexus-Mods/Vortex#142]
- the red in the bright themes font really hurts

so i cloned it and changed it to an grey tone, but:

you can't set the text-color for hovered elements, so if you set the text color to: `#2a2c2b` you can't see the text anymore. you also can't change the hover color, this means you are forced to use a bright text-color, but on the bright theme the background is bright.
you see the problem.

also, its nice to have the option to change the css directly ... but i have no clue about the used classes.

proposed solution:
- add option to change `brand-menu:hover`
- add option to change `text-color:hover`

**Comment by TanninOne** [comment]
The bright theme was removed in 0.15.2 because it wasn't supported properly anyway

**Comment by soraphis** [comment]
Why allowing custom color schemes at all if things like hover color are hard coded?

**Comment by TanninOne** [comment]
Just the bright theme was dropped, themeing is possible just as before. It is true however that the way the ui is currently built you won't get far with just a few sliders and colour pickers.
