### ISSUE TITLE
Mods do not get fully deleted from database upon uninstallation

### ISSUE THREAD

**Issue by Cutleast** [Nexus-Mods/Vortex#14202]
**Describe the bug**
When a mod is uninstalled it does not get removed from every profile that had it. I found "dead links" in the database under persistent>profiles>[PROFILEID]>modState.

**To Reproduce**
1. Add a mod to two or more profiles
2. Enable it in both
3. Uninstall it from one of the profiles
4. The mod is still in the database of the other profile

**Expected behavior**
The mod should get removed from the data of all profiles upon uninstallation.

**Screenshots**
Profile mods:
<img src="https://i.imgur.com/QDRVmR3.png" />

Installed mods:
<img src="https://i.imgur.com/IzxPAhP.png" />

**Platform (please complete the following information):**
 - OS: Windows
 - Vortex Version: latest (1.7.8)
 
**Additional context**
I found the bug while fixing an apparent error with my tool ([MMM](https://www.nexusmods.com/site/mods/545)).

**Comment by TanninOne** [comment]
This is working as intended, the profiles may have an enabled/disabled state for mods that aren't currently installed - for all Vortex knows you may plan to reinstall the mod before activating the profile again.
The modState for a profile will only be "sanitized" when it gets activated, as long as it isn't, it's allowed to be outdated.
