### ISSUE TITLE
Mods not working after Valheim extension update 

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#14217]
From Eric via e-mail

Valheim extension not working. Crashing Unity? Attached screenshots. Will pick up on Tuesday after bank hols

![image (5)](https://user-images.githubusercontent.com/26166085/230385103-1210089e-af99-4f06-ad13-b31e25e0c7e3.png)
![image (4)](https://user-images.githubusercontent.com/26166085/230385109-f6a23978-0836-4bc6-ab76-dc8372d9a1ee.png)
![image (6)](https://user-images.githubusercontent.com/26166085/230385111-6ce1117b-f045-4c17-a134-8352597762ad.png)

**Comment by IDCs** [comment]
No longer applicable - closing
