### ISSUE TITLE
Missing Bannerlord.exe file in typical location

### ISSUE THREAD

**Issue by ryancade11** [Nexus-Mods/Vortex#14215]
I bought the Bannerlord Game from the widows store so I would be able to play it on my console and on my pc from the same files(excluding mods). Once I discovered that mods could be fun, I tried downloading them via Vortex. Vortex could not find Bannerlord, so I had to manually click on the folder. I tried every folder I could try near where I knew the executable should be. The only problem is that it does not exist. Instead, to launch the game you select Launcher.Native

I believe this is what is causing Nexus confusion, but I'm not sure how to get around it. 

Important info. I deleted everything in the Xbox games folder and redownloaded Bannerlord II and am still getting the same issue.

Below are some screenshots:

![image](https://user-images.githubusercontent.com/130029338/230280445-3e0b72bd-ad50-4bde-9472-d2813588e3f3.png)

![image](https://user-images.githubusercontent.com/130029338/230280540-bcf4f99c-9e48-40da-a2e1-f917f2695ea6.png)

![image](https://user-images.githubusercontent.com/130029338/230280630-4d8daf49-9f71-4cbb-8084-634bd956efef.png)

![image](https://user-images.githubusercontent.com/130029338/230280693-ece3faaf-956b-4826-89b5-901f732a46dc.png)

![image](https://user-images.githubusercontent.com/130029338/230280772-268f1e40-9581-4c25-873b-179b76303929.png)

![image](https://user-images.githubusercontent.com/130029338/230280936-fff0e396-db89-4227-9cff-ce44fe708713.png)

![image](https://user-images.githubusercontent.com/130029338/230281132-66ee9be2-99de-4d4e-9ce1-9958a43760c8.png)

![image](https://user-images.githubusercontent.com/130029338/230281224-339ab90e-a92f-4723-8984-8076ba4d42be.png)

![image](https://user-images.githubusercontent.com/130029338/230281359-1b8bfed2-998a-40aa-be51-e359781b01b0.png)

**Comment by ryancade11** [comment]
I realize it may be confusing, but the game works fine. I just cant get Vortex to find it.

![image](https://user-images.githubusercontent.com/130029338/230281904-f15a59a2-0577-46bc-bb22-0f5f30606aee.png)

**Comment by insomnious** [comment]
I'm looking into this

**Comment by insomnious** [comment]
Will be fixed in Vortex 1.8
