### ISSUE TITLE
Will not load

### ISSUE THREAD

**Issue by rempeldev** [Nexus-Mods/Vortex#14220]
Vortex will not load. Fully updated window 10, made sure I have all dependencies. Uninstalled and reinstalled countless times since 2018.  The program will never load on my computer, never has and never will. It will just sit at the logo in the center of the screen and never do anything, which I can leave for hours at a time even overnight and it will never load the program. Task manager shows 0% cpu on the task. Output of debug from visual studio below. I am stumped, I've been using NexusModManager in the mean time but it's been 5 years, no matter how updated vortex is, it will never load on my particular computer. 

Current specs:
Windows 10 Pro 22H2 19045.2788 (not activated)
MSI B450-A Pro Max motherboard
AMD Ryzen 5 3600
16 GB DDR4 Ram
500gb m.2 western digital SSD
250gb Kingston SSD
8TB HDD
2TB Surveillance HDD

![image](https://user-images.githubusercontent.com/78399486/230686260-faa32c06-fb35-4dd7-95a3-2ff9cefb6546.png)

Visual Studio Output:

'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\ffmpeg.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\dbghelp.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\UIAutomationCore.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'.
'Vortex.exe' (Win32): Unloaded 'C:\Windows\System32\rpcrt4.dll'
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\msimg32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\propsys.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\IPHLPAPI.DLL'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\DWrite.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\winspool.drv'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\secur32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\winhttp.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\sspicli.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\umpdc.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\mswsock.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'.

'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\KBDUS.DLL'.
'Vortex.exe' (Win32): Unloaded 'C:\Windows\System32\KBDUS.DLL'
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'.
logging started
'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\libxmljs\build\Release\xmljs.node'.
'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\winapi-bindings\build\Release\winapi.node'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\RstrtMgr.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\ncrypt.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\ntasn1.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\xxhash-addon\build\Release\addon.node'.
'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\leveldown\prebuilds\win32-x64\node.napi.node'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\comctl32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\dpapi.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\nlaapi.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\nsi.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc6.dll'.
The thread 0x6714 has exited with code 0 (0x0).
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\dnsapi.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'.
'Vortex.exe' (Win32): Unloaded 'C:\Windows\System32\WinTypes.dll'
'Vortex.exe' (Win32): Unloaded 'C:\Windows\System32\WinTypes.dll'
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\Windows.UI.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\InputHost.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\WindowManagementAPI.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\twinapi.appcore.dll'.
'Vortex.exe' (Win32): Unloaded 'C:\Windows\System32\twinapi.appcore.dll'
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\wtsapi32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\winsta.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\mscms.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\coloradapterclient.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\MMDevAPI.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\ResourcePolicyClient.dll'.
'Vortex.exe' (Win32): Unloaded 'C:\Windows\System32\ResourcePolicyClient.dll'
'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\d3dcompiler_47.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\libGLESv2.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Program Files\Black Tree Gaming Ltd\Vortex\libEGL.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\dcomp.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d1bd230cd08e7436\nvldumdx.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\cryptnet.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\drvstore.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d1bd230cd08e7436\nvwgf2umx.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d1bd230cd08e7436\NvCamera\NvCameraAllowlisting64.dll'.
'Vortex.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d1bd230cd08e7436\NvCamera\NvCameraAllowlisting64.dll'
The thread 0x2ac8 has exited with code 0 (0x0).
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\nvspcap64.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'.
The thread 0x5a80 has exited with code 0 (0x0).
The thread 0x34bc has exited with code 0 (0x0).
The thread 0x5834 has exited with code 0 (0x0).
The thread 0x6af4 has exited with code 0 (0x0).
The thread 0x6994 has exited with code 0 (0x0).
The thread 0x6bdc has exited with code 0 (0x0).
The thread 0x3d5c has exited with code 0 (0x0).
The thread 0x2494 has exited with code 0 (0x0).
Exception thrown at 0x00007FF81DB34FD9 (KernelBase.dll) in Vortex.exe: 0x0000071A: The remote procedure call was canceled, or if a call time-out was specified, the call timed out.
The thread 0x67b8 has exited with code 0 (0x0).
The thread 0x6768 has exited with code 0 (0x0).
The thread 0x60b8 has exited with code 0 (0x0).
The thread 0x5ac4 has exited with code 0 (0x0).
The thread 0x1308 has exited with code 0 (0x0).
The thread 0x6368 has exited with code 0 (0x0).
The thread 0x6b6c has exited with code 0 (0x0).
The thread 0x698c has exited with code 0 (0x0).
The thread 0x379c has exited with code 0 (0x0).
The thread 0x421c has exited with code 0 (0x0).
The thread 0x3790 has exited with code 0 (0x0).
The thread 0x64cc has exited with code 0 (0x0).
The thread 0x36fc has exited with code 0 (0x0).
The thread 0x492c has exited with code 0 (0x0).
The thread 0x69b4 has exited with code 0 (0x0).
The thread 0x65c8 has exited with code 0 (0x0).
The thread 0x491c has exited with code 0 (0x0).
The thread 0x3370 has exited with code 0 (0x0).
The thread 0x3058 has exited with code 0 (0x0).
The thread 0x342c has exited with code 0 (0x0).
The thread 0x5c7c has exited with code 0 (0x0).
The thread 0x46c4 has exited with code 0 (0x0).
The thread 0x54c0 has exited with code 0 (0x0).
The thread 0x47a0 has exited with code 0 (0x0).
The thread 0xe70 has exited with code 0 (0x0).
The thread 0x22f0 has exited with code 0 (0x0).
The thread 0x226c has exited with code 0 (0x0).
The thread 0x3804 has exited with code 0 (0x0).
The thread 0x67b0 has exited with code 0 (0x0).
The thread 0x470 has exited with code 0 (0x0).
The thread 0x804 has exited with code 0 (0x0).
The program '[13216] Vortex.exe' has exited with code 0 (0x0).

**Comment by TanninOne** [comment]
I mean, you can see in that trace that it starts dying around here: 

```
'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d1bd230cd08e7436\nvwgf2umx.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d1bd230cd08e7436\NvCamera\NvCameraAllowlisting64.dll'.
'Vortex.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nv_dispi.inf_amd64_d1bd230cd08e7436\NvCamera\NvCameraAllowlisting64.dll'
The thread 0x2ac8 has exited with code 0 (0x0).
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\nvspcap64.dll'.
'Vortex.exe' (Win32): Loaded 'C:\Windows\System32\DXCore.dll'.
The thread 0x5a80 has exited with code 0 (0x0).
The thread 0x34bc has exited with code 0 (0x0).
The thread 0x5834 has exited with code 0 (0x0).
The thread 0x6af4 has exited with code 0 (0x0).
The thread 0x6994 has exited with code 0 (0x0).
The thread 0x6bdc has exited with code 0 (0x0).
The thread 0x3d5c has exited with code 0 (0x0).
The thread 0x2494 has exited with code 0 (0x0).
Exception thrown at 0x00007FF81DB34FD9 (KernelBase.dll) in Vortex.exe: 0x0000071A: The remote procedure call was canceled, or if a call time-out was specified, the call timed out.
```

The exception is probably a result of it already closing prematurely (see the threads being terminated before the exception happens.
So the problem is more likely in the loading steps above, NvCameraAllowlisting64.dll, nvspcap64.dll and DXCore.dll, all related to the graphics card driver so my first instinct would be to do a clean reinstall of your gpu drivers.

You can also try disabling gpu acceleration, for that edit (or create) the file %APPDATA%\Vortex\startup.json and make it read `{"disableGPU":true}`

If you're running that MSI Afterburner you might also want to try closing it before starting Vortex and if that makes a difference, update it.

**Comment by rempeldev** [comment]
Found it, looks like it there were some corrupted files that were remaining in the %APPDATA%\Vortex folder between each uninstall and reinstall. Did a full clean install of vortex and it resolved the issue.
