### ISSUE TITLE
Entry point not found error

### ISSUE THREAD

**Issue by darkyivt** [Nexus-Mods/Vortex#14258]
Vortex mod manager just plainly refuses to launch after the 1.8.0 update, throwing the exception "The procedure entry point DiscardVirtualMemory could not be located in the dynamic link library (filepath to Vortex.exe)"

The error happens on simply attempting to launch the program. Windows 8.1, Vortex Version 1.8.0

**Comment by TanninOne** [comment]
Vortex 1.8 uses a newer electron version that only supports windows 10 and newer. Windows 8.1 is end of life since January, you will see a lot of applications stop working soon.
