### ISSUE TITLE
Failed to install the extension "Mtframework Arc Support" from "github.com", please check the notifications.

### ISSUE THREAD

**Issue by Enesore** [Nexus-Mods/Vortex#14273]
Happens on every Vortex launch. There's nothing useful in the notifications, and I can't view my extension list because it prompts me to restart Vortex, which triggers the problem again.

[vortex.log](https://github.com/Nexus-Mods/Vortex/files/11320365/vortex.log)

**Comment by ghost** [comment]
Same here.

**Comment by Taco1701** [comment]
Got the same problem, but fixed it by dowgrading from beta to stable version

**Comment by TanninOne** [comment]
should be fixed with the last update of the extension list

**Comment by Greeley** [comment]
Still happens, just downloaded 2023-05-10
