### ISSUE TITLE
Error when Steam Library no longer exists

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#14288]
**Describe the bug**
In some cases, when a user had a Steam Library set up on a removable drive and that drive is no longer connected, Vortex will throw a confusing error when scanning for games. The error in the screenshots section is coming from https://github.com/Nexus-Mods/Vortex/blob/4dfb5eb2e3e3088858810ccff11c59c3b502685a/src/util/Steam.ts#L270 - apparently bypassing the `catch` statement. 

After troubleshooting this problem with the user, it appears to be caused by bad data in the Steam Library document (Steam\config\libraryfolders.vdf).

This issue could be mitigated by checking the library paths are valid before accepting them here: https://github.com/Nexus-Mods/Vortex/blob/4dfb5eb2e3e3088858810ccff11c59c3b502685a/src/util/Steam.ts#L244

**To Reproduce**
Steps to reproduce the behaviour:
1. Attach a separate drive. Create a Steam Library there.
2. Add a game to the library.
3. Disconnect the external drive.
4. Verify the library is still listed under `Steam\config\libraryfolders.vdf`
5. Start Vortex.
6. (Hopefully) see the error. 

**Expected behaviour**
The missing Steam library is logged in Vortex's log file but doesn't bother the user. 

**Screenshots**
![image](https://user-images.githubusercontent.com/31670524/235669351-43ee7f07-d5c6-441c-b82f-67380fb694b1.png)

[libraryfolders.vdf](https://github.com/Nexus-Mods/Vortex/files/11373238/libraryfolders.txt)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by TanninOne** [comment]
@Pickysaurus There is a reason we ask users for the version number on bug reports...
This exact issue should be fixed in 1.8
