### ISSUE TITLE
Daggerfall Unity mods' files do not get deployed into correct folders unless they are packaged preserving folders structure.

### ISSUE THREAD

**Issue by petroid** [Nexus-Mods/Vortex#14319]
**Describe the bug**
If mod author/packager zipped mod's files without preserving folders structure then files get deployed into Mod Folder configured in game's settings in Vortex (`{DaggerfallUnity install folder}\DaggerfallUnity_Data\StreamingAssets` by default) and thus do not work.

**To Reproduce**
1. Download some Daggerfall Unity mods. For instance, at the moment of writing [this](https://www.nexusmods.com/daggerfallunity/mods/54?tab=files&file_id=203&nmm=1), [this](https://www.nexusmods.com/daggerfallunity/mods/18?tab=files&file_id=54&nmm=1), [this](https://www.nexusmods.com/daggerfallunity/mods/27?tab=files&file_id=80&nmm=1) and [this](https://www.nexusmods.com/daggerfallunity/mods/144?tab=files&file_id=1733&nmm=1) mods are affected.
2. Install
3. Deploy
4. The files are deployed into `{DaggerfallUnity install folder}\DaggerfallUnity_Data\StreamingAssets` folder.

**Expected behavior**
`{DaggerfallUnity install folder}\DaggerfallUnity_Data\StreamingAssets\Mods` is where mods' .dfmod files should go.
`{DaggerfallUnity install folder}\DaggerfallUnity_Data\StreamingAssets\Sound` is the correct folder for mods' .ogg sound files.
`{DaggerfallUnity install folder}\DaggerfallUnity_Data\StreamingAssets\Docs` is for _correctly named_ mods' .txt readme files.
And so on.
For instance, [this](https://www.nexusmods.com/daggerfallunity/mods/273?tab=files&file_id=2640&nmm=1), [this ](https://www.nexusmods.com/daggerfallunity/mods/158?tab=files&file_id=1920&nmm=1)and [this](https://www.nexusmods.com/daggerfallunity/mods/20?tab=files&file_id=1939&nmm=1) mods are deployed correctly.

**Platform (please complete the following information):**
 - Windows 10
 - Vortex Version 1.8.1

**Additional context**
In Vortex there is no way to manually fix misplaced mods' files and/or fix incorrectly packaged mods.

This issue should probably go to https://github.com/Nexus-Mods/vortex-games repository but it has issues disabled. Also, fixing one game does not eliminate the problem altogether.

**Comment by TanninOne** [comment]
That's not a bug though, this is a request to improve the heuristic of how mods should be unpacked, there is always going to be _some_ way for a mod author to confuse the installer.

> In Vortex there is no way to manually fix misplaced mods' files and/or fix incorrectly packaged mods.

You can just open the staging folder and rearrange the files in whatever file manager you like. It's true that Vortex has no UI for this but imho it's also true there is basically no way we would beat a dedicated file manager in terms of functionality.

> This issue should probably go to

Technically yes, practically we prefer to have all issues in a single tracker instead of spread out over multiple repos we'd have to monitor.

**Comment by petroid** [comment]
> You can just open the staging folder and rearrange the files in whatever file manager you like.

That is what I'm doing now. Also I have problematic mods highlighted (neat feature btw) to remind myself to check them in case of updates/reinstalls. But that's a workaround not a fix though.

> improve the heuristic of how mods should be unpacked

At this point, yes. 🙂

But on a bigger scale I'd like to have a way to improve said install heuristic (or make install scripts/rules from scratch) without need of writing code in JS... I guess that's not gonna happen anytime soon 🙁
