### ISSUE TITLE
Application stalls when trying to add a game extension

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#14324]
# Describe the bug
Since 1.8, I've seen several reports of users getting stuck on the page shown below:

![image](https://github.com/Nexus-Mods/Vortex/assets/31670524/1422cbe0-055c-4f76-beb7-d03b5da459ec)

This appears to be a "dead end" for users when they try and download a game while logged out. Perhaps the OAuth changes have caused a problem here? 

# To Reproduce
1. Open Vortex.
2. Ensure you are logged out.
3. Click "Manage" on a game where you don't have the extension installed.
4. Vortex will prompt you to download it.
5. Click download.
6. Journey stalls

# Workaround

Log into Nexus Mods before trying to add a game. 

# Expected behavior
User is prompted to log in before trying to add a game extension. 

# Screenshots

![game issue](https://github.com/Nexus-Mods/Vortex/assets/31670524/9dd3eea9-9f69-44db-a24c-2e43b65fe28a)

https://forums.nexusmods.com/index.php?/topic/12883137-vortex-installing-game-forever/

https://forums.nexusmods.com/index.php?/topic/12873120-my-vortex-is-stuck-on-this-screen-trying-to-install-the-extension-for-ff12-does-anyone-know-the-solution-for-this/

# Platform (please complete the following information):
 - OS: Win11
 - Vortex Version 1.8.1

# Additional context

**Comment by Pickysaurus** [comment]
Tested on 1.7.8 and this is a bug introduced in 1.8+ 

Previously the login prompt would appear at this stage if the user was not logged in.

**Comment by nachobenedetto** [comment]
This issue is still prevalent for me on current version.

**Comment by mpccelon** [comment]
The issue is still happening. It does trigger a sign-in prompt, and the workaround is to cancel and try again once logged in w/ Vortex.

**Comment by lingonsylt** [comment]
> The issue is still happening. It does trigger a sign-in prompt, and the workaround is to cancel and try again once logged in w/ Vortex.

I had the same experience. I was prompted to sign in, which I did, and then to install the needed extenstions, which I also did. That's when I got stuck on the "Installing Game" screen. The same workaround of cancelling and installing again worked for me aswell.
