### ISSUE TITLE
Requesting UAC confirmation I have already accepted Vortex

### ISSUE THREAD

**Issue by Seismic46290** [Nexus-Mods/Vortex#14330]
I have a bunch of mods installed for Stardew Valley, and every time I go to deploy the mods, a UAC pops up. I click 'yes' on the UAC, then the screen tells me to "Please confirm user access control dialogue." Note that the message pops up even after confirming the UAC dialogue. Is this a problem with Vortex or my OS? I have also seen an options under the workarounds tab in Settings to "Allow Symlinks without elevation." From reading other issues submitted this could potentially work, but the info tab for it seems contradictory. The tab reads:

"This will give your windows account the right to create symlinks. You will have to log out or restart your computer for this change to take effect. 
---
Are there drawbacks? This is supposedly disabled for security reasons but
a) It's certainly not safer for us to constantly have to elevate a process
b) Windows lets any account create hard-links, why would symlinks be more of a security problem?
So far as I can tell, this is a win-win."

I can't tell if this is sarcasm or I'm just misunderstanding what selecting this option actually does. the first reason makes me nervous because of this. I've attached reproduction steps and my Vortex Version and OS in hopes that helps at all.

**To Reproduce**
1. Go to 'mods' 
2. Click on 'Deploy mods'
3. UAC confirmation

**Platform**
 - OS: Windows 11
 - Vortex Version 1.8.1

https://github.com/Nexus-Mods/Vortex/assets/133922153/191b0f17-d1d3-4e1b-99aa-df0e94e0e88b

That is the video of the error and the steps leading up to it. It doesn't show the UAC dialogue in the clip, I'm unsure if that has anything to do with the actual error.

**Comment by Seismic46290** [comment]
Edit: Using the "Allow Symlinks without elevation" option also doesn't work because restarting my computer like the directions say to causes the option to turn off again.

**Comment by TanninOne** [comment]
No sarcasm there, the situation is just as odd for me as it is for you. As far as I can tell, symlinks requiring admin rights is just Microsoft being stup... - I mean - weird.

The hand-wavy "Security reasons" is Microsofts own explanation why it works like this but there is no security problems with the _concept_ of symbolic links. Windows supports other types of links for any user and other OSes like Linux and MacOS have symlinks for regular users, there is just no concrete explanation anywhere why specifically symlinks on Windows should be different.
No documented security flaw either as far as I can tell.
And if MS doesn't trust their own symlink implementation, what would be the reason to allow them for admins and on developer systems? Even Admins and Developers would need to know the risks of this feature to make an educated decision...

It's really difficult for me to tell you it's safe when I - and the entire internet - don't even know what the problem _could_ be. If there is an actual reason then MS has successfully kept it secret for 25 years - I find it much more likely that some dev got high some day, had visions of symbolic links molesting him so he told his colleagues to "not trust them" and they could never be bothered to question it.

I'll try to reproduce the problem toggling the switch...

**Comment by HawthorneK456** [comment]
Hi,
Thank you for your initial report of this issue. We posted an update on 22/05/2023 requesting further information from you to allow us to continue to troubleshoot your issue. Unfortunately we haven’t received a response from you since this time. As a result, this issue will be closed.

Please ensure that you update Vortex to the latest version and if you continue to experience this issue and still require our assistance, please log a new bug report. You can reference this historic report by including a link to it if you believe it may be helpful to our future investigations.
