### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect - Stardew Valley

### ISSUE THREAD

**Issue by Pandasrcoolll** [Nexus-Mods/Vortex#14334]
I don't get what i did wrong here, the game won't start at all, what do i do, did i mess something up??

https://cdn.discordapp.com/attachments/553753627978891288/1108994111702306846/IMG_20230519_014054869_HDR.jpg

https://cdn.discordapp.com/attachments/553753627978891288/1108994112226607108/IMG_20230519_014139215_HDR.jpg

https://cdn.discordapp.com/attachments/553753627978891288/1108994112612466728/IMG_20230519_014157029_HDR.jpg

**Comment by Pandasrcoolll** [comment]
Figured it out 😁

**Comment by Prepsxtia** [comment]
how did u figure it out can u pls help because i have the same issue :)

**Comment by Prepsxtia** [comment]
can u pls help that is happening to me can u pls tell me what u did
