### ISSUE TITLE
Unresolvable dependency cycle with only one mod

### ISSUE THREAD

**Issue by PyroDevil** [Nexus-Mods/Vortex#14368]
**Describe the bug**
It seems that somehow I got a dependency cycle containing only one mod:

**To Reproduce**
Unknown. I installed a collection, but not sure if that is reproducible.

**Expected behavior**
Dependency cycles should not consist of only one mod. So if there is some sort of rule that loads A after A, then this rule should be removed by some sort of sanity check.

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/1003994/c97e4fd4-3c8b-489f-a2aa-8ef6e4577825)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.8.3

**Comment by TanninOne** [comment]
@PyroDevil Arguably this rule shouldn't be created in the first place.
If a collection contains such a rule and we simply ignore it with a sanity check, that simply hides the underlying issue that the UI allowed it to be created in the first place. The collection would still contain invalid data and it might still be an issue to other tools trying to support collections.

As such, what we have to figure out how this rules came to be in the first place - which I can't without knowing what collection this actually is.
