### ISSUE TITLE
NMM or Vortex button on Nexus for games added by Vortex

### ISSUE THREAD

**Issue by cybercatgurrl** [Nexus-Mods/Vortex#144]
I know this isn't really related to Vortex but I'd like to be able to use a button next to the manual download button on the Nexus Mods website like how it shows the NMM button but with new game support added by Vortex like Stardew Valley and Subnautica, etc.

**Comment by stavrossk** [comment]
+1. This would be an awesome feature.

**Comment by TanninOne** [comment]
This is more of an issue for the website, you can report them here: https://github.com/Nexus-Mods/web-issues
