### ISSUE TITLE
Collections: Witcher 3 Load Order import/export

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#14401]
**Describe the bug**
When using collections with Witcher 3 the load order is exported using the mod IDs in use by the curator's machine (which are derived from the name of the archive downloaded from Nexus Mods), however, when the user installs the files they may get different (usually newer) versions of certain mods. This means when the load order is imported it doesn't line up to the correct folder and therefore does not replicate the load order as expected. 

**To Reproduce**
1. Download this collection https://next.nexusmods.com/witcher3/collections/z5tjm8 (Revision 85)
2. In the load order JSON file see that the load order looks like this https://gist.github.com/Pickysaurus/e5da17d128862578823c4e7490ff255c - with "AutoLoot All-in-One NG Update_4_2_9-7198-4-2-9-1683854658" near the top.
3. Find "Auto Loot" in your mod list and see that you have "AutoLoot All-in-One NG Update_4_3_0-7198-4-3-0-1685391852" (or later) installed.
4. This is because this mod is set to "Prefer Exact" in the config, which means when the author archives the specific file, Vortex will pull a newer version instead if there is one. 
5. Once the collection install is complete, see that the load order in Vortex does not match the one in the JSON file (you can also see that the numbering system does not make sense!). 

**Expected behavior**
The load order the curator set is exported and imported correctly. 

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/31670524/ed9622c1-a505-4182-8f49-fc07a9bb1eb3)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by IDCs** [comment]
This is no longer applicable
