### ISSUE TITLE
Scan for games button. GONE!

### ISSUE THREAD

**Issue by seriousgamer42** [Nexus-Mods/Vortex#14427]
I recently updated to 1.8.5 from 1.6.5, and I cannot find the scan for games button.
Unless it has moved, where is it?

**Comment by IDCs** [comment]
Hi there - wow apologies for taking us so long to get back to you - I'm sure you know at this point that the game scanner is no longer applicable as all game thumbnails are displayed and it's up to you to select the game you want to manage.
