### ISSUE TITLE
Default mod sorting: enabling mod manually can cause it to change positions in the list

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Vortex#14448]
Quick steps:
Install some game
Install Vortex
Disable automation in Vortex
Add (but not Enable) some mods for that game. DON'T MESS WITH SORTING SETTINGS, keep these default
Start Enabling these mods one by one

ER
Mod I've just enabled stays in place

AR
Mod I've just enabled disappears from the list for some moments then reappears... somewhere.
Depending on mod it might be same position in the list, or some random position.

**Comment by IDCs** [comment]
Hi there - Unfortunately your report contains too little information. Which page are you referring to? plugins page? mods page? loadorder page?

The mods page allows you to filter the table via its columns. If a mod jumps off the screen while you enable it, that's down to your filtering. Closing.
