### ISSUE TITLE
Unresolved file conflicts: support for "prefer this file" instead of ambiguous "before/after"

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Vortex#14447]
Steps to reproduce:
Install some game
Install Vortex
Try to install two mods which contain same file
Open file conflict UI from notification

ER
Interface states clearly which actions will gonna cause which result. I. e. "For this mod pair, files from THIS mod will be preferred".

AR
No damn idea. If I remember correctly, in each particular game "before/after" outcome might be different. If I don't remember correctly - well, joke's on me and on that very clear UI then.

Treating it as a feature request since it lived long enough - and "who knows - knows". Which is not a bug per se, just a bad design choice. And I could be wrong in regard to how it REALLY works.

**Comment by IDCs** [comment]
Hi there, thanks for your report, however - "mod A after mod B" or "mod B before mod A" reads just fine to most users, but I admit that it's subjective.

At this point in development however (Vortex is getting deprecated in favour of NMA) I'm afraid that your request will not be implemented. Closing.
