### ISSUE TITLE
Triaged [Review] - Add support for dotnet version 7, in your requirements - "dotnet version 6 or later"

### ISSUE THREAD

**Issue by BeDaut** [Nexus-Mods/Vortex#14648]
**Describe the bug**
"Vortex requirex dotnet 6 or later" I have dotnet version 7.0.400
downgrading to dotnet 6 works though

**To Reproduce**
1. launch vortex with dotnet 7 installed

**Expected behavior**
"Vortex requirex dotnet 6 or later"

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.9.3

**Additional context**
Add support for dotnet version 7 please, also there's already dotnet test version 8
![изображение](https://github.com/Nexus-Mods/Vortex/assets/43664274/de3fc099-2eac-4908-90ad-59a484b4c762)
![изображение](https://github.com/Nexus-Mods/Vortex/assets/43664274/e86673f1-30d2-40f5-9635-e69c555bbcf4)

**Comment by I2pRandom** [comment]
Problem is, even if you have the correct version of DotNet even with a fresh DotNet install you will still get those errors. 
![image](https://github.com/user-attachments/assets/1a7f076a-0ed7-458c-8638-f160d061d77d)
![image](https://github.com/user-attachments/assets/395d47b7-c30a-4941-879a-abd3ae5e7095)


Hell you can wipe the entire system and at least for me, it still happens.

**Comment by IDCs** [comment]
Hi there - there are technical reasons why only .NET6 is supported by the fomod installer and it does not recognize higher versions. (mostly down to sandboxing installations to ensure the mod can't access files outside of its cwd)

The .NET checker functionality is extremely basic, can call it a "Hello World" application. The executable is compiled using .NET6 and returns 0/true if it's able to load the .NET assemblies, or 1/false if it can't.

The checker being such a basic app - guarantees that if your system is configured correctly, it will find .NET installed. So I'm afraid I'm going to close this ticket as this is 100% down to your environment. Try using sfc /scannow and see if that fixes it and make sure all .NET environment variables are present after installing the redistributable.
