### ISSUE TITLE
Triaged [Added] - Dotnet check failing if Dotnet 6 is uninstalled (Dotnet 7 is detected).

### ISSUE THREAD

**Issue by Chosin137** [Nexus-Mods/Vortex#14686]
**Describe the bug**
Dotnet 6 and above install check is not continuing past Dotnet check. If Dotnet 6 is not installed it will fail the check and then make you install Dotnet 6. It will still find Dotnet 7 installed properly but will still block you from continuing.

**To Reproduce**
Open Vortex Mod Manager

**Expected behavior**
Finds Dotnet 7 and does not block you from using Vortex.

**Screenshots**
![Dotnet 7](https://github.com/Nexus-Mods/Vortex/assets/18730594/8d1d71e3-0a3f-460a-93b0-6b205d2b87f7)

**Platform (please complete the following information):**
 - OS: Windows 11 22H2 Sept 12th update
 - Vortex Version 1.6.3

**Additional context**
Realistically I'm just looking to get clarification on this issue. Should you be able to run Vortex Mod Manager with Dotnet 7? The detection prompt makes it seem like you should. 

Thanks for your time, I understand if its a time / technical issue.

**Comment by IDCs** [comment]
Hi there,

Apologies for the late response.

Without going into too much technical detail, although .NET 7 runtimes do support .NET 6 assemblies and are backwards compatible, several bugs introduced in .NET 7 have unfortunately rendered it less desirable when used with Vortex.

Given that .NET 6 is much more stable, we advise you to use .NET 6 runtimes instead.

I'll mention this dialog to my team and see if we can word it better.

**Comment by HawthorneK456** [comment]
Hi,

This issue has been added to the Vortex backlog to improve the wording on the dialogue. We are utilising Gitlab for our internal planning which is private and not accessible to non Nexus staff. 

That said, you may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity so you may see some updates soon on these older requests, either committing them to continued Vortex development or notifying that they have been passed to the app team for consideration in their design and development. The development of the Nexus Mods App is public and we will be able to include a link to the related issue which has been created so you can continue to track its progress.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874

**Comment by HawthorneK456** [comment]
https://gitlab.nexdev.uk/nexus-mods/vortex/Vortex/-/issues/290
