### ISSUE TITLE
Impossible to ajust load order on a touch screen device like ROG ALly

### ISSUE THREAD

**Issue by fennectech** [Nexus-Mods/Vortex#14697]
**Describe the bug**
It is impossible to ajust load order with a touch screen.  A mouse is required

**To Reproduce**
1. Mod load order
2. Attempt to move a mod with finger using touch screen
3. Nothing happens

**Expected behavior**
Tapping and dragging a mod with a touch screen should move the mod.  It does not

**Platform (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Vortex Version [current]

**Additional context**
I am using an ROG Ally

**Comment by fennectech** [comment]
A workaround is to plug in a mouse or use an app like teamviewer to control the mouse.

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
