### ISSUE TITLE
Triaged [Review] - checking for mod updates fails

### ISSUE THREAD

**Issue by Tommyg930** [Nexus-Mods/Vortex#14758]
**Describe the bug**
I tried to make Vortex Check for updates to any of the mods I had installed for Cyberpunk2077, it said there wasn't an update. decided to check the page of one of the mods I was waiting on an update for but lo and behold the mod was actually updated a little over an hour ago.

**To Reproduce**
1. Have TweakXL V1.3.1 downloaded, but at status uninstalled (https://www.nexusmods.com/cyberpunk2077/mods/4197)
2. in the mods tab, Press the "check for updates" button that appears at the top just below the "go premium" advert.
3. see it report no new updates. doesn't matter if you pick 'optimized' or 'full' from the drop down.
4. now enable the mod and press the check for update button again.
5. now it correctly reports that there is an update availible

**Expected behavior**
Not sure what the distinction between "Check for updates (optimized)" and "Check for updates (Full)" is, but I at least expect at least one of those to check for updates regardless of the mods status (never installed/uninstalled/enabled/disabled)

**Screenshots**

![318aa68e3c37a42f013f90fa39681d5e](https://github.com/Nexus-Mods/Vortex/assets/33021337/4c8b7db5-ebb5-423d-b5dc-34d4bd786e42)
![889b480bc49557cb9dda926338c5d51a](https://github.com/Nexus-Mods/Vortex/assets/33021337/4f4d191a-1eb1-4579-b2b7-b42609c129c4)

**Platform (please complete the following information):**
 - OS: Windows 10 pro, version 10.0.19045 build 19045
 - Vortex Version 1.9.5

**Notes**
The reason I had most of the mods set to uninstalled was because some of those mods were broken so badly by the most recent update to CP2077 that it stopped the game from even loading up. so I was awaiting an update to the mods before enabling them again.

**Comment by insomnious** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
