### ISSUE TITLE
A function to add plugins to a group for easier sorting.

### ISSUE THREAD

**Issue by darkrain261** [Nexus-Mods/Vortex#14770]
So now my mod's plugins are about 700 and some patches between them, while related actually placed far from each other. For example Northern Road, not only I have to deal with sorting NR patches, I have also needed to sort also landscape mods as well (LaWF, Complemtary Grass Fixes and their patches) and I can't list plugins that have no common in name in one search for easier sorting.

I would like to have the ability to add plugins to an user group that has no effect on sorting order itself like the pre-defined LOOT groups but only for filtering when manually editing. For example, when I right-click on a plugin, there will be an option "Add to a group" and then I can choose to "Create a new group" or "Add to an existing group". I hope you get my idea ass it's hard to describe in word only.

That's all I want to suggest. Thank you!

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
