### ISSUE TITLE
locales removement (now it's impossible even manually)

### ISSUE THREAD

**Issue by de-served** [Nexus-Mods/Vortex#14977]
When Vortex installed it install all of the locales.
I'm cleaning every program after installation and remove unneeded/trash files.
Just did it with Vortex - removed 53 trash *.paks (excluding en_US and my locale's file)
When I started Vortex I was very surprised that it says that installation was corrupt.
Ok, "Ignore"...
I placed *.pak's back - it started.
Removed and create empty/nonempty (just few bytes) files as 52 hardlink copies of one dummy file - again "corrupt".
Why Vortex needs ALL of this localisations if there must be enough just two of them for each installation - one worldwide en_US and one for PC locale?..

1. Remove checking for "corruption" for foreign locale's files
2. Don't install them or make possibility for user at installation time to select if user needs all other locales or no (I think 99.999% will say "no")

Really, I don't need 30Mb more of trash on my system. If every software will do like that then there will be gigs of trash.
Good now that I need to clean just only ~15% of the installations. Not 50 or 90

Thank you.

**Comment by IDCs** [comment]
Hi there!

Thank you for your feedback! you may have been notified that Vortex is currently being deprecated in favor of Nexus.App - I will forward your concerns over to the new app; but from a Vortex perspective we will not be removing locales from the installer.

**Comment by de-served** [comment]
Ok, understood.
PS: didn't find such opened issue at https://github.com/Nexus-Mods/NexusMods.App
Maybe didn't search good enough or maybe it is listed somewhere else.
