### ISSUE TITLE
Suggestion - Bethesda BSA incompatibility checking

### ISSUE THREAD

**Issue by LumpySpirit** [Nexus-Mods/Vortex#14983]
Vortex should be able to check for mod incompatibility with BSA files as well as ESPs, like Mod Organizer 2.

I've tried using MO2, but unfortunately it causes issues with my computer so I was forced to uninstall it. It sucks cause I _know_ there's an incompatibility issue with a popular BSA file in my Skyrim modlist, but one of the devs just told me to use MO2, blamed me for causing the computer bugs and left me out to dry.

**Comment by IDCs** [comment]
Hi @LumpySpirit,

As you may know, Vortex is currently being deprecated in favor of the new Nexus App. The Nexus App team are aware of this requirement and will hopefully ensure to detect BSA conflicts.

On Vortex's end - we do have a backlog item for this piece of functionality but we're worried it would slow down our conflict detection system even further. Will close this ticket as there is little chance we would get to look at this piece of functionality before the Nexus App goes live.
