### ISSUE TITLE
The file  "<filename unknown>" is currently bot accesable

### ISSUE THREAD

**Issue by TomeKATANA** [Nexus-Mods/Vortex#15005]
I don't know what happened, But when ever I open vortex an error pops up that says "Drive unavaliable (433)" in the top left corner and then this as the body of it: The file "<filename unknown>" is currently not accessible. If this is a network drive, please make sure it's connected. Otherwise make sure a drive lettere hasn't changed and if neccessary, update the path within Vortex.  You can try continuing at your own risk. Possible error causes: 1. "<filenameunknown>" is a removable possibly network drive which has been disconnected. 2. An external application has interferred with file operations (Anti-Virus, Disk Management Utility, Virus)"

I am then unable to click on the cancel, ignor, nor retry buttons and the only way I can close vortex is from task manager

**To Reproduce**
I don't know how to reproduce it, but its always happening if I open vortex

**Expected behavior**
The expected behaivor is for vortex to open without that error and let me manage mods for games

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/153688677/f0f43d1c-5f03-43be-811d-02d63f4da14b)

**Platform (please complete the following information):**
windows 10
Vortex 1.9,19

**Comment by IDCs** [comment]
Hi @TomeKATANA, thanks for raising the ticket - what sort of environment do you have in terms of both physical and virtual/network drives?

Can you please install the beta version of Vortex and let us know if the error goes away?
https://github.com/Nexus-Mods/Vortex/releases/download/v1.9.11/vortex-setup-1.9.11.exe

Just make sure that Vortex is closed and install the beta before trying to run Vortex again.

**Comment by TomeKATANA** [comment]
Unfortuantly it did not seem to work.

**Comment by IDCs** [comment]
What sort of environment do you have in terms of both physical and virtual/network drives?

**Comment by TomeKATANA** [comment]
I've got 2 internal HDD's an external HDD, and 2 internal SSD's? I don't... really know what a network drive is?

**Comment by IDCs** [comment]
No worries - are you able to disconnect the external HDD and see if that makes a difference?

**Comment by IDCs** [comment]
Closing due to lack of feedback

**Comment by Thewizard3** [comment]
> Unfortuantly it did not seem to work.

I new to modding games and I had this issue trying to mod Skyrim but what worked for me is checking the storage where all my save files are to see if they are corrupted and that wasn’t the case and to purge your mod list helps get all your files back I know this is from 2023 but for the future people reading this here’s a situation that might help
