### ISSUE TITLE
Verify Extension: [734] Drug Dealer Simulator

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15038]
## Extension Information

_Get all relevant metadata and links from nexusmods.com_ ​

|  |  |
|--|--|
| **Extension Name** |  Drug Dealer Simulator Support |
| **Extension Mod ID** | 734   |
| **Extension URL** | [Drug Dealer Simulator Support](https://www.nexusmods.com/site/mods/734) |
| **Game Name** | Drug Dealer Simulator |
| **Game Domain** | drugdealersimulator  |
| **Game URL** | [Drug Dealer Simulator](https://www.nexusmods.com/drugdealersimulator) |

Check to see if there is an existing extension for this game

|  |  |
|--|--|
| **Existing Extension URL** |  |

## Verification checklist

- [ ] If there is an existing extension for this game, is this functionally better?
- [ ] Is the extension named correctly?
- [ ] Is it packaged correctly?
- [ ] Is artwork correct?
- [ ] Is the changelog accurate?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

## Adding extension to manifest

​ When complete, the verified extension needs adding to our manifest. This is completed using the [Actions at GitHub](https://github.com/Nexus-Mods/vortex-add-extension/actions), there is one action for each extension type. ​

- [ ] GitHub Action run
- [ ] Manifest file manually checked for errors
- [ ] Contacted author
- [ ] Asked Community to enable Vortex for the game
- [ ] Discord [#vortex-announcements](https://discordapp.com/channels/215154001799413770/1141024162182336612) updated. [Templates are on Confluence](https://nexusmods.atlassian.net/wiki/spaces/VORTEX/pages/2906750977/Announcements+Templates) ​

**Comment by IDCs** [comment]
🥦

**Comment by IDCs** [comment]
Not packaged correctly

**Comment by IDCs** [comment]
closed as stale
