### ISSUE TITLE
Installation corrupted: missing file: FomodInstaller.Interface.GeneratedMSBuildEditorConfig.editorconfig

### ISSUE THREAD

**Issue by ChrissW-R1** [Nexus-Mods/Vortex#15120]
**Describe the bug**
On start I get the message
> Your Vortex instillation has been corrupted. This could be the result of a virus or manual manipulation. Vortex might still appear to work (partially) but we suggest you reinstall it.

**To Reproduce**
1. Install Vortex
2. Start Vortex

**Expected behavior**
Vortex starts without an error.

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/1086210/11fe8765-fbf4-4bfd-9547-6b09829d0a78)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.9.13

**Additional context**
In the logs I found a check of a file, which is missing: C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\fomod-installer\FomodInstaller.Interface\Build\obj\Release\FomodInstaller.Interface\FomodInstaller.Interface.GeneratedMSBuildEditorConfig.editorconfig
```
Tue, 09 Jan 2024 18:48:45 GMT - info: --------------------------
Tue, 09 Jan 2024 18:48:45 GMT - info: Vortex Version 1.9.13
Tue, 09 Jan 2024 18:48:45 GMT - info: Parameters C:\Program Files\Black Tree Gaming Ltd\Vortex\Vortex.exe
Tue, 09 Jan 2024 18:48:45 GMT - info: start file validation
Tue, 09 Jan 2024 18:48:45 GMT - info: file missing fileName=resources\app.asar.unpacked\node_modules\fomod-installer\FomodInstaller.Interface\Build\obj\Release\FomodInstaller.Interface\FomodInstaller.Interface.GeneratedMSBuildEditorConfig.editorconfig, error=ENOENT: no such file or directory, open 'C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\fomod-installer\FomodInstaller.Interface\Build\obj\Release\FomodInstaller.Interface\FomodInstaller.Interface.GeneratedMSBuildEditorConfig.editorconfig'
Tue, 09 Jan 2024 18:48:46 GMT - info: done file validation
Tue, 09 Jan 2024 18:48:46 GMT - info: Files were manipulated missing=[resources\app.asar.unpacked\node_modules\fomod-installer\FomodInstaller.Interface\Build\obj\Release\FomodInstaller.Interface\FomodInstaller.Interface.GeneratedMSBuildEditorConfig.editorconfig], changed=[]
Tue, 09 Jan 2024 18:48:49 GMT - info: user ignored error, disabling reporting
Tue, 09 Jan 2024 18:48:49 GMT - debug: showing splash screen
```

**Comment by ChrissW-R1** [comment]
Can be fixed by copy the file in the attached ZIP file to:
`C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\fomod-installer\FomodInstaller.Interface\Build\obj\Release\FomodInstaller.Interface\`

[FomodInstaller.Interface.GeneratedMSBuildEditorConfig.editorconfig.zip](https://github.com/Nexus-Mods/Vortex/files/13878026/FomodInstaller.Interface.GeneratedMSBuildEditorConfig.editorconfig.zip)

**Comment by IDCs** [comment]
Hi there!

Thank you for your report - the installer itself contains all the files which are needed for Vortex to run correctly.

Any corruption related errors highlight an issue with the installation on your system or your system itself.
