### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by td5038** [Nexus-Mods/Vortex#15147]
**Is your feature request related to a problem? Please describe.**
There is no way to build for Linux. I'm very much frustrated as I want to download a very large modpack for Stardew Valley

**Describe the solution you'd like**
I want a way to build this thing in a way that it can run on Linux, like, I don't know, **MOST MODERN DOTNET APPS**.

**Describe alternatives you've considered**
I don't know, but could you just build it as a modern .NET app?

**Additional context**
I tried to build this in a Linux container (I don't know if Clang would work as a native compiler), but it failed.

**Comment by IDCs** [comment]
Hi there!

As you may be aware, Vortex is being deprecated in favour of the Nexus Mods App, which is indeed built using .NET.

Closing this as it's currently out of scope for Vortex to add Linux support.

**Comment by DraconicNEO** [comment]
Maybe this should be re-opened considering the Nexus mods app was itself canned in favor of just supporting Vortex on Linux (SteamOS).
