### ISSUE TITLE
ERROR: logged in Browser and successfully authourized, but error on the app, same with #14584

### ISSUE THREAD

**Issue by DeciusMorta** [Nexus-Mods/Vortex#15153]
**Describe the bug**
Already logged in Browser and successfully authourized, but error on the app, same with #14584, Vortex version : 1.9.12
After Clicking authourize on browser, it shows sucessfully authourized, but on the app it opens a plate that requires you to cilck "log in", click that and it opens browser again, click authourize again-success, on the app it shows log in failed and failed to get access key

**Platform (please complete the following information):**
 - OS:  Windows 10
 - Vortex Version 1.9.12

**Additional context**
Failed to get access key
Failed to parse failure response: "<!DOCTYPE html><html lang="en-US"><head><title>Jus"
    at IncomingMessage.<anonymous> (D:\Download\Vortex\resources\app.asar\renderer.js:6857:101)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by DeciusMorta** [comment]
![image](https://github.com/Nexus-Mods/Vortex/assets/130985383/6296cce4-3a3f-4011-adcc-85527cdd7473)
![image](https://github.com/Nexus-Mods/Vortex/assets/130985383/2e3114ef-131f-4728-98ac-ad5da381f3c3)
![image](https://github.com/Nexus-Mods/Vortex/assets/130985383/6a10d14d-23c8-499b-8a2b-3d9a6cfc2ba3)
![image](https://github.com/Nexus-Mods/Vortex/assets/130985383/8bcb3360-a454-4c12-a655-8ca997e269a3)
![image](https://github.com/Nexus-Mods/Vortex/assets/130985383/0151736e-6540-4a51-aec6-4859d3ffba5d)

**Comment by DeciusMorta** [comment]
tried with token. it shows
![image](https://github.com/Nexus-Mods/Vortex/assets/130985383/46d054eb-9451-4bde-8a33-06b65c1fbfc3)

**Comment by IDCs** [comment]
Hi there!

Any login issues are generally temporary and are caused by backend issues. In your case it looks like a cloudflare response has been received instead of an API response. Which is potentially due to the DDOS attack we're experiencing.

This will clear up within the next couple of hours.

**Comment by DeciusMorta** [comment]
> Hi there!
> 
> Any login issues are generally temporary and are caused by backend issues. In your case it looks like a cloudflare response has been received instead of an API response. Which is potentially due to the DDOS attack we're experiencing.
> 
> This will clear up within the next couple of hours.

Oh~ ok, thx :D
