### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by ljy87263621** [Nexus-Mods/Vortex#15189]
I can't log in.

When I click the "Authorize" button on the website it works nothing while I input the token it still doesn't work at all.

 - OS: [Windows11]
 - Vortex Version [1.9.13]

I fallback to version [1.3.21] it works. But I noticed that the link it redirects to isn't the same as the link version [1.9.13] redirects to.

**Comment by IDCs** [comment]
Hi there!

1.3.21 is a major downgrade from 1.9.13 - not even sure if the SSO token used in 1.3.21 is still active on the website! Please never do that again as it can majorly mess up your application state. Update back to 1.9.13 or the latest 1.10.6 beta and try again - login issues are generally temporary.

Can you confirm whether you're still having issues even after returning to a new version?
