### ISSUE TITLE
Support updating prerelease mod versions

### ISSUE THREAD

**Issue by madtisa** [Nexus-Mods/Vortex#15213]
**Is your feature request related to a problem? Please describe.**
Let's say we have mod with current version 1.0.0-pre1 and newest 1.0.0-pre2. Vortex won't see that the mod need an update, since both versions will be coerced, dropping prerelease part, and become equal.

**Describe the solution you'd like**
Solution: #15212 

**Describe alternatives you've considered**
Alternatives has been suggested here: #15044
For now, as a workaround I don't use prerelease versions when releasing a mod

**Comment by IDCs** [comment]
Merged in https://github.com/Nexus-Mods/Vortex/pull/15281

Should be available in our next minor release 1.11.X
