### ISSUE TITLE
Plugins tab completely missing from Vortex, STILL. 

### ISSUE THREAD

**Issue by jsauerland** [Nexus-Mods/Vortex#15289]
**Describe the bug**

My vortex installation has no plugins tab. Checked under Extensions, and Gamebryo Plugin Management is installed. I disabled it, then re-enabled it, restarted PC. Nothing. Literally no plugins tab still. Re-installed vortex as well, still no fix. 

My 'Diagnostic files' has no errors or warns related to this. 

Also installed Windows C++ redistributable for my system, which did not fix the issue. 

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/Nexus-Mods/Vortex/assets/32148757/717a1233-e653-4090-9db2-3196006a7374)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - Vortex Version [e.g. 0.16.12] Vortex version 1.9.12. 

**Additional context**

**Comment by IDCs** [comment]
@jsauerland which gamebryo game are you managing?

I'm afraid there's not much I can do without seeing your `vortex.log` files which are located in `%appdata%/vortex`

**Comment by IDCs** [comment]
Closing due to lack of response.
