### ISSUE TITLE
Starfield plugin management not working since today

### ISSUE THREAD

**Issue by smallbutfine** [Nexus-Mods/Vortex#15307]
**Describe the bug**
Starfield plugin management is not working after today's Extension update.
Only Starfields own .esm showed up. Even after trying to sync and rebuilding/reset plugins.txt.
I tried to deactivate plugin management, and this worked.
I tried to activate plugin management again, and it was greyed out.
Plugin management non-functional now.

**To Reproduce**
1. Go to '...' Load Order.
2. Click on '....' Reset, then Sync'.
3. Deactivate Vortex Plugin Management in Settings
4. Activate Vortex plugin management greyed out.
5. No error message.

**Expected behavior**
Vortex plugin management should be able to re-activate. If activated, it should sync, and find the deployed and existing ESMs from active mods in the Data folder.

**Screenshots**
<img width="960" alt="2024-03-10 19_00_05-Vortex" src="https://github.com/Nexus-Mods/Vortex/assets/80461402/70009f91-da2a-47d9-bd7a-9dfdb0687a97">

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.9.12

**Additional context**

**Comment by smallbutfine** [comment]
Addendum:
Installing Vortex, same Version, standard settings in installer, preserved personal settings but "magically" made Plugin Management on the Load Order page usable again, and plugins are now actually synced again.
Still, unexpected behaviour.

**Comment by IDCs** [comment]
Hi there - thanks for your report!

That's actually not a bug, if you hover on top of the greyed-out toggle button it will tell you that Starfield's plugin management can only be activated via the load order page itself. I agree it's a bit of weird UX, but it's done for the sake of protecting against users continuously toggling this setting on and off which can have unexpected results.

P.S. the Starfield extension hasn't been updated in the last 2 months 😬 I'm guessing you haven't used Vortex in a while and have just received the update.
