### ISSUE TITLE
Ini-Path for Enderal SE on GOG

### ISSUE THREAD

**Issue by HJHughJanus** [Nexus-Mods/Vortex#15369]
You currently cannot use Vortex with the GOG version of Enderal SE, since the ini files are not found (ini path differs from the steam version one).

Please add those necessary lines of code here: https://github.com/Nexus-Mods/extension-plugin-management/blob/18b8f9365227d592a71fbb5a45314f1d40271db4/src/util/gameSupport.ts#L167

Ini Path: "%MyDocuments%/MyGames/Enderal Special Edition GOG"
Saves Path: "%MyDocuments%/MyGames/Enderal Special Edition GOG/Saves"
Plugin.txt Path: "%AppData%\Local\Enderal Special Edition GOG"

**Comment by insomnious** [comment]
Will be part of 1.12
