### ISSUE TITLE
Collections - Batch actions caused UI freezing or crashes

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#15400]
**Describe the bug**
When editing a collection with over 1,000 mods, using the batch action to update all mods in collection edit view can cause a long hang of the UI or sometimes crash the app. Reported in the Nexus Mods Next Discord. 

**To Reproduce**
1. Have a collection with over 1,000 mods in edit mod.
2. Select all
3. Change install type to "Exact only" using the batch options

**Expected behavior**
The app does not crash or hang for a long time.

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by IDCs** [comment]
Actions applied to that many mods cannot be expected to run seamlessly. Either way 1.12.x has multiple optimizations to both collections and the installmanager which should hopefully ensure this process is as painless as possible.

Crashes were more likely to be cause by the flawed elevation scripts which have been resolved as part of 1.12.x as well.

Going to close this for the time being, but will keep an eye out for performance related issues/crashes as part of the beta release.
