### ISSUE TITLE
Remove libxmljs dependency

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15439]
# Chore

The `libxmljs` library is somewhat unmaintained, and has been causing us issues with our build system for years as it keeps dropping assets.

Currently we only use this library in the Bannerlord extension which we aim to replace/stub in the future.

We should remove this dependency so that it no longer blocks our build process.

## Outline
(Describe the task).

## Supporting Information
(Include any supporting screenshots etc to support the above).

## Checklist

- [ ] Include a description of the task.
- [ ] Include relevant department labels.
- [ ] Include any supporting information.

**Comment by Thaodan** [comment]
How was libxmljs replaced? I'm trying to understand the change as libxmljs is causing issues for me while packaging Vector as shouldn't bundle native dependencies.

**Comment by insomnious** [comment]
Deprecated in 1.13.0
