### ISSUE TITLE
Verify Extension: [838] Vermintide 2

### ISSUE THREAD

**Issue by IDCs** [Nexus-Mods/Vortex#15470]
# Verify Extension

Use this template to verify game extensions for Vortex ​

## Extension Information

_Get all relevant metadata and links from nexusmods.com_ ​

|  |  |
|--|--|
| **Extension Name** |  Warhammer Vermintide 2 Vortex Extension |
| **Extension Mod ID** | 838 |
| **Extension URL** | [Warhammer Vermintide 2](https://www.nexusmods.com/site/mods/838)  |
| **Game Name** | Warhammer Vermintide 2 |
| **Game Domain** | vermintide2  |
| **Game URL** | https://www.nexusmods.com/vermintide2 |

Check to see if there is an existing extension for this game

|  |  |
|--|--|
| **Existing Extension URL** |  |

## Checked with

|  |  |
|--|--|
| **Extension Version** |  |
| **Vortex Version** |  |

## Instructions

https://nexusmods.atlassian.net/wiki/spaces/VORTEX/pages/2892529680/Extension+Verification+Pipeline#Games ​

## Verification checklist

- [ ] If there is an existing extension for this game, is this functionally better?
- [x] Is the extension named correctly?
- [x] Is it packaged correctly?
- [x] Is artwork correct?
- [x] Is the changelog accurate?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

## Adding extension to manifest

​ When complete, the verified extension needs adding to our manifest. This is completed using the [Actions at GitHub](https://github.com/Nexus-Mods/vortex-add-extension/actions), there is one action for each extension type. ​

- [ ] GitHub Action run
- [ ] Manifest file manually checked for errors
- [ ] Contacted author
- [ ] Asked Community to enable Vortex for the game
- [ ] Discord [#vortex-announcements](https://discordapp.com/channels/215154001799413770/1141024162182336612) updated. [Templates are on Confluence](https://nexusmods.atlassian.net/wiki/spaces/VORTEX/pages/2906750977/Announcements+Templates) ​

**Comment by IDCs** [comment]
The extension is currently blocked due to:

* Mods on the site are mostly shader presets which cannot be used without a 3rd party application https://reshade.me/ the extension does not inform the users of this requirement.
* The presets probably need to be deployed to a specific folder of reshade; there are no modTypes that support this.
* As far as I can tell none of the mods will function.

To unblock:

* The extension author should at the very least raise a notification informing users of the reshade requirement
* A modType needs to be added to ensure that the shader presets are deployed to the expected reshade folder

**Comment by ChemGuy1611** [comment]
Acknowledged. Working on these updates.

**Comment by ChemGuy1611** [comment]
I have added a notification for Reshade installation to the extension.

I also added 2 mod types, one for each of the binaries folders (this is where engine injectors and reshades should go). 

On the topic of Reshade presets, these are .ini files that can technically be placed anywhere, but the game executable location (which is where this extension installs mods with the mod types above) is ideal. Additionally, if a mod does actually contain reshade shaders, these are almost always packed by the mod authors so that the mod can be deployed to the game executable's folder with the correct directory structure. Therefore, no special mods types are necessary to handle those types of mod installs.

Thank you for your time and effort on adding this extension to Vortex!

**Comment by insomnious** [comment]
@ChemGuy1611 thanks for resubmitting but I can't test as there is a fixed path to your Steam folder in your mod type section at the top of the index.js

**Comment by ChemGuy1611** [comment]
> @ChemGuy1611 thanks for resubmitting but I can't test as there is a fixed path to your Steam folder in your mod type section at the top of the index.js

Thanks for letting me know. Wasn't sure if that pathPattern function was going to work or not. I will update that path with a variable and add to the setup function to define it after game discovery.

**Comment by ChemGuy1611** [comment]
> @ChemGuy1611 thanks for resubmitting but I can't test as there is a fixed path to your Steam folder in your mod type section at the top of the index.js

Ok, I got this working now. New version uploaded to Nexus Mods. I was misunderstanding what the pathPattern function (template function from string-template library) does. I understand it now. I will update the other extensions I have uploaded that specify mod types and correct them as well.
