### ISSUE TITLE
Verify Extension: [839] The Last of Us Part I Vortex Extension

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15488]
# Verify Extension: The Last of Us Part I Vortex Extension

Use this template to verify game extensions for Vortex ​

## Extension Information

_Get all relevant metadata and links from nexusmods.com_ ​

|  |  |
|--|--|
| **Extension Name** | The Last of Us Part I Vortex Extension |
| **Extension Mod ID** | 839 |
| **Extension URL** | https://www.nexusmods.com/site/mods/839 |
| **Game Name** | The Last of Us Part I |
| **Game Domain** | thelastofuspart1 |
| **Game URL** | https://www.nexusmods.com/thelastofuspart1 |

Check to see if there is an existing extension for this game

|  |  |
|--|--|
| **Existing Extension URL** |  |

## Checked with

|  |  |
|--|--|
| **Extension Version** |  |
| **Vortex Version** |  |

## Instructions

TBC

## Verification checklist

- [ ] If there is an existing extension for this game, is this functionally better?
- [ ] Is the extension named correctly?
- [ ] Is it packaged correctly?
- [ ] Is artwork correct?
- [ ] Is the changelog accurate?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

## Adding extension to manifest

​ When complete, the verified extension needs adding to our manifest.

- [ ] GitHub Action run
- [ ] Manifest file manually checked for errors
- [ ] Contacted author
- [ ] Asked Community to enable Vortex for the game
- [ ] Discord [#vortex-announcements](https://discordapp.com/channels/215154001799413770/1141024162182336612) updated.

**Comment by IDCs** [comment]
Blocking as the extension is not using the correct domain name when registering the game object.

**Comment by ChemGuy1611** [comment]
> Blocking as the extension is not using the correct domain name when registering the game object.

This has been fixed. Just had to change the "i" to a "1" in the game id and remove the  "tm".
