### ISSUE TITLE
AWS::S3::Errors::NotFound

### ISSUE THREAD

**Issue by ShadowPandah** [Nexus-Mods/Vortex#15491]
keep getting issue AWS::S3::Errors::NotFound when trying to upload my collection...

**Comment by ShadowPandah** [comment]
seems file size for collections has an upper limit?

**Comment by IDCs** [comment]
Hi there - can't help pinpoint the reason behind the error without your vortex.log files which can be found in `%appdata%/vortex`

But yes I suppose there is a maximum size for a collection, I think it was 3GB at one point. @Pickysaurus any idea what the maximum collection size upload is?

**Comment by ShadowPandah** [comment]
That would make sense if that's the case; my bundled files for my Skyrim SE collection definitely exceed 3GB Between BodySlide, Synthesis, xLodGen, TexGen, and DynDOLOD outputs. 

I was able to push the collection successfully to Nexus Mods without those bundled; I just put the files previously mentioned onto Nexus Mods within an unlisted mod with DP turned off; and the collection is installing them from there now. 

I can attempt to re-upload the collection with the previously mentioned files bundled again, and then get my vortex.log file for you if you would like to see it to confirm that this is the case of what's occurring; just let me know.

**Comment by Pickysaurus** [comment]
> Hi there - can't help pinpoint the reason behind the error without your vortex.log files which can be found in `%appdata%/vortex`
> 
> But yes I suppose there is a maximum size for a collection, I think it was 3GB at one point. @Pickysaurus any idea what the maximum collection size upload is?

There isn't a maximum, there are collections available with tens of gigabytes of bundled data.

**Comment by IDCs** [comment]
Closing as the collection was uploaded in the end - probably a temporary server hiccup.
