### ISSUE TITLE
Verify Extension: [845] Helldivers 2 Vortex Extension

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15504]
# Verify Extension: Helldivers 2 Vortex Extension

Use this template to verify game extensions for Vortex ​

## Extension Information

_Get all relevant metadata and links from nexusmods.com_ ​

|  |  |
|--|--|
| **Extension Name** | Helldivers 2 Vortex Extension |
| **Extension Mod ID** | 845 |
| **Extension URL** | https://www.nexusmods.com/site/mods/845 |
| **Game Name** | Helldivers 2 |
| **Game Domain** | helldivers2 |
| **Game URL** | https://www.nexusmods.com/helldivers2 |

Check to see if there is an existing extension for this game

|  |  |
|--|--|
| **Existing Extension URL** |  |

## Verification checklist

- [ ] If there is an existing extension for this game, is this functionally better?
- [x] Is the extension named correctly?
- [x] Is it packaged correctly?
- [x] Is artwork correct?
- [x] Is the changelog accurate?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

## Adding extension to manifest

​ When complete, the verified extension needs adding to our manifest.

- [ ] GitHub Action run
- [ ] Manifest file manually checked for errors
- [ ] Contacted author
- [ ] Asked Community to enable Vortex for the game
- [ ] Discord [#vortex-announcements](https://discordapp.com/channels/215154001799413770/1141024162182336612) updated.

**Comment by IDCs** [comment]
Although the extension defines a couple of modTypes to support the game's different modding patterns; it does not include modType tests to correctly identify these mods. A custom installer will also be needed to cater for some mod packaging patterns.

To unblock:

* Add appropriate modType tests for each pattern (e.g. if it contains a file with the `.dl_bin` extension - that should be sufficient to assign the `helldivers2-data` modType)
* The mods are packaged hectically in some cases and will require a custom installer to be written to install those correctly.

**Comment by ChemGuy1611** [comment]
Could you help me out with how to code to automatically assign modType in mod installers? I understand how to get the installer to see the .dl_bin to check if the mod is supported for the installer, but I am not certain how to assign the modType to it at that point.

**Comment by IDCs** [comment]
Certainly - you can create an additional instruction in the installer like so:
`const setModTypeInstruction = { type: 'setmodtype', value: MODTYPE_ID }`

Then just add the new instructions to the instructions array before returning the promise.
`instructions.push(setModTypeInstruction);`

**Comment by IDCs** [comment]
Hi again - I didn't get to test your extension yet as I can already see that the installer hasn't been tested.


```
function installContent(files, gameSpec) {
  <...>
  MODTYPE_ID = "helldivers2-data"; // You're missing the variable declaration!
  const setModTypeInstruction = { type: 'setmodtype', value: MODTYPE_ID };
  <...>
  instructions.push(setModTypeInstruction);
  return Promise.resolve({ instructions });
}

// declare your variable before using it:
// const/var/let MODTYPE_ID
```

**Comment by ChemGuy1611** [comment]
Fixed and uploaded to Nexus. Just a note that I did test the code and it did work. But yes, I did add the proper declaration.
