### ISSUE TITLE
When page is loaded I receive "Type 'JObject' is not defined", runs in Visual Studio without issue.

### ISSUE THREAD

**Issue by carrzkiss** [Nexus-Mods/Vortex#15503]
**Describe the bug**
The website runs in Visual Studio. When published to the server and the page loaded in a web browser, 
I receive `Type 'JObject' is not defined`
Line 46:
```
 Compiler Error Message: BC30002: Type 'JObject' is not defined.
 Source Error:
 Line 44:             Response.Write("Server is up | ")
 Line 45:             json = New System.Net.WebClient().DownloadString("http://192.168.5.10:8007/101/metadata")
 Line 46:             Dim parsejson As JObject = JObject.Parse(json)
 Line 47:             thefilename = parsejson.SelectToken("now_playing.filename").ToString()
```

**To Reproduce**
Load the website outside of Visual Studio on a Windows 2016 Core Server running IIS 10.
I am using the code from here.
[Parse JSON with VB.NET](https://www.narendradwivedi.org/2022/04/parse-json-vb-net.html)

```
Imports System.Net
Imports Newtonsoft.Json.Linq

Public Class Form1
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12
        Dim json As String = New System.Net.WebClient().DownloadString("https://reqres.in/api/products/3")
        Dim parsejson As JObject = JObject.Parse(json)
        Dim thename = parsejson.SelectToken("data.name").ToString()
        txt1.Text = "Name Is " + thename
    End Sub
End Class
```

**Expected behavior**
Fetch data from a data feed.

**Screenshots**

**Platform (please complete the following information):**
Windows 1016 Server
IIS 10

**Additional context**
Newtonsoft.Json (Version # 13.0.3.27908)

I also just copied the files over and over-wrote the published files to see if there was something missing, and still receive the error.

**Comment by IDCs** [comment]
I'm assuming you created this issue on our issue tracker by mistake.
