### ISSUE TITLE
Verify Extension: [847] Battlefield 1 Vortex Extension

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15510]
# Verify Extension: Battlefield 1 Vortex Extension

Use this template to verify game extensions for Vortex ​

## Extension Information

_Get all relevant metadata and links from nexusmods.com_ ​

|  |  |
|--|--|
| **Extension Name** | Battlefield 1 Vortex Extension |
| **Extension Mod ID** | 847 |
| **Extension URL** | https://www.nexusmods.com/site/mods/847 |
| **Game Name** | Battlefielld 1 |
| **Game Domain** | battlefield1 |
| **Game URL** | https://www.nexusmods.com/battlefield1 |

Check to see if there is an existing extension for this game

|  |  |
|--|--|
| **Existing Extension URL** |  |

## Checked with

|  |  |
|--|--|
| **Extension Version** |  |
| **Vortex Version** |  |

## Instructions

TBC

## Verification checklist

- [ ] If there is an existing extension for this game, is this functionally better?
- [ ] Is the extension named correctly?
- [ ] Is it packaged correctly?
- [ ] Is artwork correct?
- [ ] Is the changelog accurate?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

## Adding extension to manifest

​ When complete, the verified extension needs adding to our manifest.

- [ ] GitHub Action run
- [ ] Manifest file manually checked for errors
- [ ] Contacted author
- [ ] Asked Community to enable Vortex for the game
- [ ] Discord [#vortex-announcements](https://discordapp.com/channels/215154001799413770/1141024162182336612) updated.

**Comment by IDCs** [comment]
The extension is not in a working state.

To unblock:

* The image is cropped at the bottom. Please use a 640 x 360 px image for the gameart.
![Image](https://github.com/Nexus-Mods/Vortex/assets/8960252/2ec6e1e1-039f-4f05-bb70-119e9534bdf9)

* The findGame function is set to execute before any of the game store extensions are loaded and therefore Vortex is unable to load your extension.
```
// This:
function makeFindGame(api, gameSpec) {
    return util.GameStoreHelper.findByAppId(gameSpec.discovery.ids)
      .then((game) => game.gamePath);
}

// Should be this:
function makeFindGame(api, gameSpec) {
    return () => util.GameStoreHelper.findByAppId(gameSpec.discovery.ids)
      .then((game) => game.gamePath);
}
```

**Comment by ChemGuy1611** [comment]
Thanks for pointing that out. Just a heads up that I grabbed that code block from the github documentation, so that should probably be corrected over there.

I did not have any issue loading this extension on my machine., but I have added the arrow function as shown above.

**Comment by ChemGuy1611** [comment]
> @ChemGuy1611 can you point us towards that documentation?
> 
> The up to date documentation did not take game wizard extension code into consideration.

https://github.com/Nexus-Mods/vortex-api/issues/31

I the "Game Detection" section, you'll see the findGame functions do not have the arrow function there. The Add Game Wizard does in fact use the arrow function correctly, that is why only this extension has this problem, as I did not change this function for the other extensions I've uploaded.
