### ISSUE TITLE
Failed to update masterlist

### ISSUE THREAD

**Issue by Enesore** [Nexus-Mods/Vortex#15527]
**Description**
Every time I launch Vortex, I get a connection error prompting me to delete **masterlist.yaml**. Doing so does not fix the issue, as Vortex now tries to access a file that doesn't exist. Running Vortex as admin also does not fix this. In addition, I occasionally get a "Checking for update failed" error, but it's not consistently reproducible.

**To Reproduce**
1. Launch Vortex.
2. Wait for the error message to appear.
3. Close Vortex.
4. Delete **masterlist.yaml**.
5. Launch Vortex again.

**Expected behavior**
Vortex correctly updates the masterlist and regenerates it if it's missing.

**Platform:**
 - OS: Windows 11
 - Vortex Version: 1.10.8/1.11.0.

![update-check](https://github.com/Nexus-Mods/Vortex/assets/68475470/05b7770f-da5d-4d2c-a0d8-c039e5f1b786)
![masterlist-missing](https://github.com/Nexus-Mods/Vortex/assets/68475470/547f7b81-e768-492a-bbc4-a7a5afe3fd98)
![masterlist-update](https://github.com/Nexus-Mods/Vortex/assets/68475470/4797e24a-67d0-425e-8bef-0d84d8a8b2f2)
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/14970241/vortex.log)

**Comment by IDCs** [comment]
Hi there - Your log file suggests that your machine is having trouble connecting to github api servers. Vortex can't regenerate the file unless the connection can be established.

If you're tech savvy - you could install git; and browse to the location of the masterlist and try to run `git pull` alternatively you'll have to download the file manually from LOOT's repos.
