### ISSUE TITLE
Fallout 4 Epic release

### ISSUE THREAD

**Issue by IDCs** [Nexus-Mods/Vortex#15580]
Bethesda is releasing Fallout 4 on Epic Games store as part of their "new/next-gen" update; we need to make sure that we are able to support the new release.
* Ensure discovery is functioning
* Ensure all gamebryo extensions know where to look for their respective files. (INI's, savegames, etc)
* Do we need to add both base Fallout 4 and Fallout 4: GOTY edition
* Released on Thursday 25th

**Comment by TByte007** [comment]
Discovery do not work, Searches the save games in the wrong place and probably other things.

**Comment by IDCs** [comment]
https://github.com/Nexus-Mods/extension-archive-invalidation/pull/4
https://github.com/Nexus-Mods/vortex-games/pull/112
https://github.com/Nexus-Mods/extension-local-gamesettings/pull/6
https://github.com/Nexus-Mods/extension-open-directory/pull/5
https://github.com/Nexus-Mods/extension-plugin-management/pull/24
https://github.com/Nexus-Mods/extension-gamebryo-savegames/pull/10
https://github.com/Nexus-Mods/extension-gamebryo-testsettings/pull/3
https://github.com/Nexus-Mods/Vortex/pull/15611

**Comment by insomnious** [comment]
all merged into master and into v1.11.1-beta. Building new beta for release next week
