### ISSUE TITLE
sections and drag and drop mods

### ISSUE THREAD

**Issue by asamat1k** [Nexus-Mods/Vortex#15619]
creating sections and dragging and dropping mods as in mo2 
It would be really cool if they added the ability to do that.

**Comment by IDCs** [comment]
Hi there - thanks for your suggestion! this feature is currently tracked in our feedback system https://feedback.nexusmods.com/posts/15/drag-and-drop-load-order-for-bethesda-games (and probably in several separate tickets on this repo)

I hope you don't mind if I close this issue as we will review what can be done in future releases of Vortex.
