### ISSUE TITLE
Review: Manor Lords

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15636]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/868/?tab=description

### Game URL

https://www.nexusmods.com/manorlords

### Existing Extension URL

NONE

### New features

No pre-existing extension.

Integrates Unreal Engine Mod Installer extension

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [x] Run the GitHub Actions to add to manifest
- [x] Contact author
- [x] Ask Community to enable the Vortex button for the game
- [x] Update the #vortex-announcements channel on Discord

**Comment by insomnious** [comment]
[Manor Lords Vortex Extension-868-0-1-2-1714867239.zip](https://github.com/Nexus-Mods/Vortex/files/15249109/Manor.Lords.Vortex.Extension-868-0-1-2-1714867239.zip)

**Comment by IDCs** [comment]
Hey @ChemGuy1611 

Apologies for the late review - busy, busy, busy.

Had a look at your extension and it's pretty solid but there's one potential issue I'd like us to avoid, specifically when trying to discover the XBOX or EPIC version of the game.

I can see you have placeholders in place which is fine
![Image](https://github.com/Nexus-Mods/Vortex/assets/8960252/c9412be2-724f-430a-842f-a93fd16de1e1)

But you're setting those ids for automatic discovery as seen below:

![Image](https://github.com/Nexus-Mods/Vortex/assets/8960252/8dab5e58-e52e-4260-9417-720b205ed02f)

That will actually kick off the GameStoreHelper and waste a few cycles needlessly for both the xbox and epic game stores. Please remove those ids from the game spec discovery object for now and re-add them once the placeholders have been filled out.

Thanks again for all of your contributions :)

**Comment by insomnious** [comment]
Your ok to upload to the site, that's fine. Keeps it all in the same place then and if all is well, it's ready to go and we can just un-moderate it.

**Comment by IDCs** [comment]
Thanks for your contribution - your extension has been added to the Vortex manifest.
