### ISSUE TITLE
vortex can not find my documents

### ISSUE THREAD

**Issue by Lazarathcain** [Nexus-Mods/Vortex#15638]
**Describe the bug**
I installed Vortex last night and set up mods for Fallout 4. The game and mods were working. When I restarted the computer Vortex stated it could not find My Documents all of a sudden. 
![Screenshot 2024-05-04 143440](https://github.com/Nexus-Mods/Vortex/assets/125199598/c3281289-7cc5-4601-ae97-63a4fd820be2)
![Screenshot 2024-05-04 143338](https://github.com/Nexus-Mods/Vortex/assets/125199598/0ba57219-f981-4369-b9c4-cfdfabee533e)

I read through https://wiki.nexusmods.com/index.php/Misconfigured_Documents_Folder 

![Screenshot 2024-05-04 144354](https://github.com/Nexus-Mods/Vortex/assets/125199598/c461c714-4c34-484f-ac39-499b88840ff0)
![Screenshot 2024-05-04 144411](https://github.com/Nexus-Mods/Vortex/assets/125199598/0298b196-b35a-439c-a375-f232b4b58877)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version [1.10.8]

**Additional context**

I recently did my best to remove onedrive from my computer but parts of it seem to keep popping up in my system when i deleted it from the programs and registry

**Comment by IDCs** [comment]
Hi there - lets verify what path `%USERPROFILE%/Documents` resolves to on your account.

Press Windows key + R and type `%USERPROFILE%/Documents` in the dialog that pops up.

<img width="306" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/8960252/15195497-788b-4c13-a8b3-734d583d891f">

If Windows is unable to resolve that path correctly - there's no way Vortex would be able to. You'll probably have to repair your Windows installation.

**Comment by IDCs** [comment]
Closing as this is a user environment issue - not something we can fix.
