### ISSUE TITLE
Minor issue: The link on the "Your game may not be supported yet" page leads to a dead Github link

### ISSUE THREAD

**Issue by MagicJinn** [Nexus-Mods/Vortex#15633]
**Describe the bug**
The link on the "Your game may not be supported yet but adding it yourself may be easier than you think. Click to learn how!" page leads to [a dead Github link](https://nexus-mods.github.io/vortex-api/2022/04/03/Creating-a-game-extension.html) 

**To Reproduce**
1. Search a non supported game in vortex
2. Click the button
3. Observe 404

**Expected behavior**
Link should point here instead: https://modding.wiki/en/vortex/developer/create-a-game-extension
OR
The original link should be fixed

**Comment by insomnious** [comment]
Thanks for pointing this out. We are trying to get all our docs in a single place and I must have missed this!

**Comment by insomnious** [comment]
Fixed with a url redirect
