### ISSUE TITLE
Fallout 4 - Incompatible Archives error due to new header format

### ISSUE THREAD

**Issue by MaverickMartyn** [Nexus-Mods/Vortex#15641]
**Describe the bug**
I am getting an error regarding invalid BA2 archives, using the latest version of Fallout 4, Vortex and Unofficial Fallout 4 Patch.
See the screenshot for the error message.
According to Arthmoor's post here, it is on The Vortex team to fix it: https://www.nexusmods.com/fallout4/mods/4598?tab=posts
They say it's caused by a change to the game's archive header format.
I couldn't find any existing issues covering this.

**To Reproduce**
Setup Vortex 1.10.8, FO4 1.10.980 and UFO4P 2.1.6c.

**Expected behavior**
No error message.

**Screenshots**
The error message:
![image](https://github.com/Nexus-Mods/Vortex/assets/2946618/52c7a332-fd03-4965-a18a-d8a71387c89d)

**Platform:**
 - OS: Windows 11
 - Vortex Version 1.10.8
 - Fallout 4 v1.10.980
 - Unofficial Fallout 4 Patch (UFO4P) v2.1.6c

**Comment by FunkyPixie** [comment]
Yeah same thing is happening with me as well... according to the mod devs the archive headers changed in the new update and vortex doesnt realize that

**Comment by IDCs** [comment]
Hi there! thank you for your report.

Yeah we're aware of this issue, it was fixed as part of the 1.11.x beta which will be released this week.

**Comment by MaverickMartyn** [comment]
I got this again, but only once so far, and it seemed to work for a day or two.
I've updated to the beta branch.
![image](https://github.com/Nexus-Mods/Vortex/assets/2946618/c55013da-7563-4a76-bcf8-8fb273b31e34)
