### ISSUE TITLE
Review: Crab Champions Vortex Support

### ISSUE THREAD

**Issue by 30b0** [Nexus-Mods/Vortex#15654]
### Nexus Username

30b0

### Extension URL

https://www.nexusmods.com/site/mods/870

### Game URL

https://www.nexusmods.com/crabchampions

### Existing Extension URL

https://www.nexusmods.com/site/mods/870

### New features

- Support for the Steam Version
- Creates Mod Folder (%gamedir%/CrabChampions/Content/Paks/~mods)
- Only Installs the Pak-Files in the Game Directory

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [x] Run the GitHub Actions to add to manifest
- [x] Contact author
- [x] Ask Community to enable the Vortex button for the game
- [x] Update the #vortex-announcements channel on Discord

**Comment by insomnious** [comment]
[Crab Champions Vortex Support-870-0-0-1-1715169827.zip](https://github.com/Nexus-Mods/Vortex/files/15249112/Crab.Champions.Vortex.Support-870-0-0-1-1715169827.zip)

**Comment by IDCs** [comment]
Thanks for your contribution - your extension has been added to the Vortex manifest.
