### ISSUE TITLE
Bug: UI flickering when installing mod with new update

### ISSUE THREAD

**Issue by ImmoralMalice** [Nexus-Mods/Vortex#15677]
**Describe the bug**
The ui will flicker while downloading a mod or while setting mod rules.

**To Reproduce**
Install a mod or change mod rules.

Video here, the flickering looks slower in the video:
https://github.com/Nexus-Mods/Vortex/assets/169735883/a4b1676e-eee7-46a7-913b-f49f1339d61d

I have disabled gpu acceleration and it didnt help. Started happening as soon as i downloaded the new update today.

I use an nvidia 3060ti, intel core i7, windows 11

**Comment by IDCs** [comment]
Hi there - are you perhaps using a 3rd party theme-ing application? those tend to inject themselves into open windows to re-render the theme and tend to cause glitches with Electron's renderer.

**Comment by ImmoralMalice** [comment]
> Hi there - are you perhaps using a 3rd party theme-ing application? those tend to inject themselves into open windows to re-render the theme and tend to cause glitches with Electron's renderer. If so - try disabling it and see if it makes a difference. 1.11 includes an Electron update which might be more susceptible to those kind of apps.

Nope, I only use the dark mode built into the app

**Comment by ImmoralMalice** [comment]
Looks like they've released a new update that has fixed the issue here. Gonna close this thread, thanks :)
