### ISSUE TITLE
BG3 extension unable to spawn divine/lslib when spaces are included in path

### ISSUE THREAD

**Issue by IDCs** [Nexus-Mods/Vortex#15679]

**Comment by Pickysaurus** [comment]
> When I deploy mods vortex throws a "Error: divine.exe failed: Command failed", looks like it is because the path to the mod has a space as the command is located in `C:\Users\With Spaces\AppData\Roaming\Vortex\baldursgate3\mods\ExportTool-v1.18.7\tools\divine.exe` and it throws `C:\Users\With` not recognized as a internal or external command.

A workaround is to move the mod staging folder to a location such as `C:\Vortex\Mods\{GAME}` in Settings -> Mods -> Mod Staging Folder.

**Comment by wistak103** [comment]
THis issue is linked in vortex 1.11.5 update 
![image](https://github.com/Nexus-Mods/Vortex/assets/32599249/b7bcc98e-0550-4ffb-ae68-44f868e44f95)
Shouldn't it be this?:
https://github.com/Nexus-Mods/Vortex/issues/15703

**Comment by insomnious** [comment]
Great spot. I’ll sort that out. Thanks!
