### ISSUE TITLE
Review: Sunless Sea

### ISSUE THREAD

**Issue by MagicJinn** [Nexus-Mods/Vortex#15686]
### Nexus Username

MagicJinn

### Extension URL

https://www.nexusmods.com/site/mods/873

### Game URL

https://www.nexusmods.com/sunlesssea

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hi there @MagicJinn - there are a few items that need to be catered for before the extension can be unblocked:

First of all please raise the priority of all registration calls (modType and installers) to over 25.

Secondly, your installer tests will currently return supported: true for ALL mod installations - you need to be more granular and ensure that your installers do not hijack mods that are meant to be installed as part of another game.
closes #15773

So for example 
```
function isJSONAddon(files) {
    // Initial setup for loading JSON mods
    modType = "json"
    installPath = checkJsonDirectoryStructure(files)
    let supported = true
    return Promise.resolve({
        supported,
        requiredFiles: [],
    });
}
```

should be changed to: 
```
function isJSONAddon(files, gameId) {
    // Initial setup for loading JSON mods
    modType = "json"
    installPath = checkJsonDirectoryStructure(files)
    let supported = gameId === GAME_ID;
    return Promise.resolve({
        supported,
        requiredFiles: [],
    });
}
```

**Comment by MagicJinn** [comment]
Any updates or issues?

**Comment by IDCs** [comment]
@Pickysaurus why isn't @MagicJinn able to upload a new version of his extension?

**Comment by Pickysaurus** [comment]
@IDCs You must check this box 
![image](https://github.com/user-attachments/assets/5f64ea9a-3259-4e02-8c37-24d38942b99b)

**Comment by IDCs** [comment]
Thanks @Pickysaurus,

@MagicJinn you should be able to upload new versions of your extension now - please let us know once it's done and I'll re-review.

**Comment by MagicJinn** [comment]
@IDCs new version is uploaded!

**Comment by IDCs** [comment]
Thank you for your contribution!
