### ISSUE TITLE
There is no "minimize to tray" option as mentioned in issue #12970

### ISSUE THREAD

**Issue by DimesRFT** [Nexus-Mods/Vortex#15704]
**Describe the bug**
There is no "minimize to tray" option as mentioned in issue #12970

<img width="872" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/27262093/fa87f874-9178-4850-9a78-c6201a06ed97">

**Comment by IDCs** [comment]
closing in favour of https://github.com/Nexus-Mods/Vortex/issues/12970 which contains more information
