### ISSUE TITLE
Review: Assassin's Creed Unity

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15714]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/878/

### Game URL

https://www.nexusmods.com/assassinscreedunity

### Existing Extension URL

NONE

### New features

No existing extension

Automatically downloads and installs AnvilToolkit, which is needed to repack game files for some mods. 

https://www.nexusmods.com/assassinscreedunity/mods/38

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by ChemGuy1611** [comment]
Thanks for the reply. As always, your time and assistance is greatly appreciated!

So, for the .forge package unpacking and repacking, basically AnvilToolKit will unpack the .forge files in the game folder, which contain a folder structure for the individual .data files. For most .forge mods, the mod files are the .data files in the same folder structure to be packaged into the .forge files. When the user downloads and deploys the mod in Vortex, it will deploy to the game folder and place the .data files within that folder structure, so that when the user repacks the .forge file, the new .data files will be packed into the .forge file to be loaded by the game. The files appear to use a leading number to prioritize the assets, so the mod assets using start the file names with a "1". 

Basically, we are repackaging data into the game's existing .forge files, rather than creating new ones (I don't think the game will alow you to load .forge files other than the original set). 

Here are some screenshots of how the folders look after unpack and the matching mod folder structure:

Game Folder with Extracted game asset folders in "dlc_10", "dlc_11", and "Extracted":

<img width="651" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/10227968/5480715c-9b78-4a4b-a47d-58ee3ff1ee82">

<img width="706" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/10227968/870ab940-4d6f-40e0-b930-29655e93de5f">


Example mod with files in the folder structure:

<img width="529" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/10227968/1d4850f4-d335-4769-82fd-5563848a43c7">

<img width="704" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/10227968/812d3c12-83ba-4454-bc07-a1e933eb30c8">

**Comment by IDCs** [comment]
Thanks for clarifying, and thank you for your contribution.

**Comment by NoskaCS** [comment]
hello @ChemGuy1611. I dont know if you can help but i have looked all over the internet and can't seem to find a solution that works. 

I have been wanting to try Assassin's creed unity with mods and downloaded the vortex mod manager for it to be easier since i dont have any experience with modding games. 
i downloaded ACUFixes and the AnvilToolKit and tried to lunch the game but it says that i need to re-pack the forge. files with use of AnvilToolKit, i watched some youtube videos about it and they all say that the mod should have a description where i should find the forge. files i need to re-pack in order for it to work, but there is nothing about it in the description ( https://www.nexusmods.com/assassinscreedunity/mods/131 ) there are only a guide on how to do it manual.
do you know which files i need to re-pack or how i in the future can find which forge. files i need to re-pack

**Comment by ChemGuy1611** [comment]
@NoskaCS That mod is just packaging poorly. It does not require ATK. You just need to pop the files out of the top level folder in the mod staging folder. I can also update the extension with an installer that does that for you.

**Comment by NoskaCS** [comment]
@ChemGuy1611 thank you for the fast reply.
I will try to rearange the files when i get home. thank you for helping me, i really appreciate it

if you can update the mod so it does it for you, it would be great:)

**Comment by ChemGuy1611** [comment]
The game currently has a lot of crashing issues. This is not a problem with Vortex.
