### ISSUE TITLE
error: dissapearing games

### ISSUE THREAD

**Issue by beanlvr** [Nexus-Mods/Vortex#15738]
**Describe the bug**
Games Dissapearing from managed or unmanaged on vortex. Can not be found or added even though they were being managed and modded under a month ago.

**To Reproduce**
1. Go to games
2. Click on search for a game
3. search for fallout

**Expected behavior**
I would be able to manage and mod my game.

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/170303411/110ae462-8c7f-4d85-aa95-8b1ba0b605fc)
**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**
I can manage and mod my fallout new vegas, just not 4 or 3. I have tried reinstalling both the games and vortex itself. Do I just have to manually add them? What can I do to make sure this doesn't happen again?

**Comment by IDCs** [comment]
Assumed to be resolved

**Comment by beanlvr** [comment]
> Assumed to be resolved

Hi im sorry for the late reply but im still having this issue actually. This was the text given. Please help me decipher it.

Failed to load: Cannot find module 'bluebird'
Require stack:
- D:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-fallout4\index.js
- D:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\vortex-run\lib\index.js
- D:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js
- C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\index.html
