### ISSUE TITLE
Review: Senua's Saga: Hellblade II

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15749]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/888/

### Game URL

https://www.nexusmods.com/senuassagahellblade2

### Existing Extension URL

NONE

### New features

No existing extension.

Integrates Unreal Engine Mod Installer. As far as I know, there are no differences of note for UE5, but the extension will be updated if there are. 

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by ChemGuy1611** [comment]
I removed the Unreal Engine Mod Installer for now since it only works on .pak files, whereas UE5 mods also have .ucas and .utoc files that are required. So, no load order tab for now, but that shouldn't be an issue since there are not yet any asset mods for the game.

**Comment by IDCs** [comment]
Hey @ChemGuy1611, I've been looking through the available mods and it seems like all of them are engine tweaks and reshades :/, none of which are automatically supported as the extension will just dump everything inside `paks/~mods`. I'm afraid you'll have to modify the extension to detect engine configuration and reshade mods before we can add it to the manifest.

**Comment by ChemGuy1611** [comment]
Mod has been updated. I changed the default mod location to by the .exe (mainly for reshades) and added mod installers for the config files and the future UE5 mods (.pak).

**Comment by IDCs** [comment]
@ChemGuy1611 - running through your extension again.

```
const UNREALDATA = {
  modsPath: path.join('Hellblade2', 'Content', 'Paks', '~mods'),
  fileExt: ('.pak', '.ucas', '.utoc'), // <---- You're defining an array of supported file extensions here.
  loadOrder: true,
}
const UE5_EXT = UNREALDATA.fileExt;
```

But then in your test and install function you're treating it as a regular string.
```
function testSupportedContent(files, gameId) {
  // Make sure we're able to support this mod.
  let supported = (gameId === spec.game.id) &&
      (files.find(file => path.extname(file).toLowerCase() === UE5_EXT) !== undefined); // <--- this will never find anything
```

```
function installContent(files) {
  // The UE5 mod files are expected to always be positioned in the mods directory we're going to disregard anything placed outside the root.
  const modFile = files.find(file => path.extname(file).toLowerCase() === UE5_EXT); // <--- this will never execute with the current test being flawed
```

```
// I think what you're looking for is this.
UE5_EXT.includes(path.extname(file).toLowerCase())
```

Other than that I think the ext is fine. Let me know when you fixed it.

**Comment by ChemGuy1611** [comment]
Thanks for the guidance. The other way did work in my testing, but your suggestion is cleaner. I've updated the extension (and also my Robo cop extension that uses an identical installer).

**Comment by IDCs** [comment]
Thanks for your contribution
