### ISSUE TITLE
Review: Assassin's Creed Origins

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15741]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/887/

### Game URL

https://www.nexusmods.com/assassinscreedorigins

### Existing Extension URL

NONE

### New features

No existing extension.

One note: The autodetect game install location for the Ubisoft Connect version of the game won't work until I get the ID number from a helpful user. 

This includes a notification instructing the user to download the Resorep utility (for texture injection). I am not able to auto-download as the mod file is behind a user login "wall". 

This extension also downloads AnvilToolKit for repacking .forge files, but I did not see many mods that use that method for this game. 

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [x] Run the GitHub Actions to add to manifest
- [x] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
@ChemGuy1611 thank you for your contribution! added to the manifest.
