### ISSUE TITLE
Review: RoboCop Rogue City

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15769]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/892/

### Game URL

https://www.nexusmods.com/robocoproguecity

### Existing Extension URL

NONE

### New features

No existing extension. 

Integrates the Unreal Engine Mod Installer extension. 

This extension was built from my previously reviewed and approved Manor Lords extension.

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [x] Run the GitHub Actions to add to manifest
- [x] Contact author
- [x] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by ChemGuy1611** [comment]
I removed the Unreal Engine Mod Installer for now since it only works on .pak files, whereas UE5 mods also have .ucas and .utoc files that are required. So, no load order tab for now, but that shouldn't be an issue since there are not yet any asset mods for the game.

**Comment by IDCs** [comment]
@ChemGuy1611, same as Hellblade II TBH - lots of engine tweaks and reshades, but I can see that there are some .pak mods so I'll approve the extension.

**Comment by IDCs** [comment]
Thanks again for your contributions!
