### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by peytonalexandraae** [Nexus-Mods/Vortex#15767]
**Describe the bug**
Freezes halfway through install, never finishes installing. Vortex is corrupt. Versions attempted to install: 1.11.4 and 1.11.6
**To Reproduce**
1. Go to '...' install vortex
2. Click on '....' install

**Expected behavior**
Stuck halfway through install and reinstall results in the same issue. Attempting to launch vortex results in a warning that it is corrupt and may not work
**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by insomnious** [comment]
Have you tried restarting your computer, uninstalling Vortex via Windows Add or Remove Programs (don't worry, your data is safe), downloading [latest Vortex from Nexus](https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=3242&game_id=2295), and then installing using that?

**Comment by peytonalexandraae** [comment]
I've found it happens with any version I install. Now it says it won't even launch because ffmpeg.dll was not found. The program will not reinstall. The second to latest on Nexus gives me this issue and now its all I get. I've restarted the pc multiple times. No change

**Comment by insomnious** [comment]
Are you available on the [Nexus Mods Discord](https://discord.gg/nexusmods) to continue the conversation and get you back up and running? My username is `insomnious` if you can DM me.

**Comment by peytonalexandraae** [comment]
Also reinstall of the newest triggers NSIS error.

**Comment by peytonalexandraae** [comment]
At this point even reinstalling 1.11.4 which was working two days ago fails. It freezes halfway through the install.

**Comment by kpiatkowski** [comment]
Freshly downloaded `Vortex-1-1-11-6-1716382376.exe` has 150MB (157 286 400) but https://www.nexusmods.com/site/mods/1?tab=files reports 162.1MB. Running this exe results in
```
---------------------------
NSIS Error
---------------------------
Installer integrity check has failed. Common causes include
incomplete download and damaged media. Contact the
installer's author to obtain a new copy.

More information at:
http://nsis.sf.net/NSIS_Error
---------------------------
OK   
---------------------------
```
Tried three times, previous version `Vortex-1-1-8-1-1683621179.exe` download size is correct with displayed on page and installs without issue.

**Comment by insomnious** [comment]
Re-uploaded to Nexus and it now works correctly. Thanks for pointing it out.
