### ISSUE TITLE
Review: Warhammer 40K Space Marine

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15778]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/894

### Game URL

https://www.nexusmods.com/warhammer40000spacemarine

### Existing Extension URL

NONE

### New features

No existing extension.

Nothing fancy here. Installs mods to game root folder, which is the location for most mods on Nexus.

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [x] Run the GitHub Actions to add to manifest
- [x] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Thanks again @ChemGuy1611
