### ISSUE TITLE
Review: Tomb Raider (2013)

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15777]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/893/

### Game URL

https://www.nexusmods.com/tombraider2013

### Existing Extension URL

NONE

### New features

No existing extension.

Writes mods to the root game folder, which seems to be standard for most mods on the site. There are no special tools or mod types for this game from what I can tell.

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hi @ChemGuy1611 - I can see some mods are meant to be used with a tool called textmod, others are fine to deploy to the game's root folder - overall the game has a horrendous modding pattern but I guess this is as good as it gets 🤷 

Can you please add a notification and/or mention on the extension page that it only supports mods that are packaged relative to the game's root path?

**Comment by ChemGuy1611** [comment]
I've added notes on this to the mod page and a notification in the extension as well.

**Comment by IDCs** [comment]
Thanks for your contribution
