### ISSUE TITLE
Vortex uses installer from a different extension as a fallback

### ISSUE THREAD

**Issue by MagicJinn** [Nexus-Mods/Vortex#15773]
**Describe the bug**
I was trying to help someone else create a Vortex extension, specifically trying to get [the Bellwright extension](https://github.com/Nexus-Mods/Vortex/issues/15737) to install their mod unlocker. When I tried to install the file, with no installer in place to handle it (there was only 1 installer, which installs PAK's), it installed to `Bellwright\BepInEx\plugins\Bellwright\Binaries\Win64`, which is extremely odd, since this mod is made for Unreal Engine, and never uses BepInEx. I removed [my own extension](https://github.com/Nexus-Mods/Vortex/issues/15686), which I had installed, and the install worked fine, defaulting to the base directory. Somehow, the `context.registerInstaller("Code Injection Mods", 1, isBepInExMod, installContent)` in my own extension was also applying to theirs.

**To Reproduce**
1. Download and install the extension for Bellwright (in linked issue)
2. Try installing any file, specifically a DLL file ([link to the mod unlocker](https://www.nexusmods.com/bellwright/mods/2))
3. Observe it installs to the base directory
4. Install my extension (linked in issue)
5. Restart Vortex
6. Reinstall the mod unlocker
7. Observe it installs to `Bellwright\BepInEx\plugins\Bellwright\Binaries\Win64`

**Expected behavior**
The mod should be installed to the base directory, given there is no fallback installer for it, instead of using an installer from a different extension, for a different game, **even if the game is not currently being managed**.

**Platform (please complete the following information):**
 - OS: [Windows 10]

**Comment by IDCs** [comment]
See https://github.com/Nexus-Mods/Vortex/issues/15686
