### ISSUE TITLE
Review: Terraria

### ISSUE THREAD

**Issue by Senjay-id** [Nexus-Mods/Vortex#15794]
### Nexus Username

yajneS

### Extension URL

https://www.nexusmods.com/site/mods/857

### Game URL

https://www.nexusmods.com/terraria

### New features

1.0.1 brings new gameart that follows vortex extension guidelines and installer pattern for the most popular mods including tmod mods and save mods

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hi there @Senjay-id - just started reviewing your extension; there are a few issues that need to be rectified in order for the extension to get approved:

1. The extension cannot activate properly for new users who do not have the mods path in the user documents folder.
```
function findGame() {
    return util.GameStoreHelper.findByAppId([STEAMAPP_ID, GOGAPP_ID])
        .then(game => game.gamePath); // <----- this will resolve to the location of the .sh file (wherever GoG/Steam stores it) and will be used as the discovery.path.
}

 // please note that the discovery path that Vortex stores in its state, is the location of the extension's required files.
function prepareForModding(discovery) {
    //// discovery.path will point to the location of tModLoader and not the mods path in the user's documents folder!
    return fs.ensureDirWritableAsync(path.join(discovery.path, 'Mods')); // <---- This will never create the correct mods folder 
}
```

2. Our userbase consists of mostly Windows users, yet the executable is set to a `.sh` file - please enhance the extension to run the correct script depending on the user's OS (if I'm not mistaken tModLoader comes with both `.bat` and `.sh` files)

**Comment by Senjay-id** [comment]
@IDCs Uploaded a new version.

Fixed the first issue by swapping the first return argument function with modPath

Fixed the second issue by using the .bat file present in the root tmod folder, I don't have other OS to check before implementing a function to check the user's os so i'll leave them as a bat for now

Removed the GOG discovery because i just realized that's the id for Terraria, not TModLoader and TML doesn't have a gog version, only Steam.

**Comment by IDCs** [comment]
Thank you for your contribution
