### ISSUE TITLE
Review: Ghost of Tsushima DIRECTOR'S CUT

### ISSUE THREAD

**Issue by Senjay-id** [Nexus-Mods/Vortex#15795]
### Nexus Username

yajneS

### Extension URL

https://www.nexusmods.com/site/mods/897

### Game URL

https://www.nexusmods.com/ghostoftsushima

### New features

Provides mod pattern installation for texture mods

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by ChemGuy1611** [comment]
Hello. I have already uploaded an extension for this game that is in moderation review. It includes the .psarc file installer. 

https://github.com/Nexus-Mods/Vortex/issues/15718

**Comment by Senjay-id** [comment]
ah, makes sense why the name was taken but i couldn't find the extension anywhere in nexusmods

**Comment by Senjay-id** [comment]
Closing the issue to prevent duplicate plugin

**Comment by ChemGuy1611** [comment]
Thank you for your understanding!
