### ISSUE TITLE
Review: Snowbreak: Containment Zone

### ISSUE THREAD

**Issue by Senjay-id** [Nexus-Mods/Vortex#15827]
### Nexus Username

yajneS

### Extension URL

https://www.nexusmods.com/site/mods/900/

### Game URL

https://www.nexusmods.com/snowbreakcontainmentzone

### New features

Has an installation pattern for most popular mods

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hi there @Senjay-id, I can see that your installer is trying to place the mods inside the `../paks/~mods` folder; the `~mods` folder does not exist by default though.

Can you please enhance your `prepareForModding` function so that it creates it for the user.

**Comment by Senjay-id** [comment]
@IDCs Uploaded the new version so that it creates the ~mods folder for new users

**Comment by IDCs** [comment]
Cool - added to manifest
