### ISSUE TITLE
Review: Rooftops & Alleys: The Parkour Game

### ISSUE THREAD

**Issue by LoulouNoLegend** [Nexus-Mods/Vortex#15820]
### Nexus Username

LoulouNoLegend

### Extension URL

https://www.nexusmods.com/site/mods/890

### Game URL

https://www.nexusmods.com/rooftopsandalleystheparkourgame

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [x] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [x] Run the GitHub Actions to add to manifest
- [x] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
@LoulouNoLegend thank you for your contribution to Vortex!

The game has passed review and was added to the extensions manifest.
