### ISSUE TITLE
Review: Bunny Garden

### ISSUE THREAD

**Issue by Senjay-id** [Nexus-Mods/Vortex#15825]
### Nexus Username

yajneS

### Extension URL

https://www.nexusmods.com/site/mods/899/

### Game URL

https://www.nexusmods.com/bunnygarden

### New features

Has BepInEx handling and stop pattern for texture replacing mods that's tested on the most popular mods

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [x] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
@Senjay-id - thanks for your contribution to Vortex - the extension has been added to the extensions manifest
