### ISSUE TITLE
Review: Shadow of the Tomb Raider

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15846]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/906/

### Game URL

https://www.nexusmods.com/shadowofthetombraider

### Existing Extension URL

NONE

### New features

No existing extension

Automatically downloads and installs the SOTTR Mod Manager needed to install .tiger mods for the game. The tool is used to install and enable/disable the .tiger mods after install with Vortex. These instructions are included in a notification to the user.

Also downloads (initially disasbled) a custom version of Special K used for loading legacy texture mods. I left it as disbabled as it could potentially cause startup crashes, so the user should only enable it if they need it. 

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Thanks again
