### ISSUE TITLE
Review: Ghost of Tsushima Director's Cut

### ISSUE THREAD

**Issue by mousesama** [Nexus-Mods/Vortex#15880]
### Nexus Username

GoddessMousesama

### Extension URL

https://www.nexusmods.com/site/mods/898

### Game URL

https://www.nexusmods.com/ghostoftsushima

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hi there - as far as I can see we already have an extension for GoT which supports psarc mods https://www.nexusmods.com/site/mods/879

Can you explain how your extension improves on the existing extension and why you think it should be used instead?

**Comment by mousesama** [comment]
Hi, I missed there already being an extension, in which case mine is redundant, that's my bad. Mine isn't improving on the existing one, so shouldn't be used, I'll be removing it. Thanks.

**Comment by IDCs** [comment]
Thank you for your submission nonetheless!
