### ISSUE TITLE
Review: Resident Evil 4 (2023)

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15899]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/913/

### Game URL

https://www.nexusmods.com/residentevil42023

### Existing Extension URL

NONE

### New features

This extension automatically downloads Fluffy Mod Manager and REFramework on after activating the game, Similar to my Dragon's Dogma 2 extension.

This keeps the mod files in zips when installing to the folder that Fluffy Mod Manager uses, since the archives contain many individual files. 

The user then activates mods in Fluffy Mod Manager after installing with Vortex. 

I also included an Optional File that supports the "Chainsaw Demo" for the game. Fluffy Mod Manger supports that version as well.

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
thanks for your contribution
