### ISSUE TITLE
Planet Crafter Image seems to be broken.

### ISSUE THREAD

**Issue by Furious1964** [Nexus-Mods/Vortex#15905]
**Describe the bug**
The image of the game is missing.

**To Reproduce**
1. Go to Games
2. Click on the upper left corner of Vortex.
3. See error in both ares.

**Expected behavior**
Should be an image of the game like the others.

**Screenshots**
![Screenshot 2024-06-08 164413](https://github.com/Nexus-Mods/Vortex/assets/2803725/77252bd5-1197-4ef2-aa72-d04e40c0cc82)

**Platform (please complete the following information):**
 - OS: Windows 11 Pro 
 - Vortex Version 22631.3672

**Additional context**

**Comment by IDCs** [comment]
Hi there @Furious1964 - please report that to the creator of the extension on his Nexus Mods page.

**Comment by Furious1964** [comment]
Can you provide a link to it, please? Can't seem to find it.

**Comment by IDCs** [comment]
@Furious1964 - Looks like other users reported this to the extension creator as well https://www.nexusmods.com/site/mods/547?tab=bugs

**Comment by Furious1964** [comment]
Thanks for the update, Mate. Cheers.
