### ISSUE TITLE
Updating Starfield

### ISSUE THREAD

**Issue by insomnious** [Nexus-Mods/Vortex#15918]
## Research

- ASI Loader needs disabling for Xbox as it's crashing the game.
- Plugins.txt is checked\changed by game on Main Menu load
- `ContentCatalog.txt` is created\updated when a Creation is downloaded (`AppData\Local\Starfield`) and contains metadata for Creations downloaded ingame

### Creation

- Highlight what is a Creation mod on the load order page instead of what it has now which is 'Not managed by Vortex'. I think this should be reserved for the actual game plugins.

### LOOT

- Add a setting to allow the users to switch between managing the game using the gamebryo extensions, or the current manual dnd load ordering system. A Vortex restart will be needed to switch from one to the other, as the registration calls are all on the main thread. (~2 days of work including testing)
- Add ability to sort plugins using LOOT to the actionbar of the FBLO system. This will _not_ allow us to display loot compatibility messages, unless we want to flood the validation console; and/or are willing to add a custom item renderer. (~up to 1 day of work depending on whether we want a custom item renderer)
- Add migration functionality to disable SFSE/plugins enabler if discovered.
- Add test for deprecated mods?

### Profile specific functionality

- Add independent settings and saves to Starfield profile

**Comment by IDCs** [comment]
libloot 0.23 has been released which fully supports Starfield - need to update our node-loot extension as well which is why I'm setting this to "in progress" again
