### ISSUE TITLE
"filename unknown" error when deploying mods

### ISSUE THREAD

**Issue by HaruDSX** [Nexus-Mods/Vortex#15916]
**Describe the bug**
G'day. I have having an issue after attempting to install the update for Tutorial Chest for BG3. I had the mod before and have not updated since ver 2.7 into ver 2.9. After installing I got the error for multiple mods and went to remove the old version before getting the mod.

**To Reproduce**
1. Go to search bar and typed in "Tutorial Chest"
2. Click on 'remove button' to remove ver 2.7
3. See error

**Expected behavior**
Normally it would remove the old version and give a prompt to deploy the mods again. Already created backup and exported the mod load order.

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/172341468/99da56a4-21a9-41ca-bc33-32dc10373d8e)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.11.6 (5/22/2024)

**Additional context**
I have not attempt to reboot my PC yet, but will try that next after posting issue. Will keep updated if reboot worked.

**Comment by IDCs** [comment]
Hi there - as the error states, the operating system itself is unable to access the file for some reason. I'm afraid there's not much we can do on our end. You'll have to diagnose your environment (HDD bad sectors, permissions, everything)

As a last resort try to delete the files manually 🤷

**Comment by HaruDSX** [comment]
I realized that soon the next day. I have found that the issue was that my
HDD was saving itself by turning off due to a tad bit extra heat in my
system at the time. Thank you for the quick response and the issue has been
resolved.
