### ISSUE TITLE
Vortex fails to remove Hogwarts Legacy mods files, so uninstall/remove/disable mods doesn't actually work.

### ISSUE THREAD

**Issue by gx570s** [Nexus-Mods/Vortex#15940]
**Describe the bug**
When Vortex uninstalls/removes/disables Hogwarts Legacy mods it should remove the mod files from the ~mods folder. Sometimes it does. But often it doesn't. So Vortex shows the mod as uninstalled/removed/disabled when in fact it is still installed and active.

**To Reproduce**
1. Install a bunch of Hogwarts Legacy mods via Vortex.
2. Disable all of them via Vortex.
3. Check the ~mods folder.
4. It should be empty. Sometimes it isn't.

**Expected behavior**
The ~mods folder should be empty if all mods are disabled.

**Screenshots**
I stopped using Vortex for Hogwarts Legacy (because of the problems) so I don't have any.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: Latest

**Additional context**
This has been a problem for 16 months now. I'm amazed nobody has reported it.

**Comment by gx570s** [comment]
Below is a screenshot of the output from the Hogwarts Legacy PakChunk Checker ([www.nexusmods.com/hogwartslegacy/mods/1437](www.nexusmods.com/hogwartslegacy/mods/1437)), as provided by a Vortex user on the Hogwarts Legacy Modding Discord Server. The user was suffering from game crashes so they repeatedly disabled and re-enabled their mods in an effort to identify the mod causing the crashes. But when Vortex disabled their mods it did not actually delete them from the ~mods folder. As a result the user ended up with multiple copies of many of their mods, all of which lead to multiple pakchunk conflicts and an increasingly unstable game. A single pakchunk conflict is enough to crash the game. This many makes the game so unstable that it won't even start.

![Screenshot_2024-06-15_180021](https://github.com/Nexus-Mods/Vortex/assets/134215305/a1917d6f-a385-4897-b197-e87ef3593f2a)

**Comment by IDCs** [comment]
Hi @gx570s, I can't reproduce this on my end - can you please create a collection which can be used to reproduce it reliably for me to test with?

**Comment by gx570s** [comment]
Thanks for getting back to me. I'm surprised that you can't reproduce the problem. It happened to me all the time when I was using Vortex. That's why I stopped using it. It's a widespread problem among Hogwarts Legacy's Vortex users, which is why mod creators have been advising people (for the last 16 months) not to use Vortex with Hogwarts Legacy.

I don't know if that specific user manually modified their folders, but given their level of knowledge I doubt it. However, I can be 100% certain that I did _not_ manually modify my folders. So that was not the cause of the problem in my case. Since I'm no longer using Vortex for Hogwarts Legacy I can't create a collection for you to test. But my mod list was constantly changing back then and the problem occurred pretty much all of the time, so it didn't seem to be mod-list-dependent.

Anyway, I reported this issue as a public service, since so many people are encountering it. But if you're not able to reproduce it then I guess we've hit a dead end. You can go ahead and close this bug report.

**Comment by IDCs** [comment]
@gx570s a lot has changed in the last 16 months, including multiple modifications to the FBLO API which Hogwarts uses. I appreciate your effort submitting this report as we had no knowledge of any issues with that extension beforehand, but please note that the extension itself is developed by the community and not the Nexus Mods team. Any issues with it should be primarily reported to the author on his extension page.

Little tip - stating "this is broken, please fix it" without providing a reliable method of observing the behaviour you describe is insufficient. If you actually want this issue fixed, you will give the extension developer a clear cut method of reproducing it.
