### ISSUE TITLE
Review: System Shock (2023)

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15945]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/923/

### Game URL

https://www.nexusmods.com/systemshock2023

### Existing Extension URL

NONE

### New features

Basically identical to my previously reviewed and approved Manor Lords extension. This is a UE4 game, so the Unreal Engine Mod Installer extension is integrated here. 

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hi there, looks like you have a typo over there. GAMEID isn't defined.

<img width="292" alt="image" src="https://github.com/user-attachments/assets/4da4d9b5-98f9-4115-a014-f1733d7849ed">

**Comment by ChemGuy1611** [comment]
Thanks for catching that. FIxed and reuploaded.

**Comment by IDCs** [comment]
Thank you for your contribution
