### ISSUE TITLE
Review: Dishonored 2

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15952]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/925

### Game URL

https://www.nexusmods.com/dishonored2

### Existing Extension URL

NONE

### New features

Similar to the Bioshock extensions I've uploaded, this incorporates TFC Installer for texture mods.

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
@ChemGuy1611, the code does not include the TFC installer.

**Comment by ChemGuy1611** [comment]
Yes, I removed it as it's not supported in this game. Sorry for the confusion.

**Comment by IDCs** [comment]
@ChemGuy1611, so the extension is pretty basic and relies on the mod authors to package their mods relative to the discovery path.

The game itself seems to have mostly reshades, saves, executable replacements and even a mod injector 'dinput8'. 

I think at the very least we could support for save games? (as the others differ too much)

**Comment by ChemGuy1611** [comment]
Added mod type, but having some trouble with the installer. Basically, I am finding when there is a .dat file present, indicating it is a save. I don't want to strip off the top level folder though (i.e. "SLOT41") as it is necessary to keep the slot folder. 

When I use the code below, the mod installs correctly, but I get this error. Not sure how to avoid this.

<img width="474" alt="image" src="https://github.com/user-attachments/assets/12cac5fc-30f6-46f0-b315-62f374d412a2">


`//mod installer instructions
function installSave(files) {
  //const modFile = files.find(file => path.extname(file).toLowerCase() === SAVE_EXT);
  //const idx = modFile.indexOf(path.basename(modFile));
  //const rootPath = path.dirname(modFile);
  const setModTypeInstruction = { type: 'setmodtype', value: SAVE_ID };
  /*
  const filtered = files.filter(file => 
    (file)
    //((file.indexOf(rootPath) !== -1) && (!file.endsWith(path.sep)))
  );
  */
  const instructions = files.map(file => {
    return {
      type: 'copy',
      source: file,
      destination: file,
      //destination: path.join(file.substr(idx)),
    };
  });

  instructions.push(setModTypeInstruction);
  return Promise.resolve({ instructions });
}`

**Comment by IDCs** [comment]
Are the savegame mods guaranteed to have the slot directory included? What happens if Vortex itself gets to decide the slot folder name? The installer could scan the existing slot entries on the user's machine and just assign the next available numeric value.

But if you just want to keep the slot value as is, you can use the below snippet.
As usual - that's an untested brain dump, you may have to tweak some stuff if it's erroring out or it doesn't completely fit the use case.
```
function installSave(files) {
  const filtered = files.filter(f => !!path.extname(path.basename(f));
  const save = filtered.find(file => path.extname(file).toLowerCase() === SAVE_EXT);
  const segments = save.split(path.sep);
  const idx = segments.indexOf(seg => seg.toLowerCase().startsWith('slot');
  const instructions = filtered.map(file => {
    const segments = file.split(path.sep);
    if (segments.length -1 < idx) {
       // This file is outside of the slot folder. Up to you how you want to handle this, but I'm just going to return undefined
       return undefined;
    }
    const relPathSegments = segments.slice(idx);
    const destination = relPathSegments.join(path.sep);
    return {
      type: 'copy',
      source: file,
      destination,
    };
  });

  instructions.push(setModTypeInstruction);
  return Promise.resolve({ instructions.filter(i => !!i) });
}
```

**Comment by ChemGuy1611** [comment]
Ok, so I uploaded a new version that copies the files though with the folders without throwing the silent error. That seems to work fine for the save game mods I saw on the Nexus.

**Comment by IDCs** [comment]
Thank you for your contribution
