### ISSUE TITLE
Blade and Sorcery - Extension needs updating

### ISSUE THREAD

**Issue by BrandonPotter0** [Nexus-Mods/Vortex#15962]
**Describe the bug**
Vortex will not deploy mods to the Blade and Sorcery mod folder anymore since the 1.0 update.

**To Reproduce**
Attempt to deploy mods with B&S Updated to the newest 1.0 version

**Expected behavior**
Mods to be deployed to the mod folder

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/54760537/1b83c969-4f79-43fd-b0da-f49cd4bdff9c)

**Platform (please complete the following information):**
 - Windows 10
 - Vortex Version 1.11.7

**Additional context**

**Comment by lone44** [comment]
same thing for me on update 1.0

windows 11

vortex 1.11.7

**Comment by IDCs** [comment]
Fixed by Nexus-Mods/vortex-games#119
