### ISSUE TITLE
Review: Assassin's Creed Mirage

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#15975]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/932

### Game URL

https://www.nexusmods.com/assassinscreedmirage

### Existing Extension URL

NONE

### New features

Incorporates the Forger Patch Manger for installing mods.

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
FYI @ChemGuy1611, according to the anviltoolkit mod page on Nexus, AC: Mirage is supported.

<img width="223" alt="image" src="https://github.com/user-attachments/assets/d9ef5b3b-5329-41f6-ba8a-801facef99b3">

Let me know once you've added it and I'll re-review.

**Comment by ChemGuy1611** [comment]
I think that is a typo. The UI for the tool does not include an option for Mirage.

I can always add it in later. I take it that means they will be adding support for Mirage in the future. 

![image](https://github.com/user-attachments/assets/dcb94295-ce3e-4867-b2a9-7f2573176a86)

**Comment by ChemGuy1611** [comment]
New version with ATK is uploaded!

**Comment by IDCs** [comment]
Sweet, thank you for your contribution!
