### ISSUE TITLE
Invalid mods folder for 7 Days To Die

### ISSUE THREAD

**Issue by theBr1z1k** [Nexus-Mods/Vortex#16005]
I faced such a problem that the folder with mods is not in the right place. She's opening up "D:\SteamLibrary\steamapps\common\7 Days to Die\Mods" 
![image](https://github.com/Nexus-Mods/Vortex/assets/160179143/8dc30bc1-e5d6-4355-8941-9b1d3c1ebcdc)
Vortex reveals how "C:\Program Files (x86)\Steam\steamapps\common\7 days to die\Mods\Mods"
![image](https://github.com/Nexus-Mods/Vortex/assets/160179143/002c2db5-6056-4f7f-b2c5-4aa3d201408c)

**Comment by IDCs** [comment]
Hi there - Vortex uses Steam manifests to find out where the game is installed. I'm assuming you created an additional steam library on D: and moved your game there?

Either way it looks like Steam did not clean after itself and it's still pointing to the old location. You can change the directory manually through the games page -> 7dtd thumbnail -> 3 dots at the top right corner of the thumbnail -> set manually.

**Comment by theBr1z1k** [comment]
I tried to install my own directory, it still responds to that folder
