### ISSUE TITLE
7 Days to Die saving to C:\Program\Saves

### ISSUE THREAD

**Issue by CaptMaly** [Nexus-Mods/Vortex#16004]
**Describe the bug**
Whenever I open the vortex 7D2D, it A. doesn't show saves in the vortex launcher, and B. saves all files to C:\Program\Saves instead of the 7D2D fie location

**Screenshots**
<img width="125" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/173908095/4507186a-0bc7-4032-b13c-f7d2429a2aed">
<img width="526" alt="image" src="https://github.com/Nexus-Mods/Vortex/assets/173908095/babf1f07-92db-4ba1-ab58-f496409a66e2">

**Platform (please complete the following information):**
 - Windows 11
 - Vortex Version 1.11.4

**Comment by IDCs** [comment]
Hi there - thanks for your report. Not all game extensions provide a way to view your save files, 7dtd extension does not offer that feature. That being said, going by the screenshot of your program/saves folder - that looks like the location where the game itself is keeping its saves for some reasons - this has nothing to do with Vortex.

**Comment by IDCs** [comment]
@CaptMaly, that is an issue with the game or your setup. Not a Vortex issue.

**Comment by LanceDeBrooks** [comment]
@CaptMaly How did you figure out where vortex was saving them?

**Comment by CaptMaly** [comment]
My computer popped up a warning that there was a file named c:/program
