### ISSUE TITLE
Blade and Sorcery Extension bug

### ISSUE THREAD

**Issue by BrandonPotter0** [Nexus-Mods/Vortex#16000]
**Describe the bug**
Since the latest extension update, an error pops up every time when I try to deploy mods. B&S was updated to 1.0.1 so maybe the extension isnt detecting the update properly.

**To Reproduce**
1. Download a mod
2. Attempt to deploy
3. ????
4. Profit

**Expected behavior**
No popup or error when deploying mods

**Screenshots**
![image](https://github.com/Nexus-Mods/Vortex/assets/54760537/3656b4fc-b119-474c-abbc-17219103a7f3)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.11.7

**Additional context**
![image](https://github.com/Nexus-Mods/Vortex/assets/54760537/fc94d3d7-b0ce-442d-a165-416ecb2ce7e1)

The extension is definitely not detecting the version right, as Vortex is mismatching the version, and deploying some mods as a legacy mod when they arent

**Comment by IDCs** [comment]
I think it's time to remove support for the legacy versions of the game. In the meantime you can manually fix this on your end through the mod panel on the mods page. Just double click any mod entry and set the ModType dropdown button to the official version; the mods should then deploy just fine.

**Comment by BrandonPotter0** [comment]
> I think it's time to remove support for the legacy versions of the game. In the meantime you can manually fix this on your end through the mod panel on the mods page. Just double click any mod entry and set the ModType dropdown button to the official version; the mods should then deploy just fine.

Agreed. Theres no need for legacy support anymore anyways. And yes, changing the mod type fixed the issues for me. :)
