### ISSUE TITLE
Review: Return to Castle Wolfenstein

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16038]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/937

### Game URL

https://www.nexusmods.com/returntocastlewolfenstein

### Existing Extension URL

NONE

### New features

Basic extension that installs to root game folder. Prompts the user with a notification to download one of the open source mods that allow the game to run properly on modern hardware.

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hey there @ChemGuy1611,

Just finished reviewing your extension and there's one thing that needs to be rectified in order for the extension to be approved. The RealRTCW notification in its current form will never dismiss as you're not using the `dismiss` parameter correctly which is forwarded by the notification button, not the dialog buttons.

To make it easier, just replace your `setupNotify` function with the below snippet. (note that `dismiss` is forwarded by the notification's button, the 'More' action to be exact.)

```
function setupNotify(api) {
  api.sendNotification({
    id: 'setup-notification-returntocastlewolfenstein',
    type: 'warning',
    message: 'RealRTCW Recommended',
    allowSuppress: true,
    actions: [
      {
        title: 'More',
        action: (dismiss) => {
          api.showDialog('question', 'Action required', {
            text: 'It is highly recommended that you download and install either RealRTCW or ioRTCW to improve your experience on modern systems. \n'
                + 'RealRTCW is a fork of ioRTCW and is receiving active support, so it is recommended to use RealRTCW. \n'
          }, [
            { label: 'Continue', action: () => dismiss() },
            { label: 'Download RealRTCW', action: () => {
              util.opn('https://www.moddb.com/mods/realrtcw-realism-mod/downloads').catch(err => undefined);
              dismiss();
          }},
          { label: 'Download ioRTCW', action: () => {
            util.opn('https://github.com/iortcw/iortcw').catch(err => undefined);
            dismiss();
        }},
          ]);
        },
      },
    ],
  });    
}
```

Additionally, you might be interested in the browser download Vortex functionality, which allows users to browse for a required download within a Vortex webview component and automatically install the tool/requirement inside Vortex.

Below snippet is from our UMM modtype downloader which allows the user to browse and select the required UMM version from Github, you could use this for requirements from moddb - contact me here or on Discord if you're interested in implementing this for any of your game extensions.
```
const instructions = t('Once you allow Vortex to browse to GitHub - '
    + 'Please scroll down and click on "{{archiveName}}"', { replace });
return new Promise((resolve, reject) => {
    return api.emitAndAwait('browse-for-download', dlInfo.githubUrl, instructions)
      .then((result: string[]) => {
        if (!result || !result.length) {
          // If the user clicks outside the window without downloading.
          return reject(new util.UserCanceled());
        }
        if (!result[0].includes(dlInfo.archiveName)) {
          return reject(new util.ProcessCanceled('Selected wrong download'));
        }
        api.events.emit('start-install-download', result[0], {}, undefined,
          async (error, id) => {
            if (error !== null) {
              return reject(error);
            }
            // Do something with the completed download/installation
          }, 'never');
      });
  })
  .catch(err => {
    if (err instanceof util.UserCanceled) {
      return Promise.resolve();
    } else if (err instanceof util.ProcessCanceled) {
      return downloadFromGithub(api, dlInfo);
    } else {
      return Promise.reject(err);
    }
  });
```

**Comment by ChemGuy1611** [comment]
Thank you for that correction. I will update my other extensions with notifications to fix that dismiss behavior as well.

New version is uploaded to Nexus. 

Thanks for the snippet on the browser download as well. I will chew on it and try to get it working. Will contact you on Discord if I run into any problems.

**Comment by IDCs** [comment]
Sweet, thanks for your contribution.
