### ISSUE TITLE
Review: State of Decay 2

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16053]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/946/

### Game URL

https://www.nexusmods.com/stateofdecay2/

### Existing Extension URL

NONE

### New features

No existing extension.

Automatically downloads and installs the SoD2 Mod Manger as an option for users to help load order .pak mods and resolve internal .pak content conflicts.
https://www.nexusmods.com/stateofdecay2/mods/96?tab=files 

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
How is this extension any better than https://www.nexusmods.com/site/mods/244 ?

**Comment by ChemGuy1611** [comment]
I did not notice that one. And it for some reason has not been added to the Vortex manifest? This one here uses in the included SoD2 Mod Manger as an option for load ordering. Haven't looked into the other to see how it does it.

**Comment by IDCs** [comment]
Sold.

Thank you for your contribution!
