### ISSUE TITLE
Review: The Outer Worlds

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16087]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/964/

### Game URL

https://www.nexusmods.com/theouterworlds

### Existing Extension URL

NONE

### New features

Uses Unreal Engine Mod Installer to install .pak mods and create Load Order.

Includes an Optional File for the Spacer's Choice Edition version of the game. 

Works on Steam, GOG, and Epic versions currently. 

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Thank you for your contribution

**Comment by ChemGuy1611** [comment]
@IDCs  - I think there is an issue with the file added to the manifest for the Outer Worlds. Could you re-add this one? I have updated the main file, but it is not pushing the update out. I updated other extensions, and they are coming through just fine. I think it happened because I had the Xbox version also as a main file, and it had been uploaded sooner, so I think that version was added to the manifest rather than the main version.

I did figure out how to get the Xbox version integrated into the main extension, so I will be updating the main file to support all versions as well.

**Comment by IDCs** [comment]
@ChemGuy1611 done
