### ISSUE TITLE
Review: The Legend of Heroes: Trails Through Daybreak

### ISSUE THREAD

**Issue by SheLikesCloth** [Nexus-Mods/Vortex#16080]
### Nexus Username

NotAZebrum

### Extension URL

https://www.nexusmods.com/site/mods/954/

### Game URL

https://www.nexusmods.com/thelegendofheorestrailsthroughdaybreak

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Extension has been added, thanks for your contribution.

**Comment by SheLikesCloth** [comment]
Thanks for the work on this. Can you clarify what you mean by “installed as asset replacements”? I think that is currently the only thing this extension can do.
