### ISSUE TITLE
vortex cannot be closed on windows 11

### ISSUE THREAD

**Issue by NunyaBitness** [Nexus-Mods/Vortex#16090]
**ffmpeg.dll cant be found**
lauching vortex sends me a system error for the ffmpeg.dll was not found, this didnt happen last night.

**To Reproduce**
1. Go to 'download launcher and 1/3 of the way through reports vortext can not be closed'
2. Click on 'click on task manager and check to see vortex is not running *its not*'
3. 'restarted pc and attempted to to install again see same error click on cancel see fail to uninstall old application files please try running the installer again :2 '

**Expected behavior**
the game to launch 

**Screenshots**
![Screenshot 2024-07-20 134901](https://github.com/user-attachments/assets/4907fac0-4393-4a0f-8477-3dfbd2bb071c)
![Screenshot 2024-07-20 134833](https://github.com/user-attachments/assets/791cbf1a-9e42-4aa8-9615-bab79f48131a)
![Screenshot 2024-07-20 140017](https://github.com/user-attachments/assets/c1950122-b64b-4a7a-b57d-dc957e79fed1)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Vortex Version [1-1-11-7-1718114475 ]

**Additional context**

**Comment by IDCs** [comment]
I'm afraid this is an issue with your environment - run windows repair tools (SFC/DISM/etc) to try and resolve it.
