### ISSUE TITLE
starfield deleted mods within creations still show as active in Vortex

### ISSUE THREAD

**Issue by tighearnain** [Nexus-Mods/Vortex#16104]
Hi,

If you delete mods within Creations, they are still shown as still being active, both in the mod list and load order pages on vortex. However the mod will not load until it is reinstalled again.

**Comment by IDCs** [comment]
Hi there @tighearnain - thank you for your report. The load order page has seen some significant changes as part of our 0.8.x update which will be released next week. I just double checked to see if Vortex updates the plugins list correctly if a plugin is removed externally, and it is. (As long as you press the "Refresh List" button of course)

As for the Mods Page - external changes (such as deleting a mod through the game itself) are only detected upon deploy/purge events. Having Vortex continuously check if a mod is still deployed is not an option as it will grind your system to a halt when managing larger modding environments.

Going to close this issue as there's nothing actionable on our end.
