### ISSUE TITLE
Review: Ready Or Not (UE5 Update)

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16129]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/980/

### Game URL

https://www.nexusmods.com/readyornot

### Existing Extension URL

https://www.nexusmods.com/site/mods/342

### New features

This is a new extension for Ready Or Not that supports the UE5 update for the game. This new version is necessary because .pak type mods now have multiple file types (.pak, .ucas., .utoc) that are not supported by the original extension.

Additionally, this new extension adds these features:

1. Installs mods to the Binaries folder by the game .exe by default. - Old extension installed to the game root folder, which is much less useful
2. Automatically installs mods designed to go into the root game folder.
3. Automatically installs config files to the correct folder in Local AppData.
4. Automatically installs save game files to the correct folder in Local AppData.
5. Game art that complies with Nexus Mods guidelines for extensions.
6. Active developer support. The old extension has never been updated in over 2 years.

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
@ChemGuy1611 not a big deal but the following snippet is redundant.

fileExt will always be an array, so that if statement will never hit.

```
const fileExt = UNREALDATA.fileExt;
    if (!fileExt)
      Promise.reject('Unsupported game - UE5 installer failed.');
```

**Comment by IDCs** [comment]
Given the response from the existing RoN author and his interest to keep maintaining the existing extension, I'm afraid we cannot approve this extension.

If you wish to add/refactor the existing extension, please do so via PR on the following page https://github.com/BeYkeRYkt/vortex_readyornot_extension

**Comment by insomnious** [comment]
@ChemGuy1611 have you got any links you can send regarding Ready or Not moving to use IOStore (pak\utoc\ucas)? 

Even though the game has been updated to UE 5.3, it doesn't have to use IOStore. Unreal 4.27 games can use IOStore if they'd like. PAK file formats aren't specifically set by Engine versions. I've downloaded Ready or Not this afternoon and it's still using regular PAK files for it's game content.

**Comment by ChemGuy1611** [comment]
> @ChemGuy1611 have you got any links you can send regarding Ready or Not moving to use IOStore (pak\utoc\ucas)?
> 
> Even though the game has been updated to UE 5.3, it doesn't have to use IOStore. Unreal 4.27 games can use IOStore if they'd like. PAK file formats aren't specifically set by Engine versions. I've downloaded Ready or Not this afternoon and it's still using regular PAK files for it's game content.

If I understand correctly, the developer is still working on adding support for IOStore. So at the moment there are only .pak files. If I understand how it works, you could still use only .pak files, but they do not load as efficiently as the IOStore types, which will be supported in the future, mostly for custom assets (textures and meshes). 

Additionally, there are the other mod types that are automatically installed with this extension (root game folder, config files, and saves).
