### ISSUE TITLE
Review: Wolfenstein (2009)

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16142]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/985

### Game URL

https://www.nexusmods.com/wolfenstein2009

### Existing Extension URL

NONE

### New features

Supports both the retail and Steam versions of the game

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
@ChemGuy1611,

I'm afraid we cannot approve the extension in its current form as it will not support any of the mods we have on the site.

As far as I understand it, most pk4 mods need to be deployed to `sp/base` or `mp/base` I think given that there is no way to determine where to deploy the mod from the mod package itself - I'd recommend having a custom installer which raises a dialog mid-installation to ask the user himself where to install the mod.

**Comment by ChemGuy1611** [comment]
@IDCs - I added the installer dialogue for choosing between the SP and MP folders! I was able to use snippets from the dialogue in the Unreal Engine Mod Installer extension. Nice to have another tool in the toolbellt!

New version is on the Nexus.

**Comment by IDCs** [comment]
Thank you for your contribution
