### ISSUE TITLE
[Feature Request] - Select All and Bulk Actions for mods (Enable, Disable, Uninstall, Remove, Reinstall etc)

### ISSUE THREAD

**Issue by ondrovic** [Nexus-Mods/Vortex#16164]
**Is your feature request related to a problem? Please describe.**
I have had an issue (my own fault) where I have had to disable, uninstall, enable, reinstall mods, currently it's a one by one deal

**Describe the solution you'd like**
The ability to select all mods at once, and then perform any action that can be done an individual basis

**Describe alternatives you've considered**
Currently the only way is one by one

**Additional context**
1. Add a select all checkbox  that is toggleable 
2. Once all are selected we need another menu that has the following sub items

   a. Enable
   b. Disable
   c. Uninstall
   d. Reninstall
   e. Remove
   f. Remove Related
   f. Refresh Content
   
3. Should then loop perform the actions on the selected items

**Comment by insomnious** [comment]
If you click and then shift-click the multiple mods will be selected and there is a blue menu bar that appears at the bottom. Will this fit your needs?

**Comment by IDCs** [comment]
As my colleague mentioned, Vortex uses Windows based key shortcuts to select one or more mod entries (CTRL + click/SHIFT + click)

The toolbar at the bottom can then be used to run bulk actions. Closing as this is already implemented.
