### ISSUE TITLE
Mount and Blade 2 Bannerlord: Load Order Enable All button

### ISSUE THREAD

**Issue by FatherSarge** [Nexus-Mods/Vortex#16187]
**Is your feature request related to a problem? Please describe.**
You ever try to mod bannerlord with 100 mods and also use the load order manager? Having to click each individual mod after enabling them all in the mod menu is a chore. We'd all like a button to just enable everything in the load order menu

**Describe the solution you'd like**
A button that enables all mods in the load order menu

**Describe alternatives you've considered**
Getting carpal tunnel clicking all the boxes manually

**Additional context**
I don't wanna get carpal tunnel bros

**Comment by IDCs** [comment]
@aragas

**Comment by Aragas** [comment]
Will be part of v1.1.3 of the extension

**Comment by Aragas** [comment]
Can be closed, v1.1.3 was released

**Comment by IDCs** [comment]
Thanks @Aragas
