### ISSUE TITLE
Starfield Extension Issue

### ISSUE THREAD

**Issue by BrandonPotter0** [Nexus-Mods/Vortex#16183]
**Describe the bug**
Extension throws out an error when trying to use Loot sorting feature. 

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at C:\Users\brand\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Starfield Vortex Extension v0.8.7\index.js:4441:48
    at Array.map (<anonymous>)
    at serializePluginsFile (C:\Users\brand\AppData\Roaming\Vortex\plugins\Vortex Extension Update - Starfield Vortex Extension v0.8.7\index.js:4439:26)

**To Reproduce**
Attempt to sort Plugins for Starfield using built in Loot Tool

**Expected behavior**
Sort Plugins without issue

**Screenshots**
![image](https://github.com/user-attachments/assets/6d30d327-0069-43d7-ba61-3d94e8c285f9)

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.12.0

**Additional context**
N/A

**Comment by IDCs** [comment]
Re-opening as this is 100% a bug in the Starfield extension.
