### ISSUE TITLE
Manual Game Store Selection and Launcher Requirements

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16215]
More of a heads up than an actual bug. There were recently reports of games giving a silent error when launching about "failed to determine  launcher requirement". After a bit of digging, I realized that all of these reports were for games where the extension has the structure to properly launch the Epic version of the game, but the Epic Games Store ID for the game was not yet known. I think this is because in the 1.12 Vortex update, the popup to specify the game store after manual discovery was added. This is a good feature, but it made it so that the user could specify the Epic Games Store and "trigger" the Epic launcher code that had a blank ID.

I have noticed some other extensions not made by me that had error reports, such as Subnautica. It is probably for a similar reason in that case. 

Really just posting this for awareness as it is not really a "bug" and the game will still launch OK even with this error. It will be resolved once the Epic ID is known for those games.

**Comment by IDCs** [comment]
@ChemGuy1611 - in the requiresLauncher function - simply return undefined to stop your extension from trying to launch the game through the game store. (at least until you know the epic id for the game)
