### ISSUE TITLE
The Outer Worlds Vortex Extension Not Pushing Updates Again

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16214]
Don't mean to be a bother, but my The Outer Worlds Vortex Extension is still not pushing updates out to Vortex properly. Just updated the main file to integrate support for the Spacer's Choice Edition of the game, but the update is not pushing out to Vortex. 

Not sure why this is happening on this particular extension since the 50+ others I've uploaded update just fine.

https://www.nexusmods.com/site/mods/964

**Comment by IDCs** [comment]
He @ChemGuy1611, I can see that the last manifest update had finished ~19 hours ago, depending on when you updated your extension it might be just a matter of waiting for the next update cycle to run - (which will be in 4 hours)

If the manifest doesn't update then, I'll have a look at why the updater is ignoring Outer Worlds.

**Comment by IDCs** [comment]
There's indeed an issue - appears to be down to the backend not providing the image file for the thumbnail when you don't have the extension downloaded and installed; will update you once we fix it.

**Comment by IDCs** [comment]
Fixed

**Comment by IDCs** [comment]
@ChemGuy1611, looks like several of your extensions might be affected by the same issue:
```
964: Missing picture_url { modId: 964 }
972: Missing picture_url { modId: 972 }
988: Missing picture_url { modId: 988 }
990: Missing picture_url { modId: 990 }
```

Can you please do the following for all affected mods:
1. Upload a second image to the Media section
2. Set the new image as the primary, then set it back to the old one
3. Delete the new image
