### ISSUE TITLE
[Feature Request] - Check for and install mod updates for all mods (not just enabled mods)

### ISSUE THREAD

**Issue by ondrovic** [Nexus-Mods/Vortex#16220]
**Is your feature request related to a problem? Please describe.**
Current functionality is to only check for updates of mods that are currently enabled, while disabled and uninstalled mods are ignored

**Describe the solution you'd like**
Check for updates for any mods regardless of state

If updates are found allow for updating mods in any state

**Describe alternatives you've considered**
Currently you have to do the following

1. Install / Enable mod
2. Check for update
3. update mode
4. disable or uninstall mod

**Additional context**

**Comment by ChemGuy1611** [comment]
Vortex already does check for updates to disabled mods...

**Comment by IDCs** [comment]
Confirmed - Vortex will check for updates for all mods regardless of state. If an update does not appear for a certain mod, that's down to the mod author not configuring his uploaded files correctly when he uploaded the new version.
