### ISSUE TITLE
Review: I am Future

### ISSUE THREAD

**Issue by V0IDL355** [Nexus-Mods/Vortex#16266]
### Nexus Username

VOIDL3S5

### Extension URL

https://www.nexusmods.com/site/mods/1006

### Game URL

https://www.nexusmods.com/iamfuture

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by V0IDL355** [comment]
It only installed for me after manually getting the zip from nexus and dragging it in. (Install button didn't work for whatever reason)

**Comment by ChemGuy1611** [comment]
> It only installed for me after manually getting the zip from nexus and dragging it in. (Install button didn't work for whatever reason)

This is a known issue with Vortex. It will install properly once the extension is reviewed and added to the manifest.
