### ISSUE TITLE
Game is unable to find some mods listed as enabled in Vortex.

### ISSUE THREAD

**Issue by NateConCatten** [Nexus-Mods/Vortex#16271]
Skyrim SE is unable to find some mods listed as enabled in Vortex. These mods are present in the data folder but inactive in the game. 

What worked for me to resolve this was

1. Locate and compress the original files in the data folder.
2. Rename the compressed folder
3. Uninstall and remove the original mod
4. Install the new archive

**Comment by IDCs** [comment]
Make sure the plugins for those mods are enabled in the plugins page.
