### ISSUE TITLE
Review: Lockdown Protocol

### ISSUE THREAD

**Issue by Akkiruk** [Nexus-Mods/Vortex#16299]
### Nexus Username

rboone98

### Extension URL

https://www.nexusmods.com/site/mods/1010

### Game URL

https://www.nexusmods.com/lockdownprotocol

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [x] Double-check for existing extension
- [x] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [x] Does it install into Vortex?
- [x] Does it correctly discover the game?
- [x] Does it successfully install a mod?
- [x] Does it successfully install a collection?
- [x] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by Akkiruk** [comment]
I have tested everything but the collections. I've not really used collections before and when I try to create one it says server rejected this collection because selected game is not valid. 

I'm not exactly sure what I have done wrong as everything else works. I just can't seem to find a way to point my extension at the lockdownprotocol page

**Comment by Akkiruk** [comment]
I take back my earlier comment I figured out that I just had a - in between lockdown and protocol in my index.js and my info.json which was not a part of the game on the nexus mods site. With that changed it all works now and I was able to create and install this collection. I just don't know the proper way to update the file without screwing up the moderation review part of this

https://next.nexusmods.com/lockdownprotocol/collections/twj7eh

**Comment by IDCs** [comment]
Hi there @Akkiruk, first of all thank you for your contribution!

Unfortunately the gameId value you're using in the game extension is wrong. The gameId/domainId is lockdownprotocol not lockdown-protocol.

Please change it to the correct value and you should be able to test collections as well.

**Comment by Akkiruk** [comment]
I did end up updating that in version 2.0.0 

I uploaded the new version to the nexus mods page https://www.nexusmods.com/site/mods/1010 and that new file I uploaded there should have all the changes but if the version you are downloading is still 1.0.97 and not 2.0.0 please let me know and I will try again.

That has lockdownprotocol as the gameid and not lockdown-protocol

I have been able to successfully test collections now and created this collection as my collectoin for testing. 

https://next.nexusmods.com/lockdownprotocol/collections/twj7eh

**Comment by Akkiruk** [comment]
the old bad version is version 1.0.97

the version you should be testing with the fix is version 2.0.0

I uploaded that version to the nexus mods page last night and 1.0.97 should be hidden as it doesn't work properly

**Comment by EnesDincel** [comment]
Firstly, does the game still work consistently when modded and how do we mod it?

**Comment by Akkiruk** [comment]
> Firstly, does the game still work consistently when modded and how do we mod it?

Game consistency will always depend on the mods themselves you have but of all the mods I have tried so far there have not been any issues and my game has never crashed. 


As far as how to mod it
For now we are just waiting on @IDCs to approve the extension so it can get uploaded to vortex and make mod installation easier. You can manually download and install mods right now but you will want to ask around in the lockdown protocol discord

**Comment by IDCs** [comment]
Thank you for your contribution.

**Comment by ItsBoris1** [comment]
Can somebody tell me how can i start writing mods for this game ?
