### ISSUE TITLE
[Feature Request] Allow Vortex to apply mods to non-executable files

### ISSUE THREAD

**Issue by werewolfprincess** [Nexus-Mods/Vortex#16319]
It would be nice to be able to use Vortex to add mods to non-PC games that don't have an .exe file associated with them. For 
example, there's a good few games for the Nintendo Switch on Nexus, but those use the .nsp file format so it's impossible to use Vortex to mod them. It would also be nice to be able to select a folder containing the game's files for games that have been unpacked, but that's far from necessary. In my case, I was attempting to install mods on Final Fantasy 12's Nintendo Switch release, but there were a good number of mods on the game's Nexus page that required Vortex.

**Comment by ChemGuy1611** [comment]
You don't really "need" to have an executable. I have played with this idea a little bit, and it works fine to specify other files as required. If you are talking about emulation, you can simply set the emulator executable in the extension and use that to launch the game with some command line arguments. 

Also, the mods you are referring to for FFXII are for the native PC version of the game. Not an emulator.
