### ISSUE TITLE
STOP GRABBING FOCUS and don't demand write access when you don't need it

### ISSUE THREAD

**Issue by fefe17** [Nexus-Mods/Vortex#16326]
I have Skyrim running, I see on Nexus a mod with a few presets, I download it.

The browser hands over to Vortex which was not running. I alt-tab to Skyrim.

When Vortex starts (which takes WAY TOO LONG btw) it ... grabs focus, interrupting Skyrim for no good reason.
So I curse loudly and alt-tab back into Skyrim.

Guess what happens next? Vortex grabs focus AGAIN. Maybe to inform me the download is proceeding or has ended or something? I have no idea. I did not need it to force-interrupt my Skyrim at any rate.

Are you guys _trying_ to make me switch mod managers?

So I curse loudly and alt-tab back to Skyrim, when Vortex grabs focus AGAIN to tell me it needs write access and another process is having the file open and I should quit the Skyrim process.

This is absolutely not necessary for presets.

You are leaving an absolutely terrible first impression.

**Comment by ChemGuy1611** [comment]
Please, do NOT attempt to install mods for a game while it is running. You will cause write-access conflicts since Vortex cannot re-deploy files for the game while the game is using those files. You will also interrupt your game by diverting system resources to launching and running Vortex. 

Everything you described is perfectly normal behavior for Vortex, and many Windows applications for that matter. 

It doesn't matter if the mod is a preset or any other type of mod. If Vortex runs deployment, you will get write-access errors because Vortex is trying to deploy hardlinks for all Enabled mods.

It also sounds like you are launching your game from outside of Vortex, because Vortex prevents mod deployment while a game or tool is running to avoid these errors. This is not advisable.

**Comment by fefe17** [comment]
The reason that I can launch the game without Vortex running is the main reason I'm using Vortex and not MO2 for example.

You seem to have misunderstood what I was complaining about.

If Vortex is trying to deploy mods that don't need deployment than Voxtex is doing unnecessary work that it should not be doing.

Please change Vortex so it is no longer doing that work.

Vortex does not in fact need write access to any file that is in use to install or deploy these presets.

**Comment by ChemGuy1611** [comment]
What exactly is the "preset" you are referring to? Any mod downloaded by Vortex requires deployment to work.

**Comment by fefe17** [comment]
This was the mod:

https://www.nexusmods.com/skyrimspecialedition/mods/127490

These are racemenu presets that are not loaded by Skyrim itself, but you can load them in racemenu dynamically.
Skyrim does not have them open and they have no ESP or ESM in them that would require the file with the list of mods to be updated.

Vortex does NOT need to touch any files that might be in use by Skyrim to install this mod.

**Comment by ChemGuy1611** [comment]
Again, Vortex deploys ALL ENABLED MODS on deployment. Do NOT install mods while the game is running.

**Comment by fefe17** [comment]
I don't know to  be clearer on this.

THAT IS EXACTLY THE BUG I AM REPORTING HERE.

Do not deploy all mods all the time. In fact, try to minimize writes to the disk as that causes premature aging in flash-based storage.

**Comment by ChemGuy1611** [comment]
That is NOT a bug. Please learn to read more carefully.

**Comment by fefe17** [comment]
OK, let me put this in easy words.

Me filing this bug? That's work. On my part. I do this unpaid work as part of a social contract.
It's my investment to tell you about things you should improve, and your part is to improve them.
That is in fact the whole reason this bug tracker exists in the first place.

If you are unwilling to fix bugs, then please: Just walk away.
No hard feelings. I did not expect you personally to fix this bug.
I expected someone to fix it. If you don't think it's a bug then why are you wasting time with it?
No need to stand in the way of others who actually do want to improve Vortex.

I KNOW HOW VORTEX WORKS.
AND IT'S DOING IT WRONG.
THAT'S WHY I FILED THIS BUG.

You telling me I should have read more about how Vortex works helps nobody and frankly makes you and the whole product look bad.

**Comment by ChemGuy1611** [comment]
THIS IS NOT A BUG. NO ONE WILL FIX IT.

**Comment by fefe17** [comment]
Please step away sir. You have done enough damage.

Look man I'm not trying to educate you here.
My work is done. In a few years when someone will have fixed this, I have a paper trail showing I reported this way back when the support was done by people who didn't understand that linking files is a write access to a storage medium.

People then will have realized that software is supposed to do what the people need, instead of reeducating people to work around shortcomings of the software because the dude writing the software didn't know what he was doing.

Also I have verified independent measurement now that the people who said Vortex is worse than other mod managers may actually have a point.

**Comment by IDCs** [comment]
Hi @fefe17 - there's a configuration item which will stop Vortex from grabbing focus when downloading mods.
<img width="475" alt="image" src="https://github.com/user-attachments/assets/c566a23c-912d-40d9-9690-5d9de40166f4">

The automation functionalities should also be disabled given your use case. Speaking of which, I'm sure you're perfectly aware that running two applications that are attempting to read/write from/to the same files is a very bad idea, at best you may experience performance issues as the applications grab/release file handles; at worst you will experience random crashes.

I understand that the presets you're installing are not being loaded by the game directly, but Vortex is designed to be generic and will not treat presets differently from any other mods, which means that a deployment event is necessary after mod installation. Turning off the automation options will give you full control of when and how these deployments events are called, but the matter of fact is - Vortex will grab focus and file handles whenever a deployment event is running, this will not change.
