### ISSUE TITLE
Update LOOT to v0.23.1

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16344]
LOOT needs to be updated to v0.23.1 to resolve an issue with a new .esm for Starfield not sorting properly. I see the .dll in the gamebryo-plugin-management bundledPlugin is currently v0.23.0.

https://forums.nexusmods.com/topic/13497343-starfields-latest-esm-not-being-loaded-at-the-top-keeps-being-put-at-the-bottom-of-the-load-order/#comment-130463697  

https://loot.readthedocs.io/en/latest/app/changelog.html

**Comment by IDCs** [comment]
Thanks @ChemGuy1611, this is resolved in 1.12.4 (https://github.com/Nexus-Mods/extension-plugin-management/pull/34)
