### ISSUE TITLE
Review: Deep Rock Galactic Survivor

### ISSUE THREAD

**Issue by caioreix** [Nexus-Mods/Vortex#16342]
### Nexus Username

caioreix

### Extension URL

https://www.nexusmods.com/site/mods/1021

### Game URL

https://www.nexusmods.com/deeprockgalacticsurvivor

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hi there @caioreix !

First of all, thank you for your contribution, the extension is fine, the only item I'd suggest you change is tied to the quicklauncher UI component cutting off the last 'r' when rendering the game name. You can fix that by providing a shortName for Vortex to use.

e.g.
```
const GAME_NAME_SHORT = 'DRG: Survivor'

// When registering the game:
context.registerGame({
    id: GAME_ID,
    name: GAME_NAME,
    shortName: GAME_NAME_SHORT, <-- Add this property.
    mergeMods: false,
    ...,
```

**Comment by IDCs** [comment]
Thank you for your contribution
