### ISSUE TITLE
[Feature Request] - Auto Dependency definitions  based on mod requirements

### ISSUE THREAD

**Issue by ondrovic** [Nexus-Mods/Vortex#16360]
**Is your feature request related to a problem? Please describe.**
Having to manually setup dependencies for mods

**Describe the solution you'd like**
Having dependencies defined automatically, when you install them, they requirements are already defined  for the mod you are downloading.

**Describe alternatives you've considered**
Currently the only ways to do it is manually

**Additional context**
I realize this probably means that those requirements are going to have to be exposed, as it seems like they are likely not yet, because currently there is no where in vortex to see requirements (dependencies), so that would that would need to be extended 

If you cannot do this maybe an alternate way to assign dependencies, maybe a multi select drop down.

**Comment by IDCs** [comment]
Hi there @ondrovic, thank you for your feature request. Unfortunately the requirements are not exposed by the Nexus API itself and Vortex has no way to know what the dependencies actually are when a mod installs (unless it's part of a collection)

As you probably know Vortex is being phased out in favour of NMA, it would be far more likely for the data to be exposed if the NMA team chases this requirement, please submit your request on their issue tracker https://github.com/Nexus-Mods/NexusMods.App/issues

I agree that the deploy order dependency system is less than ideal, but I'm not sure if a multi select drop down in the mods panel is the way to go; this feels like it should be its own component. I'll have a think and see what I can come up with.

Going to close this issue in favour of #16426 which asks for an alternative method to manage dependencies.
