### ISSUE TITLE
Review: EmuVR WIGUx Extension

### ISSUE THREAD

**Issue by squishylemon** [Nexus-Mods/Vortex#16364]
### Nexus Username

Squishylemon007

### Extension URL

https://www.nexusmods.com/site/mods/1031

### Game URL

https://www.nexusmods.com/emuvr

### New features

Installs mods to the root folder of the game, and supports all kinds of mods for emuvr

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hey there @squishylemon,

Was just about to start reviewing your extension but noticed that you've hidden it yourself with the following information:

"This mod is currently not supported by the author(s) and/or has issue(s) they are unable to fix yet."

Can you explain the problems you're faced with so I can try to help?

**Comment by squishylemon** [comment]
It was hidden because we did not want to release it until we were verified so then it could have all the functionality on release, The extension works and was quickly tested myself to make sure it installed mods correctly, and Vortex was installing the extension correctly, etc If i need to unhide it, thats 100% ok and can do that (I'll unhide it now as im a little late to respond to stuff, my apologies)

**Comment by squishylemon** [comment]
@IDCs No that was not intentional I'll fix that now, Thanks for pointing that out!

**Comment by squishylemon** [comment]
@IDCs  Just uploaded and removed some unnecessary tools

**Comment by IDCs** [comment]
Done, thank you for your contribution!
