### ISSUE TITLE
[Bug] Unknown opcode

### ISSUE THREAD

**Issue by ondrovic** [Nexus-Mods/Vortex#16362]
**Describe the bug**
When deploying getting a series or Unknown opcode's

**To Reproduce**
Typically it happens the deployment window is triggered, other than that not sure I know how to reproduce it

**Expected behavior**
[DEPLOY] Stage 2/5 - Script Compilation
Unknown opcode: SyntaxFloatConst
Unknown opcode: SyntaxArrayPopBack
Unknown opcode: SyntaxArrayPopBack
Unknown opcode: SyntaxConstructor
Unknown opcode: SyntaxBoolConst
Unknown opcode: SyntaxBoolConst

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 11
 - Vortex Version 1.12.3

**Additional context**
Was when I was uninstalling mods

```log
[DEPLOY] Stage 1/5 - Initialization
Mod "1 - OpenNC All-in-One" is enabled, but not found on the disk!
Mod "UnlockMeTheMods" is enabled, but not found on the disk!
Mod "Weapon Loadouts" is enabled, but not found on the disk!
Found mod "PS Button Prompts" (v1.0+V2077RED) in folder "PS Button Prompts" (enabled; deployed (v1.0+V2077RED); )
Found mod "<deleted>" (v) in folder "1 - OpenNC All-in-One" (disabled; deployed (v0.8+V2077RED); )
Found mod "<deleted>" (v) in folder "UnlockMeTheMods" (disabled; deployed (v2.1); )
Found mod "<deleted>" (v) in folder "Weapon Loadouts" (disabled; deployed (v2.1+V2077RED); )
Needs deployment: true (FORCE)
[DEPLOY] Stage 2/5 - Script Compilation
Unknown opcode: SyntaxFloatConst
Unknown opcode: SyntaxArrayPopBack
Unknown opcode: SyntaxArrayPopBack
Unknown opcode: SyntaxConstructor
Unknown opcode: SyntaxBoolConst
Unknown opcode: SyntaxBoolConst
```

**Comment by IDCs** [comment]
Hi there @ondrovic - I'm not sure what I'm looking at there, as it doesn't match any of Vortex's logging functionality.

I'm assuming this was triggered by the Cyberpunk game extension, which is developed by the community.

Please report this to the game extension developers on their page on Nexus Mods.
