### ISSUE TITLE
Can't manage file conflicts after mods have been installed

### ISSUE THREAD

**Issue by SeriousConcept1134** [Nexus-Mods/Vortex#16386]
**Describe the bug**
When attempting to resolve a file conflict between mods after they've been fully installed (i.e. not during the installation process), you are only able to select a different option in the drop-down menu (next to the file name in question) for the **first two files** at the top of the list.

Attempting to change options for any files below the first two does nothing (they remain stuck on their original option), but more than that, interacting with their drop-down menus actually affects the options in the first two files instead.

So I can attempt to select a different option for the 3rd, 7th, or 10th file in the list, but instead of affecting those files, their drop-downs affect the options in file 1 and 2 instead, while their own options remain unchanged (incorrect mapping of the drop-down menus?).

**To Reproduce**
1. Go to any mod which has more than two file conflicts
2. Right click on it and select "Manage File Conflicts"
3. Try to use the drop-down menus to change to a different option for any files below the 1st and 2nd ones

**Expected behavior**
You expect the drop-down menu next to each file to change the option for that file.

**Screenshots**
Not applicable.

**Platform:**
 - OS: Windows 11
 - Vortex Version 1.12.3

**Additional context**
Downgrading to Vortex 1.11.3 completely resolved this issue. So this bug was introduced at some point after this version.
Also I'm using Vortex exclusively for Skyrim modding (if that's relevant).

**Comment by ChemGuy1611** [comment]
Can you include a screenshot? Do you have the little lock icon on any of the mods in the conflict manager?

**Comment by SeriousConcept1134** [comment]
> Can you include a screenshot?
I'm not really sure what a screenshot would show in this scenario? You'll literally just see the file conflict dialogue.
If I have time I'll try to make a video of the issue and post it here.

> Do you have the little lock icon on any of the mods in the conflict manager?
No, there's no lock, and the problem is the same no matter what mod you try it with.

Also please don't forget that downgrading to an earlier version of Vortex fixed the issue (1.11.3 in my case).

There have also been reports about this issue from other users on Reddit and Nexus forums, I am not the first person to experience this. I just figured I would be the first one to file a bug report on this.

**Comment by ChemGuy1611** [comment]
Screenshots are very helpful. I think I understand what you are trying to say, despite confusing wording. I have seen similar reports.

**Comment by SeriousConcept1134** [comment]
> Screenshots are very helpful. 

Usually they are, just not in this case in particular :)

> I think I understand what you are trying to say, despite confusing wording.

Just out of curiosity, which wording did you find confusing? (English is not my first language)

>  I have seen similar reports.

Can you not reproduce the issue on your end?

**Comment by ChemGuy1611** [comment]
I cannot reproduce this error. My conflict manager works fine for more than 2 mods. The dropdowns on the other mods do not change the first two options. 

Have you tried reinstalling the affected mods? I have heard others say it can fix issues with conflict manager.

**Comment by IDCs** [comment]
Thanks @morhe for helping debug this issue.
