### ISSUE TITLE
7 Days To Die Errors when path to UserDataFolder contains whitespace

### ISSUE THREAD

**Issue by naspdep** [Nexus-Mods/Vortex#16445]
**Describe the bug**
Upon managing 7 Days To Die with Vortex, the game either failed to load, or loaded with several NullReferenceExceptions. When reading the log files, it seems that instead of trying to load files from:

C:\Users\Firstname Lastname\AppData\Roaming\7DaysToDie\

it instead tried to load them from 

C:\Users\Firstname\

This can be manually fixed by editing the launchersettings.json file. The line 

"AdditionalParameters" : "-UserDataFolder=C:\\Users\\Firstname Lastname\\AppData\\Roaming\\7DaysToDie"

has to be changed to

"AdditionalParameters" : "-UserDataFolder=\"C:\\Users\\Firstname Lastname\\AppData\\Roaming\\7DaysToDie\""

**To Reproduce**
1. Use a path with a whitespace for the UserDataFolder.
2. Start managing the game with Vortex
3. Try to launch the game

**Screenshots**
![Screenshot 2024-09-17 213231](https://github.com/user-attachments/assets/5fc5d6c5-de20-47e1-95cd-858ff0fa2977)
![251570_5](https://github.com/user-attachments/assets/f6c42c89-f7c1-488d-a448-79dc59c2e48d)
![Screenshot 2024-09-17 214228](https://github.com/user-attachments/assets/a06cfc91-108c-4d30-85e2-ef84739ee467)
![Screenshot 2024-09-17 214925](https://github.com/user-attachments/assets/da0d9988-a52b-407d-a336-43a3deabb105)

**Platform (please complete the following information):**
 - Windows 11
 - Vortex Version: 1.12.4
 - Game Version: V1.0 (b336)
 - Steam Version: 1726256783

**Comment by Senjay-id** [comment]
@naspdep Unfortunately I'm not the extension developer for 7d2d so we'll need to wait till a vortex dev merge it.
