### ISSUE TITLE
Vortex Doesn't Respect/User System Certificates

### ISSUE THREAD

**Issue by MeCJay12** [Nexus-Mods/Vortex#16506]
**Describe the bug**
My computer is on a managed network. The network does SSL decryption. They distribute a CA certificate that I install on my computer. In my browser SSL works fine I just see the installed certificate as the issuer instead of a normal public CA. Vortex seems to not respect/check the system certificate store so Vortex is failing to connect to anything. I was able to find and submit the URLs *.nexusmods.com and *.nexus-cdn.com. Now, downloads sit in the queue and don't actually download.

**To Reproduce**
1. Enable SSL decryption on the network
2. Install the self-signed CA on the computer
3. Try to use Vortex

**Expected behavior**
Vortex should function normally while trusting manually install CA certificatess.

**Screenshots**
![Downloads stuck with URL exceptions](https://github.com/user-attachments/assets/33135832-0ea6-4de8-bf35-9b5b576ac679)
![SSL errors](https://github.com/user-attachments/assets/56c00c96-1249-46d5-847b-bcc2f5ea5c18)

**Platform (please complete the following information):**
 - OS: Windows 11 Pro 23H2
 - Vortex Version 1.12.5

**Comment by MeCJay12** [comment]
Completely understand not wanting to allow unwilling MITM. Even with on my network, I don't want unwilling MITM. The idea of the system certificate store is that the user/admin can specify CAs to trust and distrust so respecting it would solve this. Simply disabling SSL cert checking is a bit brute force.

**Comment by IDCs** [comment]
Unfortunately the trusted CAs are hardcoded in Node, overriding that in the app would open the app to potentially malicious certificates the user had no idea were on his machine in the first place. I'm also apprehensive of allowing the user to choose a certificate file through Vortex as many users are not savvy enough to make that choice in the first place.

Node does allow users to add extra CA certificates manually through environment variables and/or CLI parameters.

CLI properties and usage instructions can be found here:
`https://nodejs.org/api/cli.html#--use-bundled-ca---use-openssl-ca`

Alternatively you can tell Node where to find the certificate using the below environment variable. Although in my experience this one is a bit finicky.
`NODE_EXTRA_CA_CERTS=file`

**Comment by MeCJay12** [comment]
Yup, that's perfect. Thanks!
