### ISSUE TITLE
Bug Report - Other: Cannot find Cyberounk in unmanaged games (2)

### ISSUE THREAD

**Issue by Korb** [Nexus-Mods/Vortex#16538]
**Describe the bug**
The game Cyberpunk 2077 cannot be found to add to Managed and set modes.

**To Reproduce**
1. Go to `Games` tab
2. Enter `Cyberpunk` or `2077` in `Search for a game...` field
4. See no games and "Can't find the game you're looking for? Your game may not be supported yet but adding it yourself may be easier than you think. Click to learn how!" message.

**Expected behavior**
The game should be displayed in the `Unmanaged (81)` section, and can be added to the Managed section.

**Screenshots**
![2024-10-08_11-10-51](https://github.com/user-attachments/assets/af34ae34-6b06-484f-b08c-7516af2c7459)

**Platform (please complete the following information):**
 - OS: Microsoft Windows 10.0.19045.4957
 - Vortex 1.12.6 (10/3/2024)

**Additional context**
[Diagnostics File](https://drive.google.com/file/d/18JyucxNod5HQz1GcaJRcm55MUUnsC1ua/view)
~  #13537, #11851, #13504

**Comment by IDCs** [comment]
Hi there - this is down to your connectivity to Github, the reasons behind this issue vary; whether it's a self signed SSL certificate on your machine, router configuration, Anti-Virus software intercepting packets and modifying them, your system admin restricting access through security policies, or just your ISP blocking certain domains.

```
{"errno":-4039,"code":"ETIMEDOUT","syscall":"connect","address":"2606:50c0:8003::154","port":443}
2024-10-08T08:08:16.656Z - error: failed to download extension list 
```

Regardless - this is an issue with your environment, not something we can fix.

**Comment by IDCs** [comment]
@Korb can you attach a screenshot of your browser window when running https://test-ipv6.com/

**Comment by Korb** [comment]
@IDCs, you were right. The problem is on my end.

![2024-10-09_10-27-42](https://github.com/user-attachments/assets/74baa529-0497-4728-ab77-0720fab25583)

The VPN that I almost always have on does not support IPv6, unlike my ISP, router and PC settings. Disabling the VPN allowed the app to download the necessary files, and the game began to appear in the Unmanaged category, and it became possible to add it to Managed. Thanks for your help!
