### ISSUE TITLE
Review: Sifu (New Version)

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16578]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/1063/

### Game URL

https://www.nexusmods.com/sifu

### Existing Extension URL

https://www.nexusmods.com/site/mods/350

### New features

This extension adds Xbox game version support, along with the standard suite of installers I've been including in all UE games (root game folder, save, config, UE4SS, Scripts, LogicMods).

I did attempt to contact Tannin42 about the existing extension but did not receive a response. 

Side note: The extension linked below is not functional and was a direct copy of the existing Tannin42 Sifu extension. It should be removed. 
https://www.nexusmods.com/site/mods/1005

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Hey @ChemGuy1611, although it's great that you added your UE installers/modTypes/etc.

Looking at the mods themselves, they all appear to follow the classic `~mods` pattern and am therefore ensure if those enhancements were required in the first place.

Ultimately your game extension adds discovery support for the xbox version right? The game pass version can still be managed using the current extension by manually selecting the location of the game.

I think it would be safest to just add the xbox id to the existing extension rather than change the entire codebase when such a minor change is required.

Please let me know if I'm missing something such as the old extension not working anymore etc.

**Comment by ChemGuy1611** [comment]
The existing Extension does not support the Xbox version. Xbox uses different executables and executable folders. That's the main thing with this updated extension. An entirely different structure has to be used to accommodate Xbox version and other versions simultaneously. 

That's the reason why that other (flawed) "WinGDK" extension was made. Except that guy just replaced the executable name without making any other changes, breaking support for Steam/Epic versions and without automatic discovery or being able to launch the game for Xbox

**Comment by IDCs** [comment]
Given that `gamelaunchhelper.exe` can potentially block access during game discovery - I argue that this game extension could potentially not detect game pass versions either. I'm sorry but I'm going to close this. Any future enhancements to the Sifu extension should be done in the existing extension.

If the old author is not interested in maintaining it - he should pass on the page to other interested parties. @ChemGuy1611 you'd have to discuss this with Tannin and or the community team.
