### ISSUE TITLE
Making the "Installation corrupted" error message more useful

### ISSUE THREAD

**Issue by yakau** [Nexus-Mods/Vortex#16591]
The current "Installation corrupted" error message lacks useful information and suggests only a blanket approach (reinstall Vortex) that sometimes fails to fix the error. Following that with a more targetted and specific error message will help users diagnose and repair their Vortex installations.

![Screenshot 2024-10-17 073203](https://github.com/user-attachments/assets/7bea344c-cf55-434d-9cc4-8d746348469d)

1. Add "Quit and check vortex.log for more details" would be a helpful instruction.
2. Even better, add a scrollable text box with the file validation results that are outputted to vortex.log. eg.

```
2024-10-16T23:31:26.796Z [INFO] done file validation 
2024-10-16T23:31:26.796Z [INFO] Files were manipulated {"missing":["resources\\app.asar.unpacked\\bundledPlugins\\game-rimworld\\gameart.jpg","resources\\app.asar.unpacked\\bundledPlugins\\game-rimworld\\index.js","resources\\app.asar.unpacked\\bundledPlugins\\game-rimworld\\info.json"],"changed":[]}
```

See this post for an example of the "Installation corrupted" vortex.log output: https://forums.nexusmods.com/topic/13481082-your-vortex-installation-has-been-corrupted-this-could-be-the-result-of-a-virus-or-manual-manipulation-vortex-might-still-appear-to-work-partially-but-we-suggest-you-reinstall-it/?do=findComment&comment=130472710

I see Reddit and Nexus posts by users with the "Installation corrupted" error, even after reinstall.

Displaying what and why validation failed can only help users prevent repeated corruptions and even some unnecessary reinstallations.

**Comment by IDCs** [comment]
I'm afraid we do not have much control over the Windows API error dialogs; but I did edit the message to refer affected users to the log file.

Thank you for your report!
