### ISSUE TITLE
Review: Dragon Age The Veilguard

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16621]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/1075

### Game URL

https://www.nexusmods.com/dragonagetheveilguard

### Existing Extension URL

NONE

### New features

This includes support for Frosty Mod Manager. I have not yet enabled automatic download for Frosty since I am not sure if it will work out of the box without an update. All the structure is in place to support Frosty Mod Manager and installing mods with it. 

### Information

- [X] I confirm the above is accurate

### Packaging

- [X] This extension is packaged correctly

### Testing

- [X] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by adastmin1** [comment]
https://skrinshoter.ru/sSVURiU0m0V

https://skrinshoter.ru/sSVx9ETzmO5

But our hands are not hooks.

**Comment by IDCs** [comment]
@ChemGuy1611 - looks like @adastmin1 encountered issues with your extension and am therefore blocking it while you get a chance to fix it.

**Comment by ChemGuy1611** [comment]
I have no idea what are in his links. I did not click them.

**Comment by IDCs** [comment]
Thank you for your contribution.
