### ISSUE TITLE
Visibility into loose file rules

### ISSUE THREAD

**Issue by hakasapl** [Nexus-Mods/Vortex#16671]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I am developing an [application for Skyrim](https://github.com/hakasapl/ParallaxGen) which would benefit from knowing about the loose file rules in vortex. I can already get data for which files belong to which mods from the vortex deployment file, but it would be great to have a similar way to know whether one mod is set to load after another mod.

**Describe alternatives you've considered**
For now I have a system where the user can specify their priority in my application, but it ends up being extra work for the user, so it would be great to have visibility into this in Vortex.

**Additional context**
N/A

**Comment by IDCs** [comment]
Hey @hakasapl, I'm afraid the conflict detection for loose files runs on a per session basis so you won't be able to extract that information. But you can still extract the details of which mod depends on which using the persistent state if that helps.

You'll have to go to your settings page -> workarounds tab -> create state backup button.

**Comment by hakasapl** [comment]
@IDCs thanks for your response.

Ideally I wouldn't have to ask the user to export anything specifically for this app. If there is no other way for external apps to know about which mods depends/loads after which I will continue with my workaround.

I was hoping that info could be added to the deployment file or saved elsewhere in some parseable plain text.

**Comment by IDCs** [comment]
Adding more information to the deployment file at this stage of development might be troublesome and may affect performance.

You _could_  use the state backups that are done hourly and/or on startup. They're located inside ```
%appdata%\vortex\temp\state_backups_full\
```.

Alternatively you could always use Vortex's CLI paraneters directly (but it has to be closed) ```./vortex.exe --get persistent.mods.skyrim```

**Comment by hakasapl** [comment]
Got it, thanks. I will look into both
