### ISSUE TITLE
Review: S.T.A.L.K.E.R. 2: Heart of Chornobyl

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16682]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/958

### Game URL

https://www.nexusmods.com/stalker2heartofchornobyl

### Existing Extension URL

NONE

### New features

Mostly standard UE5 game with Game Pass version support.

### Information

- [x] I confirm the above is accurate

### Packaging

- [x] This extension is packaged correctly

### Testing

- [x] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
So after spending some time I realized it's not the `statSync` that is causing the issue - it's the requiredFiles constant array which is not extensible for some odd reason. Rather than investigate further (Time is not on my side today) I put in the following changes to your code to get it running on GamePass, stop the spam, and avoiding immutable objects saved the day:
```
const isCorrectExec = (exec) => {
    if (!discoveryPath || !exec) {
      return false;
    }
    try {
      fs.statSync(path.join(discoveryPath, exec));
      // requiredFiles.push(exec);
      return true;
    }
    catch (err) {
      return false;
    }
  };
```

**Comment by ChemGuy1611** [comment]
> Hi [@ChemGuy1611](https://github.com/ChemGuy1611)
> 
> ![Image](https://github.com/user-attachments/assets/a056cbd4-4967-4bd1-9df4-a302e54784f3)
> 
> The 'Open Game Mods Folder' goes to the wrong folder. I think it ideally should go `\Stalker2\Content\Paks` and it's currently going to `\Stalker2\Binaries\Win64\Mods`

The default mod folder is the Binaries folder. All other mod types (like pak mods) go through and installer. The Binaries folder is the fallback location if no other installers are triggered. 

Is there a way to change where that button goes?

**Comment by ChemGuy1611** [comment]
> So after spending some time I realized it's not the `statSync` that is causing the issue - it's the requiredFiles constant array which is not extensible for some odd reason. Rather than investigate further (Time is not on my side today) I put in the following changes to your code to get it running on GamePass, stop the spam, and avoiding immutable objects saved the day:
> 
> ```
> const isCorrectExec = (exec) => {
>     if (!discoveryPath || !exec) {
>       return false;
>     }
>     try {
>       fs.statSync(path.join(discoveryPath, exec));
>       // requiredFiles.push(exec);
>       return true;
>     }
>     catch (err) {
>       return false;
>     }
>   };
> ```

I suppose it is not entirely necessary to push the executable to the required files array. I know that this code has worked in previous extensions, but if it helps avoid the error loop if Game Pass has the folder locked down, that's fine.

**Comment by ChemGuy1611** [comment]
Extension is updated to remove the requiredFiles push of the executable.

**Comment by insomnious** [comment]
> The default mod folder is the Binaries folder. All other mod types (like pak mods) go through an installer. The Binaries folder is the fallback location if no other installers are triggered.
> 
> Is there a way to change where that button goes?

Ah ok, that's fine then. I'll get this tested now and merged in.
