### ISSUE TITLE
Review: Liar's Bar

### ISSUE THREAD

**Issue by tyzeron** [Nexus-Mods/Vortex#16755]
### Nexus Username

Tyzeron

### Extension URL

https://www.nexusmods.com/site/mods/1084

### Game URL

https://www.nexusmods.com/liarsbar

### New features

This is the first Vortex extension fort he Steam game [Liar's Bar](https://store.steampowered.com/app/3097560/Liars_Bar/) and there are no existing extension for that game yet.

This Vortex extension:
- Add support to the game [Liar's Bar](https://store.steampowered.com/app/3097560/Liars_Bar/)
- Automatically fetches the required `BepInEx 5.4.23.2 (x64)` from the [official BepInEx GitHub](https://github.com/bepinex/bepinex).

Also, created a GitHub repository for anyone to fork and contribute: https://github.com/tyzeron/LiarsBar-Vortex-Extension

Finally, special thanks for _Nagev_ for the help in resolving the issue with fetching BepInEx from GitHub.

### Information

- [x] I confirm the above is accurate

### Packaging

- [x] This extension is packaged correctly

### Testing

- [x] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Thank you for your contribution!
