### ISSUE TITLE
Review: Stalker 2: Shadow of Chernobyl

### ISSUE THREAD

**Issue by DrDopeNasty** [Nexus-Mods/Vortex#16770]
### Nexus Username

DrDopeNasty

### Extension URL

https://www.nexusmods.com/site/mods/1118/

### Game URL

https://www.nexusmods.com/stalker2heartofchornobyl?tab=popular+%28all+time%29

### Information

- [x] I confirm the above is accurate

### Packaging

- [x] This extension is packaged correctly

### Testing

- [x] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by ChemGuy1611** [comment]
There is already a working STALKER 2 extension.

**Comment by IDCs** [comment]
Hi there - @DrDopeNasty, first of all thank you for your contribution. As @ChemGuy1611 stated, there is a functioning community extension for STALKER 2, rather than re-invent the wheel - get in touch with ChemGuy if the existing extension has any flaws or missing modding requirements.

Blocking/Closing as adding another extension for STALKER will end up confusing users.

**Comment by DrDopeNasty** [comment]
oh yeah i didnt see that there was an existing one until after i had posted it, i made it closer to when the game came out and promptly forgot about it lol. also it was kind of a first project in java for me so im not surprised it was cheeks. got me back into coding though so i cant complain :P
