### ISSUE TITLE
DD/MM/YYYY format in English

### ISSUE THREAD

**Issue by AeliusRuivus** [Nexus-Mods/Vortex#16821]
Hi there, I know this is a minor issue, but I can't configure Vortex to use dd/mm/yyyy if I set the language to English, and there's no option for EN-US or EN-UK.
Would it be possible to either follow the system language setting, or to offer a custom date format configuration?

**Comment by IDCs** [comment]
Hi @AeliusRuivus - as you said there's currently no EN-UK translation extension which is somewhat funny given that we're a UK based company. Either way I'm afraid that Vortex is being phased out in favour of the "Nexus Mods App".

Adding a new UK translation at this point is a bit out of scope for us. But will make sure that the NMA team is aware of this requirement.
