### ISSUE TITLE
Review: Indiana Jones and the Great Circle

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/Vortex#16862]
### Nexus Username

ChemBoy1

### Extension URL

https://www.nexusmods.com/site/mods/1123

### Game URL

https://www.nexusmods.com/indianajonesandthegreatcircle

### Existing Extension URL

NONE

### New features

Basic extension with installers for configs, saves, and sound files. All other mods install to the game root folder at this time.

I have kept in the structure to support a future mod loader, similar to my Doom Eternal extension, if the community creates one.

I will add additional mod installers as new mod types emerge. 

### Information

- [x] I confirm the above is accurate

### Packaging

- [x] This extension is packaged correctly

### Testing

- [x] This game extension has been tested
### Review Tasks

If a task fails, contact the author to request changes before continuing.

- [ ] Double-check for existing extension
- [ ] Is the extension [packaged correctly](https://github.com/Nexus-Mods/Vortex/wiki/How-to-package-a-game-extension)?
- [ ] Does it install into Vortex?
- [ ] Does it correctly discover the game?
- [ ] Does it successfully install a mod?
- [ ] Does it successfully install a collection?
- [ ] Does the game run correctly with the mods installed? ​

When reviewed and passed, please complete the following tasks:

- [ ] Run the GitHub Actions to add to manifest
- [ ] Contact author
- [ ] Ask Community to enable the Vortex button for the game
- [ ] Update the #vortex-announcements channel on Discord

**Comment by IDCs** [comment]
Thank you for your contribution
