### ISSUE TITLE
(Feature) filter plugins from mod installations

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Vortex#1772]
Link pointing to topic on nexus forums with full details of the feature request:
https://forums.nexusmods.com/index.php?/topic/7098606-feature-filter-plugins-from-mod-installations/

**Comment by TanninOne** [comment]
Copied from the referenced post:

--- Description ---

The ability to filter plugin files from installing into the game directory

 

--- Why it should be added ---

Some mods come with optional plugins that come with the main download this would also be useful in the case a particular plugin is obsolete in your set up. An example of this would be the unofficial oblivion patch that comes with an UOP Vampire Aging & Face Fix.esp which is if your using the equivalent tweak in the bashed patch for oblivion it completely makes the UOP Vampire Aging & Face Fix.esp completely redundant and not needed.

 

Taken from the advanced readme for wrye bash that can be found here: https://wrye-bash.github.io/docs/Wrye%20Bash%20Advanced%20Readme.html#patch-tweaks

![post-28621425-0-67167500-1540472678](https://user-images.githubusercontent.com/8525754/56716266-29e2bc00-673a-11e9-8bfa-642d6a95978e.png)


--- How it would work ---

1) It would work similar to the feature already present in wrye bash (esp/m filter) and mod organizer (optional plugins)

 

Note: I'm aware that you can simply delete the files you don't need as such this feature request is more oriented towards less experienced users.

**Comment by Greg-Nexus** [comment]
Added to Product Backlog: https://gitlab.nexdev.uk/vortex/vortex/-/issues/173

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
