### ISSUE TITLE
(Feature) automatic importing of external changes on a per file or mod basis

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Vortex#1773]
Link pointing to topic on nexus forums with full details of the feature request: https://forums.nexusmods.com/index.php?/topic/7098581-feature-automatic-importing-of-external-changes-on-a-per-file-or-mod-basis/

**Comment by TanninOne** [comment]
Copied from referenced thread:

--- Description ---

The ability to automatically import any external changes made to an individual file(s) or a mod as a whole.

 

--- Why it should be added ---

Some mods such as perkus maximus and skyrim redone come with a dynamic patch file that gets automatically modified everytime you rerun the patcher, this feature would be a qol improvement as the user would not have to import the changes every time as there would most likely never be an instance where you would want to revert the change to the dynamic patch file.

 

--- How it would work ---

1) The user marks a mod as automatically importing external changes by opening a context menu, button, etc that opens a list of files that came with the mod and allows the user to pick which specific file(s) they would like to automatically import external change for as well as mark the entire mod as a whole importing all changes to all files.

 

2) There should be an icon on the mod or something so the user can see at a glance what mods have had a file(s) or which mods as a whole have been assigned this behavior.

**Comment by Greg-Nexus** [comment]
Added to Product Backlog: https://gitlab.nexdev.uk/vortex/vortex/-/issues/174

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
