### ISSUE TITLE
(Feature) Monitor External Installations

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Vortex#1774]
Link pointing to topic on nexus forums with full details of the feature request: 
https://forums.nexusmods.com/index.php?/topic/7098551-feature-monitor-external-installations/

**Comment by TanninOne** [comment]
Copied from the referenced thread:
 

--- Description ---

The ability for the user to toggle a watcher for the data folder for all elder scrolls and fallout games that will take note of all new files and directories that were added to the data folder, upon disabling the watcher, present the user with the option to create a new mod out of those newly created files and directories or merge them into an existing mod.

 

This feature would be very similar to the feature already present in wrye bash except it would also have the ability to merge into an existing mod (picture taken from the advanced wrye bash readme):

 
![post-28621425-0-76680900-1540470682](https://user-images.githubusercontent.com/8525754/56716406-95c52480-673a-11e9-84e8-db38a78c1ea4.png)


 

--- Why it should be added ---

 

It would allow mod users do stuff like use oblivion mod manager to install mods with omods have vortex make a new mod out of the installed mod from oblivion mod manager and then delete it from oblivion essentially importing mods from other managers that support formats vortex does not. Another really big use from this would be for mod authors to keep there workspace cleaner by allowing the manager to manage all there assets so say a mod author is making a mod with tons of loose files and has multiple mods like this they could just deploy it to the directory and remove everything else that they don't need and vice verse when they want to play the game or work on another mod.

 

--- How it would work ---

 

1) The user toggles something to enable watching the data directory

 

2) The user does there thing (either mod making or using another manager like obmm, etc)

 

3) The users untoggles the feature and vortex makes note of all the newly added files and directories in the data directory and prompts the user on whether they would like to create a new mod out of those new files and directories or merge them into an existing mod.

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
