### ISSUE TITLE
[0.16.10] Defining dependencies triggers "Deployment necessary" message.

### ISSUE THREAD

**Issue by Anvirol** [Nexus-Mods/Vortex#1906]
After 0.16.10 this message started appearing, which is quite annoying. When doing a lot of mod installs, you'll have to press this button dozens of times. 

It's usually triggered whenever I define a rule for dependencies or conflicts, but I've seen in occur just by enabling or uninstalling mods.

![image](https://user-images.githubusercontent.com/3955313/47701899-01af5000-dc24-11e8-98db-70c43b8da3f4.png)

**Comment by TanninOne** [comment]
To make rule changes apply you need to deploy. That doesn't mean you need to deploy immediately, you can finish all your rules and _then_ hit the button, that's why we don't start the deployment automatically.
