### ISSUE TITLE
[TRANSLATION][FEATURE REQUEST]QoL improvements to extension-translate

### ISSUE THREAD

**Issue by Rummskartoffel** [Nexus-Mods/Vortex#1912]
There are currently some minor issues with extension-translate:

- As of now, extension-translate does not yet differentiate between "normal" string and names. This causes it to add game and mod names to _locales/_ language _/common.json_, which is unnecessary and clutters the file. This is minor, as a translator can just ignore those strings, but it should be fixed when Vortex is nearing non-Beta release in order to make work easier for translators and keep file size only as big as necessary.

- Currently, when a string is changed in the English version and needs to be translated again, the old version stays in _common.json_. In order to help translators in removing those, extension-translate could at some point use a feature capable of finding such strings.

- [Some strings](https://pastebin.com/xWYfuKqS) are missing variables, causing them to be added multiple times if a "dynamic" part of them changes.

As I said, these issues are not major by any means, but they should eventually be addressed before release.

Btw.: thanks for the extension, it already helps a lot with translation!

**Comment by dertrutinator** [comment]
Adding some more things:

- [Deployment progress messages](https://pastebin.com/1PCZWZfs) are also added without variables

- [this strange string](https://pastebin.com/FCGhqjXg), which _might_ possibly be that red "conflict" lightning bolt somehow wandering into text

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development. We're already building translation support into the Nexus Mods App. 

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
