### ISSUE TITLE
Can't see skse64

### ISSUE THREAD

**Issue by Dragonbornforger** [Nexus-Mods/Vortex#1951]
V won't recognize  skyse64.  I have installed skse64.  When I browse on my c drive from select games in V,  the skse64 isn't there and V says the game doesn't appear to be there.  When I look in properties from in Steam "my games/sse64",  the skse64 is there. 
I tried the alpha in Sept and couldn't get it to work.  I tried the beta yesterday.  It seemed to install and recognize nexus ok.  I tried to import from nmm.  It didn't install the three down loadable Skyrim games.  Didn't recognize  the .estm.  It got lost or I did.  I had to uninstall both V and chrome.  After a reinstall of both It seems to be working except it can't manage skse64. You may have figured out I  don't understand much of haw things work.  However, I have been using nmm for several years without any trouble I couldn't fix.  Not having much luck with v.

**Comment by Dragonbornforger** [comment]
Looks like v will be good.  Keep working

**Comment by TanninOne** [comment]
Sorry but we can't work with this report, we need details like actual error messages being reported instead of "it can't manage" and "didn't recognize".
