### ISSUE TITLE
Make "manage groups" window bigger. 

### ISSUE THREAD

**Issue by Anvirol** [Nexus-Mods/Vortex#2072]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when managing plugin groups because the editor is only a small window within the app.

**Describe the solution you'd like**
Allow us to maximize "Manage Groups" window

**Describe alternatives you've considered**
Or just open a new window that is resizable.

**Additional context**
Currently it's like this and not very usable. 
![image](https://user-images.githubusercontent.com/3955313/48104127-c8399e80-e23a-11e8-9807-159be620ee07.png)

**Comment by TanninOne** [comment]
The group system isn't designed to quadruple the number of groups, what't the point of that?
We can make the dialog bigger but then you assign each of your 300 plugins it's own group and it's still too small.
The dialog is a reasonable size for a reasonable number of groups and you can zoom and pan if you have more.
