### ISSUE TITLE
Vortex corrupted my internal hard drive

### ISSUE THREAD

**Issue by danthemanss** [Nexus-Mods/Vortex#2223]
**Describe the bug**
After installing a plethora of mods My internal 4tb hard drive stopped responding.

**To Reproduce**
1. install a lot of mods on internal hardrive

 - OS: [e.g. Windows 7]
 - Vortex Version newest

**Comment by TanninOne** [comment]
Sorry for your hard drive but of course user space applications can't damage hardware.

**Comment by danthemanss** [comment]
I'm at a loss, its a fairly new hard drive my only thought could be the
amount of drive space I took up in such a short amount of time downloading
mods through vortex. Once i had installed almost all of them the app locked
up indefinitely while "deploying mods" it was late so i left it doing that
because I assumed the amount of mods was making it take a while. In the
morning vortex had a ton of errors with mods that previously installed
without issue. it took some investigating but i eventually realized the
errors where stemming from the drive suddenly not being there. I'm a fairly
novice at a lot of this modding stuff but I'm hoping you can give me a clue
of what I did wrong?

**Comment by TanninOne** [comment]
It's a hardware defect, it happens. That's why you have warranty on new disks.
