### ISSUE TITLE
Download capped at 70KB/S at best

### ISSUE THREAD

**Issue by 2Lomi** [Nexus-Mods/Vortex#2232]
Hello.
Unless the 1MB/s is actually 1Mb/s, then I'd like to understand why I can't go past 70KB/s when downloading any mods on Vortex.
There's a huge difference between taking 30 minutes  and 4 hours for a mod :(

It's weird considering yesterday downloading speed.
I've not checked the speed of download, but I dont remember taking 3 hours for a 400MB mod.
Is it possible your server can't handle everyone's download during day ? Or is there a setting I missed ?

Thanks.

*Im very thankful for all the work you've put into modding communities, sorry if I sound too harsh. English is not my main language*

Edit : Well, I believe that Vortex stop downloading anything anytime it actually start downloading is the problem (see the screen) https://imgur.com/a/LlQtxmv

**Comment by IDCs** [comment]
Hi @2Lomi thanks for your report, something is indeed off there - could you please have a read through 
https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do and let us know the folowing:

Which country are you in? 
What is your IP address? 
What results do you get when you ping files.nexus-cdn.com?

**Comment by 2Lomi** [comment]
Im in France
176.169.202.195 (I don't like giving away my IP so I might change it in a few days)

The ping results are fine. https://imgur.com/a/Juu0sYp
Though, it seems the "bug" has stopped now ? I download at full speed again. Even during day.

I remember switching from my normal Wifi to 4G to download faster. I may have closed Vortex during the switch and it might have been bad for it ?

To put back the event in order that would be :

- Downloading mods on net1
- Adding 20 mods to queue
- 1h later, turn off computer
- Later, Boot up the computer (default net is net2)
- Launch Vortex
- Start downloading but on net2 instead of net1 since default on boot up was net 2


I might add that closing vortex when mods have not started downloading them, pop up an error that tells you Vortex can't download it since "This download is missiong info necessary to resume" but I should make another issue for that...
(When I say "not started downloading" I mean when the file size is still "???")

**Comment by IDCs** [comment]
Hi @2Lomi, glad to hear that your download speed got sorted - the web team has confirmed that our Paris server was particularly bad yesterday but has been fixed (reason why you're getting normal speeds again)
