### ISSUE TITLE
Changing the location of downloaded mods archives

### ISSUE THREAD

**Issue by 2Lomi** [Nexus-Mods/Vortex#2234]
The "Mod staging folder" in Vortex settings does nothing when it comes to downloaded archives.

- Set a custom folder in "Settings > Mods > Mod Staging folder"
- Download a mod
- Vortex will download it in %appdata%

I tried unistall and reinstall Vortex.

Screens : https://imgur.com/a/jRDhWFs (See that 'VortexMods' folder is empty)

Done under Win10

**Comment by IDCs** [comment]
Hi @2Lomi, the mod staging folder which is set under the Mods Settings tab refers to the mods themselves and not their downloads.

To change the download folder you would need to go to "Settings -> Download -> Download Folder" as seen in the screenie below:
![image](https://user-images.githubusercontent.com/8960252/48691143-59a8f900-ebc9-11e8-95fc-66f2a6c5cb09.png)
