### ISSUE TITLE
Invalid plugins after install

### ISSUE THREAD

**Issue by Foshitz** [Nexus-Mods/Vortex#2235]
Some mods give the error "Plugins not sorted because: xxx.esm/esp/esl" is not a valid plugin" after mod installation completes  even though both mod and plugin is enabled.
This is resulting in mod not working correctly in-game.

I have Auto-deploy activated in settings.
Before starting game and testing, I confirm that both mod and plugin is enabled. 

The two latest mods i saw this happen to was:
* Sim Settlements Three-in-One v.3.5.0b (simsettlements.esm)
* Force Lock and Quick Hack (BTA_ForceOpen.esp)

**Comment by TanninOne** [comment]
The message says that the plugin is not valid, not that it's missing. This would indicate the plugin is corrupted.
Does this error disappear on the next sort?

**Comment by Foshitz** [comment]
Seems there was an issue during import from NMM.. 
I cleared those two mods (and all the others, just to be safe), downloaded them again one by one from Nexus and I haven't had any further issues like this!

**Comment by TanninOne** [comment]
assumed fixed then, please feel free to re-report if this occurs again.
