### ISSUE TITLE
FNIS Data is set up to use another mods nexus id. Skyrim SE.

### ISSUE THREAD

**Issue by Gr3yStar** [Nexus-Mods/Vortex#2322]
**Describe the bug**
FNIS Data is set up to use another mods nexus id. I can't test original Skyrim, but FNIS Data (the folder created by Vortex, not FNIS that's installed by the user) is using nexus ID 42, which is for an unreleased mod called Spanish Casco Antiguo Falmer.

**To Reproduce**
1. Install FNIS
2. Configure Vortex to run FNIS automatically and set it up however you like.
3. After FNIS Data is created, double click it to examine the mod data panel.
4. notice the nexus id and all the info generated.

**Expected behavior**
FNIS Data should link to the FNIS nexus id and page (for whichever skyrim you run) or have a special ID set up for it... or not have FNIS Data use a nexus id at all.

**Screenshots**
https://i.imgur.com/woLoLpW.png

**Platform (please complete the following information):**
Vortex Version: 0.16.12
Memory: 16.00 GB
System: Windows 10 x64 (10.0.17763)

**Comment by TanninOne** [comment]
The "FNIS Data" mod is not created as a mod with "Nexus Mods" as the source at all and thus it _isn't_ a nexus id - it's just a number.
You must have changed the source and thereby changed the namespace of the mod id.

**Comment by Gr3yStar** [comment]
https://youtu.be/jaFU9DmTmRs

**Comment by TanninOne** [comment]
Exactly, at 1:00 you change the source field to be "Nexus Mods", _that's_ the problem.

**Comment by Gr3yStar** [comment]
But you saw that all the info from that mod is actually there before changing the source. that's the main problem.
