### ISSUE TITLE
Manually upgrading Vortex deletes and empties mods folder.

### ISSUE THREAD

**Issue by JamieRCHI** [Nexus-Mods/Vortex#2362]
**Describe the bug**
When manually installing the latest version of Vortex over an older version, the mods subfolder in the Vortex install folder is empty. (This has happened on the last couple of versions.)

**To Reproduce**
1. Have previous version of Vortex installed. (Either custom or normal install.)
Previously had installed Vortex (custom install location)-1-0-16-8.exe.
2. Manually install latest version of Vortex.  Vortex-1-0-16-12-1541496166.exe
3. In File manager verify files exist in the mods folder of Vortex install location. Vortex update found my current install location and updated it at G:\Games\Vortex. mods folder was empty. 
4. When opening Vortex after restoring my mods folder, the plugins tab showed most if not all of my mods as installed, but the mods tab shows many of the mods that were shown as installed in the plugins tab as Not Installed.

**Expected behavior**
On upgrade, the mods subfolder in the Vortex install should not be emptied or deleted. 

**Platform**
 - OS: Windows 7
 - Vortex Version 0.16.12

**Comment by TanninOne** [comment]
This is expected behaviour, most installers replace the entire installation directory. That's why it's a bad idea (and Vortex now warns about) putting your mod staging (or download) folder into an application directory (Vortex or any other)
