### ISSUE TITLE
Deployment Event still happens on uninstall regardless of preferences

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#2486]
**Describe the bug**
When automatic deployment is turned off, it will still force a deployment when you try removing a mod/archive in the mods tab. 

**To Reproduce**
1. Switch off auto deploy
2. Uninstall a mod (and remove archive)
3. Deployment will happen. 

**Expected behavior**
Deployment should ideally wait until it is next launched manually.

**Platform (please complete the following information):**
 - OS: Win 10
 - Vortex Version 0.16.15

**Additional context**

**Comment by TanninOne** [comment]
Yes, this is the intended and necessary behavior. We wouldn't be able to reliably undeploy that mod after it has been uninstalled.
