### ISSUE TITLE
Unable to login to Vortex - error sequence 

### ISSUE THREAD

**Issue by orca60** [Nexus-Mods/Vortex#2507]
I updated Vortex to the last version 0.16.15 and I am unable to login. Here is the sequence I am getting : 
![window in vortex advising to login -1](https://user-images.githubusercontent.com/45675323/49645984-ba1e9f80-f9eb-11e8-935d-06da234288b0.PNG)

![vortex failed to get access key -2](https://user-images.githubusercontent.com/45675323/49645991-c1de4400-f9eb-11e8-9339-97671e39c1eb.PNG)

![nexus connection closed unexpectedly -3](https://user-images.githubusercontent.com/45675323/49645996-c60a6180-f9eb-11e8-8d32-17f763590e40.PNG)

![clicking on autorise -2](https://user-images.githubusercontent.com/45675323/49646002-cacf1580-f9eb-11e8-88e6-c26b16eac63a.PNG)

![login to vortex error -4](https://user-images.githubusercontent.com/45675323/49646009-cefb3300-f9eb-11e8-93c6-b2855f1656a5.PNG)

All my extension in Vortex are Enabled. I just accepted to update Vortex and I have not made any change at all in my PC. Please help and thank you so much for your assistance. 

This issue has been also posted in Vortex Support in Nexus.

**Comment by TanninOne** [comment]
Latest Vortex versions have a fallback to log in that should always work as long as you can open the nexusmods page.
