### ISSUE TITLE
Adult files showing on "new files" window in dashboard tab while in my account is set to hide adult files

### ISSUE THREAD

**Issue by ktreus** [Nexus-Mods/Vortex#2686]
When i opened vortex, it showed on "NEW FILES" tab an adult file with explicit nudity thumbnail, while in my account on nexus is set to hide them. I don't wanna get embarrassed by someone passing by, specially my parents so we need you to fix this asap 

My vortex version is 0.16.15

**Comment by TanninOne** [comment]
This is nothing Vortex can fix. Vortex just displays the rss feed which doesn't contain the adult flag. You may want to contact the nexusmods web team about this.
