### ISSUE TITLE
not sorted because "xxx" is not a valid even though I just downloaded the mod

### ISSUE THREAD

**Issue by beydral** [Nexus-Mods/Vortex#2690]
Some mods that I download will not appear in game and will not sort in my plugins tab because "xxx" is not a valid plugin. I know this message normally appears when you delete a mod however I just downloaded these mods.  no matter if I download them manually or through vortex the same result happens.  there seems to be no pattern or reason why they will not download, Its hit or miss. Some of the I have downloaded for the first time and others I have deleted for various reasons then returned to. Have tried deleting the mods and re downloading them several times. any help would be appreciated.

**Comment by IDCs** [comment]
Hi @beydral, I assume that you're using Vortex 0.16.15 and trying to run a Gamebryo game? 

please try to purge and then re-deploy your mods and let us know if the sorting functionality kicks back in. If not, please send us your Vortex.log files which you can find under C:\Users\\{YOUR_USERNAME}\AppData\Roaming\Vortex  ( We're on holiday at the moment so it may take longer than usual for us to respond )

**Comment by IDCs** [comment]
Closing due to no feedback
