### ISSUE TITLE
Uninstalling a mod doesn't remove its folder

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/Vortex#2860]
**Describe the bug**
When you uninstall a Stardew Valley mod, the mod's folder isn't deleted from `Mods` even if it contains no unmanaged files. This causes errors in the mod loader.

**To Reproduce**
1. Install [Tractor Mod](https://www.nexusmods.com/stardewvalley/mods/1401) through Vortex.
2. Enable it through Vortex to add it to [your `Mods` folder](https://stardewvalleywiki.com/Modding:Game_folder).
3. Uninstall it through Vortex.

**Actual behaviour**
The `Mods/TractorMod` folder remains. Only these files exist in the folder:
```
TractorMod\
   assets\
      __folder_managed_by_vortex
   i18n\
      __folder_managed_by_vortex
   __folder_managed_by_vortex
```

Note that the same thing happens for mods which don't have subfolders, with a single `__folder_managed_by_vortex` in the mod's folder.

**Expected behavior**
The `TractorMod` folder should be removed from `Mods`, since it contains no unmanaged files. 

**Screenshots**
![screenshot of remaining folder](https://user-images.githubusercontent.com/230581/50799856-dee88a00-12ab-11e9-89ed-5fb6c7f7f158.png)

**Platform:**
 - OS: Windows 10 (version 1803, build 17134.472)
 - Vortex Version: 0.16.15

**Comment by IDCs** [comment]
Hi @Pathoschild, simply uninstalling a mod will not immediately purge created folders; this happens upon the next purge event which you can trigger manually by clicking the purge mods button
![image](https://user-images.githubusercontent.com/8960252/50815480-2e16d500-1315-11e9-87bc-29dd7ee60756.png)

I realize this is inconvenient in this case as the game will not execute correctly unless the folder structure is cleaned up, however, this is a performance related design choice.

**Comment by TanninOne** [comment]
Actually, considering plenty of users too got confused by the left-over directories, it might be worth it to clean up empty directories after every deployment and just accept the performance cost.

**Comment by IDCs** [comment]
Fixed in https://github.com/nexus-mods/vortex/commit/4d706c2e1c5dde04e4b0f0fe4364cd9bcda8b833
