### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by AndrewDawnbringer** [Nexus-Mods/Vortex#2869]
**Describe the bug**
Can't log in. After clicking on Authorise, nothing changes in Vortex. When I'm trying to download a mod, it says API key refused. Tried to reinstall as mentioned in **Can't login to Vortex#895** , still not working.

**To Reproduce**
1. Go to Vortex
2. Click on Log In or Register
3. Click Authorise in the opened window OR copy your link manually and paste it into any browser then clicka Authorise

**Expected behavior**
Vortex logs me in 

**Screenshots**

![image](https://user-images.githubusercontent.com/14193735/50897825-9cd75980-140d-11e9-9556-a42e67ad31fc.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 0.16.15

**Additional context**
I'm already logged in on the site.

**Comment by TanninOne** [comment]
This probably was a bug on the website that should now be fixed, please try again.
