### ISSUE TITLE
Application ID was invalid

### ISSUE THREAD

**Issue by McOni3** [Nexus-Mods/Vortex#2915]
As the title suggests, when I try to authenticate logging in in the application I get an error on the website that says:

'Sorry, there has been a problem authenticating your request. Your request may have timed out if it has been more than 5 minutes since you tried to authenticate from Vortex.
Please restart Vortex and start the login procedure again. If you keep receiving this error then please raise a bug report at https://github.com/Nexus-Mods/Vortex/issues.'
I am using the lastest Mozilla Firefox update and the most recent install of Vortex

**Comment by TanninOne** [comment]
This wasn't an error in vortex, as such it needs to be reported to https://github.com/Nexus-Mods/web-issues/issues
