### ISSUE TITLE
Unable to log in.

### ISSUE THREAD

**Issue by MORBIDLYEON** [Nexus-Mods/Vortex#2917]
**Describe the bug**
I cannot log in to the vortex application due to a problem "authenticating the request"

**To Reproduce**
1. Go to Vortex App
2. Click on Log in

**Expected behavior**
To be able to log in.

**Screenshots**
No screenshot, but here's a copypaste of what the website says in full.

"Sorry, there has been a problem authenticating your request. Your request may have timed out if it has been more than 5 minutes since you tried to authenticate from Vortex.

Please restart Vortex and start the login procedure again. If you keep receiving this error then please raise a bug report at https://github.com/Nexus-Mods/Vortex/issues."

**Platform (please complete the following information):**
 - OS: Windows 10.
 - The one on the nexus, 0.16.15?

**Additional context**

**Comment by Balder86** [comment]
Currently having the same problem. 

Was caused by Chrome 71. Firefox 55 works.

**Comment by MORBIDLYEON** [comment]
Ah yeah, after 20 or so minutes of trouble it's working now. Odd.

**Comment by lalishansh** [comment]
try using broadband (or mobile internet via USB tethering, WiFi connection didn't worked for me)
