### ISSUE TITLE
unable to change drives for mods and downloads

### ISSUE THREAD

**Issue by Stalliongoose** [Nexus-Mods/Vortex#2989]
my games are installed here, but when i try and move them too,

![annotation 2019-01-24 213144](https://user-images.githubusercontent.com/47012559/51710352-cb198380-2020-11e9-898e-7161f0a1032d.jpg)
i have this crash
![annotation 2019-01-24 213143](https://user-images.githubusercontent.com/47012559/51710377-e97f7f00-2020-11e9-8995-e224e7968143.jpg)
30 mins on waiting for anything to happen, then,task manager is the only way to kill task, and no bug reports to explain why to send.
![annotation 2019-01-24 213145](https://user-images.githubusercontent.com/47012559/51710449-25b2df80-2021-11e9-8d5b-b09169faebe6.jpg)
this is with the latest vortex 0.17.1

[small recording.zip](https://github.com/Nexus-Mods/Vortex/files/2793896/small.recording.zip)
the programme just hangs until kill task

**Comment by IDCs** [comment]
Hi @Stalliongoose, thanks for your report. Can you please let us know how big your mods folder is, and also attach your vortex.log files which can be found in C:\Users\{YOUR_USERNAME}\AppData\Roaming\vortex\

**Comment by IDCs** [comment]
Hi @Stalliongoose, just to add to my question - can you please confirm which deployment method you were using.

**Comment by Stalliongoose** [comment]
deployment method fails, has shown with these small recordings, only way i can explain, the programme hangs, until i end task.
hope the recordings will explain
thankyou

[small recording.zip](https://github.com/Nexus-Mods/Vortex/files/2796113/small.recording.zip)
[small recording2.zip](https://github.com/Nexus-Mods/Vortex/files/2796114/small.recording2.zip)

**Comment by IDCs** [comment]
Thanks @Stalliongoose, that gives us more to go on; but please attach your vortex.log files which you can find in the C:\Users{YOUR_USERNAME}\AppData\Roaming\vortex\ folder

**Comment by IDCs** [comment]
@Stalliongoose, are you 100% sure there are no log files present in your "C:\Users\Bando\AppData\Roaming\Vortex\" folder ?
![image](https://user-images.githubusercontent.com/8960252/51748988-04e09d80-20a6-11e9-9186-c8d8dcee28de.png)

This shouldn't be possible as Vortex is generating these immediately on start-up.

**Comment by Stalliongoose** [comment]
> @Stalliongoose, are you 100% sure there are no log files present in your "C:\Users\Bando\AppData\Roaming\Vortex" folder ?
> ![image](https://user-images.githubusercontent.com/8960252/51748988-04e09d80-20a6-11e9-9186-c8d8dcee28de.png)
> 
> This shouldn't be possible as Vortex is generating these immediately on start-up.

i have just uninstalled to re-installed vortex, and will attempt new install to find them,and will update you on progress 

thankyou

**Comment by Stalliongoose** [comment]
still no luck with a new install videos will show and no logs

[OBS Videos.zip](https://github.com/Nexus-Mods/Vortex/files/2796436/OBS.Videos.zip)

**Comment by TanninOne** [comment]
You're clicking right past it. The file is in Roaming\Vortex, **not** Roaming\Vortex\logs.
Since you have your explorer configured to hide file extensions the file is only shown as "vortex" but in the type column it says "Text Document".

**Comment by Stalliongoose** [comment]
> You're clicking right past it. The file is in Roaming\Vortex, **not** Roaming\Vortex\logs.
> Since you have your explorer configured to hide file extensions the file is only shown as "vortex" but in the type column it says "Text Document".

i apologize sincerely, here is a log file

**Comment by IDCs** [comment]
Hi @Stalliongoose, I see you've closed the issue - were you able to solve this issue yourself ?

We managed to reproduce your issue when attempting to move an empty staging mods folder. We've fixed this with: https://github.com/Nexus-Mods/Vortex/commit/e2b4287c1aec7f383045a358da9d24d957bfb71a
