### ISSUE TITLE
please help! failed to get acces key

### ISSUE THREAD

**Issue by geeslime** [Nexus-Mods/Vortex#3036]
whenever i try to login on vortex it gives me an error "failed to get acces key"
everything on my nexus is fine im logged in and everything
heres what it says when i click on more

error: unable to verify the first certificate    at TLSSocket.<anonymous> (_tls_wrap.js:1103:38)    at emitNone (events.js:106:13)    at TLSSocket.emit (events.js:208:7)    at TLSSocket._finishInit (_tls_wrap.js:637:8)    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:467:38)Request Stack:Error    at WebSocket (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\webpack:\src\extensions\nexus_integration\index.tsx:219:20)    at EventEmitter.api (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\webpack:\src\extensions\nexus_integration\index.tsx:382:3)    at emitOne (events.js:116:13)    at EventEmitter.emit (events.js:211:7)    at this (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\webpack:\src\extensions\nexus_integration\views\LoginDialog.tsx:37:16)    at Object.ia (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:15:131)    at Object.invokeGuardedCallback (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:16:137)    at Object.invokeGuardedCallbackAndCatchFirstError (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:16:249)    at za (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:20:288)    at Da (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:22:148)    at Fa (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:22:335)    at Ba (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:21:248)    at Ia (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:24:79)    at Ja (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:24:244)    at Hd (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:88:254)    at ci (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:222:195)

**To Reproduce**
1. Go to vortex
2. Click on log in through nexus

**Expected behavior**
i was expecting to be taken to nexus where i can authorize my account but its not working

**Platform (please complete the following information):**
os- windows 10
newest version of vortex (does this on every version i tried downloading old ones)

**Additional context**
please any help to fix this problem would be appreciated

**Comment by IDCs** [comment]
Hi @geeslime, any chance you are connecting to the internet through a VPN or proxy ?

**Comment by geeslime** [comment]
@IDCs No, im not using any type of vpn or proxy.

**Comment by TanninOne** [comment]
You should be able to log in now through the fallback mechanism which completely circumvents the code that fails here.
