### ISSUE TITLE
Login API Failure

### ISSUE THREAD

**Issue by Benedikt20** [Nexus-Mods/Vortex#3048]
Upon start following error message happens.

![grafik](https://user-images.githubusercontent.com/15967221/51997913-f9cbaa00-24b7-11e9-86b3-420467e19fa8.png)

Upon clicking the user Icon and then Log In following happens
![capture2](https://user-images.githubusercontent.com/15967221/51997944-0bad4d00-24b8-11e9-8935-8b31cf0e409e.PNG)

Vortex Log File
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/2813603/vortex.log)

**Comment by IDCs** [comment]
Hi @Benedikt20, the error message within the log indicates that the Windows root certificate on your machine has been manipulated or corrupted and it's unable to validate against the certificate we're sending you. 

Unfortunately this is an issue with your environment and we're unable to assist you with it as there are a plethora of reasons why this may be happening. (Out of date Windows, Anti Virus software manipulating the certificate, perhaps the certificate is missing completely?)

I would suggest you google for how to repair missing or invalid root certificates for your specific Windows version and see whether you can fix it.
