### ISSUE TITLE
Display full mod name on hover during conflict resolution

### ISSUE THREAD

**Issue by PhantomGamers** [Nexus-Mods/Vortex#3057]
**Is your feature request related to a problem? Please describe.**
Currently when you click More->Show under Unsolved File Conflicts mods with long names are cut off with ellipsis, making it hard to tell which mod it is for mods with multiple files.

**Describe the solution you'd like**
Display the full name of the mod in a tooltip on hover.

**Describe alternatives you've considered**
Perhaps also scale the popup box to be a little wider when there's room, currently I keep my vortex window fairly large on a ultrawide monitor and there'd be plenty of room for the text if it'd scale or be resizable. But I think tooltip text on hover is probably the simpler solution.

Or just wrap around like it does on the right hand side, but maybe there's a reason why it doesn't that I'm missing.

**Additional context**
![image](https://user-images.githubusercontent.com/844685/52068211-36e07c80-254a-11e9-8135-61015404507b.png)
(In this case it's obvious which is which because there are only two mods and it shows the entirety of the mod name on the right side, but with mods that have more than 2 files it can get confusing.)

**Comment by TanninOne** [comment]
The mod name on the left is no longer truncated but will instead wrap around.
