### ISSUE TITLE
News Dashlet is not game specific

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#3095]
News dashlet always reads from https://www.nexusmods.com/rss/news
If a news post is game specific it will be on that game's RSS feed only. For example, the article "Going Below Zero with Subnautica" appears here: https://www.nexusmods.com/subnautica/rss/news but is not on the main news RSS.

**Comment by TanninOne** [comment]
When we initially implemented it it wasn't supposed to be game-specific. If you want it to be I can change it.

**Comment by Pickysaurus** [comment]
I realised I didn't reply to you 2 years ago about this 😓 

Game-specific would be better especially as we put out some Cyberpunk 2077 specific news lately which Vortex users wouldn't have seen in the dashlet.
