### ISSUE TITLE
SKYUI.esp invalid plugin could not sort

### ISSUE THREAD

**Issue by TuWHe** [Nexus-Mods/Vortex#3136]
**Describe the bug**
I am using The Ultimate modding guide to mod skyrim 2011
I am also using Vortex even though it is not recommended by the OP
As soon as I install SMiM, checking either light or full with dragonborn option, Vortex warns me that SKYUI.esp is not a valid plugin and they cannot be sorted. If I uninstall SKYUI it's then iHUD, and if I uninstall iHUD it's yet another one that's invalid. Reinstalling everything did not fix it. SKYUI was working even though Vortex showed the error until I installed some more mods. What could cause this?

**To Reproduce**
1. install skyui, ihud, mcm, bug fixes, USLEEP, SSP, USCP, safety load, and some other basic ones
2. install SMiM
3. error

**Expected behavior**
it's supposed to not show any error.

**Screenshots**

**Platform (please complete the following information):**
Windows 10
Vortex 0.1.15 (I suppose)

sorry I messed up the post... I'm new to github. I've been trying to mod for a week. it's probably stupid me as usual, I'm going to sleep, thanks for your help.

also if it can help I've been writing down whatever edit I do on a txt file, here's the log until the issue:
[New Text Document.txt](https://github.com/Nexus-Mods/Vortex/files/2846739/New.Text.Document.txt)

**Comment by TanninOne** [comment]
Vortex 0.16.15 has a problem where it tries to read plugins at a time where they aren't actually in place yet. It's safe to ignore these "plugin invalid" warnings and continue modding.
0.17.0 fixes this, but that version is currently not yet released as stable
