### ISSUE TITLE
Search for games 

### ISSUE THREAD

**Issue by ReneMuetti** [Nexus-Mods/Vortex#3140]
**Describe the bug**
It is not recognizable whether the tool does anything at all.
I don't get any information / reactions.

On the website there is e.g. Subnautica Below Zero.
There is no information about this in the tool.

I can't really imagine that this is true.

**To Reproduce**
1. Go to 'Games'
2. Click on 'search for games'
3. it happens - nothing

**Platform (please complete the following information):**
 - OS: Windows
 - Vortex Version 0.16.15
- Electron 2.0.12
- Node 8.9.3

**Comment by TanninOne** [comment]
Subnautica is supported, Below Zero isn't (yet). Nowhere do we claim that it is.
