### ISSUE TITLE
feedback tracking in vortex

### ISSUE THREAD

**Issue by Iloei** [Nexus-Mods/Vortex#3144]
I made some suggestions using vortex's "send feedback" mechanism, and I have additional information about one of them (I was making a suggestion about an issue which now seems like it might not actually be an issue - might have been a glitch, might have been me not paying attention, I do not know yet...)

But I do not see any tracking of those issues in vortex, nor do I see them here in GitHub.

Better tracking of user feedback seems like it might improve feedback quality. (And, ok, might also provide a grouping mechanism for de-emphasizing people like me if we get too annoying in our incomprehensions and mistakes...)

**Comment by IDCs** [comment]
Hi @Iloei, we already provide feedback/github issue tracking inside Vortex via the "Issues" dashlet which can be activated/deactivated in the settings panel. 

Please keep in mind that we read/filter feedback messages internally before creating a Github issue for it (Your feedback will not appear inside the dashlet unless we export it manually to Github). Given that we receive a hefty amount of feedback on a daily basis, chances are we've yet to find your feedback but we will get there eventually!
