### ISSUE TITLE
"thunderbolt" (conflict icon) should be red for mods in cyclic conflict

### ISSUE THREAD

**Issue by Iloei** [Nexus-Mods/Vortex#3152]
Currently, if I create a cyclic dependency, all participating mods show no mod conflicts to be resolve - specifically they have a green icon instead of a red one to represent the conflicts.

This icon should be red when the user supplied rules are not useful.

**Comment by TanninOne** [comment]
Red is already the signal for "this has unsolved conflicts".
Besides, Vortex needs to invoke the sorting process to determine if there is a cycle which can take a while to process so it's not something we can update on the fly.
If Vortex went and tagged every mod that is part of a cycle and highlighted it somehow we wouldn't be able to update that highlight until the next time you sort, updating it after every time you change a rule would be impractical.

**Comment by Iloei** [comment]
Again disturbing, because it says that there's no record of what's deployed
/ deployable.

The real loser, here, though, is that with this design updates can't be
atomic, so to work reliably the user has to have a complete internal model
of the vortex update process (or wait for everything to complete between
each action which changes the deploy state, or "get lucky").
