### ISSUE TITLE
"Remove" doesn't for disabled mods

### ISSUE THREAD

**Issue by Iloei** [Nexus-Mods/Vortex#3154]
If I enable a mod (and/or later disable it), I get a "remove" button in the right hand column of vortex's mods table. This button has a popup with a checkbox to also remove the archive. But all it seems to do is disable the mod (which might already be disabled). For the remove action to do anything, I have to first uninstall the mod (using the button on the right hand side).

This button should either remove the mod as specified, or it should be grayed out (with no popup) when it won't do what it says. (Alternatively, if it's really doing something like "remove after 15 minutes of other stuff [like maybe redeploying] and I just did not wait long enough" (though that seems unlikely given my current experience), it should have an activity indicator while the action is in progress.)

(I am on windows 10, if that matters.)

**Comment by TanninOne** [comment]
I have just verified that removing a mod works just fine. You do get an indicator while deployment is running (top right) and I explained in the other  issue you posted why it's necessary.
