### ISSUE TITLE
UI aesthetic suggestions.

### ISSUE THREAD

**Issue by rzjnzk** [Nexus-Mods/Vortex#3237]
I suggest that the default color scheme be adjusted, as I find there to be too much contrast, and it quite jarring to look at first.

Suggestions:

- Duller oranges, 
- removal of light-coloured borders,
-  darker greys,
- top orange bar be aligned and scaled with the main content, e.g. mod list etc., 

As a further note, the content in the top orange bar appears to overlap when the margins are tweaked under settings then themes.

**Comment by TanninOne** [comment]
You are welcome to create your own theme and maybe share it with the community but we have plenty of users who find the current to have _too little_ contrast, you're the first to say it has too much so there is no way we're going to adjust the default theme in that direction.
