### ISSUE TITLE
Enhancement- 7 Days to Die Load Ordering

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#3259]
Reference Forum Post: https://forums.nexusmods.com/index.php?/topic/7362871-vortex-7-days-to-die-load-orders/#entry67373321

Request to Enhanced 7DTD support with Load ordering. 

_"Not really any specific link as such, but I'll detail as best I can.

In Alpha 17 the game will now look for a folder called "Mods" in the root game directory.

Inside the mods folder you place your "modlets". These are loaded Alphabetically. Currently the only way to change the load order is to rename the folder. We have been leaving this up to users to do manually.

![image](https://user-images.githubusercontent.com/31670524/52776411-6ce92a80-3039-11e9-87b0-b6d0cc963e27.png)

Inside the main folder is mod/ModInfo.xml containing the mods Name/description/version. 
Config folder contains the config files
ItemIcons is self explantory.
Resources contains Unity Bundles.

![image](https://user-images.githubusercontent.com/31670524/52776430-75416580-3039-11e9-9c82-c4f5ae3618b1.png)
 

The config directory consists of files of the same name as vanilla, but contain XPath directives which are now processed at run time. So hard modding the xml files is no longer necessary.
![image](https://user-images.githubusercontent.com/31670524/52776444-80949100-3039-11e9-8861-b914ec34dfd3.png)

because of the xpath processing on the fly is where load orders are necessary when combining mods, just like in skyrim as there may be a dependency on another "modlet".

Its where conflicts will happen. eg: If modlet A removes a node and then Modlet B tries to access the now removed node (it will just fail silently with a warning in the console).

I dont know if its anything within the scope of what you are looking at but I didnt think it could hurt to ask :)"_

**Comment by IDCs** [comment]
Hi @nelson3219, none of us have modded 7DTD before so our knowledge of its modding patterns is limited. Can you please confirm that this enhancement is indeed required and whether you would be able to pick this up ?

**Comment by nelson3219** [comment]
Hi,
i am not modding 7D2D myself, so i don´t realy know. But the way the problem is described it makes sense to me. But how to automatically load Mods in the proper order without something like a dependency structure...
Sorry for the late answer, I am very busy with my exams at the moment.

**Comment by TanninOne** [comment]
implemented in https://github.com/Nexus-Mods/vortex-games/commit/df71539b419c636a8b46b8bb82a5af0f20cc8783
