### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#3300]
This is a collection issue for reports about the game crashing.

All Vortex does is install mods and potentially do some changes to ini files, it can not directly cause your game to crash.
If you're seeing game crashes when running through Vortex this is probably caused by the mods you have enabled with Vortex, maybe they are incompatible, maybe they're using too much memory, maybe your plugins aren't ordered correctly.

We can't rule out that Vortex may be indirectly connected to it (e.g. Vortex may be failing to order the plugin list correctly) but we can't investigate issues that may or may not be indirectly related to Vortex.
This is why this issue is closed.

If you determine that Vortex is the cause of your game crash you have to report the thing the immediate thing vortex did wrong in detail, e.g. don't report "the game is crashing", report "vortex orders the plugins this way \<include plugin list\> with plugin \<a\> before plugin \<b\> but according to the mod author it has to be after \<include link\>".
Only then do we have a chance to find the issue and fix it.

**Comment by Its-me-anshul-143** [comment]
Ok
