### ISSUE TITLE
View mods in collapsable catogory tree view

### ISSUE THREAD

**Issue by rzjnzk** [Nexus-Mods/Vortex#3416]
Mods should be viewable in a collapsible tree view, where the tree corresponds to the category tree. Currently, it makes it hard for the user to see the relationship between mods, and the types of mods they are beyond the immediate single-level category name. Adding this feature would save a lot of time, and make mod-organization less straining.

**The key point of a tree view is allowing the user to see the relationship between categories.** Filtering to specified categories as currently implemented allows the user to only see the categories they want to, though, it does away with the visual relationship of a tree view. I strongly recommend that this is implemented.

A small example:

- Reskins
    - Armour
    - Apparel
    - Weapons
- Additions
    - Armour
    - Apparel
    - Weapons
    - Quests
    - Areas
- Enhancements
    - Textures
    - Sound
    - Bug fixes

**Comment by monyarm** [comment]
I concur. I sort my mods by category, but when i have 40 mods that are all in the same category, it becomes annoying to scroll through. Being able to, when sorting by category, collapse the categories, would be a very useful feature.

**Comment by TanninOne** [comment]
This has already been implemented
