### ISSUE TITLE
Uninstalled Status

### ISSUE THREAD

**Issue by Kysakio** [Nexus-Mods/Vortex#3445]
**Describe the bug**
Uninstalling one mod marked my other mods as uninstalled even though none of them were.

**Screenshots**
![uninstalled](https://user-images.githubusercontent.com/34197696/53059526-4f222800-3474-11e9-84d4-0c435fa4f9d2.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 0.17.3

**Comment by IDCs** [comment]
Hi @Kysakio, I'm not sure what you're trying to highlight in that screenshot - all your mods look enabled to me!

The red uninstalled dropdown button simply gives you the option to uninstall the selected mod. If this is not what you're trying to showcase, it would be helpful if you provided a video or step-by-step description of how you're reproducing this bug.

**Comment by TanninOne** [comment]
closed due to lack of feedback
