### ISSUE TITLE
[Issue] Mod Categories

### ISSUE THREAD

**Issue by Sirruthf** [Nexus-Mods/Vortex#3731]
Not a bug exactly, mor of an issue... But look: first one or two items in categories lists are always empty entities, representing service 'unassined' category and top-level category with 'hide top level' setting turned on. Not dangerous, just veeeery annoying. Do something, ok :)?

**Comment by IDCs** [comment]
Hi @Sirruthf, sorry but I'm not sure what you're trying to say - can you please attach a screenshot to clarify?

**Comment by IDCs** [comment]
Hi @Sirruthf, root categories displaying "Empty" may have installed mods inside their subcategories. Hopefully this is what you meant in this report - fixed in https://github.com/Nexus-Mods/Vortex/commit/0cd83d40a287b7f30a54416b470fec00dafceccf
