### ISSUE TITLE
X4 Foundations Support Directory

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#3859]
**Describe the bug**
X4: Foundations mods can be installed to both the game directory (extensions folder) and the user's documents directory  (`Documents\Egosoft\X4\extensions `for GOG,  `Documents\Egosoft\X4\[steamID]\extensions` for Steam)

Currently, Vortex only supports the game folder install, some mods do not work correctly when installed here. 

Based on discussion with members of the Egosoft Discord server it would be advisable to offer both install paths as "Mod Types" which the user documents folder as the default.

**Comment by IDCs** [comment]
Hi @Pickysaurus, can you please let us know what the [steamID] property stands for ? is it the user's Steam username or is it the numeric app ID ? 

@alexparlett, is this something you would be able to look at ?

**Comment by Pickysaurus** [comment]
I have checked with Forleyor in the X4 community and they confirmed that the "SteamID" is, in fact, the user's unique Steam32 ID.

**Comment by IDCs** [comment]
Given that we're already parsing game manifests in the core application, we're going to enhance our steam library to return the user's steam ID to any extensions that requires it to avoid having the extensions do the same thing. I'll implement this myself.

**Comment by IDCs** [comment]
Fixed in https://github.com/Nexus-Mods/vortex-games/commit/e9f7d8060fd8cf67875f75873ecb345b02b90d20
