### ISSUE TITLE
Oblivion BSA redirection non-functional

### ISSUE THREAD

**Issue by LostDragonist** [Nexus-Mods/Vortex#3922]
When BSA redirection is enabled, Vortex is accessing SResourceArchiveList in oblivion.ini.  This is incorrect as the proper setting is SArchiveList.  This makes the BSA redirection function non-functional as best as I can tell.

oblivion.ini after BSA redirection is enabled:

```
SArchiveList=Oblivion - Meshes.bsa, Oblivion - Textures - Compressed.bsa, Oblivion - Sounds.bsa, Oblivion - Voices1.bsa, Oblivion - Voices2.bsa, Oblivion - Misc.bsa
SResourceArchiveList=Vortex - BSA Redirection.bsa, Oblivion - Meshes.bsa,Oblivion - Textures - Compressed.bsa,Oblivion - Sounds.bsa,Oblivion - Voices1.bsa,Oblivion - Voices2.bsa,Oblivion - Misc.bsa
```
Last tested on Vortex 0.17.7.

**Comment by TanninOne** [comment]
I guess Mod Organizer had the same bug?

**Comment by LostDragonist** [comment]
Indeed.  I just put in a change for MO2 and happened to check if Vortex did the same thing.

**Comment by TanninOne** [comment]
Yeah, I have to admit I just consulted the MO code for which key to use, assuming that it has been tested for long enough. ;)
Thanks for the report. Will be fixed in the next release.
