### ISSUE TITLE
When Sorting plugins With vortex always get Cycle warning

### ISSUE THREAD

**Issue by Brutusvp47** [Nexus-Mods/Vortex#3935]
When I try to sort plugins with Vortex it always comes back with Plugins not sorted because of cyclic conditions, If I sort using The Loot program it shows no such errors. I can completely remove the programs that are in the error, and it will come back with the same message, but different plugins show in the message,

Last Diagnostic file;
Tue, 19 Mar 2019 02:03:25 GMT - info: Vortex Version 0.17.7
Tue, 19 Mar 2019 02:03:26 GMT - info: using C:\Users\Milt\AppData\Roaming\Vortex as the storage directory
Tue, 19 Mar 2019 02:03:28 GMT - info: python not found not found: python
Tue, 19 Mar 2019 02:03:33 GMT - info: python not found not found: python
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=settings_interface
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=settings_application
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=about_dialog
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=diagnostics_files
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=dashboard
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=starter_dashlet
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=firststeps_dashlet
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=mod_management
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=category_management
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=profile_management
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=nexus_integration
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=download_management
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=gamemode_management
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=announcement_dashlet
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=symlink_activator
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=symlink_activator_elevate
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=hardlink_activator
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=move_activator
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=updater
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=installer_fomod
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=installer_nested_fomod
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=settings_metaserver
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=test_runner
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=extension_manager
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=ini_prep
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=news_dashlet
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=sticky_mods
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=browser
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=changelog-dashlet
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=common-interpreters
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=documentation
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=fnis-integration
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-7daystodie
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-breakingwheel
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-darksouls
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-darksouls2
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-dragonage
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-dragonage2
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-dragons-dogma
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-enderal
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-factorio
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-fallout3
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-fallout4
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-fallout4vr
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-falloutnv
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-gardenpaws
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-grimrock
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-kerbalspaceprogram
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-kingdomcome-deliverance
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-monster-hunter-world
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-morrowind
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-mount-and-blade
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-neverwinter-nights
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-nomanssky
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-oblivion
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-oni
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-pathfinderkingmaker
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-pillarsofeternity2
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-sims3
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-sims4
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-skyrim
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-skyrimse
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-skyrimvr
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-starbound
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-stardewvalley
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-starsector
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-stateofdecay
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-subnautica
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-subnauticabelowzero
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-sw-kotor
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-teso
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-warthunder
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-witcher
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-witcher2
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-witcher3
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-worldoftanks
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-x4foundations
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-xcom2
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=game-xrebirth
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=gamebryo-archive-invalidation
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=gamebryo-bsa-support
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=gamebryo-plugin-indexlock
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=gamebryo-plugin-management
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=gamebryo-savegame-management
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=gamebryo-test-settings
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=gameinfo-steam
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=issue-tracker
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=local-gamesettings
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=meta-editor
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=mo-import
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=mod-dependency-manager
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=mod-highlight
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=modtype-dinput
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=modtype-dragonage
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=modtype-enb
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=modtype-gedosato
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=morrowind-plugin-management
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=mtframework-arc-support
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=nmm-import-tool
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=open-directory
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=test-gameversion
Tue, 19 Mar 2019 02:03:33 GMT - info: init extension name=theme-switcher
Tue, 19 Mar 2019 02:03:33 GMT - info: all extensions initialized
Tue, 19 Mar 2019 02:03:34 GMT - info: register protocol protocol=nxm
Tue, 19 Mar 2019 02:03:34 GMT - info: deregister protocol
Tue, 19 Mar 2019 02:03:34 GMT - info: deregister protocol
Tue, 19 Mar 2019 02:03:34 GMT - info: register protocol protocol=http
Tue, 19 Mar 2019 02:03:34 GMT - info: register protocol protocol=https
Tue, 19 Mar 2019 02:03:35 GMT - info: found game location=F:\Games\Steam\steamapps\common\Fallout 4\, name=Fallout 4
Tue, 19 Mar 2019 02:03:35 GMT - info: found game location=F:\Games\Steam\steamapps\common\Skyrim Special Edition\, name=Skyrim Special Edition
Tue, 19 Mar 2019 02:03:35 GMT - info: potential match F:\Games\Steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe
Tue, 19 Mar 2019 02:03:35 GMT - info: potential match F:\Games\Steam\steamapps\common\Fallout 4\f4se_loader.exe
Tue, 19 Mar 2019 02:03:35 GMT - info: potential match F:\Games\Steam\steamapps\common\Skyrim Special Edition\skse64_loader.exe
Tue, 19 Mar 2019 02:03:35 GMT - info: read font C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\assets\fonts\icons.svg
Tue, 19 Mar 2019 02:03:36 GMT - info: potential match F:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\tools\GenerateFNIS_for_Users\GenerateFNISforUsers.exe
Tue, 19 Mar 2019 02:03:36 GMT - info: updated loot masterlist false
Tue, 19 Mar 2019 02:03:37 GMT - info: potential match F:\Games\Steam\steamapps\common\Skyrim Special Edition\Data\tools\GenerateFNIS_for_Users\GenerateFNISforUsers.exe
Tue, 19 Mar 2019 02:03:37 GMT - info: changed game mode newMode=skyrimse
Tue, 19 Mar 2019 02:03:40 GMT - info: set channel
Tue, 19 Mar 2019 02:03:43 GMT - info: no update available
Tue, 19 Mar 2019 02:03:57 GMT - info: loot failed error=Cyclic interaction detected: AnotherSortingMod_2017-SSE.esp --[Group]-> Immersive Sounds - Compendium.esp --[Group]-> Cutting Room Floor.esp --[Master]-> AnotherSortingMod_2017-SSE.esp
Tue, 19 Mar 2019 02:16:20 GMT - info: loot failed error=Cyclic interaction detected: AnotherSortingMod_2017-SSE.esp --[Group]-> Immersive Sounds - Compendium.esp --[Group]-> Cutting Room Floor.esp --[Master]-> AnotherSortingMod_2017-SSE.esp
Tue, 19 Mar 2019 02:32:20 GMT - info: loot failed error=Cyclic interaction detected: AnotherSortingMod_2017-SSE.esp --[Group]-> Immersive Sounds - Compendium.esp --[Group]-> Cutting Room Floor.esp --[Master]-> AnotherSortingMod_2017-SSE.esp

**Comment by TanninOne** [comment]
Cycles are a problem for you to fix, not a bug.
The reason you're not getting the errors from the stand-alone loot is because the custom rules and group assignments you set inside vortex are not applied there. _They_ cause the cycle.

**Comment by Brutusvp47** [comment]
Thank you for your response, I tried every way I knew to figure it out but was unable to… until the latest update, I don’t know if I just never notice the message or it was added in the latest version (0.17.8)
I figured it was something to do with the mod “AnotherSortingMod_2017-SSE” but I uninstalled and reinstalled, redownloaded it etc. It always came up the same. Anyway today, after install of the latest Vortex version I noticed a message about duplicate entries for the AnotherSortingMod esp in the “userlist.yaml” when I removed them and reinstalled that mod the sorting now sorts with no messages and it appears to sort correct.
Even though I have been using Vortex since it was released, I learn something new about it almost every day, it is truly an extremely good, tool!!!,  Thank you for all your good work on this tool, and responding to questions that to you are obvious, but not to neophytes like me. Which now brings me to another question concerning the userlist.yaml, how does it get populated because right now I have over 140 esps but that file only has the following information and I had Uninstalled the Rigmorcyrodiil mod days ago??? Should I remove those references?
globals: []
plugins:  - name: EzEWorldMapSE.esp
    global_priority: 120
    after:
      - AHZmoreHUDInventory.esl
      - SkyrimOptimized.esp
    group: Dynamic LOD
    group: Early Loaders
  - name: Guards_Armor_Replacer.esp
    group: Late Loaders
  - name: rigmorcyrodiil - sounds.esm
    after:
      - rigmorcyrodiil.esm
  - name: rigmorcyrodiil - textures.esm
    after:
      - rigmorcyrodiil - sounds.esm
  - name: rigmorcyrodiilpatch.esp
    after:
      - rigmorcyrodiil - textures.esm
  - name: audio overhaul skyrim - immersive sounds patch.esp
    group: Fixes & Resources
 
groups: []

**Comment by TanninOne** [comment]
The userlist gets populated when you assign groups or plugin dependencies (load after) inside Vortex, it only contains plugins for which you have "customised" something.

You don't have to clean up the file, entries for plugins you don't have don't do any harm

**Comment by Brutusvp47** [comment]
Thank you very much!  that is very good to know!
