### ISSUE TITLE
Windows 10 developer mode allows symlinking without admin

### ISSUE THREAD

**Issue by argv-minus-one** [Nexus-Mods/Vortex#4062]
When running on a Windows 10 machine with developer mode turned on (Settings→Update & Security→For developers), creating a symlink doesn't require elevation. Currently, Vortex seems to only check whether it's running as admin, on the incorrect assumption that creating symlinks is never possible without admin.

Also, creating folder junctions (like with `mklink /j`) has never required special privileges. This won't help with games that mix files from different mods in the same folder (such as Elder Scrolls and Fallout), but it should help with games that expect each mod to have its own folder (such as X4: Foundations). Creating junctions requires native code, but there are several packages on npm for that.

**Comment by TanninOne** [comment]
deployment based on folder junction is something we of course considered but since precious few games would work with it it's low priority.

Regarding symbolic links you are incorrect. To determine if symbolic links require elevation vortex tries to create a dummy symlink (with regular rights and in a directory guaranteed to be writable) and only if that fails does Vortex enforce elevation to create symlinks.

**Comment by argv-minus-one** [comment]
>Regarding symbolic links you are incorrect. To determine if symbolic links require elevation vortex tries to create a dummy symlink (with regular rights and in a directory guaranteed to be writable) and only if that fails does Vortex enforce elevation to create symlinks.

Oh. Sorry I missed that. I can't seem to find it in the code in the Vortex repo, so I assume it's in a separate package?

But then, why is Vortex requiring me to elevate on my Windows 10 machine in developer mode? Is there some way I can find out? `%AppData%\Vortex\logs` exists but is empty. The in-app “diagnostics files” says nothing about failing to create a dummy symlink. Running Node from the command prompt (with `%AppData%\Vortex` as the cwd) and doing `fs.symlinkSync("foo", "bar")` works fine.

**Comment by argv-minus-one** [comment]
In the UI, the only available “Deployment Method” is “Symlink Deployment (Run as Administrator)”. The game folder is on a different drive than the staging folder.

**Comment by TanninOne** [comment]
I've found a potential issue with the current detection, please try again with the next release (which will be 0.17.10) and let us know if it changed anything.

**Comment by TanninOne** [comment]
0.17.10 is now out (testing channel), please let me know if that fixes the issue.

**Comment by argv-minus-one** [comment]
Yes, it works now. Thanks!

Oddly enough, it *didn't* work when 0.17.10 was launched by the installer. At that point, deployment still required elevation, generated a bogus error about `C:\Users\[redacted]\Documents\Egosoft\X4\2240842\extensions` being missing, and didn't actually have any effect on the file system (contents of the extensions folder were unchanged when enabling/disabling mods).

I closed Vortex and restarted it from the Start menu. Then, it requested elevation on startup, and gave me a warning about files in that extensions folder having been modified outside of Vortex (also bogus; I never touched it). I told it to revert everything. After that, deployment seems to work correctly (files appear/disappear in the extensions folder, like they should) and doesn't require elevation. Neither does Vortex request elevation on startup any more.

None of the log files from today mention any of this happening (at `INFO` level or above). I'm not going to look through the `DEBUG` logs as they're far too large, but I could post them if you want.
