### ISSUE TITLE
Invalid Version 1.0 with recent update

### ISSUE THREAD

**Issue by Hellzbellz123** [Nexus-Mods/Vortex#4065]
**Describe the bug**
I havent updated Vortex for a while and it said i should update so i did and it throw a TypeError for some reason.

Not really sure how you would reproduce the error because i dont know much info on it

![asdasrasdasdasd](https://user-images.githubusercontent.com/31550512/55161201-3adfe380-5122-11e9-99f7-2ef991b2b2e1.PNG)

**Platform:**
Windows 10  Version	10.0.17763 Build 17763

**Additional context**
Intel i5 4440
nvidia 1070

**Comment by TanninOne** [comment]
The error indicates that a game extension you have installed is invalid, but the ones included in Vortex  should all be correctly formed. Did you install an unofficial game extension? Which one?

**Comment by Hellzbellz123** [comment]
uhh i made my own extension for terratech based off of the subnautica extension
Build on exe says 0.17.80
how do i remove extensions

**Comment by Hellzbellz123** [comment]
nevermind i got it fixed
is the mod calling  on code that no longer exists?
should skip plugins that dont work would be useful feature

**Comment by TanninOne** [comment]
No, this error simply says that your game extension has version number "1.0" which is not a valid semantic version.

Vortex will usually disable extensions that fail to load but that requires the exception to be caught and handled graciously, in this case that wasn't the case. Future versions will deal with this better
