### ISSUE TITLE
[Subnautica/Subnautica Below Zero] No install pattern logic

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#4148]
**Describe the bug**
Vortex currently has a very basic installation method for Subnautica mods. It simply extracts the archive into the staging folder. This is problematic as some mods are packed in such a way that they will not work without adjustment.

From my brief research, mods for Subnautica almost always contain a `mod.json` file along with all the other required assets inside a folder named that same as the mod title. It should be fairly easy to handle things like extra folder levels or the file not being inside a folder on install. 

There are some exceptions with hardcoded asset paths, but I do not have enough information to discuss those. 

For testing, extract a valid mod archive and either add or remove a folder level then repack and install with Vortex. 

**Expected behaviour**
Installation of mods will work if the archive is mispacked.

**Comment by IDCs** [comment]
Fixed in https://github.com/Nexus-Mods/vortex-games/commit/aeda1285d71145fe104090a2f013d3804d11aa96

**Comment by AlexejheroYTB** [comment]
Does this support mods that dont have any folders?

So something like

- `mymod.zip/MyMod.dll`
- `mymod.zip/mod.json`

instead of

- `mymod.zip/MyMod/MyMod.dll`
- `mymod.zip/MyMod/mod.json`
