### ISSUE TITLE
Enhancement request: Choosing if file is Oldrim or SkyrimSE, manual description edits.

### ISSUE THREAD

**Issue by Starfis** [Nexus-Mods/Vortex#415]
I would like to request an enhancement. Would be great to be able to manually choose if the mod is from Skyrim or Skyrim SE while managing mods for SkyrimSE. I use several Oldrim mods which are not, and probably never will be uploaded to SSE Nexus, but they are at the Oldrim nexus and I would like to be able to see the proper description, author, maybe even updates. Same goes for the files from LL or other external sites, it seems like you are at least planning something like this since we can choose the source, and even though I very much doubt it would be possible to directly get the file description from LL, would be nice if we could edit the description and write our own with complete formatting just like it was possible in NMM. The "Write your own notes" simply is not enough, at least not for me. Thank you.

**Comment by TanninOne** [comment]
In the latest versions of Vortex you can open the sidebar for a mod and select the "Game Section". This controls what game section vortex retrieves the file info from.
Also, if you download a mod through vortex (from the oldrim section) and install it (in the dialog that comes up, select you want to install it for Skyrim SE) that field will be set correctly automatically.

Regarding other external sites: There are two ways you could get files for foreign files, one is the soure attribute as you've figured out yourself, which would allow others to write vortex extensions that use external sources for stuff like descriptions, mod updates and so on. We're not going to provide integration for "competing" sites ourselves though, I think it's already nice enough of us to leave that door open. ;)

The other approach is through so called "meta servers" (that is: they serve meta information, the server isn't itself meta). With these, a file gets identified via hash and can then be assigned meta information by a server, independent of where the file was retrieved from.
However, there is currently no actual server available and if/when Nexus provides one, I don't know yet how it would be used, if it could be used to assign mod information for mods that aren't uploaded to nexus.
But here too, the door is open for third parties to provide their own "meta servers".
