### ISSUE TITLE
WINE: The Witcher 2 executable definition.

### ISSUE THREAD

**Issue by Kreyren** [Nexus-Mods/Vortex#4202]
**DISCLAIMER: THIS ISSUE IS WINE COMPATIBILITY ISSUE ON LINUX.**

![image](https://user-images.githubusercontent.com/11302521/55721891-7caf3a80-59fc-11e9-9c58-c09c53c9cdd9.png)

WINE is unable to detect The Witcher 2 which is using eON wrapper that is provided by upstream as compatibility layer for linux (file hierarchy of the game is identical to windows excluding executables(?) http://ix.io/1FCv).

Requesting to update vortex definition for linux -> Add `$GAMEDIR/launcher` which is executable for shell script to invoke `./saferun.sh ./tenfoot-launcher..` accordingly
![image](https://user-images.githubusercontent.com/11302521/55722253-a4eb6900-59fd-11e9-9774-eacd4a499536.png)

In theory some check on nexusmods.com that can be crowdsourced to report linux compatibility for mods?

## Steps To Reproduce
Steps to reproduce the behavior **on Linux** are:
1. Make a new wineprefix with `dotnet46` or higger workaround provided by `winetricks` + `dxvk` -- OR -- export `dxgi.dll` from DXVK which is required by vortex and install vortex.
2. Install The Witcher 2 on Steam
3. Add The Witcher 2 in Vortex manually.

## Expected behavior
Use Linux version of The Witcher 2 for modding.

## Platform
 - OS: **Bedrock Linux 0.7.2 Poki using Gentoo + Debian strata**
![image](https://user-images.githubusercontent.com/11302521/55722633-b6814080-59fe-11e9-8cf1-0701183b03c9.png)
 - Vortex Version: **0.17.10**

**Comment by TanninOne** [comment]
We don't officially support running Vortex on Linux atm but we welcome a pull request for this.
