### ISSUE TITLE
Warthunder sound mod put on userskin folder

### ISSUE THREAD

**Issue by Darktotaled** [Nexus-Mods/Vortex#4259]
As the title says, tried adding a sound mod to warthunder via vortex(version 17.11). It was the female crew mod: https://www.nexusmods.com/warthunder/mods/2194?tab=description
i do know that most warthunder mods are user skins for planes, both fantasy and historical, so i get why the default mod folder would be there, but for sounds mods, it goes on .../warthunder/sound/mods.

Thanks in advance. Keep the good work :)

**Comment by IDCs** [comment]
Hi @Darktotaled, so any sound mods go inside ../warthunder/sound/mods, but do they have their own mod folders or are they just thrown in there loosely ?

**Comment by IDCs** [comment]
Fixed in https://github.com/Nexus-Mods/vortex-games/commit/a59acd69ecec46d7d425c668b13c1849aab4351f

**Comment by Darktotaled** [comment]
Sorry for not replying earlier. Most sounds mods come with just loose files to be thrown on sound/mods folder. Didnt see any mod doing any different from that.
