### ISSUE TITLE
Vortex freezes loading at spash screen after installing a very large amount of mods.

### ISSUE THREAD

**Issue by GitTINE** [Nexus-Mods/Vortex#4262]
**Describe the bug**
I was installing all the mods I had downloaded which totaled over 1,460 mods.

**To Reproduce**
1. download over 1,450 mods
2. install them all.
3. restart vortex
4. vortex will freeze at splash screen

**Expected behavior**
Vortex to start and show lots of installed mods.

**Platform (please complete the following information):**
 - OS: Windows7
 - Vortex Version
0.17.11

**Additional context**
My staging folder is on a separate drive(g) than my vortex install(c).
My vortex download folder is on yet another drive (z)

I wasn't planning on using all the mods at once, just have them installed so they could be updated and used in different configurations with profiles.

System has 32gigs of ram,  All hard drives have 10+gigs free space at all times.

**Comment by TanninOne** [comment]
The crash is unrelated to the number of mods or memory used. It's caused by chromium being unable to find a font to render some text (unknown what it is) even though the operating system is supposed to have fallbacks for all unicode characters.

**Comment by GitTINE** [comment]
Ok, well I don't think there's much more that we can do about this one, as the logs ran out of their history limit, and reinstalling 1,400 mods will take me quite a long time.   Most of those mods came from nexusmods.com and were installed with the hourly limit, so it would take many weeks(months) to repeat, I may re-download some, if I run into the problem again I will reopen this issue.
However I will be backing up my entire user vortex folder regularly due to the huge pain in the butt this has caused. 
Vortex doesn't save its metadata along with the downloads or have a way to import that data, so if I just drop the mod archives into the "drop files" spot, they won't be linked to the online copy which allows one to run the updates, making updates MUCH easier, and it lets you read the online info by simply right clicking the mod.
Feel free to close this issue, as it will take me many months to rebuild the downloaded mods.   :)

**Comment by TanninOne** [comment]
You can use the "Query Info" function on the downloads page to get the meta information for downloads from nexus mods, as long as the file (still) exists on Nexus. After that you should also be able to check the mod for updates and everything.
