### ISSUE TITLE
plugins disappear on startup vortex

### ISSUE THREAD

**Issue by twillinator** [Nexus-Mods/Vortex#4270]
not sure if its since vortex updated but.
every time so far that I've booted up, the plugins section is empty, even though all mods are installed and enabled. This means I have to manually deploy mods again and bulk enable the plugins, this of course makes me worried that my game may become unstable or some mods that need others to be activated first wont work. 
however i have not seen many issues if any in game so far so this is more a heads up then a holy ghost of doom situation.

**Comment by twillinator** [comment]
Not had it since i last reported this so i can't check, so for now the later seems to be if it happens again where do i look?

**Comment by IDCs** [comment]
@twillinator, inside your game's data folder, so for Skyrim it would be under:
"C:\Program Files (x86)\Steam\steamapps\common\Skyrim\Data\" when installed using steam.

**Comment by IDCs** [comment]
Going to close this issue for now, as you've mentioned that it's gone. Please re-open this issue if you happen to encounter it again!
