### ISSUE TITLE
Vortex 0.17.11 - Mod and Archive Unexpectedly Deleted (Enderal..Managed)

### ISSUE THREAD

**Issue by digitaljc** [Nexus-Mods/Vortex#4280]
When selecting the 'Remove' option button and ensuring only 'Remove Mod' is selected,  ('Delete Archive' unchecked), both the mod and associated archive are deleted.

 

Has anyone else run into this issue; known bug and/or fix?

**Comment by IDCs** [comment]
Hi @digitaljc, I'm unable to reproduce this on my end. Are you certain that the archive was indeed present at the time you attempted to remove the mod ?

Also can you please let us know which mod you were using when you encountered this issue ?

**Comment by TanninOne** [comment]
closed due to lack of feedback
