### ISSUE TITLE
7DTD when launched via vortex says steam isnt running

### ISSUE THREAD

**Issue by Darktotaled** [Nexus-Mods/Vortex#4283]
So, today i was going to play 7dtd. Launched steam, waited for it to open up as it takes some time on my machine for whoever knows the reason, then opened vortex and launched 7DTD from there. Game loads and give me a prompt saying steam isnt running. Pressing retry ingame doesnt work. So i exited the game and look it up my steam and no issue there. Even launched 7dtd from there with no issues. Tried again with vortex and no luck on that. Before posting the issue, i tried running vortex with admin rights and the game worked, but my mods didnt.

Win 7 Ultimate x64
Vortex 17.11
7DTD 17.2

Edit: I checked the mod folder and it was empty. Had to reinstall all mods via vortex and lost my character data. Map was still there though. Game is working with admin rights and reinstalling the mods, lost progress on the char, but at least i can play. Dont know why the mod folder was empty though

**Comment by IDCs** [comment]
Hi @Darktotaled, first of all we strongly suggest **against** running Vortex with admin rights as any file operations made by Vortex at that point may restrict file access for all other accounts on your system. So if you were to modify some game configuration files with Vortex (with admin rights) and then attempted to change said files from within the game (using your regular account), the game itself may then have trouble writing to its own files!

Onto the task at hand (apologies if I seem pedantic in the items below , but wording is really important here):
1. You mentioned that the game loads and gives you the Steam isn't running prompt. Does the game actually start up ? or is it the case that you click the launch button within Vortex and immediately get the Steam isn't running prompt ?

2. Pressing retry in-game ? which retry button do you mean (Please send us screenshots if possible)?

3. Sad to hear you had to re-install your mods, did you try to click the deploy button before re-installing the mods though ? if so did you get any error prompts ?

**Comment by Darktotaled** [comment]
I do know vortex shouldnt be in admin mode but unfortunately thats how i got it working. Any problem that happens after that is completelly on me.

1. Click the run game button on vortex, game starts, loads and the prompt appears before the main menu appears. It gives 3 options: Retry, play offline(dont work) and exit game.
2. Dont have a screenshot as i made it work later but i got a similar screenshot on the forums: http://prntscr.com/neci8u
its basically the same screen, but now it has a play offline option that doesnt work.
3. I did try deploying which did nothing. i saw that a file called vortex deployment appeared in the game folder and in the mods folder but no mods in either of them. Reinstalling the mods via vortex put the mods back into the mods folder though.
4. I don't remember seeing any prompt but i do remember that i came here posting about vortex putting the files in the wrong place and i got redirected to download the 17.11 version. i took my mods of the mods folder, installed that version of vortex, and installed via vortex to see if it was putting the mods in the correct folder this time, which it was. Maybe there was no prompt cuz there was no mod inside the mods folder?

Itend to be as active i can on github cause helping you bringing issues also helps the community when it gets fixed.
Best of wishes as always.

**Comment by IDCs** [comment]
Thanks @Darktotaled, I've actually managed to reproduce the issue you've reported and commited a fix https://github.com/Nexus-Mods/vortex-games/commit/db8437e0a07b7c382ab1b94b122f56364c7a7eab

The fix will be available in future testing releases (I'll ping you once a new one is out)

**Comment by Darktotaled** [comment]
Thanks and again, sorry for the late reply
