### ISSUE TITLE
Certain UI colors can't be changed 

### ISSUE THREAD

**Issue by LiamPH** [Nexus-Mods/Vortex#4300]
Almost all the UI colors can be changed via the theme options, but there are a few exceptions:

 - Some elements of the graph on the download tab (the one showing download speed) change color, but the gradient under the main line is always orange regardless of user choices. (See screenshot)

- The button to use the file browser cannot be set to not turn orange when hovered over

- Links also cannot be set to not turn orange when hovered over

- The 'run' button on tools in the starter dashlet cannot be set to not turn orange when hovered over or clicked

IMHO, these colors should be allowed to be changed based on user input to a custom theme just as all the other colors can be

![there should be no orange](https://user-images.githubusercontent.com/49850814/56480456-6206a800-6477-11e9-821f-fd43aca978a1.PNG)

**Comment by TanninOne** [comment]
The gradient is controlled by "stop-color", "stop-opacity" css property on classes "graph-gradient-start" and "graph-gradient-end" like this:

```
.graph-gradient-start {
  stop-color: rgba(0, 255, 0, 1);
}

.graph-gradient-end {
  stop-color: rgba(0, 0, 255, 0.5);
  stop-opacity: 1;
}
```
