### ISSUE TITLE
Vortex incorrectly installs Stardew Valley mods with multiple folders

### ISSUE THREAD

**Issue by Pathoschild** [Nexus-Mods/Vortex#4364]
**Describe the bug**
If a mod download has multiple root folders, Vortex incorrectly discards all but one of them.

**To Reproduce**
1. Download [Farm Extended](https://www.nexusmods.com/stardewvalley/mods/3496?tab=files) ([archived download](https://github.com/Nexus-Mods/Vortex/files/3136282/Farm.Extended-3496-1-1-1-1551782288.zip)) through Vortex.
2. Install and deploy it.
3. Check the `Mods` folder. Only one folder is installed.

**Expected behavior**
Each of the mod folders should be installed. This is common for a subset of mods that contain multiple components.

**Screenshots**
The Farm Extended download has two folders:
> ![](https://user-images.githubusercontent.com/230581/57049161-ca5a4400-6c44-11e9-91ee-50115c615ad3.png)

But Vortex only installs one of them:
> ![](https://user-images.githubusercontent.com/230581/57049181-e65de580-6c44-11e9-90c8-a0c22c14eb55.png)

**Platform:**
 - OS: Windows 10
 - Vortex Version 0.17.11

**Comment by IDCs** [comment]
Fixed in https://github.com/Nexus-Mods/vortex-games/commit/0f587d77e516a59b33e2843c79c855bd94bdd57f
