### ISSUE TITLE
No deployment method available (Dark Souls II)

### ISSUE THREAD

**Issue by DaemonPhoenix42** [Nexus-Mods/Vortex#4415]
I have Tried with both custom and native install location, respectively.
I have the mods directory as well as downloads on the same drive.
- Mods: 
"G:\Game Files\Vortex\{game}\mods"
- Downloads: 
"G:\Game Files\Vortex\downloads"

Having also changed these paths around in other ways attempting to pinpoint the issue but to no avail.

I've modified my permissions for the (G:\) drive (which I feel shouldn't have to as my user profile is listed as an admin account) and I disabled read-only for the directories listed above as well as my game directories.
Even if I wanted to "Run as Administrator" the application refuses to post and hangs on the splash logo.

All I want is to mod dark souls 2 which ModOrganizer2 doesn't have support for.

I expected this to work.
the error won't go away and I have no options for deployment.

![ehtaheaher](https://user-images.githubusercontent.com/36192863/57328028-2d286100-70c5-11e9-9ab6-dccf3f31c5b8.PNG)
Transcription:
- Problem
Can't Write to output directory.
- Solution
To resolve this problem, the current user account needs to be given write permission to "".

How can I know what to modify if it's an empty string?

 - OS: Windows 10
 - Vortex 0.17.11

I even attempted rebooting multiple times after modifying the settings for vortex and the windows itself.

Also the implications of disabling read-only on all of these files seems antithetical to the reason the option is there, as in my local account that has admin privilege (mind you this is "my" account and not the default local admin account); this account should have access to modifications while say my friends local account can't go and maker changes without specific permissions.

I might be missing something here, I wouldn't doubt it, but this is the way I'm framing it in my head. If you have any information regarding please enlighten me and get this sh!t working.
- Thank You

**Comment by TanninOne** [comment]
Hmm, Didn't you get another message as well?
Dark Souls 2 (or rather: many mods for it) requires GeDoSaTo to be modded successfully and Vortex needs to be able to discover it automatically (through the "InstallPath" registry key at "HKEY_LOCAL_MACHINE\Software\Wow6432Node\Durante\GeDoSaTo,
And then Vortex needs write permission to <path to GeDoSaTo>\textures\DarkSoulsII directory.

I think the error message means you don't have GeDoSaTo installed or the registry key doesn't exist and so Vortex doesn't know where it is and how to deploy there.

**Comment by DaemonPhoenix42** [comment]
Interesting I honestly was unaware of "GeDoSaTo", I don't beleive I receive another message or anything; 
I attempted to be as thorough as I could with my information but I honestly believe you're 100% on the money with 'GeDoSaTo' and I will look into it. thank you for the information.

I have since tried Skyrim as a means to verify it did not persist and it looks like Skyrim has no issues.

**Comment by TanninOne** [comment]
Can't really help with installing gedosato unfortunately.

If you find anything else, please let me know, if I don't hear back from you I'll assume this is resolved by installing gedosato.

**Comment by DaemonPhoenix42** [comment]
Thanks for the information, quite some over site on my part as I don't think you guys even supports mods for the "Scholar of the first sin" version of the game, so I managed to get it to recognize The original release of Dark Souls 2 after installing it as I do own both copies.
