### ISSUE TITLE
Bug: Quickly toggling mods in NMM import may mess up displayed size requirement

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#4416]
**Describe the bug**
When quickly toggling a mod between "Import" and "Don't Import" the required sizes displayed in the footer are wrong

**To Reproduce**
1. Go to 'Import from NMM'
2. Click Setup to get to the mod list
3. Slowly disable all mods, you should see the required sizes to be 0
4. Pick any mod (ideally not a small one) and quickly toggle it on/off several times by clicking on the button
5. Observe the required sizes becoming <> 0 even with all mods disabled

**Expected behavior**
Correct size requirements

**Assumption**
I assume this happens because the mod size is recalculated each time (which may take time), and then a delta added to the total, this can probably become messed up if you manage to toggle the mod again before calculation is done

**Suggestion**
Calculate the mod sizes once, cache in component state, then you can recalculate the totals synchronously.

**Comment by IDCs** [comment]
Fixed by https://github.com/Nexus-Mods/extension-nmm-import/commit/a24e9c077bd8cd8d3a07a0a06b8082c1d0058d68 (fixed as part of 1.0 to invalidate #4700)
