### ISSUE TITLE
nearly all mods redundant

### ISSUE THREAD

**Issue by kesirov** [Nexus-Mods/Vortex#4446]
After making a new profile on vortex nearly my whole mod list is redundant. I tried reapllying all rules, but it didnt work. After that Fnis for skyrimse constantly resets the load order for some of the mods and never saves the changes. Everytime i launched fnis again it said error.

Expected behavior
Making a new profile and then reanabling all my mods for another verison of my list.

![Unbenannt](https://user-images.githubusercontent.com/50520494/57570112-eefdab00-73fe-11e9-851b-348173faec6e.PNG)
![Unbenannt1](https://user-images.githubusercontent.com/50520494/57570115-f58c2280-73fe-11e9-86d7-c9db3e0055bd.PNG)
![Unbenannt2](https://user-images.githubusercontent.com/50520494/57570116-f755e600-73fe-11e9-9c26-39e6f6dd50a5.PNG)
![Unbenannt3](https://user-images.githubusercontent.com/50520494/57570117-f8871300-73fe-11e9-9114-22cee21f3e3f.PNG)
![Unbenannt4](https://user-images.githubusercontent.com/50520494/57570118-fa50d680-73fe-11e9-8472-44f8f510c8d9.PNG)

Platform 
 - OS:  Windows 10
 - Vortex Version 01.17.11

**Comment by kesirov** [comment]
it looks like i need to reinstlal all the mods again

**Comment by TanninOne** [comment]
Why do you need to reinstall mods?

**Comment by phase31** [comment]
> it looks like i need to reinstlal all the mods again

did this solve your problem??? im having the same issue

**Comment by jqxctl** [comment]
Made an account just to drop in here. The same issue happened to me today, but only after I switched from modding Skyrim to Oblivion and then back to Skyrim. Hoping for some kind of resolution!
