### ISSUE TITLE
Failed to get Access Key

### ISSUE THREAD

**Issue by ZytheSanguine** [Nexus-Mods/Vortex#4529]
It won't let me log in to Nexus, and just keeps spitting out the same error. (See attached screenshot). At first I thought it was just the Nexus server being wonkey, but it's been persistent for a couple days now. Tried a fresh install, adding firewall exceptions, changing my default browser, etc. No luck. 

Not quite sure how it happened or how to reproduce it on your end. It worked fine one night. Powered down after installing some mods, and when I fired it back up the next day it just didn't work.

No VPNs, proxies, or any fun stuff like that on my end. 

![Untitled](https://user-images.githubusercontent.com/31974680/58232065-67147c80-7ced-11e9-8021-12744d2d4f88.png)

**Comment by IDCs** [comment]
Hi @ZytheSanguine, are you still experiencing this issue ? If so, weird request - can you please re-assign your external IP by restarting your router and let us know how that goes ?

**Comment by ZytheSanguine** [comment]
Yeah, I am/was still having issues but I just figured it out. 
Resetting my router didn't fix it but that got the ol' gears turning. 

After playing with some settings in device manager it turns out Vortex just hates my NIC for some reason. It works fine if I disable my NIC, and use Onboard ethernet, but if I have both of them enabled or just my NIC enabled I get the same error. 

So it looks like it's a problem with NICs.

BTW, my network card is a Killer E2100 if that matters.

**Comment by IDCs** [comment]
Hi @ZytheSanguine, silly question but were both NICs connected to the same router? Because that may cause some network collisions, although I would expect most OS's to simply choose one interface and just use that.

**Comment by ZytheSanguine** [comment]
Yes, they're both connected to the same router, but the issue appears to be with the network card. 

If I disable the onboard ethernet controller so that my NIC is the only thing connected it still gives me this issue. The only way to get it to connect is to disable my NIC and use the onboard Ethernet controller.

**Comment by IDCs** [comment]
A very peculiar issue for sure. Thank you for bringing it to our attention and I'm glad you managed to sort it out. I'm going to close this issue given that it's fair to assume that this was down to hardware/environment configuration rather than Vortex itself, but please feel free to post any new findings here to help other users which may experience similar problems. (I did look up your NIC to see if I can find something with no luck)
