### ISSUE TITLE
Feature requests; else Ideas for extensions.

### ISSUE THREAD

**Issue by daephx** [Nexus-Mods/Vortex#4538]
### Similar ability to "make primary" but have it linked to profile.
- Would be helpful for running different executable, depending on profile. 
1. SKSE.exe -- Skyrim.exe
2. DARKSOULS.exe -- DARKSOULS.prerandomizer.exe

Maybe a custom script?

### Opening downloaded archives from UI (without Installing)
- Pretty simple, Often I'll want to check out the contents of an archive and/or extract files individually without having to install or navigate to my download directory.

**Comment by TanninOne** [comment]
I added an action to open downloads in the default (system) archive manager: a76478b40f55d4284c4985411d02ec2ed4aabf0e
The first request is sensible but it's fairly complex and will have to wait.

Please in the future don't make multiple requests in one report, we can't track issues properly this way

**Comment by DaemonPhoenix42** [comment]
Understandable, thank you and good luck!

**Comment by TanninOne** [comment]
The biggest issue I see with the first request at this time is that the UI would have to make it very clear which executable actually gets run if it's different per profile.

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
