### ISSUE TITLE
Your report contains too little information

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#4637]
You sent in a bug report that contains little to no information and is therefore not useful.

When you send in a report, provide all information that could be useful to us **in the first report**. Don't send in a one line report "it don't work" and expect us to ask you personally for added information, that's a waste of time and it would require you have a github account.

Just take a minute or two to provide as much information as you can, this improves the chance of getting the problem fixed a hundredfold.

Every bug report needs to contain
- Does the error happen every time or was it only once
- What are you doing (ideally with a step-by-step that triggers the issue)
- What happens (in as much detail as you can)
- What did you expect to happen

Depending on the situation these things are often useful
- log files
- screenshots (if there is anything to see)
- application state

If the bug refers to mods, always include the name of the mod, the exact version and variant and a link.

If the bug refers to a file on your system (something like "savegame can't be parsed", "ini file can't be read") - include the file in your report.

In general: use some common sense. Include whatever you think might help us find the problem. 

We usually can not fix issues that we can't see for ourselves and even when we can we can't verify if the fix works so sending a bug report that demands we just "trust you" on something doesn't make sense, whether we trust you or not doesn't matter. If we can't verify a bug exists we can't verify when it's fixed.

**Comment by cdrhiller** [comment]
So it appears there is no Vortex help available.   Too Bad.   BTW, as if it means anything, I use Firefox.
