### ISSUE TITLE
Erro bug

### ISSUE THREAD

**Issue by getsemanne** [Nexus-Mods/Vortex#4730]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by getsemanne** [comment]
the vortex developers require your assistance a bug/suggestion on which you have submitted. To view o ur response please click on any of the below links:

**Comment by TanninOne** [comment]
No power to drugs!
