### ISSUE TITLE
SkyrimSE's Mods should be allowed to import SkyrimVR

### ISSUE THREAD

**Issue by SwimmingTiger** [Nexus-Mods/Vortex#4768]
There is no SkyrimVR option in NMM, as we all know. So we chose SkyrimSE and then specified a SkyrimVR directory.

But Vortex supports SkyrimVR, so we no longer need to do this.

Then the question is how to import these Mods into Vortex's SkyrimVR. The current version cannot be imported at all. It will prompt "cannot find the NMM installed for this game."

**Comment by TanninOne** [comment]
Not every SSE mod is supported in SkyrimVR, also newer NMM versions do support it, so it would affect only a very small number of users.
While I see the point of this request I just don't see how it'd be worth it.

**Comment by TanninOne** [comment]
closing for the reasons mentioned above
