### ISSUE TITLE
Profile comparison

### ISSUE THREAD

**Issue by Angahran** [Nexus-Mods/Vortex#4950]
I have multiple profiles for Skyrim SE because I like to install mods and sometimes that breaks things. So, I like to have a 'clean' base profile I know works and then I copy this when I want to experiment.

**Describe the solution you'd like**
I would like the ability to compare two profiles and see exactly what is different so if a profile stops working I can see exactly where to start investigating.

**Comment by TanninOne** [comment]
duplicate of ##3307
