### ISSUE TITLE
Cannot detect missing DLCs (Fallout 4)

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#4967]
**Describe the bug**
Vortex appears to unable to detect when official DLCs for Fallout 4 are not installed. 

**To Reproduce**
Install a mod with all DLCs required (e.g. https://www.nexusmods.com/fallout4/mods/24737?tab=description)
Delete any DLC ESM files in your data folder.
Vortex will not report any errors with the plugins missing.

**Expected behavior**
Vortex/LOOT reports an error when the DLCs are missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/31670524/60099002-adc31f80-974e-11e9-8506-a3c0f7b114f3.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 0.18.9

**Additional context**
I have not tested with other Bethesda games. I did not delete the ESMs, I do not own the DLCs.

**Comment by IDCs** [comment]
fixed in https://github.com/Nexus-Mods/extension-plugin-management/commit/0975eb88ebaccd645ae2f8041f588164e0721df0
