### ISSUE TITLE
Suggestion - OpenMW support

### ISSUE THREAD

**Issue by XJDHDR** [Nexus-Mods/Vortex#4997]
I am wondering if there is interest in adding support for OpenMW. Since it is an engine replacement for Morrowind, I think much of the code Vortex uses for that game can be re-used for OpenMW. There are two main things I can think of. 

First, OpenMW stores it's data file configuration data in "%USERPROFILE%\Documents\My Games\OpenMW\openmw.cfg"
For installing mods, OpenMW allows you to install mods the regular way by putting them into Morrowind's Data Files folder. They also offer another way through that config file. That file accepts an entry _data=_ which defines where the engine can find the data files it needs. By default, it has one entry which states where Morrowind's Data Files folder is. However, it is possible to add additional _data=_ lines to that file indicating where you have placed the files for mods. These folders need to be configured in the same way they would if the files were placed in the Data files folder. The engine will then load files from all of those locations. It will also load files in the order that they appear in the config. Later entries will override earlier ones. 
If you decide to support OpenMW, it might be an idea to add this as one of the ways you can deploy a mod.

The other main difference is that OpenMW activates ESP/Ms through that config as well. There are a number of _content=_ lines in that file. Each one is for an ESP or ESM that has been activated and the engine loads them in the order they appear in the file.

For reference, here is the relevant section of my openmw.cfg:
```
data="D:\Games\GOG\Morrowind\Data Files"
data="D:\Games\OpenMW files\OpenMW Mods\1 - Patches\1 - Unofficial Morrowind Patch"
data="D:\Games\OpenMW files\OpenMW Mods\1 - Patches\2 - Correct UV Rocks"
data="D:\Games\OpenMW files\OpenMW Mods\1 - Patches\3 - Landscape texture fix v2"
data="D:\Games\OpenMW files\OpenMW Mods\1 - Patches\4 - UMPP Fixes - 40947"
data="D:\Games\OpenMW files\OpenMW Mods\1 - Patches\5 - GMST Vaccine"
data="D:\Games\OpenMW files\OpenMW Mods\1 - Patches\6 - Master Index v1.0 (42482)"
data="D:\Games\OpenMW files\OpenMW Mods\2 - Mesh replacers\1 - Mesh Improvements v1.71"
data="D:\Games\OpenMW files\OpenMW Mods\2 - Mesh replacers\2 - Better Bodies v2.2 (3880)"
data="D:\Games\OpenMW files\OpenMW Mods\2 - Mesh replacers\3 - slofs_better_beasts_1.2"
data="D:\Games\OpenMW files\OpenMW Mods\2 - Mesh replacers\4 - newbeastbodies33clean"
data="D:\Games\OpenMW files\OpenMW Mods\2 - Mesh replacers\5 - new-beast-bodies-slof-tex-3.3-clean"
data="D:\Games\OpenMW files\OpenMW Mods\2 - Mesh replacers\Unused"
data="D:\Games\OpenMW files\OpenMW Mods\3 - Texture replacers\1 - Title Screen Reworked (Widescreen) v1.0 (43657)"
data="D:\Games\OpenMW files\OpenMW Mods\3 - Texture replacers\2 - Morrowind Visual Pack v3.0 RC 1"
data="D:\Games\OpenMW files\OpenMW Mods\4 - Animation Replacers\1 - DN 1st Person Enhanced v2.1 (44080)"
data="D:\Games\OpenMW files\OpenMW Mods\4 - Animation Replacers\2 - DN 1st Person Enhanced v2.1 (44080) - Argonian swimming"
data="D:\Games\OpenMW files\OpenMW Mods\4 - Animation Replacers\3 - Dirnaes Beast Animations v1.0 (42080)"
data="D:\Games\OpenMW files\OpenMW Mods\6 - New files only\Argonian First Guard Armour v1.021"
data="D:\Games\OpenMW files\OpenMW Mods\6 - New files only\House of Mannequins-3611"
data="D:\Games\OpenMW files\OpenMW Mods\6 - New files only\Demon Xen's Werecrocs!"
data="D:\Games\OpenMW files\OpenMW Mods\6 - New files only\werecrocs! Expansion by Tornadominds"
data="D:\Games\OpenMW files\OpenMW Mods\7 - New Plugins only\Madd Leveler v1b"
data="D:\Games\OpenMW files\OpenMW Mods\7 - New Plugins only\No CharGen MessageBoxes"
content=Morrowind.esm
content=Tribunal.esm
content=Bloodmoon.esm
content=No CharGen MessageBoxes.esp
content=Madd Leveler - Base.esp
content=DX_WereCrocs!.esp
content=House of Mannequins v1.0.esp
content=Firstguard_Armour.esp
content=Better Bodies.esp
content=DN_1stPersonArmorVA.esp
content=DN_1stPersonBodiesBBNB.esp
content=DN_1stPersonClothesVA.esp
content=New Argonian Bodies (Slof Textures) - Clean.esp
content=New Khajiit Bodies (Slof Textures) - Clean.esp
content=Morrowind Patch 1.6.5 Beta (BTB Edit).esm
content=adamantiumarmor.esp
content=AreaEffectArrows.esp
content=bcsounds.esp
content=EBQ_Artifact.esp
content=LeFemmArmor.esp
content=entertainers.esp
content=master_index.esp
content=Siege at Firemoth.esp
```

**Comment by XJDHDR** [comment]
I just found this extension for Mod Organiser 2:
https://www.nexusmods.com/morrowind/mods/45642

What it does is take your list of activated mods and plugins in MO2 and adds them to OpenMW's openmw.cfg in the format required that I referenced in the OP. It even retains load order for both lists. If and when someone wants to look into this suggestion, it may be a good idea to look at this extension's source code. It is written in Python.

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As there is no existing extension in Vortex for this, it is unlikely that we will commit to creating one for Vortex and instead consider adding support for it in the Nexus Mods App.

As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
