### ISSUE TITLE
NMM import - drop import of installed mods

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5020]
Drop the import of installed mods entirely. Instead, copy only archives over from NMM, fetch meta information, then offer the user to install these mods fresh through Vortex.

By being simpler it should be more intuitive what to expect from the process. Since we're not saying "we now import your NMM setup" but just "ok, we copied your archives, now you can install these" it should be more obvious that things like load order aren't transferred.

This addresses problems a) and d) and since we're not dealing with profiles at all - unless the user does so on their own, it should also solve problem c)
It does nothing for problems b) and e)

**Comment by AugustaCalidia** [comment]
I prefer #5021. If that's not a workable solution, then I support this option.

**Comment by HadToRegister** [comment]
This solution if _all else_ fails.

**Comment by HadToRegister** [comment]
Only if other optional fail to work.

**Comment by kennethfogarty** [comment]
I think, from a purely reputational perspective, and going on the many reports of people performing a migration from NMM to Vortex and having it fail, thus blaming Vortex this may be worthy of consideration.

**Comment by TanninOne** [comment]
I think this and 5021 can be combined in a way.

Instead of importing installed mods by copying over the files we'd just fetch a list of which mods are installed in NMM, then ask the user to disable them now, then install the mods fresh as part of the import wizard.

The way I'm envisioning it right now could be almost like a tutorial where we show the user how mods are installed, conflicts are resolved and plugins ordered in Vortex, pointing out the differences to NMM.

**Comment by HadToRegister** [comment]
/The way I'm envisioning it right now could be almost like a tutorial where we show the user how mods are installed, conflicts are resolved and plugins ordered in Vortex, pointing out the differences to NMM.//

Excellent idea, this way the person has to interact and learn about Vortex and get familiarized with it

**Comment by IDCs** [comment]
NMM import will no longer import extracted mods; only archives. We opted to keep this system simple due to the 1.0 deadline, but we will definitely look into adding an on-boarding wizard in the future.
