### ISSUE TITLE
NMM import - more granular, descriptive wizard

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5021]
We do keep the import process but have it more "granular", meaning more steps, some of which would just be explanation texts like "you now need to go to NMM and uninstall your mods, do not continue before you've done that".
and "Your load order has been reset to this: <list of plugins>. Because Vortex uses a different mechanism for load ordering it's not possible to import this but this order should still work fine, try it".
Again, this should make it more explicit what the import process does and doesn't do, thus helping with a,b, c and e to varying degrees but not actually 100% fixing anything

**Comment by AugustaCalidia** [comment]
Would it be possible to add a check box to each step so that one would not be able to initiate the import process until all boxes were checked?  Otherwise I fear that some people would just plunge ahead blindly (as they do now) and meet with disaster.

**Comment by AugustaCalidia** [comment]
For reasons of public relations, I think it important to have an import option.  However, I also think this process should be a kind of obstacle course whose purpose is not only to help ensure a successful import, but also to educate the user.  Having steps to check off would also be a valuable troubleshooting tool in the Vortex Support Forum, should something go amiss.

**Comment by TanninOne** [comment]
I'm thinking the same thing. The import process could be a good opportunity to explain to the user how Vortex differs from NMM.
It could be more of a "guided mod installation for NMM users" instead of an "import"
