### ISSUE TITLE
NMM import - Deduce install order from NMM manifest 

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5022]
We can try to deduce the install order from the NMM manifest and reconstruct it in the form of rules. This would be fairly complex and error prone though.

It might resolve b) for many, maybe even most, users, but it could cause even more confusion when it fails and it does nothing to teach users about conflict resolution in Vortex.

**Comment by kennethfogarty** [comment]
I like this as an idea, but I agree, if it goes bad, it will go very bad, and it will also cause even more negativity around a process that is designed to try to help a migration. I think that the reputation of Vortex should not be negatively impacted for trying to do something positive.

**Comment by TanninOne** [comment]
Maybe we can integrate the existing install order as a suggestion into the conflict solving process but not actually force it.

So you'd still select the order yourself but the option would be displayed as
"Load before"
"Load after (like in NMM)"

If we can't deduce the order from NMM, we don't display a suggestion, no harm done.

**Comment by TanninOne** [comment]
I think this has pretty much been rejected.
