### ISSUE TITLE
NMM import - more NMM-like terminology

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5023]
We could try and make the file conflict screens have a more familiar ui to those coming from NMM, e.g. instead of "file conflicts" we could talk about "file being overwritten", instead of "load y after x" we say "overwrite x with y" or we display the conflict during mod installation in a more familiar dialog going "file xyz already exists" - "overwrite all", "skip all"

This would also make b) easier to deal with for NMM users. However I'm not a huge fan of spending the work on this and making the language more fuzzy and incorrect just so NMM users don't have to understand what Vortex actually does.

It doesn't teach users and may keep them from understanding the possibilities of the Vortex approach because they remain stuck in the mindset of files being replaced.

**Comment by HadToRegister** [comment]
The Terms "Load Before" and "Load After" aren't that difficult of a concept.

However, most NMM users think of "Load Before" "Load After" in terms of _Plugins only_, while they think of Overwrite in terms of _Textures, Meshes, BSA, and BA2_

Ideally, getting them to understand that "Load Before" (Be Overwritten), and "Load After" (Overwrite) is what should happen.

Load Before/Load After
Overwritten By/Overwrites

Now the Manage Rules page would look like this for the people who pick that option

DEFAULT
Bosmer Ceremonial Armor----BEFORE------New Colors Patch BCA
New Colors Patch BCA---------AFTER-------Bosmer Ceremonial Armor

ALT OPTION
Bosmer Ceremonial Armor----OVERWRITTEN BY------New Colors Patch BCA
New Colors Patch BCA---------OVERWRITES-------Bosmer Ceremonial Armor

Also, just a note here, please make the Manage Rules Popup Wider, some mods with long names end up making the BEFORE and AFTER boxes only show "after (sug", "before (su"

**Comment by kennethfogarty** [comment]
I agree with you that using NMM-specific verbiage is not going to help people understand the fact that Vortex is operating in a different way. I think that sticking to the correct nomenclature will (through osmosis) force people to understand key differences between the two managers.

**Comment by TanninOne** [comment]
The problem with having the terminology toggleable is that these users will then go on the forum or discord asking questions using that terminology which may cause confusion further down.

But I do agree that "load before" and "load after" is confusing, quite a few users seem to expect that rules they set up on the mods page affect their plugin order so a change in the "official" terminology may be necessary to distinguish.

It's also not necessarily clear that something that gets loaded/deployed/installed after something else also "overwrites" that.

My problem with the term overwrite is that (to me) it has the connotation of being destructive which is exactly what I want users to understand it is not.
Also, "overwrites" and "overwritten" is so - similar. If you just glance at it might be mistaken.

In MO I used "override" because it's similar enough but implies it's not the same thing. But I did take some pushback on that.

Maybe "x overlays y"? but what's the inverse then? "x underlays y"?
Or maybe just "x over y" = "y under x"?

**Comment by HadToRegister** [comment]
maybe

"Load After (Overwrites)"
"Load Before (Is Overwritten)"

I think veteran modders get the load before/load after, because they know the load order flows from Top to Bottom.

It's getting that idea across, that a mod/plugin that's lowest in the order will "overwrite' or "Take Precedence" over any mod/plugin loaded before it.

Personally I like "Load before and Load After", because I 'get' what it means.
So maybe the issue is just educating people in a better way to what Load Before and Load After mean?

**Comment by IDCs** [comment]
@TanninOne are we still considering changing conflict terminology ?

**Comment by TanninOne** [comment]
Yes, please leave it open for now.

**Comment by TanninOne** [comment]
I think this is off the table for now.
