### ISSUE TITLE
Extra confirmation before external changes dialog deletes files

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5024]
The "External Changes" could produce an additional confirmation dialog if files in the staging dir get deleted (it's rare that we actually want that)
This should alleviate problem e) with the NMM import by making it very clear that mods inside Vortex are getting damaged at that point and offering an opportunity to cancel.

This feature wouldn't only be useful in connection with the NMM import

**Comment by Rattledagger** [comment]
If "External Changes" deletion means #files in mod is zero, display warning mod will be uninstalled, and actually uninstall the mod if user chooses to delete all the mods files.
