### ISSUE TITLE
NMM import - warn if files are deployed through NMM

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5025]
We could try to automatically discover the NMM manifest (aka install log) corresponding to the files deployed inside the game directory and warn the user that there will be problems - or downright refuse to import mods until the user has uninstalled those mods in NMM.
This could tie into 1a where the import doesn't proceed until the user has uninstalled their NMM mods.

Again this should help with problem e) by pressuring the user into cleaning up their data directory.

It's possible we won't find the manifest automatically and then don't know that there are files deployed by NMM but worst case is the user doesn't get notified, they would be exactly where they are now so apart from the added work I don't see any drawbacks to this.

**Comment by HadToRegister** [comment]
Yes yes yes

**Comment by IDCs** [comment]
Vortex will block the import process if:
- We confirm that the user has enabled/deployed mods using NMM.
- NMM is running in the background (Running NMM alongside Vortex can cause plugin issues as both processes are fighting over the plugins.txt file)

The user will be showed a dialog stating they need to disable any enabled mods and close NMM before continuing; once the user has followed these steps, he can click the "check again" button which will re-check if the user has done this correctly before resuming the import process.
