### ISSUE TITLE
NMM import - don't mention profiles

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5027]
We could drop all mention of profiles from the existing import process if the user has profile management disabled, instead importing only into the default profile without further explanations or questions.

Aleviates c) and is probably what that user expects.

**Comment by IDCs** [comment]
This is actually already implemented in the existing process https://github.com/Nexus-Mods/extension-nmm-import/blob/8ddc6c370192381727a081ce84366724d824aacc/src/views/ImportDialog.tsx#L1003
