### ISSUE TITLE
Highlight empty mods

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5028]
We could highlight empty mods in the mod list to make it more obvious when mods have been damaged.

This could be further extended into a "content" column similar to what MO has, showing icons when a mod contains textures, meshes, ... and then a "mode" for that column when the mod contains nothing at all.

This isn't purely related to the NMM import, it could be useful in general.

**Comment by HadToRegister** [comment]
Any easy to spot visual cue is always welcome
