### ISSUE TITLE
Buffer cannot be null

### ISSUE THREAD

**Issue by jreidgreer** [Nexus-Mods/Vortex#5038]
**Describe the bug**
When installing "Fallout Character Overhaul" a popup window with an installer appears. Afterwords an unhandled exception occurs. It seems to also be triggered by hovering over the checkboxes of the installer.

**Exception Details:**

```
System.ArgumentNullException: Buffer cannot be null.
Parameter name: buffer
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at Script.GetImageFromFomod(String filename)
   at Script.<>c__DisplayClass4.<descMouseoverCall>b__0(Object sender, EventArgs args)
   at System.Windows.Forms.Control.OnMouseEnter(EventArgs e)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

<details> 
  <summary><strong>Loaded Assembly Information</strong></summary>
<pre>
************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
CSharpScript
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files/Black%20Tree%20Gaming%20Ltd/Vortex/resources/app.asar.unpacked/node_modules/fomod-installer/dist/CSharpScript.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
FomodInstaller.Interface
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/Black%20Tree%20Gaming%20Ltd/Vortex/resources/app.asar.unpacked/node_modules/fomod-installer/dist/FomodInstaller.Interface.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3416.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
tmpAADD
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files/Black%20Tree%20Gaming%20Ltd/Vortex/resources/app.asar.unpacked/node_modules/fomod-installer/dist/CSharpScript.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
</pre>
</details>

**To Reproduce**
1. Download "Fallout Character Overhaul" from [here](https://www.nexusmods.com/newvegas/mods/54460) via Vortex
2. Install from the Vortex UI
3. A popup installer will appear, and shortly after this exception will occur

**Expected behavior**
Installation proceeds without error

**Screenshots**

**Platform:**
 - OS: Windows 10
 - Vortex Version 0.18.12

**Comment by IDCs** [comment]
Hi @jreidgreer, it appears that the fomod script is unable to retrieve its own image files. Perhaps this is due to a faulty download. Can you please try to download the mod manually from the website and manually add it to Vortex by drag-dropping it inside the mods drop-panel.

Can you please also let us know how much RAM you have ?

Finally, please ensure you have the latest .NET framework version https://dotnet.microsoft.com/download

**Comment by TanninOne** [comment]
The error seems to happen as you hover over one of the options and it fails to load the corresponding screenshots.
This may indeed be caused by a corrupted download.
Technically it could also have been caused by the installer being invalid but I tried it out myself and hovered over every option available.

So to investigate, please let us know which option it was you hovered over, whether it happens every time and whether re-downloading helped any.

**Comment by jreidgreer** [comment]
@IDCs @TanninOne it seems after I installed .NET v.4.8 and rebooted it started working. Let me know if there's any other information I can get you to to help let me know.

**Comment by TanninOne** [comment]
Hmm, that would indicate you had either a very outdated version of .net (pre 4.6) before or the install was broken.

As I said, I checked the installer and it should work fine
