### ISSUE TITLE
So I have this bug where I have active mods but when I start up the game they aren't active in game and when I close the game vortex disables the plugins for them somereason. 

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [Nexus-Mods/Vortex#5069]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by PrinceJaxonHellsing** [comment]
here's what it looks like
![20190712223210_1](https://user-images.githubusercontent.com/48263377/61193649-cad27a80-a68a-11e9-8947-38a5c53bf290.jpg)
![bug](https://user-images.githubusercontent.com/48263377/61193670-ee95c080-a68a-11e9-92d3-efb3ef7d279f.png)
![bug2](https://user-images.githubusercontent.com/48263377/61193671-f05f8400-a68a-11e9-867d-d9e4803b1015.png)

**Comment by TanninOne** [comment]
The description template is there for you to fill out.

The second screenshot clearly shows that the plugins aren't deployed (that's what the crossed eye icon symbolifies)
There is a huge red bar across the top of the plugins tab telling you exactly that.

**Comment by PrinceJaxonHellsing** [comment]
ok.

**Comment by PrinceJaxonHellsing** [comment]
Thanks it actually worked!
