### ISSUE TITLE
[Skyrim SE/Skyrim] Check form version and BSA type 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#5093]
A problem many newer modders seem to encounter is that they install Skyrim LE mods for Skyrim SE. Plugins for the wrong version can cause save corruption and BSAs for the wrong version will prevent the game from starting (with no error displayed)

**Describe the solution you'd like**
Vortex may be able to pull the form version out of the TES5 record header. Form 43 is LE and 44 is SE. This could present a warning (or icon) in the plugins tab to make the user aware of this issue. 

When installing mods with BSAs, it may be possible to check the BSA version in some way to check if it's a compatible archive. This may slow down install/deploy though depending on how the differences are detected. 

**Describe alternatives you've considered**
A small flag when you've installed a mod that didn't come from the Nexus Mods game site intended for that game may also be a workaround. (This would be on the mods tab, not the plugins tab)

This functionality does not seem to be offered by any other mod manager at the time of writing.

**Comment by TanninOne** [comment]
The esp check is implemented in 0.19.0, bsa check I'll have to take some time for that.
We parse the esps anyway so there is no performance penalty but bsas we don't parse by default so we need to test if it would cause a slowdown.

**Comment by Pickysaurus** [comment]
I have created an extension that checks BSA versions, so we can probably close this now.
