### ISSUE TITLE
Allow window to be draggable and resizable during profile load screen.

### ISSUE THREAD

**Issue by rzjnzk** [Nexus-Mods/Vortex#5195]
Normally the Vortex window is draggable and resizable like any other window. However, after clicking 'Enable' a profile, a loading screen is shown that is not draggable, nor resizable, which, for convenience sake, it should be. 

Additionally, while implementing this, it might be a good idea to shrink the window size around the loading bar as to allow the user to work with other windows easier rather than having a large amount of real estate taken up by the large margins and padding.

**Comment by TanninOne** [comment]
The window doesn't change size while switching profile and it's not going to. You're not actually gaining any screen real estate if Vortex were shrunk during the process, either you bring a different application to the foreground to work with it - in which case that window will overlay the Vortex window anyway and then it doesn't matter how large the Vortex window is - or you don't, in which case you are _not_ working with a different application so it doesn't matter how large the Vortex window is either.

I can look into the resizing during these phases though.
