### ISSUE TITLE
Mod Pack management?

### ISSUE THREAD

**Issue by Merith-TK** [Nexus-Mods/Vortex#5213]
for the basic concept. (kinda a really rough idea here)

Allow us to group sets of mods together, and have it Link save files with those mods. so we can just toggle between our saves and the mods associated with them

For example.  You want to have 18+ mods, but also want to have a immersive game
Allow us to Select the 18+ mods, group those and add our save files to the group, and then let us select the Imersion mods, and group those together,

Or even, for example. We want to test a mod without fracking up our current save. We can save our current mods, and test the new mods and maybe decide to merge them

This way, we can have what is essentially a *mod pack* that we can toggle between

Yes. THis is a specific use case

**Comment by TanninOne** [comment]
This is what we have profiles for, it should already be working for what you want.

Mod Packs are generally considered a way to share your mod setup (profile) with other users.
