### ISSUE TITLE
My Mods Want to Go to NMM

### ISSUE THREAD

**Issue by FoxeltheFox** [Nexus-Mods/Vortex#5220]
So basically, when I click the Vortex button to download a mod, it decides it likes NMM more and tries to go there instead, even when it doesn't exist. I recently decided to give Skyrim a shot again and not go overboard with modding like last time (my pc is doo doo and will explode if I try to play it with good graphics). Now, all my mods were done through NMM and I have recently switched over to Vortex. I don't mind losing all my mods, except I didn't. I didn't know the mods would stay so I ended up having a bunch of old NMM mods mixed in with my recently downloaded Vortex mods. Me being the idiot I am, decided that deleting mods directly was a good idea, until I stopped mid-way and realized "Wait, this is stupid. Can't I just reinstall NMM and then delete the mods through there AND THEN go and uninstall it?" So I did just that, until I realized that's also stupid and just uninstalled and reinstalled Skyrim, essentially wiping everything for a very clean slate. Now the issue is, the Vortex button opens up NMM for the process, and when it's uninstalled and it just gives me a pop up that is seen in the picture below.

     I'm not sure how to reproduce it considering the circumstances.

     I expect the Vortex button to start a mod download in my Vortex application.

![2019-08-01](https://user-images.githubusercontent.com/48461536/62286572-dead0900-b40c-11e9-9e4f-6c210ccbe919.png)

     I am currently running on Windows 10 and am running the newest version of Vortex as of this point

     There was a point the Vortex button was working fine. It was just after I uninstalled and reinstalled Skyrim. It started acting up when I got down a few mods. I can download the mods manually just fine and drag them into the small box for files in Vortex, but if there's a button, I wanna use it!
     If I can get any help it'll be appreciated, thanks! Sorry for typos, it's   ##late. (P.S. Sorry if the answer is dumb or the question is kinda pointless, I'm not a very skilled file/mod manager. I was introduced to "automatic" modding first, so I never really dove into files. Also, if I have to dive into some files, please be specific! I'm not grandma levels of beginner, but as mentioned I do use automatic modding more. Be warned, if some file digging or otherwise is expected, be prepared for some questions. I can't just Google things to understand what you're asking me to do. Patience is required! Before you ask, yes, Vortex is allowed to handle mods that have a Mod Manager Download.)

**Comment by IDCs** [comment]
Hi @FoxeltheFox, Vortex should automatically set itself to handle NXM links on launch. This may be an issue with your browser. In Vortex, can you please go to Settings -> Download and click the fix now button and let us know if this solves this for you

![image](https://user-images.githubusercontent.com/8960252/62288037-687fc500-b453-11e9-8651-9ad12937bd18.png)

**Comment by IDCs** [comment]
@FoxeltheFox - Hmm, can you please startup Vortex and toggle the "Handle Mod Manager Download buttons on NexusMods.com" off and on again and then send us your vortex.log files (these are located inside your "C:\Users\_YOUR_USERNAME_\AppData\Roaming\Vortex\" folder)

Also, just wanted to confirm the version of Vortex you're running - is it 1.0.0

**Comment by FoxeltheFox** [comment]
@IDCs - Thanks for specifying the location of the files. I went over to there but couldn't find anything called a vortex.log to send you the files. If you meant the log folder that's in the Vortex folder then it was empty. I checked and am running on Vortex 1.0.0

**Comment by FoxeltheFox** [comment]
Holy smokes it just started working again. Did that toggle thing do the trick? I'm gonna download a couple more mods and so how it holds up

**Comment by FoxeltheFox** [comment]
@IDCs - Celebrated too soon, now my mods aren't appearing in game though Vortex says they're downloaded and enabled. I'm not sure if it affects all mods but I'm currently trying to install a house mod for my character and none of them are showing up. When I uninstall a mod that isn't showing up, the game doesn't give me the pop up saying that some content is no longer installed. It's almost like Vortex is saying it's good to go but in reality, it's not even modded in the game.

**Comment by IDCs** [comment]
Hi @FoxeltheFox, sorry for the late response - so you're saying that you're now able to download stuff with Vortex just fine?

Regarding the mods issue, please make sure you deploy once you enable any mods and confirm that the their files have been transferred to the game's mods folder "../Skyrim/data/"; if they have been transferred successfully then this is a problem with the mod itself rather than Vortex.

Give this one a test https://www.nexusmods.com/skyrim/mods/72366

**Comment by FoxeltheFox** [comment]
It's fine for the late reply @IDCs, just glad I got one! With the mod downloading, it worked smoothly when I was getting some a few days ago. So for now, yes the downloading is fine. I checked the mods folder to see the mod I wanted to use as my character's house was indeed in the folder. I'll need to test the mod you gave me later due to the fact that starting up Skyrim is very slow for me. Do you have any advice for the house mod not being active in-game? So much to the point that the game doesn't even acknowledge the lack of it in-game after it being installed and then uninstalled.

**Comment by IDCs** [comment]
@FoxeltheFox, can you send me a link to that house mod and I'll test it on my own environment.

**Comment by IDCs** [comment]
Hi @FoxeltheFox, I'm going to close this github issue as your original problem has been resolved but I'm more than happy to help you out with your mods setup - just send me a private message on the forums and I'll help you out.
