### ISSUE TITLE
Windows Defender flagging trojan in 1.0.0 native-errors/Detours node module

### ISSUE THREAD

**Issue by antcodd** [Nexus-Mods/Vortex#5231]
Windows defender is flagging ``C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\native-errors\Detours\bin.X64\member.exe`` as trojan ``Trojan:Win32/Skeeyah.A!MTB``

Virus Total indicates it is the only antivirus detecting this, so it is probably a false positive but please confirm as supply chain attacks are becoming more common.
https://www.virustotal.com/gui/file/255d34ac5786570b9066e325cb8bb2bac34411650ebfbac0906d315c516d3397/detection

**Steps to reprodce**
1. Download and install Vortex 1.0.0 from https://github.com/Nexus-Mods/Vortex/releases
or update
2. Window defender reports threats found and quarantines the file.

**Platform:**
 - OS: Windows 10 1903
 - Vortex Version: 1.0.0
 - Windows Defender Definition version: 1.299.1216.0 (4 August 2019)

**Comment by RobJTaylor** [comment]
Same issue here, as soon as vortex loads defender starts complaining.

Defender versions:
    Antimalware Client Version: 4.18.1907.4
    Engine Version: 1.1.16200.1
    Antivirus Version: 1.299.1180.0
    Anti-spyware Version: 1.299.1180.0

Windows version:
    1903 OS Build 18362.239

Threat details:
    Trojan:Win32/Skeeyah.A!MTB
    Alert level: Severe
    Location: `C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\node_modules\native-errors\Detours\bin.X64\member.exe`

Hopefully a false positive, but I'm not taking chances. Will be interesting if any more reports come in.

**Comment by TanninOne** [comment]
This is a false positive. It's safe to quarantine or delete the file though, it's not actually required by Vortex.

**Comment by syythe8282** [comment]
They have removed the files in the recent update :)
