### ISSUE TITLE
Plugin filenames are displayed with lowercase letters 

### ISSUE THREAD

**Issue by pStyl3** [Nexus-Mods/Vortex#5266]
**Describe the bug**
Using the `Lock Mod Index` feature in the `PLUGINS` tab on plugin X will lead to all plugins, that are between plugin X's original and new position, being displayed with exclusively lowercase letters, after the `Lock Mod Index` feature moved plugin X to it's new position.

**To Reproduce**
1. Give plugin X a lower or higher (locked) `mod index` than it's previous mod index
2. Let Vortex move the plugin

**Expected behavior**
The plugin names should always be displayed correctly, so if their names include uppercase letters, Vortex should also display those as such.

**Screenshots**
Before
https://abload.de/img/exampleoneymjzc.png

After giving `SkyUI_SE.esp` the mod index 15
https://abload.de/img/exampletwoatjhx.png

**Platform:**
 - OS: Windows 10
 - Vortex Version: 1.0.0

**Additional context**
Autosort was disabled.
This seems to be "fixable" by using `Sort Now`.

**Comment by TanninOne** [comment]
I think this is fixed in current releases or can you still reproduce it?

**Comment by TanninOne** [comment]
assumed to be fixed
