### ISSUE TITLE
[UI] Change buttons and...

### ISSUE THREAD

**Issue by vanja-san** [Nexus-Mods/Vortex#5291]
> Sorry for the bad english!

**Is your feature request related to a problem? Please describe.**
You do not have a very nice button layout!

**Describe the solution you'd like**
Maybe you should reconsider this !? For example (This is just an example, the decision is yours!):
![t](https://user-images.githubusercontent.com/7201687/63218301-d9c4b500-c181-11e9-8796-6a5f9a98ff17.png)

**Describe alternatives you've considered**
⇑⇑⇑ Above ⇑⇑⇑

**Additional context**
You can do something similar if you come up with even better!
and further
And please create repositories for translators, so that it would be more convenient to do the translation, otherwise (maybe only me) it is not clear which file to take as the basis of the translation!

**Comment by TanninOne** [comment]
You should be able to achieve that through a theme but for the official theme this has already been discussed and rejected
