### ISSUE TITLE
cant click send feedback

### ISSUE THREAD

**Issue by yggdrasil75** [Nexus-Mods/Vortex#5451]
**Describe the bug**
the Send Feeback button does nothing.

**To Reproduce**
Click hamburger in the top right
click send feedback
see it doing nothing

**Expected behavior**
should open send feedback page

**Platform (please complete the following information):**
OS: windows 10 1903 education edition
vortex 1.0.1

**Additional context**
I do have developer tools extension installed.

**Comment by TanninOne** [comment]
It works for me. Is anything in the log? If you open the dev tools before clicking on "Send Feedback", is anything reported to the console?

**Comment by yggdrasil75** [comment]
I dont see anything amiss in the log, there is nothing in the console at all, I can not click send feedback, when I go to click it, I click the titlebar instead. which is evidenced by double clicking the item causing it to change screen size. attached is the latest vortex log. I have restarted my computer since the issue began, and there is no change.
https://gist.github.com/yggdrasil75/3a00e039a3a07b67ffb2238e0bfea871

**Comment by TanninOne** [comment]
Right, sorry, it's connected to the theme. I'm using the compact theme and there the menu doesn't overlap with the titlebar.
