### ISSUE TITLE
Multiwindow css

### ISSUE THREAD

**Issue by yggdrasil75** [Nexus-Mods/Vortex#5452]
**Describe the solution you'd like**
I have a minor change I want made to vortex: either an id or a class for the vortex div which contains the flex used for having 2 screens shown simultaneously.

**Describe alternatives you've considered**
The alternative currently is manually adding the id multiwindow via developer tools to the div so that my css can see it

**Additional context**
I am wanting to do this so I can have mods on the left and plugins on the right instead of mods on the top and plugins on the bottom.

**Comment by TanninOne** [comment]
css selectors can reference chains of objects. The div you're trying to reference is the immediate and only child of #main-window-pane.

So what you want to do can be achieved with:
```
#main-window-pane > div {
    flex-direction: row !important;
}
```
