### ISSUE TITLE
An Unrecoverable Error Occurred....

### ISSUE THREAD

**Issue by Zeoinx** [Nexus-Mods/Vortex#5500]
**Describe the bug**
Brand new Windows install, fresh install of Vortex (Custom Location Installer).  When trying to launch, gets "EPERM : operation not permitted, mkdir 'C:\Users\Username\AppData\Roaming\Vortex' errno: -4048  syscall: mkdir code:EPERM path: C:\Users\Zeoinx\appdata\roaming\Vortex
If you think this is a bug, please report it to the issue tracker (Github)
**To Reproduce**
Fresh install, windows 7 pro, admin account, install vortex, launch program, and error appears.

**Expected behavior**
TO OPEN VORTEX SO I CAN USE THE PROGRAM.

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by TanninOne** [comment]
This has been discussed on the forum and in PM. Fix your permissions.
