### ISSUE TITLE
Download speeds can't pass 200kb.

### ISSUE THREAD

**Issue by brazzmo** [Nexus-Mods/Vortex#5517]
The "1MB" download speed cap for non-premium users is just a lie. Instead of capping at 1MB is caps around 200KB on a good day and 100kb most of the time (at least for me and most other people). There is nothing wrong with my internet (I've checked). It's honestly a shame that it's like this, because some of the bigger mods >500MB can take more than a day or two to complete with my computer on. Please fix this as soon as possible, its honestly just dumb and shouldn't be a problem in the first place. I've even heard that the same thing happens to actual premium users who PAY money to increase the cap...

This is ridiculous...
![image](https://user-images.githubusercontent.com/43312020/65803559-b7846680-e133-11e9-97c8-387c496ccb38.png)

**Comment by TanninOne** [comment]
This is not a Vortex issue, Vortex loads files as fast as the network will let it.
