### ISSUE TITLE
Vortex Will not launch, white screen only. latest version does not install. 

### ISSUE THREAD

**Issue by TriageONE** [Nexus-Mods/Vortex#5524]
DESCRIPTION:
After a fresh install of vortex, it installs, and starts, however, i get the vortex splash screen and nothing else. If i go into the app menu and click on vortex, a white screen appears and i cannot do anything. Iv'e already done these things:
- Reinstall 
- Install old versions (5 different versions)
- Restart the computer

My hardware:
Ryzen 5 3600X
RX 5700XT 
16GB of dual channel DDR4, 3200MHz

Install the manager, open it, it does nothing. 

**Platform:**
 - OS: Windows 10
 - Vortex Version 1.0.0 through 0.16.8, have tried all of them.
![screenshot](https://user-images.githubusercontent.com/28678092/65845419-316d4900-e308-11e9-8270-f8afe67294ad.PNG)

**Comment by IDCs** [comment]
Hi @TriageONE, any chance you had recently updated your ATI driver or installed graphics related software ?

Can you please attach your vortex.log file which should be found in "C:\Users\\{YOUR_USERNAME}\AppData\Roaming\Vortex"

Also have a look inside "..\Vortex\temp\dumps" and attach any dmp files you can find in there.

**Comment by Saipher604** [comment]
Hi I'm encountering the same issue since today. Reinstalling didn't work.

- Ryzen 3900x
- RX Vega 64
- 16 GB DDR4 @ 3600MHz

Here is the log, I couldn't find any dmp files, the application doesn't seem to be crashing. I was still able to close vortex by right-clicking the program in the task bar.


I did update my gpu drivers yesterday to the latest version I believe, but have only been encountering this since today.

**Comment by TriageONE** [comment]
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/3687870/vortex.log)

**Comment by TanninOne** [comment]
@Saipher604 @TriageONE There is no error being reported in either of these logs but as far as I can tell it stops at the point during startup where it's supposed to look for games installed through Steam.
Does that ring any bell for you? Do you have Steam installed at all? Anything "unusual" about your Steam setup? As in: Have you changed any access permissions for Steam directories, using junction points or "Steam Mover" to move games to a different drives?

**Comment by Saipher604** [comment]
@TanninOne I did reinstall Windows for a hardware upgrade. I copied the vortex appdata folder according to the wiki and made sure that the drive letter stays the same. It was working fine three days ago after I set up steam and vortex. Though yesterday windows launched the automatic file-system repair for the drive where skyrim is installed, maybe that messed something up. Up until that point everything worked as expected. I checked the access permissions and made sure that my user is the owner of everything but the result is still the same.

**Comment by TriageONE** [comment]
@TanninOne I have steam installed, and i have 4 drives with different purposes. 
I have a 512GB WD-Green 5400RPM drive that i use for storage purposes, and all my user-class directories are there such as downloads and documents, so that my C drive doesn't fill up. 
I have a faster 7200RPM 2TB SSHD i use for my games. Steam has record of this with its respective steam library folder. 
I also have a 512GB SATA SSD for games like path of exile or VR games, so that load times are not an issue. There is a steam library folder here. 
My boot drive is a 120GB NVME SSD with only windows and my programs on it, its about halfway filled. Steam's root is in the program files there. 

I recently tried this again and vortex cannot compose its graphical interface at all. The problem is the same for the latest version. The vortex.log is the same as above, and need not be posted another time since it is identical.

**Comment by Saipher604** [comment]
don't know if this helps, I was able to get it to work by going into "C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins"
and moving every game-* folder, except game-skyrim, into a backup folder. I only use vortex for skyrim and fallout 4. Moving back any other folder, including game-fallout4, causes the white screen again.
![grafik](https://user-images.githubusercontent.com/11271195/66222409-9f2ac380-e6c0-11e9-8d41-fe585f006d60.png)
![grafik](https://user-images.githubusercontent.com/11271195/66222514-dac58d80-e6c0-11e9-90da-225f7d1bb67e.png)

**Comment by TanninOne** [comment]
Please check if this error still happens in 1.1.2 @TriageONE  @Saipher604 
We found a bug in the library we use to parse steam manifest files (to discover games installed through steam) that would make it hang when it encounters a corrupted manifest file.

**Comment by Saipher604** [comment]
@TanninOne Everything seems to be working now on my end.
I can access the Fallout 4 page again.

**Comment by TanninOne** [comment]
Glad to hear it! Thanks for the feedback.
