### ISSUE TITLE
Missing Dependency Dialogue does not show a name

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#5570]
**Describe the bug**
The modal that pops out to inform you of unmet dependencies will sometimes not show a name for one or both mods. This tends to most commonly happen if the mod does not have a Nexus Mods ID linked to it. 

![image](https://user-images.githubusercontent.com/31670524/66751351-c46cbe00-ee86-11e9-9ec6-8b6f46ccb8d6.png)

The correct name appears in the "Dependencies" pop out.
![image](https://user-images.githubusercontent.com/31670524/66751415-dfd7c900-ee86-11e9-8baf-971215e44183.png)

**Expected behavior**
The name of the mod is shown. 

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.0.4 and earlier.

**Comment by TanninOne** [comment]
Should be fixed in https://github.com/Nexus-Mods/extension-mod-dependencies/commit/341de0142ea83eebcb4a9ff9883430c11a12d834
