### ISSUE TITLE
Vortex defaults to roaming appdata

### ISSUE THREAD

**Issue by barcharcraz** [Nexus-Mods/Vortex#5589]
**Describe the bug**
By default vortex downloads and installs mods in ~/AppData/Roaming, this means that anyone actually using both vortex and roaming user profiles will be "broken" (technically things will work, but it will take them potentially hours to log in).

~/AppData/Roaming is synchronized with network storage according to domain/active directory settings every time a user logs in or out. For things like vortex that create a lot of data ~/AppData/Local is the correct place for such data. Vortex configuration could still be stored at ~/AppData/Roaming though

**To Reproduce**
1. Join computer to a domain that uses roaming profiles
2. download some large mods
3. Log out
4. go to a different computer in the same domain.
5. Log in
6. observe bug

**Expected behavior**
I can log in quickly, but my mods are not synced

**Platform (please complete the following information):**
- OS: Essentially all windows (back to maybe NT4, not sure)
- Vortex: All

**Comment by TanninOne** [comment]
This is the intended behavior. AppData/Local according to MS is intended only for data that is specific to the current PC, usually stuff like caches or activity history.
The Vortex data isn't system specific, it's completely possible you may want to synchronize your mods between systems and play the same setup on different machines. If not you can change the storage directories in settings or you can configure your roaming profile to exclude the vortex dir.
