### ISSUE TITLE
when opening  vortex sometimes there's a green box in the background, sometimes this glitch travels to other things I have open too like firefox. I know this because it only happens if vortex is open.... I've never seen anything like this

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [Nexus-Mods/Vortex#5594]
as I am using it from time to time this bug starts when I only open up vortex, sometimes it goes away sometimes it stays and travels to different tabs like youtube.

**Comment by IDCs** [comment]
Hey @PrinceJaxonHellsing, this sounds familiar, I'm 99% sure that's just the Geforce Experience app but can you please send us a screenshot of what you're seeing so we can confirm.

**Comment by IDCs** [comment]
No reply - closing.
