### ISSUE TITLE
Rules broken for Fallout 4

### ISSUE THREAD

**Issue by Arkhorse** [Nexus-Mods/Vortex#5602]
**Describe the bug**
Im attempting to create mod load order that is not buggy, nor laggy. However, when I do so, vortex complains about cyclical rules. I have checked the rules over and over, and there are none that I can see, that would cause this error. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Add rule (Example: Sim Settlements: Rise of the Commonwealth - Compact City Plans Beta 003 (any esl/ esm) requires Sim Settlements: Rise of the Commonwealth)
2. Click on Sort now
3. See error

**Expected behavior**
Sorts all related esm/ esl's below the required main file

**Screenshots**
[Imgur](https://i.imgur.com/SV5ug87.png)

**Platform (please complete the following information):**
 - OS: [Windows 10]
 - Vortex Version [1.0.5]

**Comment by TanninOne** [comment]
a) The error message about cycles is never wrong.
b) There is a "More" button giving you more information. Please don't report issues without even reading the information we provide.
