### ISSUE TITLE
Documentation of tools `parameters` key (and other properties)

### ISSUE THREAD

**Issue by silveredgold** [Nexus-Mods/Vortex#5620]
**Is your feature request related to a problem? Please describe.**

The existing documentation for creating extensions (i.e. [wiki](https://wiki.nexusmods.com/index.php/Creating_a_game_extension_for_Vortex), [github](https://github.com/Nexus-Mods/vortex-api/wiki/Introduction) and [apidoc](https://nexus-mods.github.io/vortex-api/index.html)) mention that extensions can define tools using the `supportedTools` key. That seems to be basically it without reverse-engineering the api from the Vortex implementation.

**Describe the solution you'd like**

As far as I can tell, there is no documentation of several parts of the tool definition and in particular the `parameters` key, which makes controlling how a tool should be launched basically impossible. None of the extensions in `Nexus-Mods/vortex-games` use this key either.

**Additional context**

As an example, if I want to develop a tool specifically for use with Vortex, it should be possible for Vortex to provide the current install path directly to the tool as a parameter, but I can't see how that would be done.

**Comment by TanninOne** [comment]
There is documentation.
https://nexus-mods.github.io/vortex-api/interfaces/igame.html#supportedtools
says that supportedTools is of type ITool[] - that is: an array of ITool objects.
Follow the link on ITool to find the documentation for tools where you will find that parameters is an array of strings that will be passed to the tool.

But if you want to pass the Vortex path to the tool your problem isn't that "parameters" parameter but how you'd find the path of Vortex.
For that you can use https://nexus-mods.github.io/vortex-api/globals.html#getvortexpath

**Comment by silveredgold** [comment]
I was getting at more detailed information on what exactly "list of parameters to pass to the tool" means (since that says very little), but if that's all that's available, I understand.

As for paths, I was suggesting that a tool would be handed the installation path not of Vortex, but of the game that the tool is managing. As it stands, a tool that needs to know where the game is installed seems like it still has to do its own Steam detection and library parsing, which Vortex is already doing.

Apologies if this isn't making sense but I'm new to the extensibility side of Vortex and some of it is a bit tricky to understand for me.

**Comment by TanninOne** [comment]
I'm not sure what detailed information you expect? It's command line parameters. You pass them to an application. What effect they have is up to the application.

> As it stands, a tool that needs to know where the game is installed seems like it still has to do its own Steam detection and library parsing, which Vortex is already doing.

The tools feature is intended for application that are *not* specifically designed to work with Vortex. Those tools don't assume they get an auto-detected game path because why would they?

The tools dashlet is intended for stand-alone application that you would otherwise run by double-clicking in explorer or something. If you intend to write something for Vortex specifically, that's what the extension system is for.

**Comment by silveredgold** [comment]
Okay I suppose that makes sense thanks. 

For some context, I was writing a tool that directly manipulated the game files post-mod-installation which seemed to cause Vortex to complain about an "invalid installer" so I separated that logic out into a CLI. Ideally that CLI could accept the installation path as a command line parameter (from Vortex), rather than re-implementing the install locator logic from Vortex but I might need to rethink how that could be done.
