### ISSUE TITLE
Vorterx does't work on bathesda games anymore

### ISSUE THREAD

**Issue by JiyonTekuza** [Nexus-Mods/Vortex#5780]
This new vortex doesn't have the gamebryo file extensions, so it can't be used on Bethesda games. can we please get the earlier version back, or get this update corrected?

**Comment by IDCs** [comment]
Hi @JiyonTekuza, the gamebryo extensions are definitely included in the 1.1.4 release; this seems to be down to a corrupt installation. Can you please try to re-install Vortex and let us know if that helps ?

You should be able to see the extensions inside your "C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins" folder.
![image](https://user-images.githubusercontent.com/8960252/69945920-7b2e0780-14e2-11ea-816a-83e78d8ce72f.png)

**Comment by IDCs** [comment]
Also, can you please send us your vortex.log files which can be found in your "C:\Users\\{YOUR_USERNAME}\AppData\Roaming\Vortex" directory

**Comment by JiyonTekuza** [comment]
Ok thanks, I did get it to work by going back to it on desktop instead of trying to install while downloading. I will check what you said. I have no idea what I am doing so it is all trial and error. Sorry to bother you. I will donate some money to everybody once I get it to work. I started this a year ago and gave up, $2500 Cyberpower880 used as a TV shelf for a year, but now I am trying again and actually made progress. Thanx Again

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JiyonTekuza** [comment]
Okay, I found the C:\Users\lukag\AppData\Roaming\Vortex\logs
Folder, but it is empty, and Outlook doesn’t have anyplace to attach it to send it anyway, not like G-Mail. Sorry it probably went away when I re-installed Windows 10 to get rid of malware (3rd Time.)Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by JiyonTekuza** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by IDCs** [comment]
Hey @JiyonTekuza, regarding the logs; the files are not stored inside the logs directory (I know that's confusing - that directory is created automatically by Electron)

I was referring to any files named "vortex" with the ".log" extension which can be found inside the "C:\Users\{YOUR_USERNAME}\AppData\Roaming\Vortex" directory
![image](https://user-images.githubusercontent.com/8960252/69957213-14b4e380-14fa-11ea-91ba-81ba52df995f.png)

**Comment by JiyonTekuza** [comment]
I must have erased them when I did the reinstall of Windows, I now know not to do that again. (I also know now not to download any mods where it even says “Don’t listen to anyone who says what will happen if you do download it.”) I will send the new logs I generate over the next few days to you as soon as possible, but for now I must first figure out how to support you with a money donation, as I cannot continue getting a free education in Computer Science from you without giving back something in return. Thank you, I will try not to be such a pest in the future. :}

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by IDCs** [comment]
Hi @JiyonTekuza, no problem I'll leave this issue open for a week or and will close it if we don't hear back from you.

Don't worry about donating money! we're happy to help as that makes our application more robust.

**Comment by IDCs** [comment]
Hopefully everything is running smoothly now. Going to close this issue but do feel free to re-open if you're still having issues.
