### ISSUE TITLE
Any Official fallout file is not a valid plugin after changing game location

### ISSUE THREAD

**Issue by matjojo** [Nexus-Mods/Vortex#5787]
**Describe the bug**
When I change the location of the game by changing in in steam, then in vortex, and then deactivating and activating all mods an issue appears where vortex claims the base fallout files (Fallout4.esm, and upon deactivating all mods dlccoast.esm...) are invalid plugins.

**To Reproduce**
1. Change game location in steam.
2. Change game location in Vortex.
3. Have to deactivate and activate all mods once for them to load at all (Could this be an issue itself?)
4. Make a new Profile and activate all the mods on here for them to load (Same as above?)
5. Try to re-sort the load order with the sort button using LOOT.
6. See a popup that says something like: `LOOT operation "loadPlugins" failed: "dlccoast.esm" is not a valid plugin`

**Expected behavior**
Vortex loads all the mods onto the new location without problems.

**Platform (please complete the following information):**
 - OS: Windows 10.
 - Vortex Version 1.1.4 (2019-11-28)

**Additional context**
After moving the game it also updated, could this have caused an issue in some sort of hash-sensitive location?

Full trace:

```js
Error: LOOT operation "loadPlugins" failed: "dlccoast.esm" is not a valid plugin
    at handleResponse (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:39:69591)
    at Socket.e.on.e (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:39:68224)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

**Comment by matjojo** [comment]
Restarting vortex seems to have fixed this, but only after deactivating all mods first.

After then enabling all mods _again_ I see no sorting issues. Will take a moment to verify ingame if it all works though.

**Comment by TanninOne** [comment]
The error message you're getting is from LOOT, which is running as a background process. When you move the game, even if you manually update the game path within Vortex, that background process is still expecting the game in the original location.

What you were doing is quite problematic, you should not be running Vortex while you move the game. You also shouldn't disable the mods _after_ you've moved the game, you were very lucky if Vortex was able to clean up and properly reinstall the mods after that.

The proper process would have been:
- "Purge" mods within Vortex
- close Vortex
- move the game
- start the game once
- start Vortex
- Only if Vortex didn't discover the game set the path manually
- deploy mods
