### ISSUE TITLE
No support for SkyrimVR in released version

### ISSUE THREAD

**Issue by danielesegato** [Nexus-Mods/Vortex#5807]
I'm talking of the one you can download from here:
https://www.nexusmods.com/site/mods/1?tab=files

it doesn't have SkyrimVR in the list of supported games (nor in the page nor when you install it)

but i can see you have support in the actual code.

EDIT: scratch that, the game is there in 1.1.5 version, but it isn't auto-detected by quickscan or full scan and doesn't show up in the list of games until you search for it (basically need to be manually added)

**Comment by IDCs** [comment]
Hi @danielesegato, is your copy bought through Steam or some other game store ?

Also, can you please have a look in your registry and see if you have the following key value: "HKEY_LOCAL_MACHINE\Software\Wow6432Node\Bethesda Softworks\Skyrim VR\Installed Path"

**Comment by danielesegato** [comment]
Hi @IDCs sorry for late answer, yes there is with value:

`H:\SteamLibrary\steamapps\common\SkyrimVR\`

But the path has different case:
`\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\bethesda softworks\Skyrim VR`

I bought through Steam :)

**Comment by IDCs** [comment]
Hi @danielesegato, thanks for your reply! hmm.. casing shouldn't matter in this case. Silly request - can you confirm that "H:\SteamLibrary\steamapps\common\SkyrimVR\SkyrimVR.exe" exists ?

Also, is H:\ a physical drive or is it a network/virtual drive ?

**Comment by danielesegato** [comment]
H: is a real drive ;) in Flesh and SSD

I confirm `SkyrimVR.exe` is there.

Keep in mind that now I've manually added the game in my Vortex, not sure if this makes a difference.

**Comment by TanninOne** [comment]
It's lower case on my system as well yet the detection works. Odd.

**Comment by IDCs** [comment]
Hey @danielesegato, been 8 months... sorry about that...

Adding the game manually will indeed override any paths that are discovered automatically, but that wouldn't cause the issue you were seeing. At this point we can confidently assume that the registry query is failing for some reason (permissions ?) regardless, we have a fallback in place which should've detected the game through Steam's manifests - given that it didn't, we probably need to improve our game store detection to cater for this - if you still have the same setup (and still have Skyrim VR installed) can you please have a look inside "H:\SteamLibrary\steamapps\" which should have several .acf files - one of which holds information for your Skyrim VR copy, can you please send us that .acf file or simply send us the name and appid filelds

![image](https://user-images.githubusercontent.com/8960252/89866223-182f5d00-dba7-11ea-888a-f77ce7cb7072.png)

**Comment by danielesegato** [comment]
```json
"AppState"
{
	"appid"		"611670"
	"Universe"		"1"
	"name"		"The Elder Scrolls V: Skyrim VR"
	"StateFlags"		"4"
	"installdir"		"SkyrimVR"
	"LastUpdated"		"1575849360"
	"UpdateResult"		"0"
	"SizeOnDisk"		"15116271240"
	"buildid"		"2743427"
```

here it is

**Comment by IDCs** [comment]
The name in your manifest matches the name we're searching for exactly - I'm still not sure why the fallback is failing but have modified the extension so it uses our game store helper from this point on, and search for the appid instead of the game name. Fingers crossed this fixes it.

**Comment by danielesegato** [comment]
any way I can test it for you?
