### ISSUE TITLE
Unable to send a bug report.

### ISSUE THREAD

**Issue by sbeaudoin** [Nexus-Mods/Vortex#5818]
Tried to use the "send bug" feature of vortex build 1575885676.  When sending, got a failure.  The details indicate an http error 403 and the content suggest it is due to a failed captcha.  Can't send the details as I can't select the http content of the details.

**Comment by IDCs** [comment]
Thanks @sbeaudoin, we are aware of this issue and are working to fix it. Cloudflare only blocks bug reports with attachments; you should be able to submit your bug reports as long as you don't attach any files to it.
