### ISSUE TITLE
Vortex says mods are activated but they are not.

### ISSUE THREAD

**Issue by sbeaudoin** [Nexus-Mods/Vortex#5819]
Vortex build 1575885676.  Installed some mods from downloaded files and activated them.  Vortex mark them as activated, but they are not available from the game (fallout 76) and the fallout ini file is unchanged.  It should declare those mods in the archive section and it don't.

**Comment by IDCs** [comment]
Hi @sbeaudoin, I don't believe that the FO76 extension is currently meant to make any INI changes, it simply deploys files. The extension's author wxMichael is the right person to contact about this and will know more. You can get in contact with him on the extension's page on the site https://www.nexusmods.com/site/mods/35?tab=posts

Going to close this as FO76 is a 3rd party extension.
