### ISSUE TITLE
Will not connect to nexus site from Vortex App

### ISSUE THREAD

**Issue by Idontwantausername1** [Nexus-Mods/Vortex#5822]
**Describe the bug**
It seems to be common but, I'm logged in on Vortex locally but it will not permit login to Nexus mods site to update or to even access my profile.

**To Reproduce**
1. Go to 'Unknown'
2. Click on 'No clue'
3. Scroll down to 'I couldn't give this information to you if I was guided'

**Expected behavior**
Expected result login to nexus site from Vortex profile icon.

**Real result**
Can not connect to nexus mods at server.  Since the server can not be reached no login and updates can occur.

**Screenshots**
[users.nexusmods.com _ 524_ A timeout occurred.pdf](https://github.com/Nexus-Mods/Vortex/files/3993455/users.nexusmods.com._.524_.A.timeout.occurred.pdf)

**Platform (please complete the following information):**
 - OS: Windows 10 Home 64

 - Vortex Version [1.1.5]

It seems this issues reoccurs to probably new users like myself.  I noticed with the new forced login feature, you omitted a method to correct it ourselves.  I understand, this can lead to worse issues.  Sigh..  I admit I'm not a fan of asking for help, so it would be great if the steps were clear, concise, and could be duplicated for those of us who dislike asking others for directions.

**Comment by IDCs** [comment]
Hi @Idontwantausername1, there were several issues with the website during the weekend and service should have returned to normal. Please note that the Vortex github repo is aimed at reporting and tracking Vortex specific issues; server errors such as the one you mentioned are better reported to the web team support@nexusmods.com

**Comment by Idontwantausername1** [comment]
Thanks
