### ISSUE TITLE
Plugins Tab missing

### ISSUE THREAD

**Issue by AvoidedDoughnut** [Nexus-Mods/Vortex#5879]
Summary:
Plugins Tab is missing. Tried varrious methods to "re-enable". I have read and followed steps shown in these forums/threads:
https://github.com/Nexus-Mods/Vortex/issues/4617
https://forums.nexusmods.com/index.php?/topic/6538176-help-with-vortex-please/
https://forums.nexusmods.com/index.php?/topic/7263386-plug-ins-tab-missing-from-vortex-ui/

Other Info:
I only use Windows Defender for an antivirus. I could try adding the file path for vortex to the exlusions list and reinstall.

I tried to install the https://support.microsoft.com/de-de/help/2977003/the-latest-supported-visual-c-downloads to see if I was out of date, and it said nothing needed to be done.

The current error shown says "Some of the installed extensions couldn't be loaded because they have missing dependencies." When I select the fix option it says "Failed to install extension - gamebryo-plugin-management". When I click show more it says "The extension "gamebry-plugin-management" wasn't found in the repository. This might mean that the extension ins't available on Nexus at all or has been excluded for compatibility reasons. Please check the installation instructions for this extension."

I use the Vortex install for a custom location on my PC, if that makes a difference.

I have reinstalled Vortex already. Nothing has changed.

Finnally, I'll attach all available logs in hopes I can rid myself of this silly issue. I have never ran into this problem until recently.

[vortex.log](https://github.com/Nexus-Mods/Vortex/files/4062393/vortex.log)
[vortex1.log](https://github.com/Nexus-Mods/Vortex/files/4062395/vortex1.log)
[vortex2.log](https://github.com/Nexus-Mods/Vortex/files/4062396/vortex2.log)
[vortex3.log](https://github.com/Nexus-Mods/Vortex/files/4062397/vortex3.log)

Sorry about the multiple log files... No idea which one would help you.

**Comment by TanninOne** [comment]
Thanks for the comprehensive report.
The log says this:
Tue, 14 Jan 2020 23:28:24 GMT - debug: extension disabled name=gamebryo-plugin-management

Which means that the gamebryo-plugin-management extension - which is what adds the plugins tab - was disabled. And Vortex doesn't disable extensions automatically, the only way this would happen is if you manually toggled the extension on the Extensions screen.
And the solution is simply to enable it on that same screen and restart Vortex.

The errors you get are follow-up errors from that. "gamebryo-plugin-indexlock" depends on gamebryo-plugin-management so if that is disabled, it will also fail to load.

**Comment by AvoidedDoughnut** [comment]
![image](https://user-images.githubusercontent.com/59899282/72482705-7d5ad580-37b3-11ea-95dc-f5880f28fb6f.png)

**Comment by AvoidedDoughnut** [comment]
You do realize that each user has their own experience with things? I'm still new to how Vortex works, and this was where I saw people getting a lot of their answers. Sorry I don't know the technical aspect of how Vortex works. I just assumed it was a critical extension for proper functionality.

I was just hoping to edit my load order . I didn't think Vortex couldn't do something NMM was able to do. My mistake.

**Comment by gnome59** [comment]
TanninOne, just so you know your not alone, i have the same issues, I have been using "Scrap Everything" for six months or more, and all of a sudden, PTSD level 10 out of 10! thanks to this and missing Masters which the Data File says is there... errrr!
and know one seems to have a good answer, not Vortex Nexis, or Bethesda.. so frustrated! But Im not giving up anytime soon. If, I find a solution I'll try to update you.....       Gnome59
