### ISSUE TITLE
Vortex will not log in

### ISSUE THREAD

**Issue by Crazydoc1** [Nexus-Mods/Vortex#5888]
Windows 10 recently had an update and since then Vortex has been unable to login.  I can login to nexusmods.   I have attempted to manually get an API key and nexusmods.com will not recognize to allow the login.  I have added Vortex to the Windows defender white list.  

**To Reproduce**
1. start vortex
2. click on the read profile button.  this states you must manually.  i follow the instructions and get a new API key: MnN4Wi9pSk1UajNOS2FiTThVU3U0SGxpbFFIU05xUDZSQTM0OVJKdkYwK3lkVC9ETVRDUzhuR1hpREtHUnF4RS0tclhkM2dSeGpQelBYakxXSGxDTlRCZz09--c7693d64c5989c73642b19d1a4055539560a7112
3. then nothing after hitting the save button
4  error 1:
    at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket._finishInit (_tls_wrap.js:631:8)
    error 2: 

**Expected behavior**
I expect the program to login 

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version [1.1.5

**Additional context**
Screenshots: 
![vortex1](https://user-images.githubusercontent.com/53153115/72644803-f38c4300-393f-11ea-9c61-2969991d0ec3.jpg)

![vortex2](https://user-images.githubusercontent.com/53153115/72644815-f850f700-393f-11ea-8776-7c59bfb3ca0d.jpg)
![vortex3](https://user-images.githubusercontent.com/53153115/72644819-fc7d1480-393f-11ea-9181-8a7361209c4e.jpg)

**Comment by IDCs** [comment]
Hi @Crazydoc1, any chance you're using a VPN or proxy server ?

**Comment by TanninOne** [comment]
Your report is missing the actual error messages you got.
This:
```
at TLSSocket.onConnectSecure (_tls_wrap.js:1049:34)
at TLSSocket.emit (events.js:182:13)
at TLSSocket._finishInit (_tls_wrap.js:631:8)
```

is the trace that tells us _where_ the error happened (which is a foreign library in this case) in code but not what the error was.

**Comment by IDCs** [comment]
@Crazydoc1 any update on this ?

**Comment by TanninOne** [comment]
closed due to lack of feedback
