### ISSUE TITLE
Vortex will not submit bug report

### ISSUE THREAD

**Issue by Urhas** [Nexus-Mods/Vortex#5889]
**Describe the bug**
Fails to send feedback with error 
![Error](https://user-images.githubusercontent.com/8009682/72729952-4a845900-3b88-11ea-8bb6-711ba2765f63.png)

**To Reproduce**
1. Go to The 3 dots in the top right
2. Click on Send Feedback
3. Click on Submit Bug Report
4. Select Topic "Other"
5. Enter Error Details and Attach Image
6. Click Submit Feedback
7. Error Occurs

**Expected behavior**
Bug Report submits without error

**Platform (please complete the following information):**
 - OS: Windows 10 version 1909
 - Vortex Version 1.1.5

**Comment by IDCs** [comment]
Hi @Urhas, thanks for your report - cloudflare (part of our web/security infrastructure) is currently blocking feedback attachments (we're working on resolving that). In the meantime please do not attach any files to your report; provide a link to the file/s you wish to submit using your preferred cloud storage service.

**Comment by Urhas** [comment]
Thank you. Submitting the request after removing attachments worked. 
No currently not using a VPN

**Comment by TanninOne** [comment]
This is a bug in the website, not in Vortex.
