### ISSUE TITLE
preparing endlessly

### ISSUE THREAD

**Issue by deathlyhill** [Nexus-Mods/Vortex#5909]
**Describe the bug**
basically every time i try to install a mod it endlessly prepares and never installs

**To Reproduce**
1. Go and download a mod
2. Click on install

**Expected behavior**
for the mod to install successfully 

**Screenshots**
![buggs](https://user-images.githubusercontent.com/60280752/73115773-9b81ad80-3ef8-11ea-8ade-c9ef11735e08.PNG)

**Platform (please complete the following information):**
 - OS: windows 7
 - Vortex Version 1.1.10

**Additional context**

**Comment by TanninOne** [comment]
You're providing no context for us to work with. Where's the logs? which game is this about? What's your setup? E.g. where is your game installed, what's your staging folder? Are you managing other games and do you have this problem on all of them or just this game?
Did you install other mods in the past successfully or is your mod list still empty?

You can't give us just "Go and download a mod and click on install". We have hundreds of thousands of users where that works just fine, you have to give us _something_ that could tell us why your system/setup is exceptional.

**Comment by deathlyhill** [comment]
well i also mange fo3 and oblivion and fonv its happening on all 3 mods staging is appdata/roaming/vortex/(game)/mod my games installed via steam so steam apps and common step up is a windows 32 x64bit laptop memory 5.92gb 
 installed mods in the past i even deleted some i thought was causing the problem

**Comment by TanninOne** [comment]
Ok, so thanks to the log I now know what Vortex is trying to do that causes it to hang, I'm not sure why though:

When Vortex installs a mod, it will fetch meta information about the file from Nexus Mods. This info is cached on your local system to avoid unnecessary network requests.

I know from our network log that at the times in question no matching network request was made by your account, so most likely it gets stuck querying the cache.

I've never seen this happen so I can only speculate what's causing it. Either the cache got corrupted somehow or file permissions prevent Vortex from accessing the file. It's still odd that it doesn't produce an error message though.

A simple test you could do is to delete the cache. To do that close Vortex, find the directory `C:\Users\SMUser\AppData\Roaming\Vortex\metadb` and rename it to something else (like "metadb.deleteme"). Then start Vortex and see if it works now. If so it's safe to delete the "metadb.deleteme" directory - again: It's just a cache.

If you get any kind of error messages from Windows trying to move/delete the metadb directory, please take note of them and report it, that may help figure out why it broke in the first place.

If the metadb directory doesn't exist or if Vortex doesn't re-create it after you did the above step, there may be permission problems with the C:\Users\SMUser\AppData\Roaming\Vortex directory itself that prevents Vortex from creating it, please check your security settings then.

**Comment by deathlyhill** [comment]
so it didnt remake the meta folder so what i have to do via security im not computer smart lol

**Comment by TanninOne** [comment]
There are various tutorials online, e.g. this one seems to be reasonably good: https://www.webnots.com/how-to-change-file-permissions-in-windows-10/

You want your user account (SMUser I guess) to own and have full read/write access to C:\Users\SMUser\AppData\Roaming\Vortex

**Comment by IDCs** [comment]
Hi @deathlyhill, hopefully you have managed to fix your permission problems - I'm going to close this issue as we can't solve environment issues for our users.
