### ISSUE TITLE
Kingdom Come mod order.txt file never gets updated

### ISSUE THREAD

**Issue by deadair3210** [Nexus-Mods/Vortex#5910]
**Describe the bug**
The mod order.txt file in the game's mods folder never gets updated with any files after being created, leaving an empty file. This makes the game ignore all installed mods,even if they are installed correctly until the files are added to the txt file or the txt file is deleted

**To Reproduce**
1. Add mods (using hardlink, not sure if that changes anything)
2. Deploy
3. Go to game mod folder or try to launch the game
4. Notice that txt file is empty and that mods dont appear

**Expected behavior**
File to be updated correctly in correlation to the load order chosen in Vortex

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.1.10

**Additional context**
Vortex debug log attatched
https://gist.github.com/deadair3210/1cecf4efcf618ac4d541d45af8731c81

**Comment by IDCs** [comment]
Hi @deadair3210, thanks for reporting this. This has been fixed with https://github.com/Nexus-Mods/vortex-games/commit/09823163e9c942c5f2a58f360968da342653cd64 and will be available in our next release.
