### ISSUE TITLE
Vortex is not able to deploy a simple folder into the Skyrim root with "dinput" mod type!

### ISSUE THREAD

**Issue by Kongolan** [Nexus-Mods/Vortex#5945]
It's a little odd that Vortex can only deploy the SKSE64 when actually messing around with the file explorer when the zip was manually inserted and then installed. Before enabling i would need to move the files in the top directory, while it would actually better to have a folder named "skse64" where all the files, which should be put into the root folder, should be located. 

So packing a zip file beforehand with the correct folder structure and hoping for "dinput" to just put the contents of the zip into the root seems to be something which is simply not supported.

How to Reproduce:
1. Download the SKSE64.7z file from the official site
2. Extract it and move all the files 1 level up, so all is packed to top level like a normal mod would be
3. Repack it again to .7z format
4. Drag it into the Vortex manual mod installation panel or just copy it into \AppData\Roaming\Vortex\downloads\skyrimse
5. Install it
6. Double-click it and change mod type to "dinput"
7. Enable it

Normally since the SKSE is packed now in a format which is acceptable, Vortex should locate the folder of the extracted archive in it's profile\mods\ folder and put that into the root of SkyrimSE natively. Put what it does, is creating a new folder in the root of Skyrim with the name "skse64" (same name as in the mods folder), which does obviously not run. 

I'm highly against having loose files in my profile\mods\ folder of Vortex, because if i want to install more native plugins like SKSE i want them to be sorted in their folder, where they originated off, so uninstalling them does work as well.

So if this is not a Bug, please add a new Mod Type "root" or something similar so the deployment does put the .7z content which was installed into the root of Skyrim...

**Comment by IDCs** [comment]
Hi @Kongolan, the dinput modtype aims to provide easy installation for mods which create/overwrite "dinput8.dll" which is generally used to provide "hooks" for other mods. SKSE64 does not provide that file and therefore will not install correctly using this modtype, that's not a bug.

@TanninOne, what do you think about us adding a "gameroot" modtype ?

**Comment by TanninOne** [comment]
There are technical limitations in how mod types are implemented. As such we do not introduce new mod types unless strictly necessary.
Installing skse through Vortex is currently not officially supported and it will not be until we had time to revise the mod type mechanism.
If you find a workaround (and it's actually quite easy) that's fine. Otherwise install it manually according to their instructions.

**Comment by Kongolan** [comment]
For all the others who struggle with this, actually use my method but selected "enb" as mod type. If you repacked the SKSE64 to be top-leveled in the archive, it will work out.

This is a temp solution until we have like a "root" mod type.

**Comment by TanninOne** [comment]
There is no reason to repackage skse. Just install it as a mod from the original archive, change the mod type, then rearrange the files **inside the staging** folder.
That way you don't have to try and predict how Vortex is going to rearrange the files during installation and it's less work.

**Comment by Kongolan** [comment]
Yes, but i dislike the idea of messing with the staging folder, which needs to be done on every uninstall reinstall method, so i rather pack the archive before hand and share this one, so i can have proper solution, which plug and plays for everyone and new system as well.
