### ISSUE TITLE
VR games appear to ask for confirmation on every mod install

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#5947]
![image](https://user-images.githubusercontent.com/31670524/74172755-ac386000-4c28-11ea-9718-f700ca4372ac.png)

I'm assuming this is because Vortex is looking for a game called "SkyrimVR" or "Fallout4VR"? 

Is there anything we can do to address this?

**Comment by TanninOne** [comment]
This has been addressed in 1.5 now
