### ISSUE TITLE
Script Extender Plugin Errors

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#5949]
This is a collection issue for all reports about "Vortex reported script extender plugin failed to load".

As the message states: Vortex is merely forwarding an error that the script extender reported the last time it ran.
If you actually think the message is incorrect you'd have to report that to the script extender team. But you're wrong anyway.

The plugin definitively failed on the last run. This doesn't necessarily mean the mod in its entirety doesn't work, it may just be certain features that fail.
If you update the mod the message doesn't disappear until you run the game though.

**Comment by SuperMeja** [comment]
Ok I just created this account.  So... the message is just telling me that the last time the game and mods were installed I did something wrong? The CBT and campfire mods weren't even installed and I still got the message. That's goofy. I like figuring things out to fix it, and the pointless message will bug me.  I think I'm better off with Mod Organizer.

**Comment by SuperMeja** [comment]
Anywhoo, thank you @TanninOne  for pointing out that one important statement. Gawd, I'm so embarrassed.  I swear I don't go into Instant Total Spaz mode like this. The game runs fine.
