### ISSUE TITLE
wont deploy half my mods.

### ISSUE THREAD

**Issue by Budddywg** [Nexus-Mods/Vortex#5955]
half my mods are not active in game

dont know why

**Expected behavior**
my mods to work

**Screenshots**

**Platform (please complete the following information):**
 - OS: win 10 1909
 - Vortex Version1112

**Additional context**
they wont activate in game. even the unoffical patch wont activate.

**Comment by IDCs** [comment]
Your report contains absolutely no information. For us to investigate this we need application state information, logs, anything - you did not even specify the game you're managing.

**Comment by IDCs** [comment]
I'm sorry, but there's nothing to go on here.
