### ISSUE TITLE
7DaystoDie: Vortex only loads 1st modlet in a pack

### ISSUE THREAD

**Issue by XythQ** [Nexus-Mods/Vortex#6000]
**Describe the bug**
If an uploaded Mod for 7 days to die, like the creaturepacks mod, which has 5 modlets in a vortex mod .zip file, Vortex only loads the first modlet found in the pack.  Example: Mods/mod1, mod2, etc

**Expected behavior**
It should load all contents of the Mods folder

**Comment by IDCs** [comment]
Hi @XythQ,

I'm afraid this is not a bug as we don't support this type of "mod pack" and there are no plans to enhance existing game extensions to support these in the future, given that a more generic mod pack system is currently in development.

In the meantime, consider asking the mod author to package his modlets separately in preparation for the new system and also to give users a more granular control over which creature modlet they deploy into their game.
