### ISSUE TITLE
Suggestion - Show "Exensions" page, without advanced mode.

### ISSUE THREAD

**Issue by MaverickMartyn** [Nexus-Mods/Vortex#6015]
There might be a good reason for the way it currently is, but I think showing the extensions page, without having to enable advanced mode in settings, would make it easier for people to find extensions. It seems to me that many people don't even know that Vortex is extensible.

EDIT: Also, wondering: How does updating extensions work?
Do they auto update?

**Comment by IDCs** [comment]
Hi @MaverickMartyn, thanks for your suggestion. The advanced toggle has been dropped in 1.2.0 and the extensions page should now be available by default. 3rd party extensions will auto-update only if they had been downloaded through Vortex.

**Comment by MaverickMartyn** [comment]
When can I expect v1.2.0 to be released? Also I assume you are talking about the version of the extension browser, and not Vortex itself right?

**Comment by TanninOne** [comment]
We can't give a date of a release but we're expecting it to be weeks not months before 1.2 (of Vortex) goes into public testing. No telling how long it takes from there to 1.2 being considered stable.

The advanced toggle serves practically no purpose once extensions are no longer rated as a "advanced" feature so it gets dropped completely.

**Comment by MaverickMartyn** [comment]
Ah. I think I misread my Vortex installations version number, which is why i was confused about that.
Thank you for providing a bit of a time frame. I understand that it may or may not be accurate. :)
