### ISSUE TITLE
Shareable Profiles

### ISSUE THREAD

**Issue by BCDel89** [Nexus-Mods/Vortex#6023]
Modding can be a long, tedious and uninviting process that pushes many gamers away. 

A potential solution to this might be to transform profiles into more detailed mod manifests that save information like mod versions, and order similar to a package.json file that would allow users to easily export, download, and install mod packages that are curated and tested by other individuals.  Doing this could allow content creators, social media promoters, modders, and others to create packages that they have tested with the community allowing beginners, non-tech savvy users, and other time-constrained gamers to enter the modding scene.

**Comment by IDCs** [comment]
Hi @BCDel89, thanks for your suggestion. We are currently developing a mod packs system which will cater to the items you raised. No release date on that yet but in the meantime why not give the modlist backup extension a try: https://www.nexusmods.com/site/mods/67
