### ISSUE TITLE
Suggestion - Confirmation modal when clicking outside dependencies editor dialog.

### ISSUE THREAD

**Issue by EazyCheeze1978** [Nexus-Mods/Vortex#6025]
**Is your feature request related to a problem? Please describe.**
This just happened to me - I was re-setting dependencies from a previous reinstall of New Vegas. I had spent maybe five or six minutes so far in the box, when my mouse hand got a bit sloppy and clicked a handful of pixels outside the dependencies dialog. The dialog closed, and I lost all my changes.

**Describe the solution you'd like**
I'd like, when we click outside the box, a(nother) modal dialog to pop over the dependencies, if that's possible, with the options to "Apply these changes, lose them or go back to editing them?"

**Describe alternatives you've considered**
Just be more careful in where I click, don't be sloppy.

**Additional context**
For the record, I do have a small case of cerebral palsy, which may or may not have had to do with this. Also, Asperger's Syndrome, which I also have, has been known to cause movement anomalies sometimes. And lastly, there are about five dozen dependencies in my list to set and I was about four dozen through.

**Comment by TanninOne** [comment]
Agreed, this behavior is a bit annoying

**Comment by EazyCheeze1978** [comment]
Thank you for the commit! Looking forward to seeing the implementation. You're awesome!
