### ISSUE TITLE
Bug Report - Deploy Order index doesn't follow the "Rules"/Mod Deploy Order changes after restart

### ISSUE THREAD

**Issue by privatmamtora** [Nexus-Mods/Vortex#6054]
**Description**
When Mods are added they added to the bottom of the list and have the highest "deploy order" index, But when Vortex is closed and reopened, the enabled mods are alphabetically sorted and the "deploy order" index's get changed to match the "sort" index.

Because of this I now don't know what is overwriting what. I need to look at the "rules" and figure it out.

**To Reproduce**
1. Add a few mods and enable them (not in alphabetical order)
2. Close and reopen
3. Go to "Mods"

**Expected behavior**
The "Deploy Order" index should be the "Actual Deploy Order" Index. 
So when the rules are applied, the user will know which mod is over writing which.
When rules are changed all the numbers in the "Deploy Order" column should update.
This would eliminate the problem of order changing after restarting (don't store the "Deploy Order", re-calculate it each time on following events: "Start", "Mod Enabled/Disabled", "Mod Rule Changed")

**Screenshots**
![Vortex Screenshot](https://user-images.githubusercontent.com/7475401/78464109-ef68f980-76d4-11ea-953d-549150ad6421.JPG)
Things to observe:
- It is sorted by "Deploy Order"
- I have added a rule for "1. Atlas Map Markers" to be loaded after "A Quality World Map"
- Why isn't "A Quality World Map" **above** in the Deploy Order? Is it getting deployed in the right order?

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.1.15

**Comment by IDCs** [comment]
Just tested this and it's no longer an issue. We must've fixed it a while back.
