### ISSUE TITLE
start-download doesn't respect fileName parameter

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6059]
**Describe the bug**
Emitting a `start-download` event and providing a `fileName` will still result in the downloaded file using a parsed-from-the-URL file name.

**To Reproduce**

Emit a `start-download` event, passing the `fileName` parameter:

```js
context.api.events.emit('start-download', 
        ['ftp://ftp.iinet.net.au/pub/test/1meg.test'], 
        {game: 'sample'}, 
        'forcedDownloadName.data', 
        (err, id) => {
            log('error', 'error', err);
            log('info', 'downloaded with id', id);
        }, 
        true);
```

**Expected behavior**
The resulting download would be named for the `fileName` parameter.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.1.15

**Additional context**
All the existing calls to `start-download` in Vortex don't provide this parameter so I'm having trouble tracing where it gets changed and/or not used.

**Comment by TanninOne** [comment]
The filename parameter wasn't intended to be used that way.
It was intended for cases where the filename can't be deduced from the url (e.g. if the download link is something like https://files.foobar.com/sIPQkv3qh.php) to allow Vortex to show a proper filename up to the point where the download is actually started.
The expectation was that the file name is the same as what the server ends up providing, not so that the file can be renamed.

But I don't see a reason not to repurpose the parameter, in the existing cases it wouldn't make a difference anyway.

**Comment by agc93** [comment]
That makes sense @TanninOne . That's actually what I was originally trying to use it for: I'm trying to download from a site that just uses `example.com/file/<some-guid-here>`.

As an alternative to this: is there something an extension can do to change the mod name during the download/install process? I'm fine with the downloaded file having a confusing name, but the mod list being full of a bunch of id's isn't ideal.

**Comment by TanninOne** [comment]
Depends on the screen you're actually looking at. The "Downloads" page is basically a download manager so I'm ok with having file names there.

On the "Mods" page the file name is only used as a fallback if the download doesn't have a "name" attributes (aka meta information)

So an extension can change the name an (uninstalled) mod is displayed as by calling "store.dispatch(actions.setDownloadModInfo(archiveId, 'name', <your name here>));"
after the installation (e.g. in the callback of 'start-download')

Once an archive gets installed, that name flag gets copied into the "customFileName" attribute of the mod which the user can then change manually. You can change these attributes programmatically (setModAttribute) but you may then be interfering with user customization.

**Comment by agc93** [comment]
Awesome, thanks for the info @TanninOne .

I'll give `setDownloadModInfo` a try and see if I can get the flow I'm after to work.

**Comment by TanninOne** [comment]
I think this works as requested now.
