### ISSUE TITLE
Mod files are "redundant" when they are not

### ISSUE THREAD

**Issue by MrTroubleMaker** [Nexus-Mods/Vortex#6070]
**Describe the bug**
My mod is a physics preset for CBP or OCBP or OCBPC. It either contains an ini file or a txt file. Both are configurations for the physics simulations. Vortex is marking them as redundant. I'm getting 100's of complaints from users about your mod manager marking the files as redundant and not installing the mod. I don't use vortex so I 'm just reporting this error and hopefully it will be fixed. I'm getting tired of answering support questions about a mod manger I don't use.

The other cbp and ocbp preset mod authors  have the same issue.

**To Reproduce**
1. Go to https://www.nexusmods.com/fallout4/mods/39195/?
2. Click on any of the three files (two in main and one in optional)

**Expected behavior**
it should install and take priority of either cbp.ini or ocbp.ini or OCBPCollisionConfig.txt

**Additional context**
please fix, thanks

**Comment by TanninOne** [comment]
It's user error. Vortex forces users to set the installation order between your preset and ?CBP? itself and they choose to overwrite your preset with the base mod.
This is not Vortex specific, it's the same effect as if your users installed the preset first and then installed CBP on top.

The only difference is: If your user installs manually or with NMM, doing the above mistake, your preset just doesn't work but your user may not even notice or don't understand what's wrong so they don't report anything.
Vortex let's them know they made a mistake and the solution is simply to toggle the before/after rule.

There is no bug here and I don't really see how to fix it. Maybe it helps if you explain very clearly and in bold that your preset has to go *after* CBP.

**Comment by TanninOne** [comment]
MO would report the same thing btw., it just has far fewer users so you get fewer reports.
