### ISSUE TITLE
[Dark Souls 2] - Dead link for GeDoSaTo

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#6076]
This url appears to be invalid: https://github.com/Nexus-Mods/extension-modtype-gedosato/blob/master/src/index.ts#L95

**Comment by Pickysaurus** [comment]
The source code is GPL-3 : https://github.com/PeterTh/gedosato

So perhaps we could compile it and publish it as a mod on the site?

**Comment by Pickysaurus** [comment]
Alternative link https://community.pcgamingwiki.com/files/file/897-gedosato/

**Comment by TanninOne** [comment]
fixed in https://github.com/Nexus-Mods/extension-modtype-gedosato/commit/b9761cc46945b1d8288476f44458edc61ea8a3a9
