### ISSUE TITLE
Mod Migration performances

### ISSUE THREAD

**Issue by DuskDweller** [Nexus-Mods/Vortex#61]
Mod Migration file copy may need some tweaking, it seems to be currently slower than a normal Windows file copy (by half):

Migration details:
20.961 files
3.262 folders
26GB

HDs: (different locations on the same HD)
3TB 7200rpm HD

Vortex: 38 minutes
Windows: 16 minutes

**Comment by Iloei** [comment]
(What happens when several files copy requests are active together?)

**Comment by TanninOne** [comment]
That's really hard to predict, it may depend on the disk type (SSD or spinning), disk cache, fragmentation, size of the files being copied, potentially even the disk manufacturer.
In my testing copying a few files at once appears to be faster than copying one-by-one or copying many at once.
But I'm fairly certain that the file operations in electron are slow for a different reason. In my test, node.js (basis of electron) copies files reasonably quickly, but with electron it's quite slow. My working theory is that the copy is being processed in the same event loop as all UI operations and so the copy gets interrupted constantly and thus isn't limited by disk speed or CPU but by work scheduling.

A long term fix is going to be to move file operations to a separate process without UI but that requires some work and a lot of testing so it's not going to happen until everything else is stable.

**Comment by Greg-Nexus** [comment]
Added to Product Backlog: https://gitlab.nexdev.uk/vortex/vortex/-/issues/148

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. With the above in mind, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. 

If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
