### ISSUE TITLE
0 B/s download speed

### ISSUE THREAD

**Issue by NightHybrid** [Nexus-Mods/Vortex#6104]
I am trying to download Skyrim Special Edition mods but Vortex is staying at 0 Bytes per second download speed. I've hopped between 3 different networks, restarted Vortex and swapped the USB port for my wireless internet chip and nothing has fixed it.

Windows 10
Vortex 1.1.15
![Vortex 4_18_2020 9_23_42 PM](https://user-images.githubusercontent.com/63908553/79637057-20f4c100-81bb-11ea-8c8c-404e07841e3f.png)

**Comment by TanninOne** [comment]
Network problems are caused by - drumroll - the network, not the client.
This may be caused by your own connection, the ISP or the server, none of which we (Vortex devs)  can fix.
See https://help.nexusmods.com/article/92-im-having-download-issues-what-can-i-do
