### ISSUE TITLE
There's no plugins tab

### ISSUE THREAD

**Issue by keenthek** [Nexus-Mods/Vortex#6115]
There's no plugins tab, when I already added and managed my Stardew Valley folder into Vortex. I followed the other similar issues on here, enabling all the Gamebryo Plugin things, turned off anti virus while installing Vortex, and install Visual C++, but nothing changed. The plugins tab still won't appear. Or is it because SV doesn't have plugins?
 - OS: Windows 10
 - Vortex Version: 1.1.15

**Comment by TanninOne** [comment]
There is no plugins tab in SDV because there are no plugins in SDV.
Plugins are a concept specific to gamebryo games (elder scrolls series and fallout) and only shows up there.
