### ISSUE TITLE
Vortex version update issue - launch of Skyrim SE fails within application.

### ISSUE THREAD

**Issue by bmoorcroft** [Nexus-Mods/Vortex#6146]
Vortex Version: 1.2.7
Memory: 15.93 GB
System: win32 x64 (10.0.18362)

After completing a Vortex update and restarting Windows, attempting to launch an existing Skyrim SE game using SKSE (set as a Tool) from within Vortex brings up a window indicating the required content is missing. It is advising that all primary esm files (Skyrim, Update, Hearthfire, Dragonborn, plus others) are missing.  Advises that content in saved game is missing - Yes or No to proceed.  Accepting "No" returns to Vortex.   Accepting "Yes" returns to Vortex as Skyrim fails to launch.

Attempting to start Skyrim SE from a brand new game also results in returning to Vortex without Skyrim SE starting properly.

Issue has been re-verified after performing shut down and re-start, activating Vortex again and clicking Skyrim SE launch through SKSE defined as Tool.

Verified latest version of SKSE is installed.

Redeployed all mods.  Launch continues to fail on both saved games and new game.

I am able to launch Skyrim SE successfully using SKSE from outside of Vortex and access the saved games in question, plus launch a new game without issue.  Vortex was verified as not running at the time of launch.

Based on this, I deleted the Tool command in Vortex used to launch Skyrim SE and rebuilt it but it continued to fail.

I also tried running other commands defined as Tool such as Wrye Bash.  Those work without issue.

**Comment by TanninOne** [comment]
probably the same as issue #6147

**Comment by TanninOne** [comment]
duplicate of #6147

**Comment by bmoorcroft** [comment]
The ticket remains unresolved.

The issue is not a CTD in Skyrim, it is a failure of the Vortex program to successfully be able to launch the Skyrim game from within itself because it is causing the game to not recognize the ESMs associated to it.  The ability to call the game from outside Vortex is a work-around, not a fix.

Nor is this ticket a duplicate of the previously mentioned ticket 6147 because the game does not immediately CTD after reaching the logo.

This error is continuing to occur even now.

**Comment by TanninOne** [comment]
Vortex 1.2.7 and 1.2.8 had a bug that caused the game to be started without a working directory if it was being started through script extender and the script extender was set up to start as  admin.

This caused the game to not find base data files including the esms. Depending on which game it was it would crash or not find the esms.

This bug was fixed in 1.2.9.

If you still encounter a problem, that is separate from the one we were able to reproduce. In this case we need more information from you, like log files, screenshots of how you've set up skse in the game and information on which of applications (skse and game) - if any - you've set up to run as admin.

**Comment by TanninOne** [comment]
@bmoorcroft Are you planning to provide further information about your issue or can I close this after all?

**Comment by bmoorcroft** [comment]
I am completing testing for the game.  I had noted that Vortex had accepted the 1.2.7 mods, but there was nothing listed for 1.2.8 or 1.2.9, despite attempting to force updates.  I did a reload of the software after backing up my game archives and was able to obtain the remaining updates so Vortex now stands at 1.2.9.

I'd say it can be closed now.

**Comment by bmoorcroft** [comment]
Closing now.
