### ISSUE TITLE
Bug Report - Skyrim CTD after Vortex update

### ISSUE THREAD

**Issue by josec87** [Nexus-Mods/Vortex#6147]
- Windows 10
- Vortex 1.2.8
- Skyrim SE 1.5.97
- SKSE 2.0.17

After the updating today to Vortex 1.2.8, when launching SKSE from Vortex, Skyrim SE crashes right after showing the Skyrim Logo (before loading o creating a game).

My game worked fine prior to updating Vortex. And if I execute SKSE directly without Vortex, it works fine too.

I can continue to install and deploy mods and the rest of the tools (SSEEdit, Wrye Bash, etc) are working fine.

Maybe this issue is caused by something similar to #6146.

**Comment by IDCs** [comment]
Hi @josec87, can you please attach your vortex.log files to this issues; you can find them inside your "%appdata%/vortex" folder - I'm hoping we may find the error code returned by SSE when it crashed.

**Comment by IDCs** [comment]
@josec87, Also can you please edit your SKSE tool on the dashboard and send us a screenshot of the tool edit dialog

**Comment by TanninOne** [comment]
should be fixed by 1be05144759fb5ed69fc00e4d21d00cb673ffc99

**Comment by josec87** [comment]
Here you go:

![SKSE tool edit dialog](https://user-images.githubusercontent.com/747418/80100452-47767b80-8570-11ea-9130-13e0301bcf65.png)

**Comment by josec87** [comment]
Updated to 1.2.9 and working fine now. Thanks! :D

**Comment by IDCs** [comment]
Thanks for confirming @josec87 !
