### ISSUE TITLE
Installing Project Nevada for FalloutNV is going wrong. "Process data cannot perform runtime binding on a null reference"

### ISSUE THREAD

**Issue by no95typem** [Nexus-Mods/Vortex#6149]
Installing Project Nevada for FalloutNV is somehow going wrong. Everything seems to be going fine, but the installation process is very long. Vortex does not give any errors that the mod is installed incorrectly. But when I load FNV I get the error "HUD extensions not detected" and the game just freezes.
There are several lines in the debug files during installation: "process data cannot perform runtime binding on a null reference".
The problem appeared after the upgrade from version 1.1.15 to the latest 04/22/2020. Downgrade helped solve the problem.

**Comment by TanninOne** [comment]
should fixed by commit 6d0929af2e5295a17d1b046c9eb9122b356d7b8d

**Comment by TanninOne** [comment]
Should be fixed in 1.2.9
