### ISSUE TITLE
Bug Report - Conflict Rules not applied to other Versions of the Same Mod

### ISSUE THREAD

**Issue by privatmamtora** [Nexus-Mods/Vortex#6196]
**Describe the bug**
When installing a different version of the mod, the conflict rules are not carried over to the new version, even though when resolving conflicts "Any Version" selected (default)

**To Reproduce**
1. Install a Mod
2. Install a different version of the mod
3. The conflicts still show up

**Expected behavior**
The rules that were set as "Any Version" should be applied to any version of the Mod

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.2.9

**Additional context**
Vortex does identify it as the same mod, because it doesn't show up as a different mod

**Comment by TanninOne** [comment]
What have you set for the name of the mod? What's the mod named on disk?
With mods from Nexus Mods, the version is usually part of the name, so you often have a mod name like
foobarmod_1_1-12345-1-1 which would be version 1.1.
When you update the mod to 1.2, the name would end up as
foobarmod_1_2-12345-1-2.

Even if you have set the rule to match "any version", the **name** between those mods still doesn't match up.
We support wildcards in the name field though, so you could set your rule to be
foobarmod_*-12345-* (any version) and _that_ should then match both versions.

**Comment by TanninOne** [comment]
closed due to lack of feedback
