### ISSUE TITLE
 scroll bars n disable/enable 

### ISSUE THREAD

**Issue by poppajq** [Nexus-Mods/Vortex#6202]
On the mod and plug in pages, could you please widen the scroll bars or at least add a different to it, add arrows on the scroll bar? It is hard to tell where it is sometimes.

Also could you please provide a feature that allows you to disable/enable groups or all mods/plug-ins for trouble shooting?

**Comment by IDCs** [comment]
Hi @poppajq, disabling/enabling multiple mods/plugins is already implemented via the multi-select context menu - simply select the mods you wish to disable/enable as you usually do in Windows and other applications (CTRL/SHIFT + click or press CTRL + A to select everything)

![image](https://user-images.githubusercontent.com/8960252/80941643-e30eb400-8dda-11ea-98ba-95977486f9eb.png)

An action context bar will appear at the bottom with actions you can execute on your selection.

**Comment by TanninOne** [comment]
You can change the width of scroll bars in a theme, this css rule would give you a real monster of a scroll bar:

```
::-webkit-scrollbar {
  width: 16px;
}
```

**Comment by poppajq** [comment]
Hello

To IDC: I am afraid to try that. I was having mod issues 9certain mods not
showing up) and I pulled all FO4 off my desk top. The problem is I got a
warning that my meta data was erased so I am removing all mods, reloading
and reinstalling everything one at a time to avoid issues. Fun Fun.


To TanninOne: where is the location I do that too? I see nothing  on
settings where I can type that order.

**Comment by IDCs** [comment]
@poppajq, there's no reason to be afraid of disabling/enabling plugins/mods, any change you make is easily reversible. If the mods are installed correctly and the plugins don't show up, that's probably down to the files not being deployed yet. Just click the deploy button and the plugin list should be populated. Not

Regarding the theme changes which Tannin mentioned - you can modify your UI by going to Settings -> Theme - and then cloning the default theme. Once that's done you can edit the CSS by clicking the "Edit CSS manually" hyperlink and just copy paste the code at the bottom of the file and then just click apply when you're done
![image](https://user-images.githubusercontent.com/8960252/81045728-ab713c00-8eae-11ea-9067-707620533a0b.png)

**Comment by poppajq** [comment]
Hello

Sorry for being so slow but when I select the edit CSS manually it asks
"what app do I want to use." What would I use? Will it allow me to give the
scroll bars a different color or put the arrows in?

Also, I finally reloaded my mods because I was not sure which ones were
missing the Meta data.  I was not able to cut and paste the list and I do
not know if it is possible to retrieve it. Is that possible?

Anyway, some mods now are hidden or missing from Nexus now so I hope my
meta data is still there for them. Is there a feature to show you if meta
data is missing for a specific mod? If not, it would be a nice feature for
you folks to add sometime.

**Comment by vacuumdiagram** [comment]
Any notepad style app-Notepad, notepad++, etc.  Open, paste in the code, save.  Then apply, and nice size scroll bars-thanks for asking the question!  
It doesn't add arrows, but you can select dark-theme(just above the edit css bit) and that made mine pop out.  You can also change the colours in the same place.  
Mo Arrow addins though, I'm afraid!

**Comment by poppajq** [comment]
Hello

Since I use my TV and sit around 8 ft away finding the scroll area was a
real pain.  I set it to 12 and it is just fine.  Thank you all so much. It
is much easier to find the scroll bar .

Also, here is a story you can pass on to other non tech folks like me.

I bought the vanilla game on disk but I got the DLC from steam. When I
upgraded my almost full 500gb drive to a 8tb drive I re-uploaded my vanilla
disk copy but I re-downloaded my DLC from steam again.  I had a host of
mods stop working. I kept deleting the game and reloading multiple times to
no avail.  I still am not sure why but  mods like OCDecorator,
Homemaker etc always worked.

I had asked you nexus folks and /mod authors for help in why certain mods
were no longer working like build your own pool, invisible furniture etc.
I finally just did a search and deleted any fallout 4 anything and in doing
so I discovered that Steam downloaded DLC and vanilla game  in a different
location on my computer that I didn't know about. In doing so when I
reloaded everything from steam It seems to have solved the game issue but
then vortex said my meta data was missing on a bunch of mods and I did not,
do not know how to save the list.

Is there a feature to show you if your meta data is missing for your mods
specific or otherwise? Re-uploading all my mods again is something I would
not like to do again.

Thanks in advance.

**Comment by IDCs** [comment]
@poppajq, interesting - can you perhaps recall the exact message that Vortex displayed when it reported that metadata is missing? - was it something along the lines of "failed to get plugin info" ?
If so - that's reported by loot and can be down to a number of things and we can't really debug this without the full error message.

Have you possibly modified any plugin files using external software such as xEdit ?

If you're able to reproduce the metadata error, can you please send us your vortex.log files, this can be found in %appdata%/Vortex (ignore the logs folder, we're only interested in vortex.log files which are present directly inside %appdata%/Vortex)

**Comment by poppajq** [comment]
Hello

I failed to write it down but now that I think on it, it did look like a loot msg. I remember getting it back when I  switched from Nexus mod manager to vortex due to new issues I erased the old game and reloaded it and tried to use the mods again. I do not use  modified plugin files using external software such as xEdit at this time. Hopefully I will not have to reload all those mods again but I'll to write it down next time. Is there a way to contact loot to ask about meta data messages? At the least I woiuld like to know if I reloaded all those mods for nothing.

Thanx for being there for us.

Poppajq

**Comment by IDCs** [comment]
Hi again @poppajq, sounds like the metadata has been lost during NMM import; NMM has always been problematic in the way it stores its data and some cases are just too obscure for Vortex to successfully import metadata correctly. I'm afraid that in this case any metadata that has been added manually or if the mod has been sourced externally (not from Nexus Mods) has been lost.

On the bright side Vortex does provide a way to try and guess a mod's modId and attempt to pull metadata from the website if successful - this is applicable only to mods that have been downloaded from the Nexus Mods site. What you can do is select the mods which are missing their metadata and click the "Guess IDs" button in the icon bar which pops up whenever you select more than 1 mod.

![image](https://user-images.githubusercontent.com/8960252/81894362-77c99c80-95a7-11ea-8584-4ce828d50474.png)

I'm going to close this issue as your initial problem has been resolved (scroll bars). Metadata-wise, I'm afraid there's little we can do to help you on that front without the exact error, but it does sound like an NMM import gone wrong (at least metadata-wise)

Just in case you need this in the future, the loot people can be contacted on their github page https://github.com/loot/loot

**Comment by poppajq** [comment]
Hello

What command do I use to change the color of the scroll?

Just to be clear, I am letting you folks know that I first saw the "meta
data" msg when I switched to vortex last year as well as when I cleaned my
pc of all fallout 4 data.

Thanx again for the previous scroll info.

**Comment by IDCs** [comment]
Hi @poppajq, thanks for clarifying. Regarding the colour code:

To change the scrollbar colour add "background-color: colour_that_you_want"; i.e.
```
::-webkit-scrollbar {
  width: 16px;
  background-color: red;
}
```
To change the colour of the paddle/thumb, you need to add the below object.
```
::-webkit-scrollbar-thumb {
  background-color: green;
}
```

I highly recommend not using the colours in the example as they're hideous to look at haha.
The final style file should look something like this:

```
::-webkit-scrollbar {
  width: 16px;
  background-color: red;
}

::-webkit-scrollbar-thumb {
  background-color: green;
}
```

**Comment by IDCs** [comment]
@poppajq, The background-color variable can be set to a hexdecimal value btw - so you can use a html colour picker such as the one provided by w3schools: https://www.w3schools.com/colors/colors_picker.asp and then just change green/red to whatever hex value you generate.

`background-color: #3399ff;`
