### ISSUE TITLE
Multiple matching `requires` rules results in duplicate mod installation

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6283]
Thank you so much for the work getting the expanded meta server support rolled in so soon!

**Describe the bug**
If, during dependency processing, two different rules end up being fulfilled by the same match, that mod will actually get installed twice.

For example, if ModA depends on LibA^1.4.1 and ModB^1.0.0, and ModB^1.0.0 also has a dependency on LibA^1.4.5, two copies of LibA will be installed, even if the meta server lookup for both version matches (1.4.1 and 1.4.5) results in the same final package (1.4.9 for example).

![graphviz](https://user-images.githubusercontent.com/1369269/82961021-81b7ba80-9fff-11ea-957e-bbb75a6ee0f1.png)

I don't *feel* like that's expected, if the the meta server lookup for the two version matches results in the same package version.

**To Reproduce**
1. Installer returns `requires` rules for a dependency that the meta server finds a match for
2. Other dependencies in the graph return a similar dependency that the meta server finds the same match for
3. Two copies of the same matching version of the dependency are installed

Let me know if you need a hand reproducing and I can try and create a mock meta server to demonstrate better.

**Expected behavior**
Vortex thinks the dependency tree so that a single installation of the matching package is installed.

**Logs**
```text
Tue, 26 May 2020 17:13:05 GMT - debug: building dependency instructions type=rule, type=requires, logicalFileName=BS Utils, versionMatch=^1.4.6, type=rule, type=requires, logicalFileName=SongCore, versionMatch=^2.9.1
Tue, 26 May 2020 17:13:15 GMT - debug: building dependency instructions type=rule, type=requires, logicalFileName=BS Utils, versionMatch=^1.4.4
```

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.2.12 Prerelease

**Additional context**

**Comment by TanninOne** [comment]
You're right, that behavior isn't expected.
I'm so sorry you have to play tester for this feature :(

**Comment by agc93** [comment]
Hey, I'm fine with testing this stuff out, I'm just super-happy there's stuff to test out :D

**Comment by TanninOne** [comment]
This should be fixed in dc4ea3696a9cc5647dfbab9bde4656da1fefa6ef

Would you mind trying this release from our CI (https://ci.appveyor.com/project/TanninOne/vortex/build/artifacts)

It's unsigned though, so don't be surprised if your AV acts up.

**Comment by agc93** [comment]
okay so finally got a chance to test this: the duplicate installations seem to have been fixed **but** it now doesn't _seem_ to install the full dependency tree. I'm still testing to see what condition exactly causes it to skip installing certain dependencies.

**Comment by agc93** [comment]
This sounds absolutely insane since I can't work out how this would happen, but the dependencies seem to fail after **3** dependencies.

No matter the size of the dependency tree, it always warns about needing to install **3**
 (or less) dependencies, and it will successfully resolve 3 dependencies. I've included a set of sample dependency graphs below showing which worked and failed.

Let me know what you need to test this further (metaserver, more tests, sample rules, whatever) and I'm happy to try stuff out!

---
![graph_1](https://user-images.githubusercontent.com/1369269/83347210-c37d9380-a366-11ea-9a48-81c93802a75d.png)
![graph_2](https://user-images.githubusercontent.com/1369269/83347212-c8424780-a366-11ea-81e7-f6f09b8a10a7.png)
![graph_3](https://user-images.githubusercontent.com/1369269/83347215-caa4a180-a366-11ea-8a54-a3f85910d2f8.png)
![graph_4](https://user-images.githubusercontent.com/1369269/83347216-cd06fb80-a366-11ea-94ea-e8e74dbfb10d.png)

**Comment by TanninOne** [comment]
Could you give me access to the meta server so I can test? (Ideally via PM if you don't want it public) This is starting to get tedious to try and replicate.

**Comment by agc93** [comment]
Details sent via Discord PM, let me know if you need more info, happy to make this less tedious if I can :)

**Comment by TanninOne** [comment]
Please try with this version: https://ci.appveyor.com/project/TanninOne/vortex/builds/33267324/artifacts

Unrelated but I noticed that that meta server seems to return records that are missing the fileName attribute, which isn't optional. Vortex's reaction is a bit weird as it will use the record but refuse to cache it, which then leads to future queries within the same session to fail.

**Comment by agc93** [comment]
I will try out that build tomorrow and let you know what I find.

For the server response issue: is there any guidance on what `fileName` should *be*? For this particular source, it will probably end up being the same as `logicalFileName`, but just want to make sure it doesn't have extra semantic meaning or anything?

**Comment by TanninOne** [comment]
The filename should be the name of the file on disk, including a file extension

**Comment by agc93** [comment]
Haven't had a chance to test that build, but I have updated that metaserver to now return `fileName` properly which should make testing a little easier :)

**Comment by agc93** [comment]
At least for all the mods I've tested, this is working much better. I had some failures earlier, but I think it may have been a flow-on from the bug in the metaserver. Seems to be working pretty reliably now.

Have noticed Vortex doesn't set any of the metadata attributes for dependency downloads even if they're in the response, but I'll file that as a feature request since it's not exactly high priority!

**Comment by TanninOne** [comment]
Thanks for testing this. The next release (1.2.13) is going to be out soon so I'll be looking into the metadata stuff for the release after that.

I'll close this issue under the assumption that this works properly now, feel free to contact/mention me if it needs to be reopened after all.
