### ISSUE TITLE
Oblivion: Empty folders are not being deleted

### ISSUE THREAD

**Issue by XJDHDR** [Nexus-Mods/Vortex#630]
Basically, empty folders that are the result of Vortex creating them during mod deployment are not being deleted when the contents of the folder are removed/purged. I have attached a screenshot of one example of this behaviour.
![unpurged folder](https://user-images.githubusercontent.com/7355441/43359696-d4f4caee-92fa-11e8-883a-e4c142485e54.png)

**Comment by TanninOne** [comment]
Are you sure the directories are not removed when you hit the "Purge" button? Because that is supposed to remove them.
Simply disabling a mod does not remove these directories. This is intentional because it would increase deployment times unnecessarily.
