### ISSUE TITLE
Suggestion - Mod load order support for Blade & Sorcery

### ISSUE THREAD

**Issue by Kingo64** [Nexus-Mods/Vortex#6301]
**Is your feature request related to a problem? Please describe.**
Some mods can run into load order conflicts. There is currently no way to modify mod load order for Blade & Sorcery through Vortex yet you can do so for other supported games.

**Describe the solution you'd like**
The game loads mods alphabetically by folder name in the mod folder i.e. "Blade & Sorcery\BladeAndSorcery_Data\StreamingAssets". It would be great if there were a way to allow Vortex to manage mod load orders, perhaps by prefixing the mod folder names like: 

- 01_ModA
- 02_ModB
- Mod_Unmanaged
- 99_ModZ

**Describe alternatives you've considered**
Currently the only solution is to manually manipulate the folder names which would of cause confuse Vortex deployments.

**Comment by IDCs** [comment]
Hi @Kingo64, would you be willing to help us test this enhancement ? (due to covid we don't have access to our VR hardware and can't test this ourselves)

**Comment by Kingo64** [comment]
Yeah I can test it. 

Might be a delay from me though since a major update for the game just came out and I have a lot of work to do.

**Comment by IDCs** [comment]
Hey @Kingo64, thanks for helping us out with this!

Ok, so before you do anything with the attached extension, please backup ALL of your Blade and Sorcery mods - simplest way to get to them is to start up Vortex and open your staging folder.
![image](https://user-images.githubusercontent.com/8960252/83907716-cceb6f00-a75d-11ea-903a-fd9cbc227692.png)

Backup all the folders you find there just in case anything goes wrong
![image](https://user-images.githubusercontent.com/8960252/83907884-0b812980-a75e-11ea-81bf-545eb3baa2d0.png)

You mentioned you had manually manipulated the folder names within the game's mods folder - back those up as well and please make sure that the game's mods directory is clean, i.e. only has the "default" folder in it.

Once that's done, go to the following directory "**C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\game-bladeandsorcery**" and backup the entire game-bladeandsorcery folder so you can re-instate the old extension once you're done testing. Please note that if you used the custom Vortex installer then you will have to look for that directory wherever you had installed your copy of Vortex.

Once everything is backed up, extract the contents of the archive that I've attached to this comment into the directory specified above in bold and overwrite the plugin files. End result should look something like this:
![image](https://user-images.githubusercontent.com/8960252/83908350-e50fbe00-a75e-11ea-8648-8c0266a51533.png)

Launch Vortex - you will get the below dialog - it's expected as the extension hashes don't match anymore - just click ignore and proceed.
![image](https://user-images.githubusercontent.com/8960252/83908431-083a6d80-a75f-11ea-86c5-2de63c659d2f.png)

You should be able to see the load order page added to the left below the Mods tab; it will be populated with any valid mods that Vortex managed to detect.

A few things to keep in mind: 
- If you have installed a single mod which has multiple mod manifests  (basically a mod pack of sorts) - there's currently no way for Vortex to include modpacks in the load order, and those mods will be ignored by the LO functionality; you will have to separate those into different mods to be able to use them.
- You will notice a checkbox for each mod entry - ignore it - they're currently in there by default and they do not do anything. They will be removed in the next stable release that includes the LO changes
- Vortex cannot manage manually added mods.

Please let me know if you run into any issues, and always include your latest vortex.log file in your replies so I can debug any odd behaviour - you can find the log files in your "%appdata%/Vortex" directory. (**Not** inside %appdata%/Vortex/logs)

[game-bladeandsorcery.zip](https://github.com/Nexus-Mods/Vortex/files/4737708/game-bladeandsorcery.zip)

**Comment by Kingo64** [comment]
Ok from what I've tried so far it seems to work however I have a few notes on usability.

1. It's not clear to the user that they must 'Deploy' after changing the load order. I would suggest either displaying a notification to the user that the load order has changed and requires a redeployment OR modifying the filesystem when the user changes load order in Vortex without redeployment.

2. There's currently no way to 'un-manage' a mod from the load order. As a result, mods are always prefixed with the load order tag (AAA, AAB) which may introduce load order issues that were unintended by the mod author. There should be a way to exclude mods from load order management.

3. There's currently no way to send a mod to the end of the load order (e.g. ZZZ) if there are non-Vortex mods installed.

4. As you've already identified, non-Vortex installed mods (even with valid manifests) are not visible in the load order and cannot be managed. This is pretty essential for load order management to be effective.

5. There's a typo in the description.
![image](https://user-images.githubusercontent.com/22741730/84152267-c0418080-aaa7-11ea-83ff-ac181e2b1298.png)


I have not included any log files as I have not encountered any errors or issues.

**Comment by IDCs** [comment]
Hi @Kingo64, apologies for not keeping you up to date regarding BaS load ordering - we had a chat with KospY and the game implementation at the time could not guarantee that mods would indeed load in alphabetical order, reason why we waited for a while for this to get rectified in the game first.

Regarding the items you raised in your last post:
1. A notification is now displayed whenever the user changes the LO

2. In this use case, mod authors would be required to manage the mod manually (add it outside Vortex) as IMO catering for it from inside Vortex introduces potential for regular users to mess up.

3, 4. I've added the ability to view externally managed mods inside the Load Order page - these would be locked to a certain prefix and the user will be able to drag them around as he sees fit (and all other mods will react to the prefix change), as long a prefix is available (e.g. if you have AAB-externalMod and AAC-AAD managed mods, you can drag AAC or AAD above AAB, but you will not be able to drag both above AAB as only AAA is available).

To use this functionality, the user needs to open the mods folder and manually add the required prefix, so for example if you have fakeMod inside the mods folder and you want it set to AAC, you simply rename the folder to AAC-fakeMod and hit the refresh button inside the LO page (if it wasn't picked up automatically) - I may add a context menu in the future to allow users to set the prefix from within Vortex in the future.

5. Typo has been fixed, and I've added quite a bit of extra information in there.

The changes are now available to whoever opts into the testing branch of Vortex (currently at 1.3.0). You can opt in through Settings => Vortex => Update
![image](https://user-images.githubusercontent.com/8960252/89282640-bd947f00-d643-11ea-842a-98ade027c800.png)

**Comment by IDCs** [comment]
The update has been well received so far - going to close this down as the functionality has been implemented.
