### ISSUE TITLE
Battlefront 2 infinite "preparing game for modding" notification

### ISSUE THREAD

**Issue by Exclaimedagte4** [Nexus-Mods/Vortex#6331]
**Describe the bug**
Star wars battlefront 2(2017) doesn't work properly.
I have a notification that says "preparing game for modding" forever and never 

**To Reproduce**
I don't fully know how the problem occurred, but this is what I've done that could have caused it.
1. uninstalled the bf2 mod extension 
2. reinstalled the extension

**Expected behavior**
I expected the game to run the mods. but it just says "preparing game for modding"
**Screenshots**

![Vortex problem](https://user-images.githubusercontent.com/66586352/83996777-7f6c2f00-a922-11ea-89d0-fb4fd60a5450.png)

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 1.2.11 ]

**Additional context**
I own battlefront 2(2017) on Origin I was told on another forum that could be a issue

**Comment by IDCs** [comment]
Hi @Exclaimedagte4, SW Battlefront II is a 3rd party extension written by alistair3149 (https://www.nexusmods.com/site/mods/112).  The fact that the extension is stuck during preparation suggests that the extension itself is causing the issue. Can you please contact the extension developer directly through his extension page: https://www.nexusmods.com/site/mods/112?tab=bugs

If I'm not mistaken SWB II uses frosty mod manager - I would suggest ensuring that tool is installed and configured correctly before contacting Alistair.

**Comment by Exclaimedagte4** [comment]
thank you for the help

**Comment by TanninOne** [comment]
I explained what's happening in your forum thread: https://forums.nexusmods.com/index.php?/topic/8792848-it-says-preparing-game-for-modding-for-hours-and-i-dont-know-what-to-do/page-2
