### ISSUE TITLE
Existing mod dependencies are not detected from downloads, redownloaded anyway

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6332]
**Describe the bug**

> So I think this is basically an extension of #6322  in some ways.

*From what I can tell*, the `findDownloadByRef` in `mod_management/util/dependencies.ts` uses whatever `IReference` an installer provides (`logicalFileName`, `md5Hash`, whatever) to detect whether a dependency has already been installed.

**However**, at download time, only the MD5 hash is actually calculated and stored with the download (I think that's in `DownloadObserver->handleDownloadFinished`). So if you install a mod again, and the installer gives dependency refs by anything other than MD5, it will attempt to redownload (correctly prompting the user whether to download again or not), even if it's still in the download list.

**To Reproduce**
1. Install a mod that has dependencies specified by `logicalFileName`
2. Uninstall the mod and it's dependencies (but don't remove the archive)
3. Install the mod again
4. You should be prompted to redownload mods that are already in the mod list

**Expected behavior**
I don't really know how (or if) this can be fixed. I suppose storing the `logicalFileName` or something like that with the downloads (like how the final file name and MD5 hash are) might work, but I'm fumbling in the dark a bit here 😆 .

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.2.13 Testing

**Additional context**

As always, I could have this wrong, but that's my best guess from poking at the code.

**Comment by TanninOne** [comment]
@agc93 There were massive changes to the dependency resolution system as part of the collections update, so I think this should be fixed in 1.5
