### ISSUE TITLE
Triggering mod updates for non-Nexus mods results in errors

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6567]
**Describe the bug**

If a non-Nexus mod has a known update available (i.e. `newestVersion` and `newestFileId` available), the Mods list will show the update prompt (expected). However, clicking this will still result in the updater from `nexus_integration` attempting to install the update. 

For Premium users, this results in an Invalid Link error notification (since the URL [generated by `downloadFile`](https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/nexus_integration/eventHandlers.ts#L184) doesn't exist. For non-Premium users, a browser is launched, but just goes to a 404 (since [its generated URL](https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/nexus_integration/eventHandlers.ts#L145) also doesn't exist.)

**To Reproduce**
Steps to reproduce the behavior (I'll admit this isn't easy):
1. Install a mod from any non-Nexus source
2. Mark it as available for updating (using `newestVersion` and `newestFileId` attributes)
3. Click the Update prompt from the Mods list

**Expected behavior**
I'd say this should only be triggered for Nexus mods, and I'm guessing by:

```ts
// TODO: Need some way to identify if this request is actually for a nexus mod
```

that that's supposed to be the case 😆.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex 1.2.16

**Additional context**

I'm guessing by the implementation for `check-mods-version` (in `util.checkModVersionsImpl`) that checking for a mod having a `source` attribute of `nexus` would be enough to filter out non-Nexus stuff, but I might be missing something, as always!

**Comment by TanninOne** [comment]
No, you're completely right, checking the source attribute should be enough, I don't think we had that attribute when that code was initially written.
