### ISSUE TITLE
DiagnosticsFilesDialog will never display log messages of `warn` level

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6611]
**Describe the bug**

If I'm both testing this right and reading `DiagnosticsFilesDialogs.tsx` right, warning messages printed using the normal `log('warn', 'message here');` function from `util` will never be shown in the Diagnostics Files dialog.

It looks like the component state that the dialog uses to render logs uses the full `warning` while the `LogLevel` definition in `log.ts` uses `warn` instead.

**To Reproduce**
1. Log a warning message using `log('warn', 'message');` using log from `util`/`vortex-api`
2. Open the Diagnostics Files dialog
3. Filter to Warning messages
4. No logs shown

**Expected behavior**

I would imagine this is just a `warn` vs `warning` problem, but I could be reading it wrong.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex 1.2.16

**Comment by TanninOne** [comment]
oh boy, how didn't this get noticed earlier?
You're completely right, it's looking for "warning" when it should just be "warn"
