### ISSUE TITLE
Vortex Mod Manager - Failed Deployment -Failure Running Installed Files

### ISSUE THREAD

**Issue by NightingaleZK** [Nexus-Mods/Vortex#6746]
**Describe the bug**
Alright, so I'm having several frustrating issues with Vortex, and part of the frustration I believe is in the fact I haven't touched Skyrim since a year after it had been released and the mod manager is very different (that's not a bad thing) from what I'm familiar with.
I'm writing all of this after having made several complete uninstall and reinstall attempts with Skyrim Scrypt Extender, Skyrim (Steam), and Vortex with a consistent re-occurrence of certain issues:

1) Vortex is failing to deploy successfully; it states it failed to run FNIS (which is installed) and gives me a report FNIS needs to be installed and placed as a Tool for Vortex, which doesn't help me as I haven't seen or found any instructions of how to do this.
2) I keep getting a red flag stating 2 files failed to correctly deploy (check log for details, which I couldn't find where to access this), stating the files are locked by external applications, which I hadn't experienced before until after I decided to remove mods from Vortex and my Skyrim that was proving to being too buggy for my game to handle. After I did that, it seems like all hell broke lose and I constantly am getting prompted by a pop-up at every deployment attempt stating thus:

"ACCESS DENIED

Vortex needs access "c:\program files(x86)\steam\steamapps\common\Skyrim\data\tools\GenerateFNIS_for_Users\hkxcmd.exe" but doesn't have permission to. If your account has admin rights Vortex can try to unlock the file for you.

which when I try to, its a non-stop pop-up loop where I'm basically being denied and there is something blocking me from proceeding so I have to click cancel at every prompted pop-up window.

3) I tried removed Vortex, and now I permanently have a blank file of Vortex stuck in my Downloads folder that I can neither overwrite with another downloaded Vortex Installer file, nor can I delete. I don't know how in blazes this happened, but I'd REALLY like a solution to this please and thank you very very much.

Replicating?? Well I think either I uninstalled everything wrong or downloaded a virus (or both), though I have downloaded mods before from LoversLab, Steam Workshop, and Nexus Mod Manager in the past, but security in files with mods are a gamble if they're not endorsed or thoroughly made/supported so I guess a virus is a possibility. 

**Screenshots**
 https://drive.google.com/drive/folders/1fedGGczFpnxxs5s3_os-4DYAJJuHNf-v?usp=sharing here are all the screenshots I've taken concerning the issues, as well as the platform spec information of my computer.

I'm currently using the latest version of Vortex: Version 1.2.17

**Additional context**
Thank you to all who give feedback to my questions, I appreciate the patience and cooperative support to my redundancy.

**Comment by TanninOne** [comment]
re 1: There is a huuuge "Add Tool" button on the Dashboard, the first screen that opens when you start Vortex
re 2: When Vortex reports that access was denied on a file or the file is locked by a different application, it's not imagining that. The fact you got these error messages mean that Vortex tried to access the files (in the one screen for example it was trying to deploy hxcmd.exe) and windows refused the access. At this point that's not a Vortex problem any more, file permission exists exactly to limit applications access to the disk, Vortex is being limited to a point where it can't do its job anymore, that's between you and your windows.
re 3: Again, this has nothing to do with Vortex, if you can't delete a file, either that file is currently being used by something, your access permissions on the file don't allow your account to delete it (at least without first acquiring admin rights) or your filesystem is corrupted.

This feedback system exists to report bugs or improvement requests for Vortex and none of this is anything that could be fixed on the Vortex side.

You _could_ run Vortex as administrator which would probably solve the access denied errors but please understand that you running stuff as admin which don't need admin rights is likely you're in this mess in the first place. "Run as admin" is evil unless you actually need it.
The alternative is to use the right-click->properties->security screen to fix the permissions on the files in question.
