### ISSUE TITLE
Tools In Starter Dashlet Change Position When Vortex Starts

### ISSUE THREAD

**Issue by nt5raham** [Nexus-Mods/Vortex#6776]
Of 16 tools, Vortex 1.2.17 is rearranging the last two on the list.  It typically moves Creation Kit (c:\apps\steam\...\Skyrim Special Edition\), and Archive (c:\apps\steam\...\Skyrim Special Edition\tools\archive\) further up the list, about midway.  Where it puts them is somewhat random, but close to the same each time.  The other tools that are being leap-frogged (xEdit, DynDOLOD, TexGen, etc.) are not in the game folder but rather stored in c:\apps\xEdit, c:\apps\DynDOLOD, etc.  The result is inconsistent; i.e. sometimes CK ends up before xEdit, sometimes after.  Once it moves these two apps off of the bottom of the list, if left alone by the user it seems to stabilize for subsequent starts.

**Comment by nt5raham** [comment]
Before and After screenshots provided:

![Before](https://user-images.githubusercontent.com/67662253/86183184-12018780-baf7-11ea-9bfd-7e91d1984dc0.jpg)
![After](https://user-images.githubusercontent.com/67662253/86183193-17f76880-baf7-11ea-94da-109f1bc0c208.jpg)

**Comment by nt5raham** [comment]
Closed inadvertently.

**Comment by nt5raham** [comment]
Before and After screenshots provided below:
![Before](https://user-images.githubusercontent.com/67662253/86183584-f6e34780-baf7-11ea-8a84-987c2701e24d.jpg)
![After](https://user-images.githubusercontent.com/67662253/86183590-fa76ce80-baf7-11ea-806b-d1f07bccc5d4.jpg)

**Comment by TanninOne** [comment]
Hmm, that's a bit weird, as far as I can tell the tools should be ordered pre-configured first, in the order the extension author listed them, then the manually added tools in the order they were added

**Comment by nt5raham** [comment]
They do order themselves that way initially.  In the first screenshot, Archive and Creation Kit were the last two added.  I have not observed tools being moved higher than position 6 (occupied by BodySlide in the screenshots).  The pre-configured tools remain static.

**Comment by IDCs** [comment]
@TanninOne, it appears that when you first add the tools they will indeed display in the order the user added them, however these are stored against the tool's id which is randomly generated whenever a tool is created. Next time you start Vortex, these are fed to the starter in ASCII order using the tool ids, reason why the order seems random upon restart.

We can ensure that we sort these by timestamp when we generate the tools, but that means that any change to an existing tool will change the order yet again. This sounds bad but actually it gives the user an interesting way to organize his tools IMO. Any tools that are left alone after creation will obviously remain in their respectful position.

**Comment by IDCs** [comment]
Not sure if github allow gifs, but basically it would looks something like this:
![asdasd](https://user-images.githubusercontent.com/8960252/86348791-12656400-bc58-11ea-93aa-9c16c251af13.gif)

**Comment by IDCs** [comment]
Actually, the tool ids doesn't explain why nt5raham has a different order each time...

@nt5raham, did you possibly remove/re-create some of those tools ? that would cause the tool ids to change and therefore also change their position in the order.

**Comment by nt5raham** [comment]
I have removed/re-created the tools as a response to the re-ordering, but that is not what causes the problem to begin with.  Remove/re-create is how I have been attempting to manipulate CK and Archive back to the bottom again, where I prefer them.  But the re-ordering is happening regardless.  As noted above, once they re-order themselves they seem to stabilize.  If I can't put up with where they land the first time, I will remove/re-create again and restart Vortex to prompt them to take another shot.  It is like a crap shoot.  They are currently in a "tolerable" position, and they are staying put.  But they will not stay where I manually place them by creating them in a particular order.

I could work with a time stamp ordering process.  That's the way it appears at first anyway.  At least it would provide consistent results.  Ideal would be a drag-and-drop arrangement, but I realize that is another matter.

**Comment by IDCs** [comment]
Hey @nt5raham, thanks for confirming, and yes I agree that the best solution would be to allow users to drag/drop their tools into the wanted position but as we're already considering a UI/UX overhaul - I think a good middle ground would be to sort them by timestamp for now. I'm going to close this issue as the commit above should resolve your issue, but we will keep this use case in mind and potentially allow users to drag/drop their tools around in the future.

**Comment by nt5raham** [comment]
Awesome!  Thanks for your prompt attention!
