### ISSUE TITLE
API Request: Allow dialogs to use both inputs and choices/checkboxes

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#6822]
**Is your feature request related to a problem? Please describe.**
I only recently discovered that dialogs created using `IExtensionApi.showDialog` can't use *both* text inputs (i.e. the `inputs` property) and radio buttons (i.e. the `choices` property). It would be nice to be able to show a dialog with both options since currently asking a user for both a free text response and a fixed-options choice (using either of `checkboxes` or `choices`) has to be done in two separate dialogs.

**Describe the solution you'd like**
I'm no UX designer, but it *seems* like at least some of the controls that are currently `else if`'d could coexist, especially since text input seems to take the upper end of the dialog and the radio/checkbox controls are bottom-aligned, but I don't know exactly to be honest.

**Describe alternatives you've considered**
As it stands, this just means two back-to-back dialogs which is hardly an ideal UX, but workable at least.

**Additional context**
What made me find this was (I would think) the reasonably straightforward use case of asking a user to both name a file and choose its format, which now takes 2 dialogs (or a wizard) since `input` and `choices` can't be on the same dialog.

**Comment by TanninOne** [comment]
This is actually already implemented in the current master branch (so it would be released with 1.3.0)
the input content is then independent of anything else.
The reason some controls are mutually exclusive is simply visuals, it gets increasingly complex to keep it usable the more controls can be combined
