### ISSUE TITLE
Cross-Modtype file conflicts result in odd deployment behaviour. 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#6850]
**Describe the bug**
When managing mods of different modtypes that have file conflicts, the external changes dialogue is raised in cases where it probably should not be. 

**To Reproduce**
Install the following for Skyrim SE:
SKSE64
Vanilla Script Sources (go to your data folder and grab the Scripts.zip, then install it as a mod)

To make this work you also need to manually modify the scripts.zip mod structure. In the "scripts" folder, add another level called "source" and move all PSC files into that folder. 

If you did this correctly Vortex will report 38 conflicts between the two mods. 

Resolve the conflicts by telling SKSE to load after the vanilla sources. Deploy. 

**You will get an external changes dialogue for the vanilla sources saying they've been modified.** (As the SKSE files have replaced them). Choose "revert change" to prevent the edit we don't want. 

Now disable the vanilla sources mod. You'll then see the SKSE reports the same 38 files have been edited. This also needs to be reverted. 

**Expected behaviour**
A clean switch between the files from both mod types.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.2.18

**Comment by TanninOne** [comment]
This has nothing to do with conflict detection, this problem would have occurred before. The entire system was simply never designed for mods of different types to end up in the same directory for them to conflict.
This won't be fixed until the deployment system as a whole can be overhauled.
