### ISSUE TITLE
Vortex Wine - Mouse User Interface Interaction Issue

### ISSUE THREAD

**Issue by ThisNekoGuy** [Nexus-Mods/Vortex#6869]
**Describe the bug**
Using Vortex Mod Manager in Wine (installs and runs fine as long as Winetricks .NET is installed) has a mouse detection issue where hovering over UI elements requires that you place the mouse higher than where a button actually is.

(Also, the custom window border has to be disabled or else attempting to maximize the window gets it stuck in an incorrect maximize position even after restarting Vortex.)
(The UI is also very small in higher than 1k screen resolutions but I suspect this might be an issue with running it in Wine and not Vortex itself.)

(Selecting tabs can also be slow sometimes.)

I did this by using Wine 5.6-5 provided by Lutris.

**To Reproduce**
1. Install Wine normally, as Lutris requires that for its own Wine solution
2. Install Lutris
3. In the Wine tab to the left, in Lutris, click the box-ish icon and install either the aforementioned Wine version or newer
4. Click add new game in the top left in Lutris
5. Name the application and set the Runner to Wine; then in the game options: set the executable to the installer (can be changed to Vortex.exe later)
6. Set the Wine prefix to 64-bit and select the Wine prefix/bottle folder to a place for Vortex to be installed and click save
7. Click on Vortex in Lutris once and select Wine Configuration on the right list to setup the Wine prefix folder (select compatibility to Windows 7 as this usually has the best compatibility for apps then click apply)
8. Click "Ok" in Wine then click Winetricks in the list to the left
9. Select "the default wine prefix"
10. Select "install a Windows DLL or Component"
11. Scroll down and select "d3dcompiler_47" and ".NET 4.7.1"
12. Click "OK" then wait for the installation (Could take a while)
13. Once Winetricks reappears, click cancel until it closes again
14. Click "Start" or doubleclick on Vortex in Lutris to install it
15. Vortex will launch after installation and the issue can then be shown as according to the description.

**Expected behavior**
The corresponding UI elements should be clickable once they are hovered over.

**Screenshots**
![image](https://user-images.githubusercontent.com/28468662/86978702-1bb56b80-c145-11ea-9bc2-e306afd08a61.png)

**Platform (please complete the following information):**
 - OS: Manjaro KDE (64-bit Linux, Kernel 5.7.0-3)
 - Vortex Version: Vortex-1-1-2-19-1594196154

**Comment by IDCs** [comment]
Hi @ThisNekoGuy, I'm afraid we do not support running Vortex through Wine which is most certainly the reason why the UI is glitchy. The dream is to have Vortex run on Linux natively one day, but until that point I'm afraid you will need to run Windows in order to use Vortex. Thankfully we can now actually build the application on Linux but some of our functionality is still Windows only. Keep an eye out on https://github.com/Nexus-Mods/Vortex/issues/2862 for Linux updates.
