### ISSUE TITLE
Increase the size of the "Load Errors" attribute in the extensions table.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#6881]
![image](https://user-images.githubusercontent.com/31670524/87040314-6f2cc580-c1e8-11ea-83dc-b9f701f1ae62.png)

This text box is too small to read the full error, there is also no way (without using the inspector) to see more of the message. Perhaps it can be made into a paragraph field instead of a single line?

**Comment by TanninOne** [comment]
The error message can of course be found in the log file, the sidebar is generally very narrow to show an error message.

**Comment by TanninOne** [comment]
This has been addressed in a recent update.
