### ISSUE TITLE
External changes outside Vortex

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/Vortex#6883]
The above function needs to be fine-tuned/fixed with regards to FNIS.  I'm constantly being bombarded with "External changes made outside Vortex" messages when running tools like FNIS (GenerateFNISforUsers.exe) & SSE Edit...  Please fix this.  Vortex keeps insisting upon reverting the necessary changes made by FNIS since running the .exe included with FNIS is necessary to prevent issues with T-Pose...

**Comment by scjohnson1981** [comment]
Another issue I encounter is Vortex reverting plugins that have the added esl flag to a regular .esp.  Newer versions of Wrye Bash allow the user to add the .esl flag to a .esp if the record count is less than 2K.  I find it to be quite annoying that Vortex would revert a plugin back to regular .esp format when an esl flag helps save a load order slot...  This also needs to be addressed if at all possible.

**Comment by IDCs** [comment]
Hi @scjohnson1981, Vortex does not insist upon reverting anything; you had executed FNIS/xEdit/Wrye Bash and made changes to your mod files - Vortex offers to save the changes to the staging folder to ensure that your changes are applied permanently or if the changes are faulty or unwanted for any reason, you can choose to revert them; it's the user decision. 

Regarding the esl flag, Vortex itself offers the ability to eslify a plugin through the plugin panel which would allow you to skip the external changes dialog completely (at least for that use case)
