### ISSUE TITLE
Vortex stopped functioning

### ISSUE THREAD

**Issue by WanderingThought** [Nexus-Mods/Vortex#6935]
I went on vacation and when I came back Vortex has broken. It won't open, Windows says "This app can't run on your PC" as if it's somehow suddenly a different file extension. All the Vortex files appear to be in the right places. The last thing I did in Vortex was to resize the panes in the window. The icon has changed to the simple folded-corner sheet for unknown file extensions, having done away with the yellow Vortex vortex.

**To Reproduce**
1. Go to Florida
2. Fly home
3. Open Vortex
  3a. "This app can't run on your PC"
4. Go to Google for help

**Expected behavior**
Vortex opens and lets me play Fallout 4

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: Yes

**Additional context**
I have bad posture in this chair.

**Comment by IDCs** [comment]
Hi @WanderingThought, looks like Windows had a few updates during your time in Florida, that error is broad and can have multiple causes behind it all of which are Windows/Environment related. We unfortunately cannot fix/debug this for you.

A few tips though:
1. Try re-installing the latest version of Vortex on top of your existing installation - perhaps something had gone screwy with the installation, this shouldn't affect any of your mods/downloads UNLESS you have set the downloads/staging folders inside Vortex's installation folder (please never ever do that!) - if that is the case, make sure to back up your mods or they will be removed when you update.
2. Open up your Windows' App and Browser Control and have a look at the Check app and files section and make sure it's set to "Warn" and not "Block".
![image](https://user-images.githubusercontent.com/8960252/87391341-71a16d80-c5a2-11ea-98b5-784cfafa202b.png)
3. Make sure that no new security policies had been added by family members during your holiday (revenge for leaving them behind?) which might block you from executing some applications
4. Open up a command prompt with admin rights and type in "sfc /scannow" and wait for it to finish - that should fix any corrupted system files.
5. Google-foo - this is a common issue in Windows and there are multiple solutions out there for it. The very first link I got had some good suggestions (https://www.minitool.com/backup-tips/this-app-cannot-run-on-pc.html) obviously completely avoid any "solution" that requires you to download anything, those are bullshit.
6. I'd say fix your bad posture but mine is worse.

I'm afraid I'm going to close this issue as there's really nothing we can do on our end to help - good luck!
