### ISSUE TITLE
Vortex disables plugins

### ISSUE THREAD

**Issue by Flamingspear2016** [Nexus-Mods/Vortex#6952]
I noticed today that Vortex disables a ton of my plugins on launch. Causing my saved game character (Skyrim SE) to appear naked and in a different location, getting instantly attacked by whatever NPC is close enough to notice him.
This has never occurred before. Not until I updated my vortex this morning. 
 

All I did was launch the game like I usually do ( from vortex ofcourse). I haven't done any further modifications, save for updating Vortex itself.

Any advice or aid would be appreciated.
I'm running the game on Windows 10.

**Comment by TanninOne** [comment]
Vortex doesn't just disable plugins, the only time it "disables" plugins is if you do so manually or if you disable/purge mods (in which case the plugins aren't in the game directory so they can't be enabled).
Another possible cause is if you run foreign tools that might write to the plugin list, like Wrye Bash or the game launcher, those may disable plugins.

Without further information (e.g. log files) I can't really help here.
