### ISSUE TITLE
Vortex reporting an extension as unable to be installed and 4 enxtension are failing to enable.

### ISSUE THREAD

**Issue by AnnaPlays** [Nexus-Mods/Vortex#6975]
**Describe the bug**
I was modding Fallout 4 and when I thought I was done with LOOT and FO4Edit I loaded up Vortex and it reported that "Some of the installed extentions couldn't be loaded because they have missing dependancies" and when I clicked the fix button it says "**Failed to install extention** gamebryo-plugin-management" and the pluglins folder is missing

**To Reproduce**
I am uncertain because I wasn't working with vortex, I was working with LOOT and FO4EditQuickAutoClean to fix the masters and when I was done with that and opened vortex to launch Fallout 4 I got this error

**Expected behavior**
I expected to load vortex, launch Fallout 4 and see if my mods were working

**Screenshots**
![Screenshot_5](https://user-images.githubusercontent.com/68464403/87850539-45416600-c8ae-11ea-89fe-9fe229074cf6.png)
![Screenshot_6](https://user-images.githubusercontent.com/68464403/87850541-45d9fc80-c8ae-11ea-85ac-fbaa1c32b6d8.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.2.19

**Additional context**
I reinstalled vortex completely and nothing changed. I clicked the more button on the second error and it says "The extention 'gamebryo-plugin-management' wasn't found in the repository. This might mean that the extention isn't available on Nexus at all orhas been excluded for conmpatibility reasons. Please check the installation intructions for this extention."

**Comment by IDCs** [comment]
Hi @AnnaPlays, can we please have a look at your vortex.log files. You can find those inside %appdata%/Vortex

**Comment by IDCs** [comment]
closing due to lack of feedback
