### ISSUE TITLE
only runs once on lutris

### ISSUE THREAD

**Issue by codeman101** [Nexus-Mods/Vortex#7018]
**Describe the bug**
The lutris installer script gets the program to run but only once. When I tried to run it today I got an error that links to it's documentation which is here https://docs.microsoft.com/en-us/dotnet/framework/install/application-not-started?version=(null)&processName=rundll32.exe&platform=0009&osver=5&isServer=0&shimver=4.0.30319.0 I tried telling lutris to use the system winetricks and install .Net 4.0 and 4.8 on the system winetricks as well as the .net verifier and even installed the linux version of mono but it still didn't help. For more info on the issue please check out the comments here by others. https://lutris.net/games/vortex-mod-manager/
**To Reproduce**
1. run the install script
2. close vortex
3. relaunch it

**Expected behavior**
Vortex launches

**Platform (please complete the following information):**
 - OS: Manjaro Linux
 - Vortex Version which one is tied to this installer I don't know what it is since I can't launch it https://lutris.net/games/vortex-mod-manager/

I get that this issue is with the installer script and not the app itself but I was hoping someone here could update it. Given what I tried I don't know what the update would be but I'm hoping someone here does.

**Comment by IDCs** [comment]
Hi @codeman101, as I'm sure you know, we currently do not support Vortex on Linux, whether it's using Lutris, Wine or any other "emulator"; AFAIK neither of us even has a Linux environment to attempt to test the installer script and TBH if we did, we would be more occupied with trying to get Vortex to run natively rather than through tools.

That being said, I'll leave this open with the "help wanted" label - hopefully someone from the community could have a look at the installer script; but I would suggest raising this on the Lutris bug tracker instead https://github.com/lutris/lutris/issues

**Comment by codeman101** [comment]
@IDCs 

Thanks for leaving it open and no problem. Tbh I got surprised when I first noticed the lutris script for vortex on the lutris site and I assumed someone in the community on this repo was the author.

**Comment by OknoLombarda** [comment]
I guess it's too late for OP, but someone might still be facing this issue. It seems current lutris installer is not tested properly, so I tried installing an older version. [This](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/1.9.3) one works well. Just download the `vortex.yml` file and run
```shell
lutris -i "$HOME/Downloads/vortex.yml"
```
If you have any further problems, you might find solution [here](https://github.com/rockerbacon/modorganizer2-linux-installer/tree/0203cd1fdc9832152ae1d87c488c7492ea3ecc61)

**Comment by nomiddlename** [comment]
Thanks @OknoLombarda - this suggestion got it working for me.

**Comment by IDCs** [comment]
Thanks for sharing that information @OknoLombarda. And thanks @nomiddlename for confirming the fix works - closing.
