### ISSUE TITLE
Vortex corrupts FNIS Behavior files/XPMSSE install each time it's opened to install/uninstall mods

### ISSUE THREAD

**Issue by scjohnson1981** [Nexus-Mods/Vortex#7166]
**Describe the bug**
Each time I open Vortex to install or uninstall a mod, it borks my entire XPMSSE (XP32 Maximum Skeleton Extended SE) installation, causing my game to crash on load.

**To Reproduce**
1. Install XPMSSE
2. Install/Uninstall other mods using Vortex
3. Launch game (Skyrim SE)
4. Watch as the game CTDs upon any attempt to load.  Reinstalling XPMSSE fixes this issue but the issue returns if Vortex is opened again to install/uninstall other mods.  This is a serious issue & why Vortex borks XPMSSE after each session is beyond me.  I'm in the middle of an extensive rebuild of Skyrim SE after a total crash/burn of my entire modded install a few weeks ago & this issue is hindering my progress.

**Expected behavior**
Game loads when New Game is selected after installing/uninstalling other mods.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 7 Professional x64
 - Vortex Version: 1.2.20

**Additional context**
Reinstalling XPMSSE after each instance of the CTD on New Game after running Vortex fixes this issue.  However, if Vortex is launched again to install/uninstall other mods, the issue with CTD on New Game returns.  I strongly suspect Vortex corrupting XPMSSE files each time it is launched since as previously stated, a reinstall of XPMSSE fixes this issue until Vortex is launched again.  This seems to be an issue with exceptionally large load orders/mod setups.  Please investigate/fix this mess if at all possible.

Update: I also believe Vortex is borking newly-generated FNIS Behavior files as well.  Each time I use Vortex to install/uninstall mods, it hits me with an External Change dialog regarding the newly-generated FNIS Behavior files...  Of course I select the Save Changes (Use Deployed File) option in the dialog box but starting the game immediately thereafter results in a CTD on load, forcing me to reinstall XPMSSE/rerun GenerateFNISforUsers.exe, starting this cycle all over again.  Beyond annoying/ridiculous & needs to be addressed/fixed ASAP.

**Comment by TanninOne** [comment]
Vortex isn't modifying any mod files. It is however auto-running fnis if you have enabled that optional feature. Maybe you have that enabled but not set up your FNIS settings within Vortex?

**Comment by scjohnson1981** [comment]
No, I do not.  I know for a fact that Vortex is breaking my FNIS install after each session since if I don't rerun FNIS, the game crashes on load/New Game each & every time...  Vortex is obviously doing something since the game will not run unless I rerun FNIS after each Vortex session, which is beyond ridiculous.

**Comment by TanninOne** [comment]
I can guarantee you that Vortex does not touch any animation files if you don't have FNIS automation enabled.
You don't do yourself any favors by insisting on something that simply can't be true, you're looking for the cause of your issue in the wrong place and you won't find a solution that way.

When Vortex deploys it creates hard-links (symlinks aren't supported by Skyrim) for the mods in your staging directory to the game directory.
If you run FNIS outside Vortex, Vortex will probably notice that the files were changed externally and ask you how to deal with that. If you now _choose_ to revert the files (use the originals from staging) then yes, Vortex will restore the original files, but you'd be explicitly telling Vortex to do so and I'm sure you wouldn't constantly tell Vortex to revert the files and then complain here that Vortex is doing just that.
Beyond that, Vortex will not do anything with the files.
