### ISSUE TITLE
Could Vortex support PORTABLE mode?

### ISSUE THREAD

**Issue by lyne408** [Nexus-Mods/Vortex#7200]
The user-shared mode of Vortex is system-dependent, so could **Vortex support PORTABLE mode**.

Some people use several Win10, and some people reinstall Windows every few months.
MO has the PORTABLE mode, but Vortex not.

PORTABLE is the best user-shared, like the INDEPENDENT for software engineering.

In fact, in order to make its data independent of the system, I use junction, symbolic links or hard links, link `D:/TEST/vortex_data` to `C:/ProgramData/vortex`, but the third part plugins display 'failed', may be caused by some electron mechanisms. On node, all these can work.

**Comment by IDCs** [comment]
Hi @lyne408, as you probably already know, Vortex can store all of its data in AppData/Roaming which should allow your user account to access Vortex data from any PC that is part of the same Domain.

I understand that what you're asking though is to have Vortex fully portable so you can use it across Domains; we can potentially do that but it's not going to be a trivial task. I'll highlight this as a future enhancement and we will consider implementing this in the future.

**Comment by TanninOne** [comment]
duplicate of #106
