### ISSUE TITLE
Some download URLs will fail to download, or fail to save to disk correctly

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#7215]
**Describe the bug**

> First off, this problem _might_ be in the API I'm using here, but my hands are a bit tied on that.

Some download URLs that will download and save just fine in browsers will cause some very weird behaviour in Vortex.

Some URLs [0] will cause the file to be downloaded correctly, but then the resulting file on disk is wrong (not recognised as a ZIP, or maybe wrong file extension). Other URLs [1] will simply never complete and cannot be downloaded, even after manually resuming the download.

These are being tested using the `start-download` event.

**To Reproduce**
1. Start a download using `api.events.emit('start-download', [<url-from-example>]...`
2. Download will either complete, but be saved incorrectly, or not complete at all

To make this easier to reproduce, I've [slapped together an extension](https://github.com/agc93/repro-vortex-download) that can repro this reliably. Install it from [CI builds](https://github.com/agc93/repro-vortex-download) and it will add a global menu action to start downloads using the URLs below.

**Expected behavior**

These files should be downloaded, recognised as archives and extracted as per normal.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.2.20 and 1.3.1

---

[0]: `https://beatmods.com/uploads/5f2739645baf5a5145fefaf4/universal/Custom Campaigns-2.6.2.zip`
[1]: `https://beatmods.com/uploads/5f274a875baf5a5145fefb05/universal/CustomCampaignLeaderboardLibrary-1.2.2.zip`

**Comment by agc93** [comment]
I've just done a little more digging and can tell you that the "broken" files from Vortex downloads and the valid files from downloading in a browser are **almost** exactly the same. The files downloaded through Vortex however, have 15 extra bytes _prepended_ to the file that aren't there in the browser-sourced versions. To be honest, I have no idea what could be causing that.

**Comment by IDCs** [comment]
Hey @agc93, had a quick look through our download manager to find out why those files aren't being downloaded properly and it looks like Vortex doesn't currently support the way that beatmods.com is serving files; the HTML response is actually served by CloudFlare which immediately closes off the connection, followed by chunks being sent back in an unexpected format (hence why the files downloaded by Vortex differ from the files you would get when downloading through a browser) I'll have a look at this sometime this week - possibly leave it to @TanninOne if I can't figure it out.

**Comment by agc93** [comment]
Thanks for the update @IDCs ! Thought it might be something like that after I started poking around the headers but don't know Vortex's download code well enough to be sure 👍

**Comment by TanninOne** [comment]
The unexpected format is gzip with apparently no compression whatsoever.
Vortex actually advertises to the server that it supports gzip - but doesn't. We used to use a third party library that does this automatically but now we use node.js directly so the header we send isn't actually correct. Weird this didn't come up sooner.

**Comment by agc93** [comment]
Thanks for the update @TanninOne 👍 Is that fix likely to make it for the next `1.3.x` release, or will it have to wait?

**Comment by TanninOne** [comment]
Yeah, it will be in 1.3.2, probably due in the next few days.
