### ISSUE TITLE
Vortex automaticall unzipping zips for new game extension

### ISSUE THREAD

**Issue by Endur1el** [Nexus-Mods/Vortex#7235]
**Describe the bug**
I'm trying to set up a game extension for a new game where mods are stored as simple zip files to be put into a specific folder. I followed the instructions https://wiki.nexusmods.com/index.php/Creating_a_game_extension_for_Vortex here changing .pak to .zip, but for some reason when I give the mod manager a mod to install it automatically unpacks it before placing it in the staging area.

**To Reproduce**
Create a basic vortex extension, and try to install a mod by clicking the install button

**Expected behavior**
Copy the files rather than extract them.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.2.20

**Additional context**
I'm fairly sure this isn't the right place to put this but this repository is by far the most active source of information for vortex. And when this works I'll be making a pull request to add the game pretty soon ^^.

**Comment by IDCs** [comment]
Hi @Endur1el, the problem with mods stored as archive types when using Vortex, is that Vortex automatically assumes that any archive type needs to be extracted to be installed in the staging folder. There are ways around this but both will feel hacky/unnecessary. One thing you could do (and has been done by other extension developers in the past) is double zip your mod file, e.g. cheatMode.zip zipped inside another archive myCheatMod.zip - upon installation Vortex will extract myCheatMod.zip into "stagingFolder/myCheatMod/cheatMode.zip" which will give you the behaviour you're after.

Alternatively you could register a custom installer which re-packs the mod during the installation process; might seem like overkill, but will give you the ability to filter through the extracted archive and read/write from/to files if needed before re-packing it.

Finally I would suggest against submitting a pull request as that would limit the update rate of your extension to whenever we release a new Vortex version. Uploading it directly to the website instead would be the preferred approach!

**Comment by IDCs** [comment]
BTW - feel free to respond to this issue - although I closed it, I will still answer any further questions you have (and yes this is the right place to ask these questions, alternatively you can also find help on our forums or discord channel)

**Comment by Endur1el** [comment]
Thank you, I'll try and go with the second option so that all the mods that are already up can be enabled to work with the extension. I'll also upload the extension to the link you gave me.

**Comment by Endur1el** [comment]
Is there an instruction or some way to pack folders easily in vortex or do I have to import an external library?

**Comment by IDCs** [comment]
You can use one of the modules we've bundled with vortex-api. e.g.
`const { util } = require('vortex-api');
 const szip = new util.SevenZip();
 szip.add(archiveName, filesArray);
`
And that should create it just fine.

**Comment by Endur1el** [comment]
Thank you so much! One final question, if I upload the extension to the site, the game won't show up as support by vortex when you download vortex right? Could I do both once I have it set up properly? Upload a version I could update faster to the site and then create a pull request for a definitely stable version?

**Comment by IDCs** [comment]
No worries buddy - we actually have a mechanism that can pick up 3rd party extensions from the website directly and display them inside Vortex's Extensions and Games pages; so no need to submit a PR request - the game will be available inside Vortex for all users once you upload it to the site and I test it and confirm it works correctly.

**Comment by Endur1el** [comment]
Great, thanks again!

**Comment by Endur1el** [comment]
I'm really sorry for continuing to pester you like this but I'm really struggling to understand this despite looking at documentation likely due to my inexperience with javascript, and I'm just getting really frustrated at this point which isn't helping...

Vortex seems to be using general methods instead of the ones I create in the plugin when they would error out so I'm unable to even properly debug what I'm doing. log('error', text) doesn't seem to work either for that reason I assume.

Any chance you could help me correct the installContent function so that it would take all the files, zip them, and then put them into the mod directory?
`function installContent(files) {
	const szip = new util.SevenZip();

	szip.add(files[0], files);
	log('error', 'test')
	const instructions = filtered.map(file => {
    return {
		type: 'generatefile',
		source: szip,
		destination: 'C:\Users\kacpe\Documents\Battle Brothers\test',
    };
  });

  return Promise.resolve({ instructions });
}`

**Comment by IDCs** [comment]
Hey dude, no worries - the documentation is not robust enough for your use case.
```
const path = require('path'); // Add these to the top if you haven't already
const { log, fs, util } = require('vortex-api');

async function installContent(files, destinationPath) {
    const szip = new util.SevenZip();
    const archiveName = path.basename(destinationPath, '.installing') + '.zip';
    const archivePath = path.join(destinationPath, archiveName);
    await szip.add(archivePath, files.map(file => path.join(destinationPath, file)));
    const data = await fs.readFileAsync(archivePath);
    const instructions = [{
       type: 'generatefile',
       data,
       destination: archiveName,
    }];
    return Promise.resolve({ instructions });
}

```

log('error', text) should write the text to the vortex.log file which is located inside "%appdata%/Vortex" alternatively you could install the dev-tools extension through Vortex's extensions browser and use that to debug your extension directly (It basically gives you access to the debugger https://javascript.info/debugging-chrome ).

**Comment by IDCs** [comment]
@Endur1el, just tagging you so you get the notification that I responded :P

**Comment by Endur1el** [comment]
Thanks for the tag, looking into it.

**Comment by Endur1el** [comment]
It doesn't work if I just replace the previous function. I'm pretty sure I've stumbled onto some weird vortex behavior with it unpacking an archive that only contains folders at the highest level. 

I knew how log is supposed to work and I actually managed to get something from it if I used a double archived mod (as in vortex would then actually run my function when installing). 

If the mod wasn't double compiled I could even have errors in my code so long as it wasn't syntax and it would never come up during the mod install process as I assume vortex is using some other function instead.

@IDCs if you want to continue the conversation on discord it'd be a lot faster to go back and forth. I joined the nexumods discord earlier today you can just tag me as Enduriel#2727.
