### ISSUE TITLE
Column showing in wrong game.

### ISSUE THREAD

**Issue by ChaosGodstone** [Nexus-Mods/Vortex#7390]
**Describe the bug**
Updated to 1.3.5.
Beat Saber.. I think it is, has updated and it's Reference Status column is present in Skyrim SE.

**Screenshots**
![Column](https://user-images.githubusercontent.com/69998756/92816923-f3a0ed80-f3bd-11ea-91bb-8266f5d8e4e6.png)

**Comment by TanninOne** [comment]
The Reference column was added in Vortex 1.3.5, it's not a beat saber feature.
