### ISSUE TITLE
Feature Request: Retain manually added mod dependencies.

### ISSUE THREAD

**Issue by JeffreysDA** [Nexus-Mods/Vortex#7419]
My Minor Issue:
I noticed that you can add additional dependencies and/or rules to a mod in the "Mods" tab. This is very useful for several of my merged mods, as well as my personal mods. Unfortunately, I discovered that the manually added dependencies (as well as custom name, notes, etc.) are not retained when the mod updates, which seems rather strange as mods are updated somewhat frequently. Additionally, I found it tedious to have to click and drag mods to each other to declare such dependencies, as this can be an issue if you have a few hundred mods installed. 

My Humble Request:
If it's not too difficult, I would love to see the dependencies and other manually entered mod information retained during updates. Furthermore, it would be much easier to use if the Dependencies interface for mods could be more like how the Rules interface is for plugins, where you have dropdown menus and can scroll or type the name of the mod that the currently selected mod is dependent upon.

Additional Comments:
While the above two features would be much appreciated, and are my primary suggestions, I do have a separate, yet similar request to be able to "Tag" mods or add them into "Groups" that are separate from their designated Category for easier  management and organization.

My Thanks: 
I would like to everyone who works on and improves Vortex. I, as well as many others, greatly appreciate all the hard work you do to bring us gamers an amazing mod management program. Keep up the spectacular work.

**Comment by TanninOne** [comment]
This was addressed in fd5e4b5f6d243168fae371a0b09937be73484037
