### ISSUE TITLE
Including a Panel.Heading component will "push" the Panel's contents outside the page bounds

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#7506]
**Describe the bug**
Using a MainPage -> Panel structure, including a Panel.Heading component with any content in it will "push" the panel down by the height of the header, so that the Panel.Body will extend below the bounds of the window.

```typescript
<Panel id="test-panel-heading">
    <Panel.Heading>
        This heading will cause the layout to be shifted down incorrectly so the bounds of the panel body below will extend below the app's bounds.
    </Panel.Heading>
    <Panel.Body>
        {/* trimmed */}
    </Panel.Body>
</Panel>
```

This doesn't occur when using `MainPage.Header`, only using `Panel.Heading` inside a `MainPage`.

**To Reproduce**

I've created a sample of both cases (panel heading with wrong layout, page heading with right layout) in [this repo](https://github.com/whyareyoudoingthis/repro-vortex-headings) (with [CI extension builds available](https://github.com/whyareyoudoingthis/repro-vortex-headings/actions/runs/272178422))

**Expected behavior**

I would've expected `Panel.Heading` to work similarly to `MainPage.Header` so that the `Panel.Body` would only take the remaining space.

**Screenshots**
With panel heading:
![image](https://user-images.githubusercontent.com/1369269/94252642-8d909a80-ff67-11ea-962e-6f758360cf64.png)

With page heading:
![image](https://user-images.githubusercontent.com/1369269/94252682-9bdeb680-ff67-11ea-8635-1a652b8b97d8.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.3.9

**Additional context**

I mean it's *possible* this is intended behaviour, but that seems unlikely 😆 To me, it would be nice to be able to use Panel headings for a) multiple panels in a single MainPage and b) more subtle heading styling without resorting to CSS.

**Comment by TanninOne** [comment]
I can change the panel to also be a flexbox so that the existence of the header shrinks the body, but you won't get away completely without css I think because the panel by default doesn't control how overflow is handled, meaning that if you want to scroll in that list you still have to set "overflow: auto" on the body of that panel.
