### ISSUE TITLE
DraggableList doesn't seem to work for TS extensions

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#7514]
**Describe the bug**
This could be user error, however, both agc93 and I have tried to use the DraggableList component exported from the vortex-api and it duplicates items instead of re-ordering them. 

**To Reproduce**
1) Build this extension and load the new tab. https://github.com/whyareyoudoingthis/vortex-draggable
2) Attempt to re-order any of the list items. 
3) Notice that the item you dragged has been duplicated

**Expected behavior**
List is re-ordered

**Comment by Pickysaurus** [comment]
As an additional note, this Component seems to work in pure JS extensions such as game support for Spyro and Bloodstained. 

GenericLoadOrder also appears to use it's own, independent DraggableList.

**Comment by TanninOne** [comment]
DraggableList currently only works if items are strings or numbers.
