### ISSUE TITLE
Record when Plugins marked light or not light

### ISSUE THREAD

**Issue by alandtse** [Nexus-Mods/Vortex#7608]
**Is your feature request related to a problem? Please describe.**
When marking multiple plugins light, sometimes it's hard to remember what was last changed to undo it if it ends up breaking something in the game.

**Describe the solution you'd like**
Vortex could keep a record of when a mod was marked light (within the Plugins UI; obviously if people use other apps I wouldn't expect Vortex to know) or not so users could determine what may need to be undone. This could be shown as another optional column on the Plugins tab. If it helps to generalize it to last time modified by Vortex that could work as I think only the Mark Light/Not Light option is a change from Vortex.

**Describe alternatives you've considered**
Vortex does note that the files have been changed and asks if the newer version should be used. However, to use this to help figure out what needs to be undone, this would require not confirming the change.

**Additional context**
I'm running SkyrimSSE so may not understand other use cases with other games that could complicate this feature.

**Comment by N3Xu5drIfteR** [comment]
Is there a way, or could there be a way, to easily monitor ESL status when upgrading a mod for Skyrim SE?  I have been having trouble getting a stable mod configuration with all of the recent updates from mod authors, which are in some cases bugfixes.  With so many ESL mods in my load order,  I think that it would be very beneficial to get a warning when a non-ESL plugin is replacing an ESL plugin, so I can take the necessary steps to remedy the situation, or avoid the update.  There are many mod authors who do not use Vortex, and so have no idea how their updates affect the load order in Vortex.  Thank you for your time.

**Comment by TanninOne** [comment]
esps being made light is tracked in the plugin history starting with 1.5.2
