### ISSUE TITLE
vortex plugin menu stuck at loading

### ISSUE THREAD

**Issue by WesamLaith** [Nexus-Mods/Vortex#7733]
recently I've decided to change all of the mods I'm using and when i deleted the mods and instilled the other mods but when installed i went to check my plugins but for some reason  the plugin menu won't open and its stuck at the loading screen

![Vortex 10_19_2020 3_07_13 PM](https://user-images.githubusercontent.com/73113460/96449634-d1508a00-121d-11eb-8c66-f448f67dd1d6.png)

**Comment by IDCs** [comment]
Hi @WesamLaith, can you please send us your application state and vortex.log files. Using Vortex's internal feedback system (top right -> 3 dots -> Send Feedback) and use the dropdown button to add your Vortex logs and application state.

Also, we all the mod changes you made done within Vortex's UI or did you perhaps delete/install anything manually ?

**Comment by WesamLaith** [comment]
hi @IDCs, can you tell me where is the dropdown button, because I'm new at modding

**Comment by IDCs** [comment]
Hi @WesamLaith, no worries, so if you go to the internal feedback system through the 3 dot menu as seen below.
![image](https://user-images.githubusercontent.com/8960252/96680587-b2610d80-136d-11eb-933a-fc7d75731b52.png)

Select "bug report" in the next page and type in "Response to #7733" in the title box and at the bottom left you should see a dropdown button as seen in the snippet below. Just click it and attach your vortex logs and application state.
![image](https://user-images.githubusercontent.com/8960252/96680834-27ccde00-136e-11eb-80c8-50c80233e38e.png)

Is there any reason why you don't install/delete mods through Vortex itself ? It's possible that Vortex is having trouble reading one of your manually added plugins, but will have to look at your log to

**Comment by IDCs** [comment]
Ok, after doing some testing - the only way I managed to reproduce your issue is by manually deleting all my plugins from the data folder (including the game's plugins) which will indeed leave the plugin screen in a perpetual loading state.

Given that you confirmed you install/delete mods manually, I'm quite certain that you deleted your game's plugins by mistake - to restore those you will have to re-install your game.

Going to close this issue as I'm quite confident that's the root of your issue, but please let me know if I'm wrong and I will re-open.

**Comment by WesamLaith** [comment]
Hi @IDCs, I did before try uninstalling and installing the game but it didn’t resolve the issue

**Comment by TanninOne** [comment]
Attachment to the previous comment: tmp-159804aaFeFh1wCM2.7z

**Comment by IDCs** [comment]
Re-opening as @WesamLaith is still faced with this issue even after re-installing the game.

**Comment by IDCs** [comment]
Hi @WesamLaith, I can see from your logs that Vortex does actually find your plugins and forwards them to the loot process to retrieve plugin metadata - I think it might be hanging there for some reason - can you please disable all your mods and click the "purge mods" in the mods page and switch back to the plugins page to see if at least the native plugins appear correctly ?

**Comment by WesamLaith** [comment]
Hi @IDCs, the plugin page is still stuck in loading.


![Vortex 10_27_2020 1_40_25 PM](https://user-images.githubusercontent.com/73113460/97290728-02523f80-185a-11eb-8357-2a1bc134c6bb.png)

**Comment by IDCs** [comment]
Thanks @WesamLaith, lets try one last thing before I escalate this to a different member of our team. Can you please switch deployment methods - I can see you're using USVFS; please try using the hardlink deployment method instead - you will be required to move your staging folder to the same partition as your game before the hardlink option becomes available.

Go to the settings page -> Mods -> Deployment method -> Hardlink Deployment as seen below;
![image](https://user-images.githubusercontent.com/8960252/97296440-94514c80-1848-11eb-9624-8960915962ab.png)

Go to your mods page -> Deploy Mods; then switch to the plugins page and let us know if that solved it.

**Comment by WesamLaith** [comment]
No worries @IDCs, it didn't solve it

**Comment by IDCs** [comment]
@TanninOne, I'm going to need your help with this one - the user seems to have the game and mods installed correctly and the plugins are deployed and forwarded to the loot process to retrieve metadata, but for some reason the plugins page is still in a perpetual loading state which hints that the metadata retrieval process never actually finishes? Any idea what might be causing this?

**Comment by WesamLaith** [comment]
Hi @IDCs , the plugin menu is now working

**Comment by IDCs** [comment]
Hi @WesamLaith - please let us know how you managed to fix it! Did you update to 1.3.14 by any chance ?

**Comment by WesamLaith** [comment]
Hi @IDCs, I don't know what fixed it i just was playing the game and downloaded some mods from the game own mods section and went to check on vortex and I found the plugin menu working.

**Comment by IDCs** [comment]
Thanks @WesamLaith, I'm going to assume this was fixed by 1.3.14.
