### ISSUE TITLE
Vortex doesn't change the fallout new vegas game folder, so the game runs without mods.

### ISSUE THREAD

**Issue by ArtyomKaltovich** [Nexus-Mods/Vortex#7740]
**Describe the bug**
Hello.

I can't understand how does vortex works? I downloaded and installed some modes, but the game folder aren't changed at all, so the game is launched without modes.

**To Reproduce**
1. Install Fallout NV and Vortex
2. Install NVSE
3. Install 4GB patch (I guess these two steps are optional)
4. Try to install any mod, e.g. https://www.nexusmods.com/newvegas/mods/35049/
5. Run game
6. The dialog boxes aren't changed.

**Expected behavior**
6. Dialog boxes has more then 3 items.

Vortex doesn't create any warning and shows mod as installed and enabled.

**Screenshots**

**Platform (please complete the following information):**
 - OS: [Windows 10]
 - Vortex Version [1.3.13]

**Comment by IDCs** [comment]
Hi @ArtyomKaltovich, first of all just wanted to make sure you've actually deployed your files. Whenever enabling/disabling a mod, you should get the deployment required notification as seen below. Without deploying, the mod files will not be present in the game's directory and therefore won't be picked up by the game. 

![image](https://user-images.githubusercontent.com/8960252/96682006-14bb0d80-1370-11eb-8758-33301847c9ae.png)

In the case of mod 35049 - I believe you need the archive invalidation/bsa redirection mod enabled for that specific mod to function correctly. If you go to Settings Page -> Workarounds and you should see a "BSA redirection" toggle - make sure that's enabled.

When you have time I would read through the "Knowledge Base" page as that includes a getting started section which will explain most of Vortex's core functionality.
![image](https://user-images.githubusercontent.com/8960252/96683209-bdb63800-1371-11eb-92e3-4f50ff2e681b.png)

**Comment by ArtyomKaltovich** [comment]
Update:
After reinstalling all from the scratch vortex can deploy the mods.
