### ISSUE TITLE
{USERDATA} on linux

### ISSUE THREAD

**Issue by basxto** [Nexus-Mods/Vortex#7746]
**Is your feature request related to a problem? Please describe.**
Vortex uses wrong folder for `{USERDATA}` according to the basedir specification, but that does not impact it’s usage

**Describe the solution you'd like**
`{USERDATA}` should point to `~/.local/share/vortex_devel/` or `$XDG_DATA_HOME` if defined instead of `~/.config/vortex_devel/`

**Additional context**

 > $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used.

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used. 

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by IDCs** [comment]
Hi @basxto, as you probably know, I'm afraid we don't currently support Linux - but we will definitely keep this in mind once we port it over - thanks.

**Comment by IDCs** [comment]
Keep an eye on #2862

**Comment by TanninOne** [comment]
We use the electron api function getPath (https://www.electronjs.org/docs/api/app#appgetpathname) to get at the userdata folder, according to the documentation it should be looking at XDG_CONFIG_HOME

**Comment by basxto** [comment]
Configuration files, cached files and the rest are usually split.

Looking into `~/.config/vortex_devel/`, I think it would be best to do:
- `$XDG_CONFIG_HOME`:  `./Preferences`
- `$XDG_CACHE_HOME`: `./Code\ Cache` `./Cache` `./GPUCache` and maybe `./temp`
- `$XDG_DATA_HOME`:  everything else
(That’s probably not correct, since I don’t understand where the real configuration data is stored ye. But configurations in `$XDG_DATA_HOME` is a bit better than the other way around)

(Those variables all get supplied by https://www.npmjs.com/package/xdg-basedir)

But since that would likely be a lot of work and electron does it wrong by default, I would just make sure to move all the games (`{USERDATA}/gamename`), `extension` and `downloads`, since those are most likely to grow.

I’ll see how much I can get that working with a local fork.
