### ISSUE TITLE
Plugins not sorted because of cyclic rules: false info about masters in tooltips

### ISSUE THREAD

**Issue by Bl4ckread** [Nexus-Mods/Vortex#7751]
**Describe the bug**
If the plugin sorting fails due to there being cyclic rules caused by some of the involved plugins being masters and some not, Vortex gives some erroneous information when hovering your cursor over the arrows in the More info window.

In my case there were three plugins involved: Immersive Encounters.esp, CollegeOfWinterholdImmersive.esp and Cutting Room Floor.esp. CollegeOfWinterholdImmersive.esp and Cutting Room Floor.esp were flagged as ESM and Immersive Encounters.esp was not. The cycle of rules was reported as follows:
Immersive Encounters.esp --> Cutting Room Floor.esp --> CollegeOfWinterholdImmersive.esp --> Immersive Encounters.esp
The first two rules were reported as masterlist rules. The third one said "Immersive Encounters.esp is a master and CollegeOfWinterholdImmersive.esp isn't", which is infact exactly the opposite of what is true. After flagging Immersive Encounters.esp as ESM plugins sorted correctly.

**Expected behavior**
Expecting Vortex to correctly report Immersive Encounters.esp as not a master.

**Screenshots**
[https://snipboard.io/Fg5Eq4.jpg](https://snipboard.io/Fg5Eq4.jpg)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.3.13

**Comment by TanninOne** [comment]
fixed in https://github.com/Nexus-Mods/extension-plugin-management/commit/8b1b839def90f80efdb43d4d1ef847b809ddd574
