### ISSUE TITLE
Vortex cannot read nested FOMOD xmls

### ISSUE THREAD

**Issue by Sulhir** [Nexus-Mods/Vortex#7760]
This is likely not a defect, so consider this more of a suggestion.

First off, story time.
I am old and remember the days when if you extracted an archive the files went everywhere and you would have to hunt each of them down... unless you extracted them to a specific folder for that archive.
So I developed the habit of when zipping files to put them in their own folder and then zip *that* folder, so that when I went to extract it again later it would already be in its own specific folder.  Tidiness achieved!

Most mod managers do this natively, so my habit is redundant.  But it's still a habit.

Mod Organizer 2 can detect a fomod that is packed this way.
```
Mod Folder
>Fomod
>>xml
>File Folder
>File Folder
```

Vortex can only read a mod that is packed *this* way
```
Fomod
>xml
File Folder
File Folder
```

It only took me a few hours of googling fomod xml info and ascertaining that there was nothing wrong with my xml files
and then downloading another fomod that I knew worked
and comparing the two until I narrowed down the problem to file structure

Easier than changing how Vortex reads FOMODs perhaps there's a place where you show proper file structure for Vortex compatibility?  I remember something like this for NMM and maybe it exists and I just didn't notice it through my hours of scouring the internet for answers... which is more an issue for poor search engine crawling on this hypothetical page than the certainty that it does not exist.

**Comment by TanninOne** [comment]
I can't reproduce your problem, the directory structure you described installs just fine in my testing. Could you provide an actual example that doesn't install?

**Comment by TanninOne** [comment]
closed due to lack of feedback

**Comment by Sulhir** [comment]
Sorry.  Missed your request.  I'll try it again and see if it's still happening before I bother you again.

**Comment by TanninOne** [comment]
@Sulhir thank you. If you can still reproduce it, please let me know and either create a new issue or tag me in your reply here and then I'll reopen the issue
