### ISSUE TITLE
Xcom 2 War Of The Chosen cant be found only vanilla

### ISSUE THREAD

**Issue by magic10128** [Nexus-Mods/Vortex#7785]
Using crack version of the game so the application says modlauncher instead of "XCOM2 WOTC" exe. Only works for vanilla xcom2 but still crashes from red screen. The crack game is for WoTc but the vanilla from that same file is the target. I successfully managed to get wotc working once but vortex wouldn't recognize it as a Xcom2 game which defeats the purpose of being able install  mods. 

Yes wotc works when not using vortex. Is there a way I could just directly download then extract mods into folder?

**Comment by magic10128** [comment]
Nvm seems im not the only one. SMH no idea why Vortex mods won't make Wotc be its own game. Its dlc , sure but its massive overhaul. New game in its own right.

**Comment by IDCs** [comment]
WOTC support hasn't been implemented yet #6304
