### ISSUE TITLE
1.3 vortex skyrim save games Chinese display garbled

### ISSUE THREAD

**Issue by xuqingxin001** [Nexus-Mods/Vortex#7794]
1.3.x garbled
![QQ截图20201028002537](https://user-images.githubusercontent.com/33855438/97381595-5fa2cb00-1904-11eb-8812-f36c6630fe5e.jpg)

1.2.x normal
![QQ截图20201028002757](https://user-images.githubusercontent.com/33855438/97381632-6f221400-1904-11eb-87b6-287c7d1e7cc2.jpg)

**Comment by TanninOne** [comment]
Hi @xuqingxin001 , could you please send us a savegame from the chinese version so we can test the fix? You can either send in a feedback and attach the savegame or zip it and attach it here on github directly.

**Comment by xuqingxin001** [comment]
> Hi @xuqingxin001 , could you please send us a savegame from the chinese version so we can test the fix? You can either send in a feedback and attach the savegame or zip it and attach it here on github directly.

I use simplified Chinese mod. Fallout 4 simplified Chinese There is the same problem, skyrin Legendary Edition，Save has mod.

[Fallout4 save.zip](https://github.com/Nexus-Mods/Vortex/files/5450381/Fallout4.save.zip)

[Skyrim save.zip](https://github.com/Nexus-Mods/Vortex/files/5450391/Skyrim.save.zip)

**Comment by TanninOne** [comment]
Fixed by https://github.com/Nexus-Mods/extension-gamebryo-savegames/commit/f9ca3535a865b831af0ab71e79c581d9555e6dd2

In 1.2 the display of Cyrillic characters was broken, in my attempt to fix that I broke it for chinese (and maybe other languages). Hopefully this now works.
