### ISSUE TITLE
Lost mods after update

### ISSUE THREAD

**Issue by Cystallia** [Nexus-Mods/Vortex#7798]
Finally updated to Windows 10 (don't ask) and setting everything up again. However, all my mods on Vortex are gone? Didn't realise this would be an issue so didn't create a backup. I tried to restore save game plugins but it just said that the plugins were missing.  Help online says that the website keeps a record of all downloaded mods but I can't find it. If you could give a link or some other help that would be fab.

**Comment by IDCs** [comment]
Hi @Cystallia, sorry to hear you've lost your mods - unfortunately I'm not sure what state a Windows upgrade would leave Vortex's application data so I'm not able to suggest a fix for that. But you can indeed use your download history to re-download any missing mods https://www.nexusmods.com/users/myaccount?tab=download+history

In the future, please note that this issue tracker is used solely for Vortex specific bugs. It's better practice (and will probably get a quicker answer) to ask any usage/website related question on Discord or the forums.
