### ISSUE TITLE
Vortex hangs on startup

### ISSUE THREAD

**Issue by NekoMiku39** [Nexus-Mods/Vortex#7870]
When I start Vortex, it freezes for 2 to 3 min. And when I open the task manager, it shows 5x Vortex with 1000mb to 12000mb Ram. I used the latest version of Vortex but the problem still exists. I'm not the only one with this problem, regarding to the entrys in the nexus forums:

https://forums.nexusmods.com/index.php?/topic/9269688-vortex-hangs-on-startup/?p=86762723#entry86762723

Windows Version: Windows 10 Pro
Vortex Version: 1.3.17

**Comment by IDCs** [comment]
Hi @NekoMiku39, could you please attach your vortex.log files (located inside %appdata%/Vortex) - hopefully they could shed some light on what it was doing during the freeze.

**Comment by TanninOne** [comment]
Closed due to lack of feedback
