### ISSUE TITLE
Every mod for Pillars of Eternity 2 is marked as incompatible with current game version

### ISSUE THREAD

**Issue by Nightliss** [Nexus-Mods/Vortex#788]
Vortex 0.15.7/0.15.8
Windows 10 Home x64 Latest
Pillars of Eternity 2 Steam Latest

I believe after PoE got updated to 2.0 which added ingame mod manager every mod inside Vortex was marked as incompatible. Currently I have only one installed:

![image](https://user-images.githubusercontent.com/30467858/44004637-a9a02674-9e65-11e8-8e5e-1ff42029598b.png)

Mod link: https://www.nexusmods.com/pillarsofeternity2/mods/32/
Version: 1.2.2

If you need more info, please let me know.

**Comment by TanninOne** [comment]
fixed in https://github.com/Nexus-Mods/test-gameversion/commit/094bed8508074342fb1b791df61f92f300380aac
