### ISSUE TITLE
FOSE Loader couldn't find fallout3ng.exe

### ISSUE THREAD

**Issue by gazzawazza** [Nexus-Mods/Vortex#7930]
**summary**
I can't get fallout 3 GOTY (steam 1.7.0.3) to run from vortex 1.3.17

i get this error:

"Couldn't find C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\fallout3ng.exe, make sure you're running this from the same folder as fallout3.exe"

However, game works ok via steam (albeit with a fose missing error, because one of my primary mods is dependent on it).

FOMM works fine.

fose_loader.exe runs the game fine.

**detail**
I've various mods installed (FOSE, archive invalidation, latest unofficial patch, FWE, HR_ironsights & project reality)

I believe everything is up-to-date and in the correct order. I've been very careful to check the mod instructions too.

FWE complains about a lack of FOSE, if i run the game from steam.

FOSE runs fine (fose_loader.exe)

FOMM runs the game fine too.

**main error (when i click play for FO3 in vortex)** 

"Couldn't find C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\fallout3ng.exe, make sure you're running this from the same folder as fallout3.exe"

![image](https://user-images.githubusercontent.com/3268066/99182981-89475900-2730-11eb-8e0b-4a3d788cc40f.png)

clicking ok on the dialogue box results in the vortex circle continuing for maybe 1 second, then stops.

I've tried both fose 1.2 beta2 and 1.3beta2

**secondary error 1:**
After a clean install of FOSE, on running FO3, vortex notifies:

"failed to run tool" 

clicking on more produces a pop-up

"executable doesn't exist, please check the configuration for the tool you tried to start"

"Executable: C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\Data\fose_loader.exe"

![image](https://user-images.githubusercontent.com/3268066/99183074-34f0a900-2731-11eb-80c7-2d4fec461f6a.png)

This is fixed by copying the missing .exe into this location

NOTE: running the fose_loader.exe from this new location produces the main fallout3ng.exe error

NOTE1: running fose_loader.exe from the next folder up i.e. C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\ produces a successful load.

**secondary error 2:**
the fose mod dependancy in vortex reports a conflict

"conflicts with fallout script extender (FOSE) <1.3.2 ¦¦ > 1.3.2"

![image](https://user-images.githubusercontent.com/3268066/99182898-e7277100-272f-11eb-9e17-a09c7fa6f83b.png)

removing this and redeploying makes no difference to launching FO3 from vortex

**fallout3ng.exe**
My research suggests that fallout3ng.exe is the german no gore executable. I've not been able to find this .exe anywhere on my system. I've done verify local steam files but this hasn't helped. I've of course got a legitimate steam version of the game.

Regards,

Gary

**Comment by IDCs** [comment]
Hi @gazzawazza,

FOSE needs to be installed in "C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty\" alongside the fallout3 executable (I believe you had this installed correctly initially before you moved the executable to ../data/) please make sure to restore it to its original state, read the following article for more information about how to install script extenders and how to configure them https://wiki.nexusmods.com/index.php/Tool_Setup:_Script_Extenders

Once that's done - please make sure that the tool on the dashboard is configured correctly - (the SE tool on my end is for Skyrim VR but all Bethesda games script extenders should be configured the same way)

Go to the dashboard -> click the 3 dots on the fallout script extender tool -> click edit
![image](https://user-images.githubusercontent.com/8960252/99226034-fadee000-27e0-11eb-8499-b9c984f1296e.png)

Make sure the target field is set to the fose executable located inside the game's base/root directory. And make sure that your "Start In" field is set to the game's base/root directory. That should fix your issue.
![image](https://user-images.githubusercontent.com/8960252/99226177-3b3e5e00-27e1-11eb-83d2-8be0cc96640f.png)

Don't worry about the conflict rule - that's being set automatically by our script extender installer.

P.S. not sure why FOSE is searching for fallout3ng.exe instead of regular fallout3.exe, I expect the script extender has a fallback in place which tries to run the ng executable if it can't find the regular fallout3.exe

**Comment by gazzawazza** [comment]
> 
> 
> Hi @gazzawazza,
> 
> FOSE needs to be installed in "C:\Program Files (x86)\Steam\steamapps\common\Fallout 3 goty" alongside the fallout3 executable (I believe you had this installed correctly initially before you moved the executable to ../data/) please make sure to restore it to its original state, read the following article for more information about how to install script extenders and how to configure them https://wiki.nexusmods.com/index.php/Tool_Setup:_Script_Extenders
> 
> Once that's done - please make sure that the tool on the dashboard is configured correctly - (the SE tool on my end is for Skyrim VR but all Bethesda games script extenders should be configured the same way)
> 
> Go to the dashboard -> click the 3 dots on the fallout script extender tool -> click edit
> ![image](https://user-images.githubusercontent.com/8960252/99226034-fadee000-27e0-11eb-8499-b9c984f1296e.png)
> 
> Make sure the target field is set to the fose executable located inside the game's base/root directory. And make sure that your "Start In" field is set to the game's base/root directory. That should fix your issue.
> ![image](https://user-images.githubusercontent.com/8960252/99226177-3b3e5e00-27e1-11eb-83d2-8be0cc96640f.png)
> 
> Don't worry about the conflict rule - that's being set automatically by our script extender installer.
> 
> P.S. not sure why FOSE is searching for fallout3ng.exe instead of regular fallout3.exe, I expect the script extender has a fallback in place which tries to run the ng executable if it can't find the regular fallout3.exe
> 
> P.P.S. your report suggests you haven't used Vortex for Bethesda games before - I recommend you spend some time reading through our knowledge base page - particularly the "Getting Started" and "User Interface" sections

Hi @IDCs 

thanks for the comprehensive reply.

yep I'm new to vortex. FOMM hasn't been supported for ages and i thought I'd try it, as i play skyrim too and I've been looking to try and buff up skyrim a bit with mods.

Regarding your instructions, sadly everything you've described is currently configured correctly.

![image](https://user-images.githubusercontent.com/3268066/99272170-63e54880-281f-11eb-9622-f2c8a4044434.png)

Secondly, i actually copied the fose_loader into data, not move (just to try and placate it lol).

Thirdly, even more bafflingly, i'm not getting any errors now!

Literally all i've done today is run the FOSE from the FO3 dashboard panel (rather than clicking play top left) and a) that worked fine and b) now the play button works fine for FO3 too. Note: i've not upgraded to vortex 1.3.18

![image](https://user-images.githubusercontent.com/3268066/99271778-ea4d5a80-281e-11eb-9736-3f05e8d222b5.png)

i did a little test, which is interesting. I renamed the \data fose_loader.exe and now i get the error about it being missing AND the pathway's changed in vortex (no config from me).

![image](https://user-images.githubusercontent.com/3268066/99271967-25e82480-281f-11eb-82a5-6d32c2ecf021.png)

I had to manually edit the pathway to point back to fallout 3 GOTY folder but, again, i must stress that i didn't do that previously.

So i don't know whether FOSE decides on the FOSE pathway or vortex but there's something not quite right occurring.



regards,

Gary

**Comment by IDCs** [comment]
Hi @gazzawazza, when switching to a Gamebryo game Vortex will scan the game's folder for any pre-configured tools - in previous versions (1.3.17 and lower) script extender tools would become "discovered" regardless of where the tool would be placed within the game's folder structure which is obviously wrong. In 1.3.18 script extender tool discovery is much stricter and should ensure that the use case you describe above shouldn't occur. (plus we have added a test that would immediately notify users if the tool is misconfigured)

**Comment by gazzawazza** [comment]
> 
> 
> Hi @gazzawazza, when switching to a Gamebryo game Vortex will scan the game's folder for any pre-configured tools - in previous versions (1.3.17 and lower) script extender tools would become "discovered" regardless of where the tool would be placed within the game's folder structure which is obviously wrong. In 1.3.18 script extender tool discovery is much stricter and should ensure that the use case you describe above shouldn't occur. (plus we have added a test that would immediately notify users if the tool is misconfigured)
> 
> I'm glad to hear everything is now functioning as expected. Even though we don't know for sure what caused the initial issue you encountered, I'm quite confident that the 1.3.18 fixes should ensure it never happens again.

I tried renaming the fose_loader.exe in the data folder and no error. All is well :+1: 

Thanks once again
