### ISSUE TITLE
notifications UI

### ISSUE THREAD

**Issue by ronamit** [Nexus-Mods/Vortex#7987]
**The problem**
The notifications pop-up on the bell icon is good if there are only a few notifications,  but when there are many it is hard to miss important things.
Another problem is that if I can't see previous notifications if I want to check them out again.

**Suggestion** 
Add a fixed UI box on the left pane, below the tabs menu.
It should show the newest notifications on top and have a scroll slider.
It can also have buttons to toggle - show all notifications \only read \ only unread

**Comment by TanninOne** [comment]
> but when there are many it is hard to miss important things.

Good, you wouldn't want to miss an important thing! ;)

> Another problem is that if I can't see previous notifications if I want to check them out again.

Notifications only disappear permanently if you dismiss them. If you don't want that, just click the bell to hide the box temporarily, then you can open it again.

The notification area is certainly something that will see some love in a future ui redesign but it would then have to be considered together with a bunch of other ui changes.

**Comment by ronamit** [comment]
thanks for the answer.
A few times I dismissed a notification by mistake, because it popped out while I tried to click on dismiss for another notification...
so I didn't even got a chance to read it before dismissing it
