### ISSUE TITLE
Customizes categories 

### ISSUE THREAD

**Issue by LeFlemard** [Nexus-Mods/Vortex#799]
Oyo/
I'll try to be concise.
I have a lot of mods installed (like too much than it is safe).
While troubleshooting, I would love to be able to remove an entire list of mods that use one specific mods as its master.
It would be nice if we could add our custom categories in the mods tab view, obviously that would unlink them from nexus categorizations, but it's a non problem imo.
Is it possible to implement something like that?

**Comment by TanninOne** [comment]
You can already change and add categories in Vortex, just click the "Categories" button at the top of the mods tab.
