### ISSUE TITLE
Extensions cannot be installed from the downloads tab

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#8062]
**Describe the bug**
Vortex extensions downloaded by NXM links do not install from the downloads tab. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Download an extension using an NXM link: nxm://site/mods/126/files/523
2. Go to the downloads tab.
3. Click "Install"
4. Note that nothing happens. 

**Expected behaviour**
The extension installs or an error message is displayed.

Tested in Vortex 1.3.19 on 2 different PCs

**Comment by TanninOne** [comment]
this will be addressed in 1.4.0
