### ISSUE TITLE
Triaged - Reorder the tools on the Dashboard

### ISSUE THREAD

**Issue by HylianSteel** [Nexus-Mods/Vortex#807]
Would you give us the ability to reorder tools how we like? Drag and drop would be preferable I think.

**Comment by Vargr0** [comment]
Oh yes, please!
The only real annoyance I have with Vortex is the inability to reorder the tools on the Dashboard.

**Comment by Greg-Nexus** [comment]
Added to Product Backlog: https://gitlab.nexdev.uk/vortex/vortex/-/issues/167

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
