### ISSUE TITLE
Invalid userlist YAML will prevent Vortex from opening

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#8130]
To be clear, I haven't personally encountered this, but just helped someone through this on Discord

---

**Describe the bug**
If the `userlist.yaml` file for a Gamebryo game exists, but is invalid YAML, Vortex will just close during startup (when the gamemode activates)

**To Reproduce**
1. Close Vortex with SSE (or another Gamebryo game) active
1. Put an invalid file called `userlist.yaml` in the game directory: `%appdata%\Vortex\skyrimse`. (just using `fsutil file createnew userlist.yaml 64` should work)
1. Launch Vortex again and it should fail during startup when the `skyrimse` profile activates

**Expected behavior**
Vortex either handles the invalid file or just updates it on error.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.3.20 (I think)

**Additional context**

Extract of startup log from the user below:

```text
Wed, 16 Dec 2020 07:54:05 GMT - info: changed game mode oldMode=undefined, newMode=skyrimse
Wed, 16 Dec 2020 07:54:05 GMT - debug: gamemode activated skyrimse
Wed, 16 Dec 2020 07:54:05 GMT - debug: [mod-dependency-manager] game mode activated, updating conflict info gameMode=skyrimse
Wed, 16 Dec 2020 07:54:05 GMT - info: css result err=undefined
Wed, 16 Dec 2020 07:54:05 GMT - debug: style rendered successfully
Wed, 16 Dec 2020 07:54:05 GMT - debug: render with language language=en
Wed, 16 Dec 2020 07:54:05 GMT - info: read font C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\assets\fonts\icons.svg
Wed, 16 Dec 2020 07:54:05 GMT - info: sorting mods modCount=88
Wed, 16 Dec 2020 07:54:05 GMT - info: [gamebryo-plugin-management] updated loot masterlist false
Wed, 16 Dec 2020 07:54:05 GMT - debug: initialised
Wed, 16 Dec 2020 07:54:05 GMT - debug: running checks event=gamemode-activated, count=15
Wed, 16 Dec 2020 07:54:05 GMT - debug: [checking staging folder] gameMode=skyrimse
Wed, 16 Dec 2020 07:54:05 GMT - debug: [checking staging folder] stagingPath=D:\Steam\steamapps\common\SSE Mods, vortexPath=C:\Program Files\Black Tree Gaming Ltd\Vortex, gamePath=D:\Steam\steamapps\common\Skyrim Special Edition\
Wed, 16 Dec 2020 07:54:05 GMT - debug: running checks event=startup, count=3
Wed, 16 Dec 2020 07:54:05 GMT - warn: warning notification message=Loose files may not get loaded, title=undefined
Wed, 16 Dec 2020 07:54:05 GMT - debug: sync to profile complete
Wed, 16 Dec 2020 07:54:06 GMT - warn: Failed to load master-/userlist text=LOOT operation "loadLists" failed: yaml-cpp: error at line 1, column 3: unknown escape character: 
cause.func:	loadLists
func:	loadLists, message=Error: LOOT operation "loadLists" failed: yaml-cpp: error at line 1, column 3: unknown escape character: 
    at handleResponse (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:42:33066)
    at Socket.<anonymous> (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins\gamebryo-plugin-management\index.js:42:31572)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:182:23), , wrap=false, allowReport=undefined
Wed, 16 Dec 2020 07:54:06 GMT - debug: all checks completed event=startup
Wed, 16 Dec 2020 07:54:06 GMT - debug: [gamebryo-plugin-management] synching plugins pluginsPath=C:\Users\<user>\AppData\Local\Skyrim Special Edition
```

**Comment by TanninOne** [comment]
It's intentional that Vortex doesn't continue if the userlist isn't readable, because
a) It has to have been manipulated by a user outside Vortex, otherwise why would it be syntactically incorrect?
b) If we did continue, the userlist would be overwritten with blank data.
That means a user tries to change something in the userlist, makes a small syntactical error and as soon as he starts Vortex all their rules are gone. Not a great experience when all it would have taken is them fixing the syntax.

There's supposed to be a dialog explaining this before Vortex quits though.

**Comment by TanninOne** [comment]
Ok, so apparently the code wasn't updated when electron changed their api for displaying dialogs from synchronous to asynchronous so instead of waiting for the user to select whether they want to continue (resetting their userlist) or quit, the dialog only comes up for a few ms before Vortex quits.
