### ISSUE TITLE
"More..." text in the download area doesn't do anything 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#8167]
![image](https://user-images.githubusercontent.com/31670524/102797417-93035280-43a7-11eb-866b-32f62f6328ad.png)

This "More..." text does not appear to be linked to anything. Perhaps it was intended to open the downloads page?

**Comment by TanninOne** [comment]
As an addendum: No, this text was never intended to be clickable, just information that there are further downloads in queue.
But I do think it's a neat enhancement.
