### ISSUE TITLE
GTA 5 Extension: Vortex not triggering OpenIV after deploying 

### ISSUE THREAD

**Issue by popcoin99** [Nexus-Mods/Vortex#8270]
**Describe the bug**
As per the extension description, if replacer mods are installed with the default mod type, deploying should open OpenIV install dialog asking where to install the mods (to mods folder or game files). However this doesn't happen for me at all no matter what I try to fix it. All I end up with is the mods in question being placed in mods/source/content/MODNAME folder. 

**To Reproduce**
1. Set up replacer mods as per extension instructions (update/update,.rpf/common/data... etc. with .rpf being a folder/directory) 
2. Open vortex, and accept the mod changes (if prompted) and set the mod type to default if it isn't already)
3. click deploy mods, which should then trigger OpenIV at the end

**Expected behavior**
After deploying, OpenIV should open as if you're installing an .oiv mod package, asking whether to install to the game files directly or to the mod folder.

**Platform (please complete the following information):**
 - OS: Windows 10 build 19042
 - Vortex Version: 1.3.21

**Additional context**
GTA is installed on E drive, Vortex installed to E drive (for testing, no change in behaviour with it on C drive), mod staging folder on E drive.

**Comment by TanninOne** [comment]
@popcoin99 when you deploy (or vortex starts deploying automatically) you with GTA5 you should be getting a notification "You have to deploy before you play the game" that you have to confirm, did you do that?

Also: could you provide a vortex log with your report? (can be found at C:\Users\<username>\AppData\Roaming\Vortex, ideally send in both vortex.log and vortex1.log)

**Comment by ghost** [comment]
I've just tried launching without deploying the mods, but I do not get a notification about having to deploy before playing (if I launch GTA through vortex), and when launching after deploying my mods, the result is the same as before, scripts apply fine, but replacers aren't working properly. I've attached vortex.log, but I do not have a vortex1.log

Also if this helps, my game also does not have the vortex logo or the word modded in the lower left, as it should according to the extension page.

**Comment by TanninOne** [comment]
> Mon, 11 Jan 2021 10:52:16 GMT - debug: deployment progress text=Deploying: OpenIV, percent=54

This looks like you have installed OpenIV as a mod. That doesn't work, openiv is a tool that you need to install before Vortex can use it. So that ovisetup.exe you have to run, not install as a mod.

**Comment by popcoin99** [comment]
Ah yes I can see how that would look in the log, I’ve got open Iv installed (both manually from their site, and I’ve also tried letting vortex manage the download and install, either made no difference to the outcome though) 

what I’ve done there is I’ve got a folder in the staging folder for openiv.asi/any related logs, so that I can pull out everything for a completely clean folder layout. However I’ve also tried not having that setup and instead having the .asi in the games folder outside of vortex management, that also resulted in the same outcome of openIV not launching when deploying/playing via vortex

**Comment by TanninOne** [comment]
Sorry, this ticket kind of fell by the wayside. From the log all I can see is that OpenIV was not found and afaict Vortex showed a warning notification about that.
We haven't received any other reports claiming Vortex silently doesn't invoke OpenIV.

If this is still an issue, please create a new ticket, otherwise I'll assume you've either found a solution or moved on.
