### ISSUE TITLE
game search can get stuck in an endless loop

### ISSUE THREAD

**Issue by TanninOne** [Nexus-Mods/Vortex#83]
Apparently the walk method used in the game search follows links, so if it encounters a link that points to a directory higher up in the directory tree, it will continue to loop forever.

**Comment by M4lik** [comment]
I assume you mean symlinks, beacuse shell links (`.lnk`) should be treated as regular files...

The best method for this should be (in my opinion) to just skip these. If somebody has a symlink on windows to another dir, you could simply add this directory as another search path.

**Comment by TanninOne** [comment]
should be fixed by #112
