### ISSUE TITLE
Bug Report - Vortex unable to remove deployed files deployed with hidden attribute

### ISSUE THREAD

**Issue by Kingo64** [Nexus-Mods/Vortex#8302]
**Describe the bug**
Vortex is unable to remove any files that were deployed with the hidden attribute set in the original installation source. The files also do not correctly deploy with the original file attributes either.

**To Reproduce**
1. Download the main mod files for [TOR](Use case this applies to: https://www.nexusmods.com/bladeandsorcery/mods/528)
2. Install and deploy via Vortex
3. Uninstall/remove the mod via Vortex
4. The files that were marked as hidden in the install zip file are not removed by Vortex and are left behind. The are also not hidden as intended either.

**Expected behavior**
It is expected that all files deployed by the mod are removed including these files. It is also expected that Vortex respects the original file attributes when deploying and thus would deploy the files as Hidden.

**Screenshots**
Folders left over after removing the mod via Vortex
![unknown](https://user-images.githubusercontent.com/22741730/104552440-f3c33980-568c-11eb-8849-bb185cfc188c.png)

"Hidden files" left over after removing the mod via Vortex. Note they do not have the hidden attribute either.
![unknown](https://user-images.githubusercontent.com/22741730/104552516-16ede900-568d-11eb-8f4b-841c032f658d.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.3.22

**Additional context**
Use case this applies to: https://www.nexusmods.com/bladeandsorcery/mods/528
The JSON files are marked with the Hidden file attribute as they are easter egg items, this does not cause problems with manual installs.

**Comment by TanninOne** [comment]
Can confirm. These files will disappear when you deploy the next time though.
