### ISSUE TITLE
[FO4] Vortex still giving me the set error message: yaml-cpp: error at line 69, column 7: bad conversion: set elements must be unique

### ISSUE THREAD

**Issue by twist3dimages** [Nexus-Mods/Vortex#84]
https://github.com/loot/loot/issues/872#issuecomment-366272828

I think I'm going to go ahead and import everything again. I purged all the mods. What would you recommend doing? Should I delete the AppData\Roaming\Vortex folder?

I guess what I mean is a fresh clean import

**Comment by twist3dimages** [comment]
Oh I feel dumb. I deleted all the dependencies and it didn't give me the error. I still see certain esps show up at the top (image below). Not sure if this is normal or not.

![image](https://user-images.githubusercontent.com/33134502/36318374-a4303ff0-130d-11e8-8f59-58fcc2acb2c6.png)

**Comment by TanninOne** [comment]
Vortex currently only sorts by one attribute, there is no "secondary" sort column, so when you're sorting by priority (like in this screen) all plugins with a prio of 0 have the same "rank" and the order among them is essentially random.

**Comment by twist3dimages** [comment]
Do you have an example of what your priorities look like?
