### ISSUE TITLE
Some text can't be translated

### ISSUE THREAD

**Issue by SettingDust** [Nexus-Mods/Vortex#8471]
**Describe the bug**
- [ ] https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/hardlink_activator/index.ts#L35
![image](https://user-images.githubusercontent.com/19922286/107173210-38c75b00-6a02-11eb-98a0-6df916905a73.png)
---
## Game name
- [ ] https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/mod_management/views/Settings.tsx#L166
![image](https://user-images.githubusercontent.com/19922286/107173336-89d74f00-6a02-11eb-9bff-1d6827588701.png)
- [ ] https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/profile_management/views/ProfileView.tsx#L270
![image](https://user-images.githubusercontent.com/19922286/107174944-85149a00-6a06-11eb-886a-5a1bd36a08b4.png)
- [ ] https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/profile_management/views/ProfileItem.tsx#L138
![image](https://user-images.githubusercontent.com/19922286/107173772-93ad8200-6a03-11eb-8c61-6dcbad2888b1.png)
- [ ] https://github.com/Nexus-Mods/Vortex/blob/master/src/controls/table/GameFilter.tsx#L44
![image](https://user-images.githubusercontent.com/19922286/107174999-a1b0d200-6a06-11eb-958a-2f8a31a4188a.png)
![image](https://user-images.githubusercontent.com/19922286/107173349-8e9c0300-6a02-11eb-8701-3d348f05bdba.png)
They should be translated (The last). The name in Chinese has been set.
---
- [ ] "Select..." in every drop menu
![image](https://user-images.githubusercontent.com/19922286/107173727-7973a400-6a03-11eb-9303-2f779e260a87.png)
- [ ] The widgets name in "Settings"
![image](https://user-images.githubusercontent.com/19922286/107174123-631a1800-6a04-11eb-96be-b232cacd5ff7.png)
- [ ] https://github.com/Nexus-Mods/Vortex/blob/master/src/extensions/download_management/views/DownloadProgressFilter.tsx#L11
![image](https://user-images.githubusercontent.com/19922286/107174351-f5222080-6a04-11eb-8895-af28e2eb07c0.png)
![image](https://user-images.githubusercontent.com/19922286/107174363-fa7f6b00-6a04-11eb-832d-517e441d9f89.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.3.22

**Comment by TanninOne** [comment]
Thanks for the report.

Regarding the "Hardlink deployment" specifically: Is it actually a good idea to translate technical terms like this? These are names and if a user tries to find help about a problem with it it will have an easier time if they know the english term.
I'm german myself and I was never a fan of localized technical terms.

But I guess I can mark the text localizable and leave that decision to you.
