### ISSUE TITLE
Built-in extensions cannot be overriden by extensions added through appdata

### ISSUE THREAD

**Issue by ObsidianMinor** [Nexus-Mods/Vortex#85]
When working on [Nexus-Mods/vortex-games](https://github.com/Nexus-Mods/vortex-games) I made changes to the No Man's Sky extension. I copied the changed extension to `%appdata%/Vortex/plugins` and opened Vortex to test the extension to make sure it worked. When I opened Vortex I checked the supported games list and No Man's Sky appeared twice. I tried to manually set the install path on both and both returned the error I was trying to fix. Changing the ID for the new extension made it so I could test it however with the new ID all Nexus API integration was destroyed since "nomanssky2" isn't a game on Nexus Mods.

This makes it extremely difficult to test changes made to built-in extensions since with the current repository design you have to fork each extension individually and you can't commit changes to submodules.

**Comment by TanninOne** [comment]
Agreed, this needs to be fixed. for the time being you can disable the extension from the extension menu and then copy your modified version to the appdata directory, this way only the one gets used.
Or you delete the bundled version of the extension at C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar.unpacked\bundledPlugins

**Comment by ObsidianMinor** [comment]
Disabling the extension and then moving the modified version to appdata doesn't work since Vortex considers both the built-in extension and the extension in appdata to be same thing and disables both.

**Comment by TanninOne** [comment]
Only if you name your extension (the directory name) exactly the same.

**Comment by TanninOne** [comment]
This has been fixed a while ago.
