### ISSUE TITLE
Pre-release

### ISSUE THREAD

**Issue by class101** [Nexus-Mods/Vortex#8511]
When you install 1.4.0 pre-release, you get  a notification that there is a new version available.

Upon installing the new version, it is back to 1.3.22

I have the feeling Vortex trolled me -_-

**Comment by TanninOne** [comment]
Don't install 1.4 by downloading from github, go to settings->vortex and set the update channel to "Beta".

Vortex will always update to the newest version on the configured channel, if that is set to stable, Vortex will update to the latest stable version which is 1.3.22.

**Comment by class101** [comment]
If I want to download it on Github that's my choice, otherwise, don't publish.

Shouldn't be that hard to code if version < latest release = update rather than if version != latest release = update. I develop software myself and I find this a bad design.

Thank you for the reply anyway.
