### ISSUE TITLE
Witcher3 - Implement sort functionality to assign LO priorities according to dependency rules

### ISSUE THREAD

**Issue by morphelianus** [Nexus-Mods/Vortex#8515]
Hey @morphelianus, regarding setting the LO according to deploy order - this is something that I can't do by default as this behaviour might not be desirable by other users - but I could indeed add functionality to sort the LO according to deploy order on button click (added to the LO page toolbar) could you please create a feature request for this so I can track it ?

_Originally posted by @IDCs in https://github.com/Nexus-Mods/Vortex/issues/8503#issuecomment-777265389_

**Comment by morphelianus** [comment]
The deploy order can be set by drag and drop the dependencies. By doing that an popup opens asking to set something like "must load before / after", "requires" or "in conflict with". The result of this approach is my desired deploy order and pretty much what I need as load order. Is it possible to implement something that forces the load order in the same order as I setup the deploy order? Not by drag and drop the mod in LO node, maybe just by clicking a sync button? That would be great and closer to my wish to automate some processes, e.g. whenever I test a mod or switch to another profile.

**Comment by TanninOne** [comment]
Please clarify which game this is about.
This doesn't necessarily make sense for every game so the feature should be provided very selectively.

**Comment by IDCs** [comment]
This enhancement would only apply to Witcher 3 - I'll be adding new sorting functionality to assign priorities to LO entries using the dependency rules defined by the user in the mods table.
