### ISSUE TITLE
Mods updated in Vortex not updating "Last Downloaded" on Nexus

### ISSUE THREAD

**Issue by rosskinard** [Nexus-Mods/Vortex#852]
Searched and didn't see this anywhere else so hopefully not duplicating.

I use the **Track Mod** feature in Nexus to get a central location for all my mods, and any mods I've updated from within Vortex did not update the "Last Downloaded" date in Nexus. So even though my mods are current versions according to Vortex, only the mods I manually selected and installed from Nexus actually changed the DL dates. The tracking page still shows DL dates of a few months ago and the "Updated" overlay on the Vortex-updated ones.

Shouldn't Vortex update Nexus with a current DL date when the mod is updated within the app?

**Comment by TanninOne** [comment]
It would be the job of the API Server to keep track of downloads from clients.
This is a known issue internally but if you want to report it anyway it should be reported here: https://github.com/Nexus-Mods/web-issues/issues
