### ISSUE TITLE
Add a way to see file conflicts between mods

### ISSUE THREAD

**Issue by CreeperLava** [Nexus-Mods/Vortex#86]
Similar to MO's conflict window, it would be very useful to have a way to see which mods conflict with each other (ie overwrite each other's files). Bonus if we can have a preview of each mod's files, which would be great to quickly compare textures.
![modorganizer_2018-02-18_13-22-40](https://user-images.githubusercontent.com/12874678/36351761-e59eac86-14ae-11e8-8d1d-0edde6d4037a.png)

Additionally, it seems odd that there is no way to change the order of the mods like in MO.
![modorganizer_2018-02-18_13-23-04](https://user-images.githubusercontent.com/12874678/36351760-e5815f82-14ae-11e8-957a-51f2a20d42d1.png)

I know I'm comparing a lot to MO, but I suppose we're all expecting similar to superior features to MO in Vortex, so I think it's only fair :).

**Comment by TanninOne** [comment]
Part of this is already implemented. If two mods conflict Vortex will also show a lightning bolt in the dependencies column (which may be hidden).
When you click it it will show all other mods that the selected one conflicts with, the number of conflicting files and (in a popover) which files those are.

**Comment by CreeperLava** [comment]
I see, my apologies. I hadn't tested thoroughly enough. However, the way it is implemented right now isn't practical and, imo, confusing.

A few remarks :
- The most important issue I have with the conflict management is that you have to use a separate UI from the main list (the conflicts popup, screenshot below). This means more clicks, and it is harder for the user to grasp a global view of their load order.
- The task of resolving conflicts becomes more tedious the more mods you have, because of the way conflicts are shown relative to a mod (eg load mod Y before/after mod X), and not to the mod order. Here an example with several large mods conflicting with each other. Seeing what exactly conflicts isn't easy, and I can see conflicts becoming impossible to manage the more mods you have (eg load Y before Z but after X, etc).
![vortex_2018-02-19_11-34-00](https://user-images.githubusercontent.com/12874678/36373564-d3d5864a-1568-11e8-852b-a468c1c3b4ae.png)
- I believe it would be possible to solve both these issues by going the MO way and allowing drag and drop of mods in the main mod list, to change the mod order. That way you keep the additional UI of Vortex (screenshot above) to show details about the conflicts, while enabling quick mod order changes.
- There is no way to open the folder in which the conflicting files are located (screenshot below). Adding some functionality to a right click context menu (open file, open folder), would be useful.
![vortex_2018-02-19_11-34-06](https://user-images.githubusercontent.com/12874678/36373563-d370f446-1568-11e8-8fde-9aa8eac19007.png)

I suppose the reason you removed those functionalities compared to MO is to make the tool simpler to use for casual users, but it makes it much more difficult to use effectively for advanced users. It's a difficult balance to achieve. Hope this helps !

**Comment by cybercatgurrl** [comment]
I'd like to add that it's very confusing which files are actually being used. It needs some way to distinguish that between all the conflicts which mods files are really being used. I'm not able to make it do what I want it right now because I have no idea what it's actually doing.

**Comment by TanninOne** [comment]
@Arcanant Handling of  individual file conflicts is on the todo list. As is a way to preview the files (as far as we can implement the file types)

@cybercatgurrl I don't really understand your problem. The last mod being loaded will win a conflict, as if you  had installed them in that order and had always picked "overwrite all", except that with vortex you can change it around at any time.
If you set a rule "mod a loads after mod b" then the files  in mod a will be picked over the ones from mod b, and the popover tells you which those are.
But any rule only decides the order between those too mod, if you have "mod c loads after mod a" then mod c will win over mod a and, in extension, over mod b.

**Comment by cybercatgurrl** [comment]
@TanninOne I'm not sure I can describe the situation more. I tell Vortex to load a skin texture after CBBE and the skin texture never gets installed. So I just assumed I don't actually understand the ordering of dependencies rather than it being an issue with it simply not copying the files into SkyrimSE.

On another note, when more than 4 mods have files that overwrite (as such in the case of texture replacers) each other it becomes a hell to maintain and keep track of without getting cyclical dependencies. The current setup just isn't working for me.

**Comment by TanninOne** [comment]
Individual file conflicts have been implemented in the meantime. Since this issue seems to touch several to topics and some have been addressed, please do me a favour and create new issues for remaining enhancement requests.
