### ISSUE TITLE
QuickBMS integration filters out all results when using placeholders in wildcards

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#8606]
**Describe the bug**
If a wildcard (provided in the `qbmsOptions.wildCards` property) uses a placeholder (like the very common `{}` for all), the `parseList` function will filter out all results returned from QuickBMS since it assumes an explicit string wildcard.

**To Reproduce**
1. Install the `QBMSTest` extension that the docs provide as a sample
1. Change the wildcard on line 21 to `{}.png`, or just `{}` for that matter
1. Click on Test QBMS List
1. Either step through `parseList` or check the logs to see that nothing was returned

**Expected behavior**
Given the docs explicitly mention using wildcards like `{}.png`, I'd expect them to work, but they don't appear to. This is especially odd when _not_ providing a wildcard causes errors in the same line in `parseList` (since `wildCards.find` will blow up).

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.4.2

**Additional context**

**Comment by IDCs** [comment]
@agc93, thanks for testing the QBMS extension out, being its sole user made me foolishly unaware of issues such as the one you describe above.

**Comment by agc93** [comment]
Thanks for sorting that @IDCs , much appreciated!

Not a problem, saw the new integration and had to give it a try so finding the bugs as I go 👍
