### ISSUE TITLE
Typo in Symlinks error

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#8616]
I've just seen this while helping out a user:
![image](https://user-images.githubusercontent.com/31670524/109014419-06795700-76ac-11eb-84aa-b9b1099906d7.png)

It should probably say "Symlinks are not supported"? I'm not entirely sure under what conditions the message is shown though.

**Comment by agc93** [comment]
@IDCs I think the original report was about `support` vs `supported`, not the lack of `are` 😅

**Comment by IDCs** [comment]
Ha! I shouldn't commit stuff before having coffee, thanks @agc93
