### ISSUE TITLE
Potential problem posted in Vortex Forum about Uninstalling, THEN purging.

### ISSUE THREAD

**Issue by HadToRegister** [Nexus-Mods/Vortex#8629]
A person has reported in the Vortex Forum that Vortex has been purging mods for 6 hours. Version 1.3.22

Apparently what they did was they UNINSTALLED the Mods first, THEN told Vortex to purge the mods.

If this is the cause of the 6 hour non-stop purge, can some type of check be implemented so that Vortex doesn't end up in an endless loop of trying to purge mods that don't exist because they've been uninstalled? 

Apologies if this has been addressed in 1.4.xx, but I think it needed attention drawn to it, just in case.

**Comment by IDCs** [comment]
Hi @HadToRegister, I'm afraid we can't begin looking at this without the user's log file (the one that captures this behaviour)

**Comment by TanninOne** [comment]
Yes, without a log there isn't really anything we can do. If you suspect a user has a legit bug report, please ask them to report it through the feedback system inside Vortex or to github directly.
In almost every case (this one included) we will need a log.
