### ISSUE TITLE
Blade and sorcery still broken.

### ISSUE THREAD

**Issue by Darkwolf1515** [Nexus-Mods/Vortex#8631]
**Describe the bug**
Mods extract into whatever vortex decides it wants to call them, this breaks the mods.

**To Reproduce**
Install a mod through vortex
see that it does not work
install manually
works

**Platform (please complete the following information):**
 - OS: windows 10
 - Vortex Version 1.4.2

**Additional context**
Vortex keeps trying to install these game updates, one being for blade and socrery from 2 weeks ago, clicking install does nothing, a fresh install of vortex did nothing.

**Comment by Darkwolf1515** [comment]
Fresh vortex install, issue still persists.

**Comment by IDCs** [comment]
@Darkwolf1515 you're going to have to provide links to the mods that fail to install correctly and also confirm that you have version 0.2.4 of the blade and sorcery extension (in the extensions page). I ran some tests when I initially noticed your report an hour ago and I can't reproduce the behaviour you've encountered.

Currently 0.2.4 will always use the mod folder as provided by the mod author unless the mod author did not provide a mod folder, in which case it will use the name property inside the manifest file.

**Comment by Darkwolf1515** [comment]
> 
> 
> @Darkwolf1515 you're going to have to provide links to the mods that fail to install correctly and also confirm that you have version 0.2.4 of the blade and sorcery extension (in the extensions page). I ran some tests when I initially noticed your report an hour ago and I can't reproduce the behaviour you've encountered.
> 
> Currently 0.2.4 will always use the mod folder as provided by the mod author unless the mod author did not provide a mod folder, in which case it will use the name property inside the manifest file.

Says 0,23, i have been unable to install 0.24 it seems, even on a fresh install,.

**Comment by Darkwolf1515** [comment]
Ill download the source and replace the extension that way

**Comment by IDCs** [comment]
@Darkwolf1515, are you sure you have 1.4.2 installed ? 0.2.4 should've been included in that version of Vortex...

**Comment by Darkwolf1515** [comment]
![Screenshot 2021-02-27 001659](https://user-images.githubusercontent.com/65789901/109381776-3145f400-78d4-11eb-98fe-a7d408b1d1ec.png)
Yes, fresh install, i tried replacing it with what was in the source, renamed the folder to have the right number, apon reboot, vortex redownloaded 0.2.3

**Comment by IDCs** [comment]
If you go to the about page, the Vortex version should be displayed

![image](https://user-images.githubusercontent.com/8960252/109381792-46bb1e00-78d4-11eb-859b-7f3f11873d91.png)

**Comment by Darkwolf1515** [comment]
Hitting remove reverts to 2.2 and causes vortex to claim theres a new install and they need to restart, restarting brings back 2,3

**Comment by IDCs** [comment]
A fresh install will usually default to 1.3.22 unless the beta update channel is selected

![image](https://user-images.githubusercontent.com/8960252/109381829-87b33280-78d4-11eb-8745-2b46122d1d08.png)

**Comment by IDCs** [comment]
> Hitting remove reverts to 2.2 and causes vortex to claim theres a new install and they need to restart, restarting brings back 2,3

That suggests you're on 1.3.22 not 1.4.2

**Comment by Darkwolf1515** [comment]
> 
> 
> > Hitting remove reverts to 2.2 and causes vortex to claim theres a new install and they need to restart, restarting brings back 2,3
> 
> That suggests you're on Vortex 1.3.22 not 1.4.2

Ah, i see now, I thought it would have hit stable, swtiching to beta just says "update failed" so ill try the github exe

**Comment by Darkwolf1515** [comment]
On the new version, 0.2.4, but purging and redeploying does not change anything, do i have to renistall?

**Comment by IDCs** [comment]
yes, all mods need to be reinstalled

**Comment by Darkwolf1515** [comment]
Right, sorry to waste time.

**Comment by IDCs** [comment]
1.4.x hasn't gone stable yet - we still have a few issues we would like to address before that can happen.

Don't worry about. If you could, please let us know why the update to the beta failed for you - that would be something that we need to look into

**Comment by Darkwolf1515** [comment]
> 
> 
> 1.4.x hasn't gone stable yet - we still have a few issues we would like to address before that can happen.
> 
> Don't worry about. If you could, please let us know why the update to the beta failed for you (through the Vortex UI) - that would be something that we need to look into

I wish I knew, I updated through github, and my internet doesn't appear to be blocking anything nexus related, swapping to it and restarting just gave an update fail error, if theres something I can give you, let me know.

**Comment by IDCs** [comment]
Yeah we could use having a look through your log files. Any vortex.log files inside "%appdata%/vortex"

**Comment by Darkwolf1515** [comment]
[vortex1.log](https://github.com/Nexus-Mods/Vortex/files/6054001/vortex1.log)
[vortex2.log](https://github.com/Nexus-Mods/Vortex/files/6054002/vortex2.log)
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/6054003/vortex.log)
