### ISSUE TITLE
QuickBMS integration request: allow disabling/suppression of operation notifications

### ISSUE THREAD

**Issue by agc93** [Nexus-Mods/Vortex#8650]
**Is your feature request related to a problem? Please describe.**
I'm using a QuickBMS list operation in the background, running in an event handler on a state change. As such, it's completely silent and ideally the user would never notice it was happening. However, since the [`successfulOp`](https://github.com/Nexus-Mods/extension-quickbms-support/blob/master/src/index.ts#L27) function is always called if a callback is used, there's also always a notification for 'QBMS operation completed'. Now it does disappear after 3 seconds, but it would still be nice to opt-out of that notification where the integration is ideally running in the background, rather than from a user action.

**Describe the solution you'd like**
Given both the `IQBMSOpProps` options object and therefore also the `IQBMSOptions` is still passed into `successfulOp` maybe it could have an extra key to skip the notification, or more generally an equivalent to the `quiet` flag for making _Vortex_ quiet rather than QBMS?

**Describe alternatives you've considered**
Obviously not the end of the world given the notification auto-dismisses, and I guess I could always put my own notification in with the same ID to short-circuit the logic in `successfulOp` but that feels hacky.

**Comment by IDCs** [comment]
@agc93, yeah that shouldn't be a problem, I think it would make sense for the quiet flag to also silence error notifications alongside the successful ones (just in case the extension developer doesn't want that to be made apparent to the user either)

The error will obviously still get forwarded to the game extension, but it will be the game extension's responsibility to do with it as it wills.
