### ISSUE TITLE
Add column filters to managed rules panel

### ISSUE THREAD

**Issue by Sriep** [Nexus-Mods/Vortex#8742]
The `manage rules` toolbar option on the `Mods` tab needs column filters.

A typical modlist has hundreds of mods and thousands or even tens of thousands of rules (e.g. my Fallout New Vegas setup). As this is just a static list of data I can't see any reason not to have filtering headings for the columns. Also, text search through the list of mods, sometimes you just know the mod you want to change and want to jump there.

It would be really convenient for fixing conflicts if you could search on `???`.

Also for fixing `rule cycles`. Currently, I have to take a screenshot of the error message, copy it to another app to look at while searching the thousands of mods in the `manage rule` dialogue. If there are ten mods in the conflict list, you only really need to view 10x10 = 100 rules, it would be nice if you could just display those.

Anyway adding a column filter and text search to the `manage rules` dialogue will make life easier for all vortex users.

<img width="1152" alt="rules" src="https://user-images.githubusercontent.com/6240686/111033053-4ad45900-8407-11eb-9a07-00558fb186f2.png">

**Comment by Pickysaurus** [comment]
That window has had some pretty nice upgrades in 1.4 - you can opt into the beta if you want to try it early :)

**Comment by TanninOne** [comment]
@Sriep now that 1.4 is stable, do you feel the changes we made to the screen are sufficient?

**Comment by Sriep** [comment]
Looks a lot better. Just got a new PC and I'll be setting up my Oblivion modlist probably [Bevilex' modlist](https://www.nexusmods.com/oblivion/mods/47591) at the weekend, I'll see how it feels.

**Comment by IDCs** [comment]
As nothing new has been discussed in the last 29 days, I'm assuming that the changes to the rules management dialog are satisfactory and am therefore closing this issue - please re-open if I'm wrong.

Any new suggestions on how to improve the current dialog should be raised through a new github report.
