### ISSUE TITLE
Vortex 0.16.0 Update - All mods uninstalled after forced download folder move.

### ISSUE THREAD

**Issue by Anvirol** [Nexus-Mods/Vortex#880]
Lost all 200+ Fallout 4 mod installations. Happened after Vortex forced me to move downloads folder.

![image](https://user-images.githubusercontent.com/3955313/44494008-da139880-a672-11e8-8dc0-4055eb5a2182.png)

Also lost some of the metadata that was tied to the downloaded mod files.

**Comment by Anvirol** [comment]
My folder structure was something like this:
G:\Vortex\downloads\{GAME}
G:\Vortex\mods\{GAME}

It moved the files and there wasn't any error printed out, but all installations vanished. 
I did a clean install of Vortex, reinstalled all mods and tried again, but I couldn't reproduce this.. but let's see if we get any more reports.

Btw. why isn't this structure acceptable? Is there a point to moving the archives?
![image](https://user-images.githubusercontent.com/3955313/44545668-5dd68f00-a71e-11e8-9779-4c9c408addeb.png)

**Comment by TanninOne** [comment]
I'm confused. Sorry, your post isn't very clear.
G:\Vortex\mods\{GAME} and G\Vortex\mods\fallout4
are the same directories. So when you say "It moved the files" - where did it move them?

Also: The screenshot you're showing is obviously from an older version again and it's using a completely different path (E:\Vortex\fallout4) so what is this even trying to tell me?

**Comment by Anvirol** [comment]
Vortex 0.16.0 moved downloaded archives and at the same time lost installation status for mods. 
Installed mods (extracted archives) weren't moved anywhere.

Screenshot is from 0.15.9. For some reason this folder structure was unacceptable for 0.16.0 update and forces to us move all downloaded archives to different folder.

**Comment by Anvirol** [comment]
Closing this since no one else reported issues. 
I hope it was a one time quirk or corrupt installation.

**Comment by TanninOne** [comment]
The "installation status" is a derived thing, If a directory exists in the configured mod directory (G\Vortex\mods\fallout4 in your case. Btw.: I assume that colon wasn't actually missing in your settings?) then that is an installed mod. It may be disabled or enabled but it can't be uninstalled. It's technically impossible for a directory inside the mod directory to not appear as an installed mod inside Vortex.
