### ISSUE TITLE
Game Not Discovered

### ISSUE THREAD

**Issue by kkendra78** [Nexus-Mods/Vortex#8850]
I have been using Vortex for the last 3 months playing Skyrim SE. Today I opened Vortex and the game was not in my managed games. It wants me to set the game folder. I do that and it tells me the directory doesn't appear to contain the game. This is frustrating as I opened the game folder outside of this ( E:\SteamLibrary\steamapps\common\Skyrim Special Edition ) and the game IS there. When I try to select the folder through Vortex it ISN'T there. What do I need to do?

**Comment by IDCs** [comment]
Hi @kkendra78, your log file will possibly explain why the game became undiscoverable - please attach it here so we can have a look at it - any vortex.log files located inside "%appdata%/Vortex"

**Comment by IDCs** [comment]
Vortex runs a series of tests whenever it attempts to automatically discover a game - regardless of whether the folder is there or not, if any of the tests fail Vortex will assume that the modding environment is unviable. The reason why discovery fails should be present in your log files - please attach those to this issue so we can investigate. The vortex.log files are located inside "%appdata%/Vortex"

**Comment by IDCs** [comment]
Hi @kkendra78, @!kalukali, is this still an issue ? if it is please send us your vortex.log files which can be found inside "%appdata%/Vortex" - I'll be closing this issue off in the next couple of days if I don't hear back from you.

**Comment by IDCs** [comment]
Assumed fixed.
