### ISSUE TITLE
Enderal SE - INI setting management not working 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#8880]
**Describe the bug**
Vortex 1.4.8
The baked/base INIs don't get created in the Enderal folder under "My Games" when managing the Steam release of Enderal SE. This implies that something isn't right with INI management. When swapping between Gamebyro games the attached error will also appear. 

**To Reproduce**
1. Install Enderal SE on Steam
2. Manage it in Vortex
3. Switch to another game (Skyrim SE) 

**Expected behavior**
The same functionality as the other main Gamebyro games. 

**Screenshots**
![image](https://user-images.githubusercontent.com/31670524/111989203-5f9ca500-8b09-11eb-9177-217365b97114.png)

**Additional context**
I cannot reliably test this for the Skyrim SE install of Enderal as my Skyrim INI baked/base files already exist and I don't want to break my setup.

**Comment by TanninOne** [comment]
@Pickysaurus you seem to have forgotten to attach the log file.

**Comment by Pickysaurus** [comment]
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/6189657/vortex.log)
