### ISSUE TITLE
userlist.yaml was broken or corrupted

### ISSUE THREAD

**Issue by gamerguythat4** [Nexus-Mods/Vortex#8883]
Explanation:
It said that userlist.yaml in Skyrim SE couldn't be read. It said I should quit Vortex and repair it. I didn't modify the file myself.
File location:
Users\YourUser\AppData\Roaming\Vortex\skyrimse\userlist.yaml
What was Expected:
To open up Vortex and the message wouldn't pop up.
Platform:
Windows 10
Vortex version: 1.4.8

**Comment by IDCs** [comment]
Hi @gamerguythat4, can you think of what may have caused the corruption ? could've this been caused by a crash or perhaps you forced Vortex to close while it was trying to modify the file ?

Either way we're going to need to see your userlist.yaml file - attach it here.

**Comment by IDCs** [comment]
Assumed fixed
