### ISSUE TITLE
Downloads fail after update to 1.4.8

### ISSUE THREAD

**Issue by d3dc** [Nexus-Mods/Vortex#8903]
Clicking a Vortex download button results in a node_modules resolution error:

![image](https://user-images.githubusercontent.com/4175887/112249144-dffffa80-8c1c-11eb-8d83-6607bcc0c1d6.png)

**To Reproduce**
1. Go to 'any mod'
2. Click on 'vortex download button'
3. Wait

**Expected behavior**
The download starts in Vortex.

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version 1.4.8

**Additional context**
Works fine in 1.3.22 - even with the same appdata.
Fails on a clean install with appdata removed .

**Comment by IDCs** [comment]
Hi @d3dc, do you have an AV installed? does disabling the AV and re-installing Vortex fix it ?

**Comment by IDCs** [comment]
Try disabling SmartScreen and re-install Vortex and let us know if the error goes away https://support.microsoft.com/en-us/topic/what-is-smartscreen-and-how-can-it-help-protect-me-1c9a874a-6826-be5e-45b1-67fa445a74c8

**Comment by TanninOne** [comment]
@d3dc please test if 1.4.9 fixes this.

**Comment by d3dc** [comment]
@TanninOne Works great.

AV is Windows Defender.
