### ISSUE TITLE
RR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by F9thRet** [Nexus-Mods/Vortex#8923]
**Describe the bug**

When I close Skyrim SE, this bug invariably pops up, then closes Vortex. Example below.

Thu, 25 Mar 2021 03:53:33 GMT - error: unrecoverable error message=net::ERR_HTTP2_PROTOCOL_ERROR, title=undefined, subtitle=undefined, stack=Error: net::ERR_HTTP2_PROTOCOL_ERROR

**To Reproduce**
1. Start Skyrim SE
2. Play game
3. Exit Game
4. Vortex pops up with error, then closes.

**Expected behavior**
For Vortex to stay active and not close down.

**Screenshots**

**Platform (please complete the following information):**
 - OS: Windows 10 PRo
 - Vortex Version 1.3..22

**Additional context**
I just hope I did this report right.

**Comment by TanninOne** [comment]
The current version of Vortex is 1.4.9 and this is probably fixed in that version.
