### ISSUE TITLE
Closed issue that wasn't properly addressed.  

### ISSUE THREAD

**Issue by GrinningStudios** [Nexus-Mods/Vortex#8928]
**Describe the bug**
Original issue is here: https://github.com/Nexus-Mods/Vortex/issues/8926
Please reopen this issue and I will help give you any information needed to find and fix this bug. Closing the issue within an hour of it's post without any follow up is a disservice to the users of this excellent software, unless of course I, the OP, am the only person that has or will ever have this problem.  Something I hope is true, but I wouldn't bet on it.

Here is the updated info: for the original info, please reopen the 8926 issue. 

###Copied from https://github.com/Nexus-Mods/Vortex/issues/8926###

Thanks for the response. Unfortunately this did not fix the problem. This happened when I updated Vortex to 1.4.8 - I mean to say, it was working fine until I updated to 1.4.8 then it stopped working, even though I didn't change any mods or anything. The only thing I did was update. I thought it might be a mod doing something weird, even though I didn't change any of the mods. So I updated the mods that needed updating. Still not working. however, I was able to create a new tool and the new tool allows me to edit the target and start in location. But the main one does not. In other words, the new tool works, but I have to edit the command line with any changes I make.

NOW I am getting a new error that symlinks on my system can only be created by an elevated process and my system just refused/failed to run the process elevated with no error message. This is new...

Now there is another update... I am installing the update.
Now the version of Vortex is 1.4.9
No change to the problem. It is still trying to launch the launcher instead of the game.
Again, the NEW tool I created works, but if I make any changes to the mods or mod load order, I have to manually input them into the command line of the new tool. I can just copy and paste from the "main" tool but it adds a step and increases my frustration. Perhaps others might not even realize they can make their own launch tool and edit it themselves. I sincerely hope I am the only person with this problem. At least the Symlinks error is gone now.

Since this issue is closed and the problem persists, even though you refer the problem to a mod, however I have strong reason to believe it isn't, I'd like to leave this note for the record. This issue continues and it has not been resolved.

Created a NEW profile. Removed all the mods. Attempted to start the game. SAME problem. There are no mods to cause this problem.

**Comment by IDCs** [comment]
@GrinningStudios, ask and ye shall receive: #8926 reopened
