### ISSUE TITLE
Make updates available in China

### ISSUE THREAD

**Issue by platespinningdog** [Nexus-Mods/Vortex#8946]
I'm always frustrated when I start Vortex and the message "Failed to check for Updates" and some other message shows up as an "error". I live in China, and the reason for this is with the server holding whatver Vortex uses to check whether it should update or not is blocked in China. I suggest putting the update packages on a server that can be accessed in China, instead of assuming that everyone in the whole world can access your website, or else make the message less obtrusive or give us a switch to turn them off. The software will update when I'm connected to a VPN (which is quite often of course) and I have never experienced any issues with this, so in my opinion there is no need for these annoying in-your-face ërrors" that are not errors every time I start the program.  

Don't get me wrong, I love Vortex and it's many times better than anything else out there. This is just a suggestion.

**Comment by TanninOne** [comment]
Vortex updates are hosted on a completely legitimate inoffensive website. It is not comprehensible or predictable to those outside China which sites you're blocking or why. Hosting on a different site would be a major inconvenience for us and potentially our other users and there is no way to pick a host where we can be sure China won't decide to block it next.

You can disable the update check though, simply go to settings->vortex and switch "Update" to "No automatic updates". Then you can fetch new versions from https://www.nexusmods.com/site/mods/1 which I assume you can access.
