### ISSUE TITLE
Mod Author info URL is malformed

### ISSUE THREAD

**Issue by HylianSteel** [Nexus-Mods/Vortex#9024]
**Bug**

Currently, Vortex uses https://www.nexusmods.com/games/users/ when filling mod author URL info in a mod.
If someone follows said link, it leads to a blank page.
As an example, If I were to download the Skyrim Special Edition Mod called Serana Dialogue Add-On and open the author link to Martimius' nexus profile, it'd send me to https://www.nexusmods.com/games/users/25150304 instead of https://www.nexusmods.com/users/25150304 or https://www.nexusmods.com/skyrimspecialedition/users/25150304

**To Reproduce**

1. Download and install any mod.
2. Double click mod to open side panel
3. Click the author's name to open the link in your web browser.
4. See blank web page leading nowhere

**Expected behavior**

The author link should lead to the author's profile instead of a blank page.

**Platform**

 - OS: Windows 10 (20H2)
 - Vortex Version 1.4.9

**Comment by IDCs** [comment]
Hi @HylianSteel, thanks for your report - this is actually a bug in the Nexus API. Vortex simply uses what the API sends us. I notified my colleagues - and hopefully will have a fix for this soon.

**Comment by TanninOne** [comment]
As far as I can tell this has been fixed
