### ISSUE TITLE
Vortex I/O Error 1392

### ISSUE THREAD

**Issue by Br00klynShadow** [Nexus-Mods/Vortex#9076]
**Describe the bug**
Every time I try to deploy or delete this damn mod this error comes up.

**To Reproduce**
1. Open Vortex
2. Try to deploy mods or delete Skiibadaa Weapon Pack REDUX
3. See error

**Expected behavior**
I expected Vortex to deploy my mods or delete Skiibadaa's Weapon Pack REDUX.

**Screenshots**
![image](https://user-images.githubusercontent.com/82415069/114458864-c57ec880-9bad-11eb-8508-52c3aeb54d71.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version: 1.4.9

**Additional context**
When the window opens, anything i do instantly re-opens it. All i can do is force close Vortex via Task Manager.

**Comment by IDCs** [comment]
Hi there - error 1392 is an operating system error code which indicates disk corruption or hardware failure - there is absolutely nothing we can do to assist you with this issue. What you can try to do is open a command prompt and run the following command: `chkdsk e: /r` and let Windows attempt to fix the drive - if that doesn't work, I'm afraid it's time to buy a new storage device.
