### ISSUE TITLE
How to open Creation Kit through Vortex?

### ISSUE THREAD

**Issue by twist3dimages** [Nexus-Mods/Vortex#91]
I know Mod Organizer had a weird issue with opening Creation Kit (having to overwrite the steam app id: 202480) to use the correct mods/load order.

How would I do this in Vortex?

**Comment by Ca1ebS** [comment]
MO is completely different from Vortex. You don't need to do anything special.
Set it up as a tool on the dashboard or simply run the exe from the game folder.

**Comment by twist3dimages** [comment]
You're right. I didn't see them added to the top of the load order (pre-import)
