### ISSUE TITLE
Allow extensions to use the "Check for mods complete" notification

### ISSUE THREAD

**Issue by davidwhitman** [Nexus-Mods/Vortex#9230]
**Is your feature request related to a problem? Please describe.**
My extension's game, Starsector, checks for updates found at urls in a mod's metadata file, rather than the Nexus.
Vortex displays a notification when an user clicks "Check for updates" to show progress, and then shows the results.
These notifications cannot be modified by an extension, as they are Nexus-specific, so I display a second notification that shows the custom update progress and results.

**Describe the solution you'd like**
To allow an extension to either directly or indirectly (by having the notification read some metadata that an extension can modify) change the update messages.

**Describe alternatives you've considered**
I display a second notification that shows the custom update progress and results.

**Additional context**
![image](https://user-images.githubusercontent.com/1343347/116913565-452d0f80-ac0f-11eb-8974-1a5721876e88.png)
Code here: https://github.com/davidwhitman/vortex-starsector-extension/tree/master/src

**Comment by IDCs** [comment]
Hey @davidwhitman, you can actually tie your Starsector specific update mechanism to Vortex's through the async event system.

When a user clicks the check for update button, an asynchronous event "check-mods-version" is emitted which allows Vortex extensions to respond and inform the event emitter of newly updated mods.

I can see in your code that you're already calling the update function inside the `context.once` callback, so you can change the code as seen below and the setupUpdates function will get called whenever the user clicks the update mods button.

```
context.once(() => {
    util.installIconSet(GAME_ID, path.join(__dirname, 'icons.svg'));
    context.api.onAsync('check-mods-version', () => setupUpdates(context.api));
    context.api.events.on('open-mod-page', openStarsectorModPage(context.api));
});
```

Make sure that the setupUpdates function returns the modIds of the mods that were updated (if any) and the update success notification will inform the user of the updated mods.
