### ISSUE TITLE
Individual output folders for each app/tool

### ISSUE THREAD

**Issue by zax-ftw** [Nexus-Mods/Vortex#9302]
Let us set an individual "output" folders for each app we run from Vortex.

The output folders could work similarly to "Overwrite" in MO but they wouldn't use virtual file system like MO (but would most likely require VFS to catch the output). 

Usage examples:
- BodySlide Output - thousands of TRI files cluttering our game directory
- DynDOLOD Output
- Nemesis Output - generates shit-ton of stuff
- FNIS Output

This way all files generated by these apps would be stored in their own stagging folder that is treated as normal mod (deployed, hardlinked etc) with its own priority and dependencies.

**Comment by IDCs** [comment]
Given that our USVFS extension is not part of the core application and the way our current tool system is designed, this is wouldn't be a trivial task. @TanninOne, what do you think about this proposal ?

**Comment by TanninOne** [comment]
This is not possible. Vortex doesn't hook into the process so it can't determine which process created a file.
Even with MO style file system virtualization it'd be quite complex.

Vortex does trigger events when new files were added to the game directory. If you can determine which files belong to which tool (e.g. by the file extension or the directory they are in) you could write an extension that then moves them into a mod directory.
I don't think we'll be doing this as a core feature for Vortex though, it's a way too specific need.
