### ISSUE TITLE
LOOT operation failed (more than one entry exists for a plugin with the same name)

### ISSUE THREAD

**Issue by twist3dimages** [Nexus-Mods/Vortex#94]
Getting this when I try and sort my plugins
![image](https://user-images.githubusercontent.com/33134502/36699041-913081a8-1b19-11e8-9e89-273c044d6d8b.png)

The problem is it's been saying this when I _didn't_ have any plugins with that name (Autodoors Patches.esp). I recreated another one and it didn't solve the issue (using FO4edit)

Can I find out where Loot is getting this info from?

**Comment by TanninOne** [comment]
There is no rule for "Autodoors Patches.esp" so it has to be rules you set up yourself. And you can see those using the "Manage Dependencies" button on the plugins page.

**Comment by twist3dimages** [comment]
There was a dependency but I created that after I got this issue. Removing the dependency didn't fix it. Even when there are no plugins called "Autodoors Patches.esp" is says there are multiple

**Comment by twist3dimages** [comment]
So there is no rule in my userlist.yaml file for Autodoors Patches ...

Is there another area it could be?

**Comment by TanninOne** [comment]
Are you looking at the correct userlist? It should be in C:\Users\<username>\AppData\Roaming\vortex\fallout4
And you should not just looking for rules for Autodoors but also for rules referencing autodoors, like

```
plugins:
  - name: someplugin.esp
     after:
        - Autodoors Patches.esp
        - Autodoors Patches.esp
```

But you should also be able to fix this from inside Vortex using the "Manage Dependencies" menu.

**Comment by twist3dimages** [comment]
It looks like my userlist hasn't been updated in over 2 weeks but I know for a fact I've created dependencies (Manage Dependencies shows more entries)
https://pastebin.com/sbMasQUU

I went through the "Manage Dependencies" in Vortex and didn't see a single entry for Autodoors Patches

Should I try deleting the userlist.yaml file?

**Comment by twist3dimages** [comment]
Can this be marked as open as it does appear to be a Vortex issue?

**Comment by TanninOne** [comment]
Vortex certainly has no hard-coded rules for "Autodoors Patches.esp". If you don't have the plugin and you don't have a rule, where do you figure the error comes from?
Vortex stores its plugins inside the userlist, there is no other place. If "managed dependencies" shows different entries than the userlist then you're looking at the wrong file.
Have you toggled to "Shared" mode in Settings? If so the user list vortex uses will be in c:\ProgramData\vortex\fallout4 instead of the path I posted before.

**Comment by twist3dimages** [comment]
I figured out the issue. It was defaulted to shared mode so it was in the C:\program data\ folder. Yay! 

Should I set it to single user? I copy over the changes I made. No one else uses this desktop
