### ISSUE TITLE
More Support for Oblivion mod types

### ISSUE THREAD

**Issue by spacecowgirl314** [Nexus-Mods/Vortex#95]
BAIN (used by Wrye Bash and MO) archives aren't supported. Would be nice to be able to use these. From my understanding these are the vast majority of mods on Nexus with the except of DaRN UI which is omod.

**Comment by TanninOne** [comment]
BAIN archives (without wizards) should be fairly easy to support through an extension.
OMOD and BAIN wizards are essentially DSL (domain specific languages) that would have to be implemented and lacking documentation that would be a b*tch to do.
OMOD we could maybe integrate into the existing fomod installer using the existing code from NMM

but BAIN wizards? Unless there is some documentation I haven't seen the amount of work that would have to go into this is in no relation to the number of mods using it. It would probably be quicker for us to write a fomod installer from scratch for every single one of them than to support the format.

**Comment by LexiconCode** [comment]
> Unless there is some documentation...

@TanninOne are you aware the following resource for [BAIN wizards](https://wrye-bash.github.io/docs/Wrye%20Bash%20Technical%20Readme.html#wizards)?

**Comment by Infernio** [comment]
In case you guys are interested, I (Wrye Bash dev) am working on a new parser for BAIN wizards which uses a formal grammar written in ANTLR to generate its parser. See here: https://github.com/Infernio/wizparse. ANTLR supports JS too: https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md, so once it's done you could think about using that to just generate a parser. The AST converter / interpreter would obviously still have to be written manually.

**Comment by TanninOne** [comment]
@LexiconCode thanks, bookmarked for later reference

@Infernio That is absolutely fantastic news, thank you. I'll be sure to keep an eye on that

**Comment by GoAwayNow** [comment]
Definitely hoping to see this happen eventually. Having to make fomod installers for everything I've ever wanted to install is tiring. Honestly has me feeling like giving up on Oblivion before I even get to the game.

**Comment by TanninOne** [comment]
omod support is going to be tracked in #406 so this issue is going to be about BAIN (with and without wizards) packages only.

**Comment by Greg-Nexus** [comment]
Added to Product Backlog: https://gitlab.nexdev.uk/vortex/vortex/-/issues/149

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development. 

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
