### ISSUE TITLE
Vortex open but unreachable

### ISSUE THREAD

**Issue by Zakastar** [Nexus-Mods/Vortex#9546]
The vortex icon is open in the taskbar, the loading screen is working like normal, but after the loadingscreen, the application is just not there, I can see vortex in the small window when toggling my mouse over the icon but can't see the application in any way.  Reinstalling does not work either
**To Reproduce**
1. Go to desktop or windows start
2. Click on Vortex
3. Scroll down to nothing 
4. See Error

**Expected behavior**
Being able to see and use the app
**Screenshots**
![204959889_4376240009094092_3590350329818932504_n](https://user-images.githubusercontent.com/70346641/123530296-e197fd80-d6f8-11eb-8f40-9e61bae5ed00.png)
You can't tell by the picture, but my mouse is over the small vortex screen, which would usually show the app on the screen
**Platform (please complete the following information):**
 - OS: Windows 10
 - Vortex Version Latest

**Additional context**
No

**Comment by TanninOne** [comment]
That's not a Vortex problem. You probably moved your Vortex window off screen or so far down that the only visible part of it is below the the task  bar.

You can fix this by clicking the taskbar icon (so Vortex is shown as active) and then press alt+space to open the window menu, select "Move" and then use the arrow keys to move the window back into view.
