### ISSUE TITLE
Suggestion: add option to make mod name same as filename

### ISSUE THREAD

**Issue by Jinxtaposition** [Nexus-Mods/Vortex#9565]
Hello all,

I would like to request the option to set the **Mod Name** field to be the same as the **file name** of the imported mod.
This would consists of two parts:
(1) add an option to the **Settings** that sets the Mod Name to be equal to the File Name by default; 
(2) add an option to the **Settings** such that, when using the Vortex-Nexus link, you get a window allowing you to set both file name and mod name manually instead of just going with whatever the modder uses.

The effect would then be that:
- in the case of (1), whenever I import a non-nexus or manually downloaded mod, the mod's Title field is overwritten with the file name;
- in the case of (2), whenever I click a Nexus download link, I can manually set a mod/filename which is fixed (even after updates etc). 

The problem is this: mod naming conventions are one big mess. New modders don't always give the mods they upload to Nexus a sensible name, or give a quick name and forget to change it and then forget, or just don't bother at all. Downloading directly from Nexus means the mod is installed with its title, and once you have more than 30 mods or so it quickly becomes difficult to find your way (not to mention when you have literally hundreds, or are a modder yourself and may have 10 different versions of a mod as you're testing and developing). 

An indirect consequence is that I can also not use Vortex' update feature since that seems to have trouble with mods with deviant file names (though that's a separate issue, it would be nice if I could start using that as well).

My current solution is to manually download each and every mod, give it a sensible file name, install it, and copy-paste the filename into the mod title. This ensures I have a sensible structure, can find what I want quickly both in the list and using search, and I can also search for the corresponding files or folders in Explorer. Such uniformity quickly becomes a necessity for larger mod lists.

I think this would go a long way to helping people add structure to larger mod lists. It also avoids forcing any naming convention on modders - they can just implement their own. No doubt everyone has a different view of what an organised mod list should look like, and that's fine; this way they can use whatever suits them.

Thank you for your time :)

**Comment by IDCs** [comment]
Hi there - imported archives are immediately md5 checked and identified through our API which is why the mod name is set to whatever the mod author set it to. I understand that this is not a feature that works for yourself, but I guarantee that you're in the minority.

I think a good middle ground which would satisfy your requirement would be to add a table attribute to the mod list which would allow you to sort by archive file name.

**Comment by Jinxtaposition** [comment]
Hi,

Yes that's my current method. I understand I'm a minority in that regard. And indeed an extra field with the mod name would be a workaround, I just wish I could also use the auto update feature since that also becomes much more useful with many mods :)

Just a thought: wouldn't it be more practical to hash every file inside the archive of any newly uploaded/updated mod instead? That way, you could also allow Vortex to simply upload the deltas of mods when people click Update, rather than the whole mod each time, which would save considerable bandwidth on both ends. It also removes dependency on the filename for the hash. So it would work as follows:

- new mod gets uploaded by creator
- mod is extracted, files hashed, file hashes go into the database (together with a master hash of the hashes as a UID0)
- users download, install and use the mod
- new mod gets updated by creator
- mod is again extracted and hashed, deltas are noted
- users do an update scan with Vortex, find the mod has been updated, click Update
- Vortex queries Nexus, and Nexus sends back the files which have different hashes, Vortex backs up the older versions and then installs these files

It would depend on your situation of course, but perhaps it is worth doing a rough calculation to see the impact on your hosting costs. Most mod updates only update a few files at a time so it could seriously reduce bandwidth capacity requirements, especially for mods that get updated every 43 seconds (like Smart Harvest SE or Serana Dialogue Addon). It would also make life easier for users running from low capacity connections. 

Anyway, thank you for listening to my ramblings. Best of luck!
