### ISSUE TITLE
Mods are not deploying. Ive deleted and redownloaded both fallout and vortex.

### ISSUE THREAD

**Issue by smwlkins** [Nexus-Mods/Vortex#9567]
**Describe the bug**

Mods are not deploying even after i click deploy, and all the folders are on the same drive.
Old mods i downloaded on fallout 4 ingame worked just fine and showed up under plugins, but after i migrated over the old ones stayed and the new ones did not appear ### **_even after i clicked deploy using all of the methods._** 

**To Reproduce**
1. Go to Mods
2. Click on Deploy
3. Scroll down to Plugins
4. See error; mods have not been deployed.

**Expected behavior**
i click deploy and my mods appear on the plugins.
**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10] Windows 10
 - Vortex Version [e.g. 0.16.12] The latest, ive downloaded and redownloaded Vortex a few times the past day and today

**Additional context**

All folders are on the same drive
Ive deleted fully and redownloaded fallout
ive uninstalled using the vortex unsinstall application

**Comment by TanninOne** [comment]
You're not providing a whole lot of tangible information to go by
a) Where's the log?
b) Where's the error message you seem to be getting?
c) What do you mean by "migrate"? This seems to be what started your problems but you don't even explain what you migrated to where - or how.
d) What mods (samples) are you trying to deploy, and what plugins from those are you missing?

**Comment by IDCs** [comment]
Closing due to lack of feedback from affected user/s
