### ISSUE TITLE
7 Days to die Dedicated Server

### ISSUE THREAD

**Issue by VenicDragon-Penguinz** [Nexus-Mods/Vortex#9570]
After there is an integration to use Vortex on a Linux run server. Would you be able to make Vortex work with the 7 Days to die dedicated server? So that way mods can be downloaded directly to the Dedicated server and run with no issues.

**Comment by TanninOne** [comment]
I don't see why it wouldn't be possible. Linux support is already tracked in #2862 though and there aren't any plans right now for official linux support anyway so I'd like to defer to that issue.
