### ISSUE TITLE
I need Help Badly Please

### ISSUE THREAD

**Issue by 19ghostryder57** [Nexus-Mods/Vortex#9592]
Yes, this is not a Vortex issue but please hear me out...

I have been unable to use the Nexus support it will not let me submit a report.

Something went wrong with my Nexus Account or they did an update of some thing. I was logged out so I logged back in with no problem... However, ALL of my downloads everything was gone including my Premium status.. I have no idea what to do about it, I hope they have some kind of record to show what I had.. Please Help Me

ghostryder

coffman1957@gmail.com

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Vortex Version [e.g. 0.16.12]

**Additional context**

**Comment by IDCs** [comment]
Hi - send an email to support@nexusmods.com and they'll be able to sort you out.
