### ISSUE TITLE
"Unknown Download" error lacks any context

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/Vortex#9597]
**Describe the bug**
There is no context to the "Unknown Download". Could you please add the mod/download name to the notification or modal so users can tell which mod/file this error is in relation to?

I installed several mods using the "Install all" notification button and cannot say for sure which one failed. 

![image](https://user-images.githubusercontent.com/31670524/124579020-aad38d00-de46-11eb-8f45-69912dfab456.png)

![image](https://user-images.githubusercontent.com/31670524/124579064-b4f58b80-de46-11eb-93c1-222a3d31b3bb.png)

I would also suggest changing the wording of the message to be consistent with the tone of newer messages. 

> Title: Unknown download
> Body: The archive associated with MODNAME could not be identified. Please locate the file in the downloads tab to reinstall this mod.

**Comment by Pickysaurus** [comment]
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/6769067/vortex.log)

**Comment by IDCs** [comment]
@Pickysaurus - did you perhaps delete any of the archives you were trying to install (before/during the installation process) ?

So the issue here is that when Vortex tried to install the archive above, it was completely missing from the application state; we can't really display any information in that dialog if there's no sign of the download existing in the first place :/

**Comment by IDCs** [comment]
I guess I can add an optional IDownloadContext/IDownloadOptions object to the start-install-download event listener. But obviously we can't control what community extensions send when they emit that event, so we can only display information in that dialog when it's available.

**Comment by Pickysaurus** [comment]
In my case, I simply downloaded around 7 mods and clicked "Install all" from the notification. So I have a feeling Vortex got confused, but as it doesn't give me any details on which file/mod it failed on I can't be sure.

**Comment by IDCs** [comment]
"fixed" in https://github.com/Nexus-Mods/Vortex/commit/7c52393c29e59953d6b1bf39185de41d432cb42b

**Comment by IDCs** [comment]
Also - https://github.com/Nexus-Mods/Vortex/commit/677c276b1dbdebf56901088f3e42d95e64e824b3
