### ISSUE TITLE
Vortex not detecting the my documents folder

### ISSUE THREAD

**Issue by AvionSwift20** [Nexus-Mods/Vortex#9600]
I was having some issues with some of my games saving, and I was forced to delete my OneDrive in order for anything to work. I was able to get all the files and stuff out, however after I moved it all and deleted OneDrive, Vortex no longer launched, saying that it was unable to find the my documents folder. I moved the folder to the area where it recommended but still showed the same error.

Windows 10
Vortex latest version

**Comment by IDCs** [comment]
Hey @AvionSwift20, I'm afraid that deleting the OneDrive folder outright was a mistake - moving the documents folder outside of the OneDrive service is done via different configuration changes through Windows itself, not through manual removal of folders.

Unfortunately there is no way for me to gauge the amount of damage you may have caused to your system (it's out of scope as far as Vortex is concerned); if Vortex can't resolve where your documents folder is located - you'll quickly find that all other applications on your system have the same issue.

Hopefully these will help:
https://support.microsoft.com/en-us/topic/configuration-of-the-my-documents-folder-dfd9a90d-8f80-18d6-e7cc-f1566fc3b10b
https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e

Closing as this is not a Vortex issue.
