### ISSUE TITLE
Dragon Age Origins Ultimate Edition mods not letting access dlc

### ISSUE THREAD

**Issue by Doom13** [Nexus-Mods/Vortex#9620]
Ok so after playing the ME Legendary edition i decided to play Dragon Age again. I wanted to use mods again. So i downloaded mods through Vortex and I noticed that none of the dlc was showing up. I thought it was weird since i used mods back when nexus mod manager was a thing and everything worked fine. so then i repaired the game in the Orgin app logged back in and then the dlc was accessible again. I then quit redeployed the vortex mods logged back in and then the dlc dissappeared again.

**Comment by IDCs** [comment]
Hi @Doom13, not sure how you managed to get the Origin app to work in the first place - kudos.

I just tested the merge functionality for DA:O on Vortex 1.4.14 and could not reproduce the issue you are seeing. Perhaps it's down to one of the mods you have installed - I would need you to submit a bug report through Vortex's internal system (top right -> 3 dots -> Send Feedback) and attach the following to your bug report:
1. your vortex logs
2. application state 
3. separate before deployment/after deployment copies of your `C:\Users\{YOUR_USERNAME}\Documents\BioWare\Dragon Age\Settings\Addins.xml` file

Make sure to mention your report is in reply to 9620 - please note we can't investigate this without all the attachments I requested above.

**Comment by IDCs** [comment]
@Doom13 any update on this ?

**Comment by IDCs** [comment]
Closing due to lack of feedback from user/Can't reproduce
