### ISSUE TITLE
Vortex won't download file from Nexus 

### ISSUE THREAD

**Issue by LeiK34F** [Nexus-Mods/Vortex#9623]
Whenever I hit on the button "Mod Manager Download" on firefox, Vortex does open itself like it always does if it was closed(same thing happens If I previously opened it before downloading)  but then nothing, no download appears nothing happens, and yes I already unnistalled MO2 or any other mod manager, I have re installed vortex, checked the settings/download and handle links but they haven't worked.
[vortex.log](https://github.com/Nexus-Mods/Vortex/files/6797650/vortex.log)

Here is what diagnostics files shows whenever I download with the Mod Manager Download button

Sun, 11 Jul 2021 20:36:12 GMT - warn: [steam] failed to read steam config file errno=-4058, code=ENOENT, syscall=open, path=C:\Games\Devil May Cry 5\Steam\config\config.vdf
Sun, 11 Jul 2021 20:36:13 GMT - warn: check failed to run id=game-version, err=The specified resource type cannot be found in the image file., stack=Error

Could this issue happen because of the current state of the extension used to handle the game? In this case Bayonetta https://www.nexusmods.com/site/mods/260
currently it is on a beta state

At the moment I don't have a way to test if the issue is only with the Bayonetta extension or something else on my pc 

Windows 10 pro (19043.1083)
Vortex Version 1.4.14

**Comment by IDCs** [comment]
Hi @LeiK34F , first of all - none of the below statements are relevant to the issue you're experiencing
```
Sun, 11 Jul 2021 20:36:12 GMT - warn: [steam] failed to read steam config file errno=-4058, code=ENOENT, syscall=open, path=C:\Games\Devil May Cry 5\Steam\config\config.vdf
Sun, 11 Jul 2021 20:36:13 GMT - warn: check failed to run id=game-version, err=The specified resource type cannot be found in the image file., stack=Error

Could this issue happen because of the current state of the extension used to handle the game? In this case Bayonetta https://www.nexusmods.com/site/mods/260
currently it is on a beta state
```

Can you please try again to download a Bayonetta mod and attach your `network.log` file which is located in the same directory where you got the `vortex.log` file.

**Comment by TanninOne** [comment]
downloading is game independent, the extension doesn't affect that.

From the logs it looks like Vortex never receives the url from firefox, I'm pretty sure this is a configuration problem in Firefox.

Firefox allows overriding the system default of which application handles a protocol, if you ever did that (e.g. for MO2), Vortex can't reconfigure it, Vortex only changes the system default.

To check, go to firefox -> settings -> general, scroll down to Applications and find the Content Type "nxm".
It should be saying "Use Vortex (default)"

**Comment by LeiK34F** [comment]
Ohhhhhhhhhhhhhhhhhh omg thank you so much for that, it worked! I was worried it was the extension.
