### ISSUE TITLE
Archives with a Data folder wind up creating a Data folder within the Data folder

### ISSUE THREAD

**Issue by cybercatgurrl** [Nexus-Mods/Vortex#97]
This means mods don't like https://www.nexusmods.com/skyrimspecialedition/mods/13836 or https://www.nexusmods.com/skyrimspecialedition/mods/14968 don't install to the correct location.

**Comment by TanninOne** [comment]
Both of these mods (and similar) install correctly in the latest Vortex releases (0.15.5 and later).
If you encounter other mods that don't install correctly, please report them
