### ISSUE TITLE
[ UI ] Just wanted to suggest... (Updatable)

### ISSUE THREAD

**Issue by vanja-san** [Nexus-Mods/Vortex#977]
_`Sorry for my English!`_ 😅
1. ~~Correct banner "Premium", delete unnecessary buttons and make entire banner link.~~
2. ~~And please delete this "unnecessary" user panel.~~
3. ~~Make moving - title of panel.~~
4. ~~Make "Add tool" by a small button. (Design in your hands! 😋)~~
4.1 Can then at least move the button here. Standard location "not very", seriously. (screenshot)
5. ~~Finally, move "Update" icon to its place.~~
6. I think it's worth ~~doing~~ shift a "scroll" below! (well, it's more of a trifle)
7. Add indents here (screenshot). _I mean both sides._
8. Can make a similar font for Cyrillic?
Soon more...

**4.1(Sketch)↴**
![1](https://user-images.githubusercontent.com/7201687/45518506-f1f6bc00-b7db-11e8-8de2-1aafd3f7a2d0.png)

**6.↴**
![2018-09-11-03-45-36_li](https://user-images.githubusercontent.com/7201687/45323813-85c74e80-b576-11e8-9cf4-06c43c558075.jpg)

**7.↴**
![2018-09](https://user-images.githubusercontent.com/7201687/45520128-24a3b300-b7e2-11e8-9397-b534e9eef533.png)

**8.↴**
![2018-09-14-06-00-110](https://user-images.githubusercontent.com/7201687/45520527-f0c98d00-b7e3-11e8-8776-e810e4c882a3.png)

I'm sure that I will use this program, if you do not abandon it, and for this I see that I really do not need it. I will continue to send my requests.

**Comment by TanninOne** [comment]
You can disable the panel from settings.
Regarding the premium banners I will assign this to Kit, our UI designer.

**Comment by ArtaiosGreybark** [comment]
As an aside, when you do disable the Nexus banner in settings it will not give you more viewable area in the dashboard since the other widgets do not expand. Would be nice if they did.

**Comment by TanninOne** [comment]
Oh you do get space for more widgets but the height of widgets is fixed, there are good reasons to arrange the widgets in a fixed grid and expanding the grid as a whole might be useful for some widgets but others would simply look odd. On the screenshot the "starter" and "recent games" widget would simply have more unused gray area which would look odd, the premium banner would probably get a gray border around it as well.
Except for widgets like the news widgets that are built to scroll vertically, adding vertical space will never really add anything useful to the widget, best case scenario you get slightly bigger pictures when the original size was already fine.

There are already plans to allow certain widgets (where it makes sense) to be grown but it would always be user-configured, not automatic just by making more space available and it would always be in multiples of the grid sizes.

**Comment by ArtaiosGreybark** [comment]
Naturally you do get more space but with many configurations it is just wasted.
![avtvifr](https://user-images.githubusercontent.com/24878945/45265749-6f26d780-b450-11e8-9cb4-5e4de47fb7b7.png)
This is my current configuration and I am really happy with it but a bit more vertical space would be really nice.

Even maximizing the window at 1920x1080 and removing the Nexus banner will not allow me to stack more than 2 widgets vertically as seen here:
![m5mk6ur](https://user-images.githubusercontent.com/24878945/45265784-00964980-b451-11e8-8066-4f9efb51366e.png)
As you said, the News and New Files widgets would really benefit from it.

**Comment by TanninOne** [comment]
3. won't happen. Without a separate icon for moving the widget many users don't realize they can even move it at all.
For the same reason I don't think 4 is a good idea, a small button may be too easy to overlook or not understand the function.
6. I don't understand. There already is a scroll bar below the recently managed icons if they don't fit?

**Comment by vanja-san** [comment]
> 
> 
>     4. I don't understand. There already is a scroll bar below 
>        the recently managed icons if they don't fit?

Do not "**do**", but "**shift**". `I speak English by 10%.` Sorry!

**Comment by insomnious** [comment]
We are in the process of developing a new default theme that more closely matches our site and branding. This should address your concerns.
