### ISSUE TITLE
Python 2.x dependency

### ISSUE THREAD

**Issue by spbennett** [Nexus-Mods/Vortex#979]
As Vortex is still in alpha, we should consider migrating to Python 3 before a more broad launch.
> Being the last of the 2.x series, 2.7 will have an extended period of maintenance. Specifically, 2.7 will receive bugfix support until January 1, 2020. After the last release, 2.7 will receive no support.

Source: [PEP 373](https://www.python.org/dev/peps/pep-0373/)

I can't tell from the source where Python is required.  Is Python used by another downstream dependency?

**Comment by TanninOne** [comment]
python is only used during build time by node-gyp and that doesn't support 2.7.

Also, I'm willing to bet that python 2 support will not end in 2020, if the python devs stop supporting python 2 someone will fork it and continue supporting it. Python 2 is still way too relevant to give up.
