### ISSUE TITLE
[Feature request] Add Mod Title column to mods list

### ISSUE THREAD

**Issue by Anvirol** [Nexus-Mods/Vortex#98]
I've sent same feedback to [nexusmods forums](https://forums.nexusmods.com/index.php?/topic/6449251-mods-list-add-mod-title-column/)

Currently Vortex is displaying only the file names in mods list. Would it be possible to add 'Mod Title' column?

Sorting mods can be super confusing as many mods have file names similar to these:

- Main File
- Fixed Alpha Map
- Fixes for 2.4
- 10 Colors Standalone
- DEF_UI Compatibility Patch
- Textures 4k version

The list goes on and on, but you'll get the idea. Users might not know which mods these are, unless they double click the mod and "Visit on www.nexusmods.com".

With hundreds of mods, it's quite cumbersome to figure out which mods to enable.

It would be ideal if mod authors always named their files according to a specific pattern, but that'll probably never happen. Auto generation could work tho: Mod title - file name - version.

Thanks.

**Comment by Anvirol** [comment]
Any updates on this? This kinda of file naming keeps popping up and it would be nice to see the actual title of the mod.

![image](https://user-images.githubusercontent.com/3955313/42396367-0a497a66-816a-11e8-934c-139368d58b67.png)
![image](https://user-images.githubusercontent.com/3955313/42396378-18b86eae-816a-11e8-8740-5cc0b1fa9ab2.png)
![image](https://user-images.githubusercontent.com/3955313/42396390-22db3560-816a-11e8-8e7d-fc12b1947c75.png)
![image](https://user-images.githubusercontent.com/3955313/42396402-2f628da6-816a-11e8-8b2d-2af133cc552d.png)

**Comment by TanninOne** [comment]
What I want to avoid is names like "The Eyes of Beauty Fallout Edition - The Eyes of Beauty Fallout Kaleidoscope Edition - All-in-One"
In the lastest release (0.16.3) Vortex tries to determine (using fuzzy matching) if the mod name and file name are substantially different. If so the mod name is prepended.

So if the name of the mod is "The Eyes of Beauty Fallout Edition" and the file name is "The Eyes of Beauty Fallout Kaleidoscope Edition - All-in-One" then Vortex will continue to use only the file name, however if the mod name is "Synths Revamped" and the file name is "DiMA" then Vortex will display both, like this: "Synths Revamped - DiMA"

In my limited testing this produced pretty good results but obviously it's still a heuristic.
