### ISSUE TITLE
i m trying to register my tools in vortex and find any support/informations to do it right 

### ISSUE THREAD

**Issue by SCARaw** [Nexus-Mods/Vortex#9800]
So i made this piece of code so far (wip)
https://github.com/SCARaw/vortex-games/blob/master/game-kenshi/index.js

and this 2 tools for my mods kind of:
https://www.nexusmods.com/kenshi/mods/804
https://www.nexusmods.com/kenshi/mods/602

Questions i have:
how can i add my logos?
do they need to be in repo folder or right next to EXE in my folder?
Question 2:
How can i get aplication ID and stuffs to make sure i fill this data correctly
Question 3:
When there is field Api requirements and my aplication require DLL files not just exe, should i list it all?
Question 4:
How does process of adding my code or improved version of it to vortex works?
Question 5:
do i need to know something more?
Question 6: 
is my current code sequence okey and will works just like that or should i register tools somewhere else too?

Sorry if my questions sounds nooby, i m not exactly best programmer in the world, just doing best i can to mod game i like

**Comment by IDCs** [comment]
Hi @SCARaw 

Q1:  Add a logo property to the tool object - the logo value is relative to the game extension's path, so it should be in the repo next to your code. The executable value is relative to the tool's path, whatever it may be.
```{
    id: 'nvidiaProfileInspector',
    logo: 'whatever.jpg', // Relative to the game extension path
    name: 'Darkmod inspector',
    executable: () => 'nvidiaProfileInspector.exe',
    requiredFiles: [
      'nvidiaProfileInspector.exe',
    ],
  },
```

Q2: The id value isn't set in stone - you can set it to whatever you want. The important bit is to ensure you got the executable values right as that's what Vortex uses to run the tool.

Q3: The executable is usually enough as long as it can act as a unique identifier for the tool. i.e. if a tool has a non-unique executable name like "app.exe", that's when you would have to add additional files to make sure Vortex can distinguish between tools with potentially identical filenames.

Q4: You create a fork of the repo you wish to modify (you already did) then if you're happy with the results and have tested your changes - you submit a pull request. We then review your code and decide if we want to merge it into the main repo.
![image](https://user-images.githubusercontent.com/8960252/129315868-c48f2f4b-30d7-4e48-992a-6059c7b685b4.png)

Q5:
https://wiki.nexusmods.com/index.php/Creating_a_game_extension_for_Vortex#Defining_tools
https://nexus-mods.github.io/vortex-api/

Q6: You defined an array containing tool objects but you're not using it anywhere - you need to modify the game registration call to include the tools you've added.
```
context.registerGame({
    id: KENSHI_ID,
    name: 'Kenshi',
    mergeMods: true,
    queryPath: findGame,
    queryModPath: () => 'mods',
    logo: 'gameart.jpg',
    executable: (discoveryPath) => getExecutable(discoveryPath),
    supportedToos: tools, // Assign the tools in the registerGame API call
    requiredFiles: [
      'OgreMain_x64.dll',
      path.join('data', 'kenshi.ico'),
    ],
    setup: prepareForModding,
    requiresLauncher,
    environment: {
      SteamAPPId: '233860',
    },
    details: {
      steamAppId: 233860,
    },
  });
```

**Comment by SCARaw** [comment]
Thank you for fast and detailed response, i will take evening to do it right or at least to try do it right and hope for the best
