### ISSUE TITLE
Nexusmods.com appears to be down from Ashburn server

### ISSUE THREAD

**Issue by CATboardBETA** [Nexus-Mods/Vortex#9805]
**Describe the bug**
the Ashburn Cloudflare server can no longer reach nexusmods.com.

**To Reproduce**
1. Live in or use a VPN to put yourself near Ashburn
2. Attempt to connect to www.nexusmods.com

**Expected behavior**
Website loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/66703887/129350673-f214e608-c138-4990-9748-fc6d0404b4a0.png)

**Platform (please complete the following information):**
 - OS: Windows 10 Home V21H1, Build 19042.1165
 - Vortex Version N/A

**Comment by CATboardBETA** [comment]
Nevermind. This resolved itself while I was writing.

**Comment by IDCs** [comment]
@CATboardBETA this is also the wrong issue tracker to report connectivity issues. If you ever encounter this again please report it to the web team, not Vortex support.

https://github.com/Nexus-Mods/web-issues
