### ISSUE TITLE
Not a bug, just out of curiosity

### ISSUE THREAD

**Issue by Dallong** [Nexus-Mods/Vortex#9928]
Hey, Just some user of vortex here. I was wondering, is vortex(or any other files I downloaded for modding purpose) affect outside of games I'm modding? My computer is not for only gaming and acting quite strange (I'm sorry as the word "strange" doesn't give out thorough information, but I can't quite put it other way.) after few days I set up modded skyrim. I'm sure it's my end of problem as no other people mentioned it. If modding is not an issue, then I can Relax as I didn't mess up my computer so simple 'no, it doesn't do that.' would be nice. 
Except for ENB for enboost and Nemesis, every mods are downloaded from Nexus. No suspicious sites were visited in my mod-searching-rampage. 
Thanks for your time, I hope this question doesn't bother you.

**Comment by IDCs** [comment]
No, Vortex does not affect anything outside the games you're modding. The project is open source (all of the code is public) so don't take our word for it, read the code and convince yourself.

**Comment by Dallong** [comment]
Cool! I'm grateful for your answer as my question was silly even for me. Have a nice day!

**Comment by IDCs** [comment]
I should point out that although Vortex is 100% clean, some mods might not be - especially the ones in .dll form. The website automatically scans all uploads for viruses, and we do review the code of suspicious uploads; but obviously I can't guarantee that none of the mods are malicious.

Vortex sandboxes mod installations which will guarantee that no malicious attempts are executed during mod installation, but depending on a game's modding pattern and how the mods are being loaded into the game; the game itself might not be able to make the same guarantee.

Just something to keep in mind.
