### ISSUE TITLE
Add "PC Building Simulator"

### ISSUE THREAD

**Issue by ghost** [Nexus-Mods/Vortex#9983]
Vortex: 1.4.15
16GB RAM
Windows 10 64 bit
Add the game PC Building Simulator to install mods automatically and there's lots of mods on nexusmods.

**Comment by HawthorneK456** [comment]
Hi,

Thank you for taking time to open this request for Vortex. You may have seen our recent news post letting our users know that we are currently working on developing a successor to Vortex; Nexus Mods App which will deliver the next generation of mod management.

With this in mind, we are undertaking a review of all outstanding Vortex requests to determine their validity. As there is no existing extension for Vortex for this game, it is unlikely that we will commit to creating one for Vortex and instead consider adding support for the game in the Nexus Mods App. That said, if a member of the community submits an extension for verification then this could be an alternative way that the game may acquire support in Vortex.

As a result, this request will be closed here and passed to the Nexus Mods App team for their consideration in its design & development.

Once again, thank you for being an active member. If you missed the news post, you can read it here: https://www.nexusmods.com/news/14874
